### ISSUE TITLE
Trying s2i tutorial: zeitwerk requires Ruby version >= 2.4.4.

### ISSUE THREAD

**Issue by carloreggiani** [openshift/source-to-image#1005]
I'm trying to execute my first s2i image (from README.md):

`$ s2i build https://github.com/openshift/ruby-hello-world centos/ruby-23-centos7 test-ruby-app`

But I'm getting:
```
Installing zeitwerk 2.2.1

Gem::InstallError: zeitwerk requires Ruby version >= 2.4.4.
An error occurred while installing zeitwerk (2.2.1), and Bundler cannot
continue.
```

**Comment by bparees** [comment]
try `centos/ruby-25-centos7` instead.  i'll update the readme.
