### ISSUE TITLE
Arm binary or  cross-platform images

### ISSUE THREAD

**Issue by uocxp** [openshift/source-to-image#1008]
Is there any Arm-Binary for the s2i tool ? Or is it possible to generate arm-supported docker images with it (like [buildx](https://github.com/docker/buildx)) ?

**Comment by adambkaplan** [comment]
We do not release an ARM binary or images yet.

You can build an ARM binary yourself from source, though:

```
$ GOOS=linux GOARCH=arm64 go build ./cmd/s2i
```

**Comment by LinuxSuRen** [comment]
No offense, but IMO it's a pretty common request for the users of `s2i`. I was wondering if you can give some background about why don't offer the ARM binary or images. Thanks.

**Comment by adambkaplan** [comment]
>  I was wondering if you can give some background about why don't offer the ARM binary or images. Thanks.

s2i is a part of the OpenShift ecosystem. There is hardly any demand for ARM architectures today - for example, OpenShift 4 only works on x86_64, IBM Power, and IBM Z architectures.

**Comment by LinuxSuRen** [comment]
I understand your concern. But it seems that some people hope to use `s2i` in other platform separately. Of course, see it from the whole OpenShift ecosystem is good.
