### ISSUE TITLE
remote docker

### ISSUE THREAD

**Issue by mohapsub** [openshift/source-to-image#1009]
Does s2i needs a local docker? Which docker host is used to build image? If it expects a local docker then followup question is can it use remote docker host?

**Comment by bparees** [comment]
unless you use the --as-dockerfile argument (which simply generates a dockerfile you can build yourself with whatever image building tool you want (e.g. buildah)), you need a docker. It does not need to be local, you can pass the docker host/socket to use via the "--url" argument to s2i.

**Comment by mohapsub** [comment]
is this going to be s2i --url <remote docker>? Can i invoke s2i as a java method?

**Comment by bparees** [comment]
yes, `s2i build --url <url> other args`

s2i is written in Go(not java) and not really designed for consumption as a library, but if you're motivated certainly you could stitch it together via JNA.  (you might find it easier to just exec the s2i binary from your java code though).

**Comment by mohapsub** [comment]
awesome!!! thanks
