### ISSUE TITLE
Version yields "s2i unknow" after installing with "go get"

### ISSUE THREAD

**Issue by RafalSkolasinski** [openshift/source-to-image#1013]
Hi,

I just installed `s2i` using 
```sh
go get github.com/openshift/source-to-image/cmd/s2i
```
command and noticed that s2i's version is yield as unknown

```bash
$ s2i version
s2i unknown
```

**Comment by adambkaplan** [comment]
Version numbers are dynamically added via our `make build` command. I'm not sure how we can inject this data via `go get`.
