### ISSUE TITLE
Docker Inside Docker oom_score_adj: invalid argument

### ISSUE THREAD

**Issue by rajivml** [openshift/source-to-image#1016]
Hi,

On Kubernetes, to build docker images, we use Docker Inside Docker (dind) where a couple of processes i.e docker daemon and containerd daemon will be running on each pod to build the images

This is how we start those daemons, 

```
# Start docker daemon
dockerd --host=unix:///var/run/docker.sock --host=tcp://0.0.0.0:2375 &

# start container daemon
containerd --config /var/run/docker/containerd/containerd.toml --log-level info &
```

And we use **s2i** to build docker images and some times times we have observed that the docker image creation fails abruptly with the below error and not sure whether it's an s2i error or it's because either container daemon or docker daemon one of them is getting killed,

Can you please let us know in what all scenarios we encounter this kind of error ? and BTW in our setup each Node can have multiple pod's running dind and these multiple pods can build images in parallel by connecting to the docker socket running on the host Node

Before posting here, I have posted this issue on stack-overflow and didn't received any answer so I thought it would be the correct place to log this issue,
https://stackoverflow.com/questions/59906873/docker-inside-docker-oom-score-adj-invalid-argument

```
Executing build command => s2i build "/tmpModelManagement/host/xxx/xxx/xxx/automatedModelKZDnZlBV" abc/ml-py36-cpu:0.12 gcr.io/abc-12345/host/xxxx/automatedmodelkzdnzlbv:1 --loglevel=2 -e MODEL_NAME="automatedModelKZDnZlBV" -e GUNICORN_WORKERS="1" -e PERSISTENCE="0" -e TENANT_ID="xxxx" -e SERVICE_TYPE="MODEL" -e API_TYPE="REST"

DockerBuild failed for gcr.io/dave-xxxx/host/xxxx/automatedmodelzeietrjr:1 with messages:Running S2I version "v1.1.13"
Builder Image: abc/ml-py36-cpu:0.12Source: /tmpModelManagement/host/xxxx/xxxx/xxxx/automatedModelZeIetRJROutput Image Tag: gcr.io/dave-xxxx/host/xxxx/automatedmodelzeietrjr:1Environment: MODEL_NAME=automatedModelZeIetRJR,GUNICORN_WORKERS=1,PERSISTENCE=0,TENANT_ID=xxxx,SERVICE_TYPE=MODEL,API_TYPE=RESTLabels: Incremental Build: disabledRemove Old Build: disabledBuilder Pull Policy: if-not-presentPrevious Image Pull Policy: if-not-presentQuiet: disabledLayered Build: disabledDocker Endpoint: tcp://localhost:2375Image sha256:709e0aad20136fdcd4a99874ab004e3973b438edbf62c8839072e667b47e88a8 contains io.openshift.s2i.scripts-url set to "image:///s2i/bin"

Preparing to build gcr.io/dave-xxxx/host/xxxx/automatedmodelzeietrjr:1
Copying sources from "/tmpModelManagement/host/xxxx/xxxx/xxxx/automatedModelZeIetRJR" to "/tmp/s2i834345991/upload/src"Clean build will be performedPerforming source build from /tmpModelManagement/host/xxxx/xxxx/xxxx/automatedModelZeIetRJRRunning "assemble" in "gcr.io/dave-xxxx/host/xxxx/automatedmodelzeietrjr:1

"Using image name abc/ml-py36-cpu:0.12 starting the source uploading ...Image sha256:709e0aad20136fdcd4a99874ab004e3973b438edbf62c8839072e667b47e88a8 contains io.openshift.s2i.scripts-url set to "image:///s2i/bin"Base directory for S2I scripts is '/s2i/bin'. 
Untarring destination is '/tmp'.Creating container with options {Name:"s2i_uipath_aifbr_py36_cpu_0_12_df6b0670" Config:{Hostname: Domainname: User: AttachStdin:false AttachStdout:true AttachStderr:false 
ExposedPorts:map[] Tty:false OpenStdin:true StdinOnce:true Env:[MODEL_NAME=automatedModelZeIetRJR GUNICORN_WORKERS=1 PERSISTENCE=0 TENANT_ID=xxxx SERVICE_TYPE=MODEL API_TYPE=REST] Cmd:[/bin/sh -c tar -C /tmp -xf - && /s2i/bin/assemble] Healthcheck:<nil> ArgsEscaped:false Image:abc/ml-py36-cpu:0.12 Volumes:map[] WorkingDir: Entrypoint:[] NetworkDisabled:false MacAddress: OnBuild:[] Labels:map[] StopSignal: StopTimeout:<nil> Shell:[]} HostConfig:&{Binds:[] ContainerIDFile: LogConfig:{Type: Config:map[]} NetworkMode: PortBindings:map[] RestartPolicy:{Name: MaximumRetryCount:0} AutoRemove:false VolumeDriver: VolumesFrom:[] CapAdd:[] CapDrop:[] DNS:[] DNSOptions:[] DNSSearch:[] ExtraHosts:[] GroupAdd:[] IpcMode: Cgroup: Links:[] OomScoreAdj:0 PidMode: Privileged:false PublishAllPorts:false ReadonlyRootfs:false SecurityOpt:[] StorageOpt:map[] Tmpfs:map[] UTSMode: UsernsMode: ShmSize:67108864 Sysctls:map[] Runtime: ConsoleSize:[0 0] Isolation: Resources:{CPUShares:0 Memory:0 NanoCPUs:0 CgroupParent: BlkioWeight:0 BlkioWeightDevice:[] BlkioDeviceReadBps:[] BlkioDeviceWriteBps:[] BlkioDeviceReadIOps:[] BlkioDeviceWriteIOps:[] CPUPeriod:0 CPUQuota:0 CPURealtimePeriod:0 CPURealtimeRuntime:0 CpusetCpus: CpusetMems: Devices:[] DeviceCgroupRules:[] DiskQuota:0 KernelMemory:0 MemoryReservation:0 MemorySwap:0 MemorySwappiness:<nil> OomKillDisable:<nil> PidsLimit:0 Ulimits:[] CPUCount:0 CPUPercent:0 IOMaximumIOps:0 IOMaximumBandwidth:0} Mounts:[] Init:<nil>}} ...
Attaching to container "55597834a210527f506675a16ee13b4e73fc874d82785c4f96e1c387674c4d63" ...Starting container "55597834a210527f506675a16ee13b4e73fc874d82785c4f96e1c387674c4d63" ...
ERROR: Error writing header for "scripts": io: read/write on closed pipe
ERROR: Error writing tar: io: read/write on closed pipe
Removing temporary directory /tmp/s2i834345991
Removing directory '/tmp/s2i834345991'
Build failed ERROR: An error occurred: Error response from daemon: set shim OOM score: write /proc/9092/oom_score_adj: invalid argument: unknown
```

Thanks,
Rajiv

**Comment by bparees** [comment]
i'm not particularly familiar w/ that setup, but it seems like the container that s2i has launched is being killed, it does not look like an s2i error (other than that s2i ran into an error trying to talk to the container it created).

**Comment by rajivml** [comment]
thanks @bparees , then will further investigate why container is getting killed

**Comment by rajivml** [comment]
@bparees any idea, how can I set the oom_score of the containers which s2i is spawning, because we see lot of such errors in production where docker builds are failing many a times

**Comment by bparees** [comment]
i'm afraid i don't think s2i exposes a way to control that but if you're really running into oom kills it seems like you need to throttle your builds.

btw, there is now an s2i task for tekton which you might find to be a more stable way to accomplish your goal.

https://github.com/openshift/pipelines-tutorial
https://blog.openshift.com/cloud-native-ci-cd-with-openshift-pipelines/
https://www.youtube.com/watch?v=VblUusADGuQ

**Comment by rajivml** [comment]
@bparees can I pass how much memory and CPU should be allocated to the s2i container that gets spawned at the time of s2i image build ? I am searching for some references on how can I pass it through command line but no luck

**Comment by bparees** [comment]
> @bparees can I pass how much memory and CPU should be allocated to the s2i container that gets spawned at the time of s2i image build ? I am searching for some references on how can I pass it through command line but no luck

looks like there is no flag for that so you get whatever the docker daemon uses for defaults.  it is likely a relatively easy thing to add if you're interested in submitting a PR (I don't have time to develop that feature in my current role)
