### ISSUE TITLE
“s2i” cannot be opened because the developer cannot be verified

### ISSUE THREAD

**Issue by maxandersen** [openshift/source-to-image#1021]
when downloading latest release  on osx and run `s2i` you get the dreaded "“s2i” cannot be opened because the developer cannot be verified"

any plans on signing or documenting steps to avoid these?

**Comment by mhainke** [comment]
/reopen

The error on MacOS still exists with the latest version.

![Error_verified_developer](https://user-images.githubusercontent.com/58296390/122739966-cefa7000-d283-11eb-8ab5-11b824589213.png)
