### ISSUE TITLE
S2I fails to download python dependencies inside container injected with Istio 1.4 envoy side car

### ISSUE THREAD

**Issue by yangyao-uipath** [openshift/source-to-image#1026]
How to reproduce:
1. exec into a k8s container injected with istio 1.4 envoy proxy sidecar, 
2. run 
"s2i build https://github.com/sclorg/django-ex centos/python-35-centos7 hello-python"
  
This will produce error 
"
 Retrying (Retry(total=4, connect=None, read=None, redirect=None)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))': /simple/django/
  Retrying (Retry(total=3, connect=None, read=None, redirect=None)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))': /simple/django/
  Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))': /simple/django/
  Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))': /simple/django/
  Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))': /simple/django/
"

Notes
1. pip install -r requirements.txt works perfectly fine inside the same container.
2. S2I works fine with Istio 1.2 envoy side car proxy.

Suspicion:
S2I is doing something special compared to pip causing the s2i dependency download to fail.

**Comment by bparees** [comment]
s2i talks directly to the docker daemon on the host and spawns a new container, which istio will be totally unaware of(the container is not part of k8s), so i'm not surprised this does not work if you are dependent on the istio proxy sidecar for network connectivity.

(I assume this means you are mounting the docker socket into the pod you're attempting this from)

**Comment by yangyao-uipath** [comment]
Thanks a lot for getting back so quickly! 

We actually spin up a docker daemon inside this specific k8s container where s2i is located so s2i will be talking to the docker daemon in the same container. 

It took me quite a while to realize the network connectivity inside container !=After some search for docker container connectivity issue, ran into https://stackoverflow.com/questions/20430371/my-docker-container-has-no-internet. 

The following iptable and bridge reset command saved the day:

```
iptables -t nat -F
ifconfig docker0 down
brctl delbr docker0
```

It seems the issue has nothing to do with s2i but the docker daemon inside k8s container that s2i talks to. 
I think there will be users who install s2i inside k8s containers proxied by istio and run into similar issue/errors when they upgrade to istio 1.4 and above, hopefully this issue can be helpful for them :)

**Comment by yangyao-uipath** [comment]
A follow up, after resolving the connection reset error.
S2I build fails around half the time with error:
"ReadTimeoutError("HTTPSConnectionPool(host='pypi.org', port=443): Read timed out. (read timeout=15)"

One of the suggestion is that set the pip install time out to 100s instead of default 15s. https://stackoverflow.com/questions/43298872/how-to-solve-readtimeouterror-httpsconnectionpoolhost-pypi-python-org-port

Is there a way to set the pip install timeout during invoking s2i build command?

**Comment by bparees** [comment]
not that i see in the exsiting image, unless you provide your own override assemble script (which s2i does allow):
https://github.com/sclorg/s2i-python-container/blob/master/3.5/s2i/bin/assemble#L47-L64

**Comment by yangyao-uipath** [comment]
Updates, after more investigation. 
Docker in docker network is somehow behaving strangely for k8s cluster with weave.
The pip connection reset by peer and pip read timeout errors are fixed by adding "--network host" flag into s2i build command.
