### ISSUE TITLE
Cannot pull image from registry.redhat.io with s2i using docker for Windows in Virtualbox

### ISSUE THREAD

**Issue by ghijsma** [openshift/source-to-image#1028]
Hello

I'm trying to build an image with s2i. I'm not able to pull the base image from registry.redhat.io using s2i. However, when I do docker pull registry.redhat.io/rhel8/nodejs-10:latest it works fine. Somehow s2i cannot or does not pick up the local docker credentials to login with registry.redhat.io.

Fails when image is not available in local registry: 
$ s2i build --loglevel=3 git@github.com:digipolisgent/node_service_reservations-client.git -r master registry.redhat.io/rhel8/nodejs-10 reservations-client-api
I0221 10:11:44.913428    2464 build.go:50] Running S2I version "v1.2.0"
I0221 10:11:45.042081    2464 docker.go:486] Image "registry.redhat.io/rhel8/nodejs-10:latest" not available locally, pulling ...
I0221 10:11:45.906908    2464 docker.go:565] pulling image error : Error response from daemon: Get https://registry.redhat.io/v2/rhel8/nodejs-10/manifests/latest: unauthorized: Please login to the Red Hat Registry using your Customer Portal credentials. Further instructions can be found here: https://access.redhat.com/RegistryAuthentication
I0221 10:11:45.909877    2464 build.go:163]
Error describing image:         unable to get registry.redhat.io/rhel8/nodejs-10:latest
Source:                         git@github.com:digipolisgent/node_service_reservations-client.git#master
Output Image Tag:               reservations-client-api
Environment:
Labels:
Incremental Build:              disabled
Remove Old Build:               disabled
Builder Pull Policy:            if-not-present
Previous Image Pull Policy:     if-not-present
Quiet:                          disabled
Layered Build:                  disabled
Docker Endpoint:                tcp://192.168.99.102:2376

I0221 10:11:45.912763    2464 docker.go:486] Image "registry.redhat.io/rhel8/nodejs-10:latest" not available locally, pulling ...
I0221 10:11:46.572208    2464 docker.go:565] pulling image error : Error response from daemon: Get https://registry.redhat.io/v2/rhel8/nodejs-10/manifests/latest: unauthorized: Please login to the Red Hat Registry using your Customer Portal credentials. Further instructions can be found here: https://access.redhat.com/RegistryAuthentication
E0221 10:11:46.576112    2464 errors.go:286] An error occurred: unable to get registry.redhat.io/rhel8/nodejs-10:latest
E0221 10:11:46.576112    2464 errors.go:287] Suggested solution: check image name, or if using a local image set the builder image pull policy to "never"
I0221 10:11:46.576112    2464 errors.go:289] Details: Error response from daemon: Get https://registry.redhat.io/v2/rhel8/nodejs-10/manifests/latest: unauthorized: Please login to the Red Hat Registry using your Customer Portal credentials. Further instructions can be found here: https://access.redhat.com/RegistryAuthentication
E0221 10:11:46.576112    2464 errors.go:291] If the problem persists consult the docs at https://github.com/openshift/source-to-image/tree/master/docs. Eventually reach us on freenode #openshift or file an issue at https://github.com/openshift/source-to-image/issues providing us with a log from your build using log output level 3.

When pulling the image with docker pull it works, so it would seem that docker is authenticated with registry.redhat.io: 
$ docker pull registry.redhat.io/rhel8/nodejs-10:latest
latest: Pulling from rhel8/nodejs-10
Digest: sha256:8cd20f86207b5d1d20ef6b055490d895c1f3e404a53d13b3fae74d626e567956
Status: Downloaded newer image for registry.redhat.io/rhel8/nodejs-10:latest
registry.redhat.io/rhel8/nodejs-10:latest

When the image is available in the local registry the s2i build works. We would like it to work also with s2i when the image is not locally available. 

This approach worked fine when using the now almost deprecated "registry.access.redhat.com".

**Comment by bparees** [comment]
can you try using the ` --dockercfg-path` to pass a path to a dockercfg file that you know has correct auth for the registry?

and ensure the file only has one auth stanza for registry.redhat.io (if it has more than one it's possible one is valid and one is not and we're picking the wrong one)
