### ISSUE TITLE
pulling image error : repository docker.io/rhscl/python-36-rhel7 not found: does not exist or no pull access

### ISSUE THREAD

**Issue by basurohit77** [openshift/source-to-image#1030]
[rohbas11@oc4458204364 software]$ sudo ./s2i build https://github.com/sclorg/s2i-python-container.git --context-dir=3.6/test/setup-test-app/ rhscl/python-36-rhel7 python-sample-app
[sudo] password for rohbas11: 

ERRoR:
----------------------
pulling image error : repository docker.io/rhscl/python-36-rhel7 not found: does not exist or no pull access
pulling image error : repository docker.io/rhscl/python-36-rhel7 not found: does not exist or no pull access
ERROR: An error occurred: unable to get rhscl/python-36-rhel7:latest
ERROR: Suggested solution: check image name, or if using a local image set the builder image pull policy to "never"
ERROR: If the problem persists consult the docs at https://github.com/openshift/source-to-image/tree/master/docs. Eventually reach us on freenode #openshift or file an issue at https://github.com/openshift/source-to-image/issues providing us with a log from your build using log output level 3.

regards
rohit
7019803706

**Comment by basurohit77** [comment]
looks like rhscl/python-36-rhel7:latest is not any more avialable in docker.
Can any one provide me the correct linux x86_64, python 3.6 image

**Comment by bparees** [comment]
use registry.redhat.io/rhscl/python-36-rhel7

**Comment by bparees** [comment]
(you will need to create an account)
