### ISSUE TITLE
Whats the deal with v1.3.0?

### ISSUE THREAD

**Issue by erinn** [openshift/source-to-image#1035]
It's tagged, it's listed on releases, it doesn't have builds for x64 etc. only the source archives. It also isn't marked as latest. Is this intentional? Should users only be using 1.2.0? 

Thanks,
-Erinn

**Comment by bparees** [comment]
looks like it's still a draft release, @adambkaplan did you forget to come back and finish the release?

**Comment by adambkaplan** [comment]
@bparees @erinn apologies for the large delay. In drafting 1.3.0 I discovered a few documentation gaps. That is now done (I believe) - I can circle back and if all looks good I will update the tag & publish binaries.

**Comment by adambkaplan** [comment]
v1.3.0 is now up! Thanks @erinn for the reminder.
