### ISSUE TITLE
Failed to find required env var MODEL_NAME

### ISSUE THREAD

**Issue by decoin** [openshift/source-to-image#1037]
command:
<pre>
s2i build . seldonio/seldon-core-s2i-python3:0.18 pre_model:0.1
</pre>

error msg:
<pre>
Failed to find required env var MODEL_NAME
Build failed
ERROR: An error occurred: non-zero (13) exit code from seldonio/seldon-core-s2i-python3:0.18
</pre>

**Comment by adambkaplan** [comment]
This environment variable seems to be required by the assemble script in `seldon-core-s2i-python3`. I would contact the developers who maintain that image.

**Comment by adambkaplan** [comment]
Note too that you can pass in environment variables via the `-e` or `--env` command line flags.

**Comment by decoin** [comment]
ok, thanks.

**Comment by decoin** [comment]
--env load an single env var, use --environment-file  to specified a env file path can load multiple env vars.
