### ISSUE TITLE
incremental builds should be signalled to the image in some way (env var?)

### ISSUE THREAD

**Issue by jmtd** [openshift/source-to-image#1038]
When a builder image is being used via the incremental workflow, it needs to preserve whatever needs to be passed on by `save-artifacts`.

When a builder image is *not* being used via the incremental workflow, it may be that we don't want to preserve that stuff. Indeed some customers are asking us not to do this for the OpenJDK image.

The trouble is at the point when the cache is populated : the initiial `assemble`, there's no way of knowing within the image whether or not `--incremental` is in effect. This is before `save-artefacts` is executed. And so we have to default to preserving those artefacts.

If S2I set an environment variable or in some other way signalled that incremental was enabled, we could conditionally save or purge the build artefacts accordingly.

**Comment by adambkaplan** [comment]
This feels almost identical to #950 (which is still open).

@jmtd if this sounds like what you are looking for then please close this issue, and we can continue the discussion there.

**Comment by jmtd** [comment]
@adambkaplan yep this is a dupe of that, thanks!
