### ISSUE TITLE
Additional language templates

### ISSUE THREAD

**Issue by jarcher** [openshift/source-to-image#1042]
Are there plans for R, Rust, Scala, Octave, and Julia support?

**Comment by bparees** [comment]
s2i is a framework, the creation of specific builder images that support specific languages is an ecosystem question.  

looks like there already is at least one scala s2i builder (i have no idea how new/functional it is, just did a google search for `s2i scala`):
https://github.com/radanalyticsio/s2i-scala-container

there is also a (pretty dated looking) Rust builder:
https://github.com/openshift-s2i/s2i-rust

**Comment by jarcher** [comment]
ah ok so maybe testing/shipping these then?

**Comment by bparees** [comment]
> ah ok so maybe testing/shipping these then?

who are you suggesting could/should test+ship them?

s2i(the project) would not(as it's beyond the scope of the project).  OpenShift (the product that is the primary consumer of s2i) could, as it ships other sample s2i builder images but that would be an RFE to OpenShift.

**Comment by adambkaplan** [comment]
Red Hat software collections also maintains a set of s2i builder images. There is a rust container, but that does not appear to be s2i enabled: https://github.com/sclorg/rust-container. 

I don't think they have container images data science/ML languages you list, nor is there a container image for Scala (which is a bit surprising IMO).
