### ISSUE TITLE
Question regarding Git tag 1.3.0

### ISSUE THREAD

**Issue by alebcay** [openshift/source-to-image#1047]
Hello, I'm one of the maintainers of the [Homebrew package manager](https://brew.sh). We're currently shipping v1.3.0 of `source-to-image` and noticed that the revision tagged as 1.3.0 has changed since its original release. Has the code been rebased or a new copy of v1.3.0 been retagged? I notice that it was tagged in April 2020 and the copy of v1.3.0 that we're distributing seems older than that.

I just wanted to verify that this change was intentional and also understand if there were any breaking changes during the retag process. Thanks!

**Comment by adambkaplan** [comment]
@alebcay if you are able to post the SHA that was used in the original distribution, I can tell you if we added any breaking changes. I don't think I did - after I created the tag, we discovered some important docs were missing. I believe `s2i version` will print out the commit SHA.

**Comment by alebcay** [comment]
The original v1.3.0 revision that we distributed seems to be `ecf5524df96eb4def4db8ef0969a9630e59ec890`, while the v1.3.0 tag now points at `eed2850f2187435ef5d83487e05bf3dc18622ceb`.

**Comment by adambkaplan** [comment]
@alebcay no breaking changes for end-users between those commits. One bug fix related to the new generate command.

**Comment by alebcay** [comment]
I see. Thanks for clarifying! 👍
