### ISSUE TITLE
Question: execute test inside openshift s2i build

### ISSUE THREAD

**Issue by magick93** [openshift/source-to-image#1048]
Hello

I'm wondering if the following is possible.

I'm wanting to build an image, in Openshift 3.11, using s2i, and if the s2i test passes, then the image is promoted to another openshift environment.

I have a custom s2i project, and I see it has a `test` directory and `run` script. Is it possible to run this in openshift, and do a `push` if it passes?

**Comment by bparees** [comment]
yes, you should be able to use a post commit hook to run a command inside the image that was just built, and if the command passese, the image will be pushed to whatever target your buildconfig specifies:
https://docs.openshift.com/container-platform/3.11/dev_guide/builds/build_hooks.html#build-hooks
