### ISSUE TITLE
S2i killed

### ISSUE THREAD

**Issue by narennadig** [openshift/source-to-image#1051]
```
(base) [narendranath24 ~]$ s2i
Killed

```

I keep getting this error  when using s2i..How do I fix it?

**Comment by narennadig** [comment]
Red Hat Enterprise Linux Workstation release 7.8 (Maipo) @adambkaplan 
I'm not able to run s2i version as well..same error

**Comment by adambkaplan** [comment]
@narennadig do you recall how you installed s2i - did you download from GitHub or yum install an rpm?

**Comment by narennadig** [comment]
I think rpm ... Should I re install it?

**Comment by adambkaplan** [comment]
The rpm shipped in RHEL is very old and is not maintained by this project. You can file a Bugzilla to see if it can be upgraded to the latest release.

**Comment by adambkaplan** [comment]
Note that the s2i RPM requires docker, which may not be present on RHEL 7.8 machines.

**Comment by kstephen314159** [comment]
I have this problem too but (1) I get it when running the "help" command and (2) I installed from tar.gz

[zaphod@oc6010654212 ocp-tools]$ tar -xvzf ~/Downloads/source-to-image-v1.3.0-eed2850f-linux-386.tar.gz 
./
./sti
./s2i
[zaphod@oc6010654212 ocp-tools]$ ./s2i
Source-to-image (S2I) is a tool for building repeatable docker images.

A command line interface that injects and assembles source code into a docker image.
Complete documentation is available at http://github.com/openshift/source-to-image

Usage:
  s2i [flags]
  s2i [command]

Available Commands:
  build       Build a new image
  completion  Generate completion for the s2i command (bash or zsh)
  create      Bootstrap a new S2I image repository
  generate    Generate a Dockerfile using an existing S2I builder	image that can be used to produce an image by any application supporting the format.
  rebuild     Rebuild an existing image
  usage       Print usage of the assemble script associated with the image
  version     Display version

Flags:
      --ca string        Set the path of the docker TLS ca file (default "/home/zaphod/.docker/ca.pem")
      --cert string      Set the path of the docker TLS certificate file (default "/home/zaphod/.docker/cert.pem")
  -h, --help             help for s2i
      --key string       Set the path of the docker TLS key file (default "/home/zaphod/.docker/key.pem")
      --loglevel int32   Set the level of log output (0-5)
      --tls              Use TLS to connect to docker; implied by --tlsverify
      --tlsverify        Use TLS to connect to docker and verify the remote
  -U, --url string       Set the url of the docker socket to use (default "unix:///var/run/docker.sock")

Use "s2i [command] --help" for more information about a command.
[zaphod@oc6010654212 ocp-tools]$ ./s2i help completion
Killed
[zaphod@oc6010654212 ocp-tools]$ ./s2i help build
Killed
[zaphod@oc6010654212 ocp-tools]$ ./s2i completion
Killed

RHEL 7.8

**Comment by kstephen314159** [comment]
I use podman instead of docker. Does s2i work with podman? Is that the problem?

**Comment by kstephen314159** [comment]
Well that was embarrassing. As you may have noticed from the output I included, I had accidentally tried the 386 version instead of the 64-bit one. The amd64 build works fine.

**Comment by adambkaplan** [comment]
> I use podman instead of docker. Does s2i work with podman? Is that the problem?

Unfortunately most `s2i build` commands do not work without docker. The exceptions are `s2i build --as-dockerfile` and `s2i generate`. We've previously that we need to remove our explicit dependency on docker (see #966)
