### ISSUE TITLE
Installation issue on RHEL 8

### ISSUE THREAD

**Issue by SankBad** [openshift/source-to-image#1052]
I am using RHEL 8 and trying to install s2i.

When I am running the command:
`$ go get github.com/openshift/source-to-image/cmd/s2i`

I am getting the error:

```
Package devmapper was not found in the pkg-config search path.
Perhaps you should add the directory containing devmapper.pc
to the PKG_CONFIG_PATH environment variable
Package 'devmapper', required by 'virtual:world', not found
pkg-config: exit status 1
# github.com/openshift/source-to-image/vendor/github.com/containers/storage/drivers/btrfs
go/src/github.com/openshift/source-to-image/vendor/github.com/containers/storage/drivers/btrfs/btrfs.go:8:10: fatal error: btrfs/ioctl.h: No such file or directory
 #include <btrfs/ioctl.h>
          ^~~~~~~~~~~~~~~
compilation terminated.
```

Is there any dependency, that I am missing?

**Comment by SankBad** [comment]
Installation using tar is working for me

**Comment by biyiklioglu** [comment]
**btrfs-progs-devel** and **device-mapper-devel** packages are required to build **s2i** on **RHEL8/CentOS8**

The former can be found in the **elrepo-testing** repository, whereas the latter can be downloaded from the **EPEL powertools** repository.

You can install them as:

```
dnf install https://www.elrepo.org/elrepo-release-8.el8.elrepo.noarch.rpm
dnf --enablerepo=elrepo-testing install btrfs-progs-devel
```

```
dnf install https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
dnf --enablerepo=powertools install device-mapper-devel
```

and install s2i 

`go get github.com/openshift/source-to-image/cmd/s2i`

Hope that helps
