### ISSUE TITLE
assemble-runtime not found 

### ISSUE THREAD

**Issue by mkwapisz** [openshift/source-to-image#1059]
Windows 10 system, s2i 1.3.1, scripts are in .s2i/bin along with my source code. 
There are no problems with a builder image stage. WORKDIR in runtime image is set to /s2i and this directory exists.

`I1030 12:29:27.341228   10876 postexecutorstep.go:357] /bin/sh: 1: **s2iscripts/assemble-runtime**: not found`

notice that / was removed form the path. If I set WORKDIR to /s2i/something then s2isomethingscripts/assemble-runtime is displayed
What is interesting if I remove assemble-runtime from .s2i/bin then assemble-runtime from my runtime image is used and an application image is built properly. I can run my dockerized app and the run script is executed successfully. It occurs that it is properly uploaded to the /s2i/scripts location. What is wrong with assemble-runtime script?

**Comment by adambkaplan** [comment]
@mkwapisz can you please provide the specific command you ran, and in which environment you ran this in?

Please also provide the version of Docker you are using.

**Comment by mkwapisz** [comment]
Docker Desktop 2.4, WSL, Windows 10 -> Docker Engine v19.03.13

`s2i build SampleWebShop maven-builder samplewebshop --copy --runtime-image payara-runtime --runtime-artifact /project/src/target/SampleWebShop-JEE8.war`

Builder image is based on maven:latest and runtime image is based on payara/server-full:5.2020.5-jdk11
When I don't use .s2i/bin scripts everything works perfectly. All scripts are executed as intended. Instead of modifying assemble-runtime in my runtime image I added .s2i/bin/assemble-runtime and run scripts to my sample project and problems occurred.

**Builder dockerfile (part with my personal data is removed):**
LABEL io.k8s.description="Payara Server Full 5.2020" \
    io.k8s.display-name="Payara 5.2020" \
    io.openshift.expose-services="8080:http,8181:https,4848:4848" \
    io.openshift.tags="payara,builder,webserver,html" \
    io.openshift.s2i.destination="${PROJECT_BASE}" \
    io.openshift.s2i.scripts-url="image:///usr/libexec/s2i" 

USER root

RUN mkdir -p ${PROJECT_SOURCES} && mkdir -p /project/init
#WORKDIR "${PROJECT_SOURCES}"

COPY ./s2i/bin/ /usr/libexec/s2i

COPY . /project/init
WORKDIR /project/init
RUN mvn install
WORKDIR "${PROJECT_SOURCES}"

CMD ["/usr/libexec/s2i/usage"]

**Runtime dockerfile:**
LABEL io.k8s.description="Payara Server Full 5.2020" \
    io.k8s.display-name="Payara Runtime 5.2020" \
    io.openshift.expose-services="8080:http,8181:https,4848:4848" \
    io.openshift.tags="payara,runtime,webserver,html" \
    io.openshift.s2i.scripts-url="image:///usr/libexec/s2i" 

USER root

RUN mkdir -p ${PROJECT_SOURCES}

COPY ./s2i/bin/ /usr/libexec/s2i
RUN chown -R payara:payara /usr/libexec/s2i

USER payara
WORKDIR /s2i
