### ISSUE TITLE
Building an image without sti-helper from a file system source fails silently

### ISSUE THREAD

**Issue by accursoft** [openshift/source-to-image#106]
`sti build` using source from the local filesystem and an image without `sti-helper` fails silently when copying the source to `upload/src`, as the upload directory does not exist yet.

The error output from `cp` is suppressed, even with `--loglevel=3`.

**Comment by accursoft** [comment]
Quick fix for `sti build`, in `executor.go:293`:
```go
	} else {		
+		h.fs.Mkdir(filepath.Join(h.request.WorkingDir, "upload"))
		h.fs.Copy(h.request.Source, targetSourceDir)
	}
```

**Comment by bparees** [comment]
thanks for the PR: https://github.com/openshift/source-to-image/pull/107

**Comment by bparees** [comment]
merged https://github.com/openshift/source-to-image/pull/107, good to close this?
