### ISSUE TITLE
Could not fetch URL https://pypi.org/simple/pip/: There was a problem confirming the ssl certificate

### ISSUE THREAD

**Issue by ShahabMokari** [openshift/source-to-image#1061]
When I ran following command:
`s2i rebuild . seldonio/seldon-core-s2i-python3:0.16 my_model`
I get this error message:
`Could not fetch URL https://pypi.org/simple/pip/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/pip/ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1056)'))) - skipping`

I checked my pypi settings and it works fine, it doesn't cause any similar error at all.
I wonder if this error has something to do with the "s2i" underneath works? Any solution?

**Comment by adambkaplan** [comment]
The certificate presented by pypi.org isn't being trusted by your builder image. A few things can cause this:

1. pypi is misconfigured, and is not sending intermediate certificate authorities that are needed to validate the trust chain. Possible, but not likely.
2. You are running s2i behind a proxy, and that proxy uses a self-signed or corporate certificate. In this case you need ensure that your docker engine is configured to trust the proxy's certificate authority.

**Comment by ShahabMokari** [comment]
Thank you @adambkaplan . Yes the problem was the proxy and it is resolved now.
