### ISSUE TITLE
Hash code in download link

### ISSUE THREAD

**Issue by brunowego** [openshift/source-to-image#1064]
I'm try looking a way to download dynamic the last version of Linux zip file, but have a hash on the link. Is possible remove this from the links? Thanks.

```sh
S2I_VERSION="$(curl -ks https://api.github.com/repos/openshift/source-to-image/releases/latest | grep tag_name | cut -d '"' -f 4)"; \
  curl -L "https://github.com/openshift/source-to-image/releases/download/${S2I_VERSION}/source-to-image-${S2I_VERSION}-????????-linux-amd64.tar.gz" | \
    sudo tar -xzC '/usr/local/bin' --strip-components 1 && \
      sudo chmod +x '/usr/local/bin/s2i'
```

**Comment by gustavodescs** [comment]
It'd be nice!!!

**Comment by adambkaplan** [comment]
Agree - the hash is not necessary, especially since GitHub releases are always tied to a tag.

**Comment by Romain-Geissler-1A** [comment]
Hi,

Would it be possible to re-open this issue again ? It's still the case nowadays, and it seems the number of digit of the git commit is not even stable (release 1.6.2 used 9 chars, previous releases used 8 chars, so even trying to "find and shortify" ourselves the commit of the release isn't working reliably...)
