### ISSUE TITLE
"The developer cannot be verified" - error on MacOS

### ISSUE THREAD

**Issue by mhainke** [openshift/source-to-image#1067]
As described in https://github.com/openshift/source-to-image/issues/1021 the error on MacOS still exists with the latest version.
Due to security reasons in company and on our business macs we're only allowed using verified developer software products so a signature would be necessary.
![Error_verified_developer_en](https://user-images.githubusercontent.com/58296390/122741076-e2f2a180-d284-11eb-94a1-c3202d76213d.png)

**Comment by coreydaley** [comment]
/close

As this is an Open Source project, you will need to modify the settings on your operating system to allow executable files from unknown sources.
