### ISSUE TITLE
Build s2i releases for AArch64

### ISSUE THREAD

**Issue by tmds** [openshift/source-to-image#1077]
This is a request to also provide binaries for AArch64 on the [Releases](https://github.com/openshift/source-to-image/releases) page.

cc @adambkaplan @aslicerh @omajid

**Comment by tmds** [comment]
cc @bparees

**Comment by adambkaplan** [comment]
@tmds the cross-compile script gets its list of targeted platforms [here](https://github.com/openshift/source-to-image/blob/master/hack/common.sh#L30-L37). Please feel free to submit a PR adding `linux/aarch64` and `darwin/aarch64` to the cross-compile targets (to support the new M1 Macbooks). Note that the latter may also require us to upgrade the golang version - we should be using 1.16.
