### ISSUE TITLE
`ONBUILD ENTRYPOINT` in base images

### ISSUE THREAD

**Issue by soltysh** [openshift/source-to-image#108]
Since just recently STI allows using arbitrary images for doing build, the problem arises when one of the base images includes [ONBUILD ENTRYPOINT](https://docs.docker.com/reference/builder/#onbuild) instruction. This results in an image where the `.sti/bin/run` command will be appended after the [ENTRYPOINT](https://docs.docker.com/reference/builder/#entrypoint). This results in some weird behavior, depending what was specified as the `ENTRYPOINT`.

**Comment by soltysh** [comment]
Similar problem exists k8s guys, see https://github.com/GoogleCloudPlatform/kubernetes/issues/2316

**Comment by mfojtik** [comment]
@soltysh we should have more modular builds that detect ONBUILD instruction and execute 'on-build' type of build. We should not be trying to do anything smart if the image we consume already have ONBUILD it uses this mechanism to build the application images.

**Comment by mfojtik** [comment]
Fixed in https://github.com/openshift/source-to-image/pull/124 you can now close this issue.
