### ISSUE TITLE
run_cli_script: command not found

### ISSUE THREAD

**Issue by jmanuelgiriboni** [openshift/source-to-image#1084]
I have configured the module and driver for oracle in a jboss image. That has worked fine for me. Through a configuration.cli I am trying to create a datasource. For this I add the configuration in my install.sh file:

```
#!/bin/bash

injected_dir=$1
source /usr/local/s2i/install-common.sh
install_modules ${injected_dir}/modules
configure_drivers ${injected_dir}/drivers.env

S2I_CLI_SCRIPT="${injected_dir}/configuration.cli"

run_cli_script "${S2I_CLI_SCRIPT}"
```

when trying to create the image I get:

`/tmp/src/extensions/install.sh: line 10: run_cli_script: command not found`

I have checked the /usr/local/s2i/install-common.sh file and it doesn't really contain the run_cli_script function

**Comment by coreydaley** [comment]
Where is the command `run_cli_script` located in the image? You might have to update your `PATH` to include the executable.
