### ISSUE TITLE
Add darwin/aarch64 binaries

### ISSUE THREAD

**Issue by galderz** [openshift/source-to-image#1085]

**Comment by coreydaley** [comment]
/close
Please provide more details about what you are wanting and reopen this issue or create a new one.
Are you wanting them included in the `release` or in a build script or ?

**Comment by galderz** [comment]
Well, you offer `darwin/amd64` binaries, any reason not to offer `darwin/aarch64` too? Last release is from 2020 so not sure this is going anywhere.
