### ISSUE TITLE
Add `--platform` flag so user can build for various architectures. 

### ISSUE THREAD

**Issue by matejvasek** [openshift/source-to-image#1087]
The `s2i` images are multiarch which is good. Local docker daemon pulls appropriate image for local architecture. It run much faster than when emulation another architecture.

However this may cause issues whey trying to run image in cluster that has different architecture.
It would be nice to have some flag that forces foreign architecture.

This is currently possible by workaround: just force appropriate image by specifying image with `sha` tag.

**Comment by matejvasek** [comment]
Specifically on colleague has issue using image build locally on `M1` in cluster.

**Comment by coreydaley** [comment]
/close

Feel free to open a pull request with appropriate tests and we will be happy to review it.

**Comment by mshka** [comment]
was this ever implemented?

**Comment by matejvasek** [comment]
I do not think so. @mshka
