### ISSUE TITLE
Issue with multi stage builds

### ISSUE THREAD

**Issue by rprakashg-redhat** [openshift/source-to-image#1095]
Im trying out multi stage build with the cli in an azure devops pipeline with .Net 6.0 and is getting error
It fails on post execute step with this error /bin/sh: /usr/libexec/s2i/assemble-runtime: No such file or directory. 

I tried to create the container image with a Dockerfile using the ubi8/dotnet-60-runtime runtime, copied the dll in to working directory and start the server and it worked fine. 

Unable to do the same with the s2i builder
 

Here is the build command run from the pipeline

s2i build $(Build.Repository.LocalPath) \
        registry.access.redhat.com/ubi8/dotnet-60 --copy \
        --runtime-image registry.access.redhat.com/ubi8/dotnet-60-runtime \
        --runtime-artifact /opt/app-root/src/bin/Release/net6.0/greetingservice.dll \
        --runtime-pull-policy always \
        greeting-service

if I remove the --runtime* parameters it works but need the final image built with just runtime and the .NET dlls

Here is the detail task log from the Azure DevOps pipeline

```

##[debug]found: '/usr/bin/bash'
##[debug]which '/usr/bin/bash'
##[debug]found: '/usr/bin/bash'
##[debug]/usr/bin/bash arg: --noprofile
##[debug]/usr/bin/bash arg: --norc
##[debug]/usr/bin/bash arg: /home/vsts/work/_temp/b74ddb9c-bd1f-4cd2-99b4-f7928b65f529.sh
##[debug]exec tool: /usr/bin/bash
##[debug]arguments:
##[debug]   --noprofile
##[debug]   --norc
##[debug]   /home/vsts/work/_temp/b74ddb9c-bd1f-4cd2-99b4-f7928b65f529.sh
/usr/bin/bash --noprofile --norc /home/vsts/work/_temp/b74ddb9c-bd1f-4cd2-99b4-f7928b65f529.sh
Pulling image "registry.access.redhat.com/ubi8/dotnet-60-runtime" ...
---> Installing application source...
Using SDK: 6.0.107
---> Restoring application dependencies...
Determining projects to restore...
Restored /opt/app-root/src/greetingservice.csproj (in 1.33 sec).
---> Publishing application...
Microsoft (R) Build Engine version 17.0.0+c9eb9dd64 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

greetingservice -> /opt/app-root/src/bin/Release/net6.0/greetingservice.dll
greetingservice -> /opt/app-root/app/
/bin/sh: /usr/libexec/s2i/assemble-runtime: No such file or directory
error: Execution of post execute step failed
Build failed
ERROR: An error occurred: non-zero (13) exit code from registry.access.redhat.com/ubi8/dotnet-60
Error response from daemon: No such image: greeting-service:latest
##[debug]Exit code 1 received from tool '/usr/bin/bash'
##[debug]STDIO streams have closed for tool '/usr/bin/bash'
##[error]Bash exited with code '1'.
##[debug]Processed: ##vso[task.issue type=error;]Bash exited with code '1'.
##[debug]task result: Failed
##[debug]Processed: ##vso[task.complete result=Failed;done=true;]
Finishing: running s2i build

```

**Comment by rprakashg-redhat** [comment]
I should also mention pipeline is using latest ubuntu image that microsoft provides and since s2i requires docker I've also installed latest docker engine using Docker task. See below

```
- task: DockerInstaller@0
    inputs:
      dockerVersion: '20.10.9'
    displayName: Installing container runtime
```

**Comment by rprakashg-redhat** [comment]
When I look in the repo for net runtime image I don't see a script named assemble-runtime in s2i bin directory. I do see one named assemble. Is there a way to specify the correct script path when running s2i build?

**Comment by rprakashg-redhat** [comment]
This message from the logs "/bin/sh: /usr/libexec/s2i/assemble-runtime: No such file or directory"

I looked at the repo https://github.com/redhat-developer/s2i-dotnetcore/tree/master/6.0/runtime/s2i/bin and I don't see an assemble-runtime script.

**Comment by coreydaley** [comment]
Since that runtime image does not supply the `assemble-runtime` script, you will need to provide it as noted here: https://github.com/openshift/source-to-image/blob/30d81a9440f30b472bb32e592b12c1a83a396edd/docs/runtime_image.md#runtime-image-requirements

```
run and assemble-runtime scripts can be placed inside of the runtime image. Scripts from the image will be used as a fallback when user does not provide them in the .s2i/bin directory of the source repository and an alternative location is not specified with the --scripts-url option. The location of the scripts is defined by the value of the io.openshift.s2i.scripts-url label that should be presented on the image. For example, you can set it to image:///usr/libexec/s2i
```

So it looks like you need to place them in your source repositories `.s2i/bin` directory.

**Comment by rprakashg-redhat** [comment]
I can see that copying of the runtime artifact from builder to runtime is being done by s2i build process because when I specify an invalid source path i get an error. i'm trying to figure out what other logic I want to include in the assemble runtime script. Do you have something you can point me as far as guidance or example. Other things I'm wondering is entrypoint and how the application starts up which I can see how that is being done in the s2i dotnet core repo.

**Comment by coreydaley** [comment]
The entrypoint/application startup would be defined in the  registry.access.redhat.com/ubi8/dotnet-60-runtime image I would think. As for the assemble-runtime script, it would be for copying artifacts into their final location within the runtime image or setting up anything needed to run your application.

**Comment by rprakashg-redhat** [comment]
ok so I got little further by adding assemble-runtime script in .s2i/bin directory. I looked at the assemble script for the builder and created a modified version that looks like this

```
#!/bin/bash

set -e

# Create run script in publish folder
cat << EOF >"$DOTNET_APP_PATH/$DOTNET_DEFAULT_CMD"
#!/bin/bash
exec dotnet ${APP_DLL_NAME}
EOF
chmod +x "$DOTNET_APP_PATH/$DOTNET_DEFAULT_CMD"

# fix permissions
fix-permissions /opt/app-root
```

Now it creates the runtime image but when I run the container I get an error and its because the dll that gets generated is a debug version. Is there a way to tell s2i build to create a publish version. Similar to when i run the command below and use the runtime image instead of builder

```
dotnet publish -c Release /p:MicrosoftNETPlatformLibrary=Microsoft.NETCore.App
```

**Comment by rprakashg-redhat** [comment]
I dumped the environment variables into output to see if the --runtime-artifact passed via s2i build command is available for me to use. Couldn't find it so I passed APP_DLL_NAME via --env parameter. Now the issue is the assembly generated by builder is not a publish version. How to tell build command to create a publish version
