### ISSUE TITLE
Unable to use s2i using Amazon EC2 Linux 2023

### ISSUE THREAD

**Issue by SuryaSHalwasia** [openshift/source-to-image#1137]
<img width="715" alt="s2iError" src="https://github.com/openshift/source-to-image/assets/118595736/e6631463-b920-46df-b91f-c005328bc6e3">

I also tried it with sudo command and did docker login. But still it persists for all repositories. Kindly help

**Comment by jmtd** [comment]
> and did docker login

You logged into registry.redhat.io via docker? Could you successfully pull a red hat container directly with docker after doing that?

**Comment by SuryaSHalwasia** [comment]
No, I meant my docker credentials. I'm unable to do it for any repository, not even mine.

**Comment by jmtd** [comment]
To pull from `registry.redhat.io`, you need to be logged into the Red Hat repository with Red Hat credentials.

Luckily, the image you want is one of the UBI images, which is also available from the "unauthenticated" registry: try using `registry.access.redhat.com/ubi8/ruby-27:latest` instead.

**Comment by SuryaSHalwasia** [comment]
I'm unable to use it in Linux for local docker s2i. Its working fine in Windows. It's also not working on WSL.
