### ISSUE TITLE
Make run script optional

### ISSUE THREAD

**Issue by goldmann** [openshift/source-to-image#114]
Currently the `run` script is required. I would like it to have optional. This would let it reuse the `CMD` command which was specified in the image we could possibly extend by creating the builder image.

Imagine the `jboss/wildfly` image. This is upstream image has already defined a `CMD` command. I don't see a reason to duplicate it just to satisfy the requirement of having the `run` command. In my case I would just repeat what I have already defined, but this is unnecessary + adds another file and possibly could confuse people.

Without a `run` script, the `CMD` or `ENTRYPOINT` from the extended image should be used as-is. In case the run script exist - it should override those.

**Comment by bparees** [comment]
+1, sounds good to me...  @csrwng / @soltysh ?

**Comment by mfojtik** [comment]
+1

**Comment by csrwng** [comment]
+1

**Comment by goldmann** [comment]
I'll work on a PR for this, give me a bit, since I'm new to golang :)

**Comment by mfojtik** [comment]
@goldmann the run script is now optional for the OnBuild type of build. You will have to rebase this against the new code layout and make it part of the sti build strategy.

**Comment by goldmann** [comment]
@mfojtik Cool, thanks for heads up, I'll rebase it. I just had no time so far to work on this, but it's on my TODO list.

**Comment by soltysh** [comment]
Migrated from #236, to have both in the same place as they cover the same idea of having optional run script:

I wrote following `Dockerfile`:
```
FROM busybox

WORKDIR /

ONBUILD RUN touch /sti-fake/src/onbuild

ADD scripts/.sti/bin/run /tmp/scripts/
LABEL io.openshift.s2i.scripts-url=image:///tmp/scripts/

ENTRYPOINT /tmp/scripts/run
```
The run scripts is from [here](https://github.com/soltysh/source-to-image/blob/master/test/integration/scripts/.sti/bin/run).

Now I'm running:
```
$ sti build git://github.com/pmorie/simple-html onbuild --loglevel=3

Builder Image:          onbuild
Source:                 git://github.com/pmorie/simple-html
Output Image Tag:
Incremental Build:      enabled
Remove Old Build:       disabled
Force Pull:             enabled
Quiet:                  disabled
Layered Build:          disabled
Docker Endpoint:        unix:///var/run/docker.sock
Docker Pull Config:     /home/maszulik/.dockercfg
Docker Pull User:       soltysh

I0709 11:08:34.487580 14672 docker.go:216] Pulling image onbuild:latest
I0709 11:08:40.536989 14672 docker.go:219] An error was received from the PullImage call: Error: image library/onbuild:latest not found
W0709 11:08:40.537033 14672 strategies.go:42] An error occurred when pulling onbuild: unable to get onbuild:latest. Attempting to use local image.
I0709 11:08:40.539688 14672 onbuild.go:73] Preparing the source code for build
I0709 11:08:40.539818 14672 clone.go:27] Cloning into /tmp/sti166480374/upload/src
I0709 11:08:41.565607 14672 docker.go:199] Image onbuild:latest available locally
I0709 11:08:41.565643 14672 docker.go:305] Image contains io.openshift.s2i.scripts-url set to 'image:///tmp/scripts/'
I0709 11:08:41.566723 14672 docker.go:199] Image onbuild:latest available locally
I0709 11:08:41.566735 14672 docker.go:305] Image contains io.openshift.s2i.scripts-url set to 'image:///tmp/scripts/'
I0709 11:08:41.566758 14672 download.go:57] Using image internal scripts from: image:///tmp/scripts//assemble
I0709 11:08:41.566769 14672 download.go:57] Using image internal scripts from: image:///tmp/scripts//run
I0709 11:08:41.566776 14672 sti.go:186] Using assemble from image:///tmp/scripts/
I0709 11:08:41.566784 14672 sti.go:186] Using run from image:///tmp/scripts/
I0709 11:08:41.566798 14672 onbuild.go:83] Creating application Dockerfile
I0709 11:08:41.566856 14672 main.go:337] An error occurred: No valid entrypoint specified
```
S2I complains about no valid entrypoint, but I do set one in my builder image, imho it should accept that one as well.

**Comment by bparees** [comment]
@PI-Victor far from a priority, but a good opportunity to dig into some of the code.

**Comment by PI-Victor** [comment]
@bparees thanks i'll look into it as soon as possible

**Comment by PI-Victor** [comment]
update: there's a story card for this for a while so this will get fixed by whoever gets the card https://trello.com/c/oDj441HE/571-2-make-run-script-for-s2i-optional

**Comment by soltysh** [comment]
If there's a card already I'd propose closing this in favor of that card, @bparees agreed?

**Comment by gabemontero** [comment]
That is the process we use - @bparees is on PTO - I'll hit the close button.
