### ISSUE TITLE
Allow seeing STI logs when doing integration tests

### ISSUE THREAD

**Issue by soltysh** [openshift/source-to-image#133]
Currently adding `-v` flag to `hack/test-integration.sh` shows only the logs from the integration tests itself. Whereas when searching for test error I'd like also to see STI internal which you turn on with `--loglevel=3`.

**Comment by bparees** [comment]
@gabemontero note that this is in the source-to-image repo, not origin.

**Comment by gabemontero** [comment]
Based on some chatter in #openshift-brno, this item could also encompass creating a debug guide for STI.

**Comment by gabemontero** [comment]
pull 233 delivered the code changes which have been merged into openshift:master, but leaving this open to address the debug guide for STI.

I've solicited (and already received some) feedback on what could feed into a debug guide.  I'll paste that initial feedback here once it seems to have stabilized, and start writing from there.

**Comment by gabemontero** [comment]
The feedback I received regarding an STI debug guide:

From Maciej:
I suggest you have a look at our pkg/errors/errors.go where we've put
'suggestions' to certain errors. Those contain some hints which could
be a good starting point for such guide. Additionally when you'll be
going further down the road don't hesitate to add/change that parts
and update the suggestions or even adding additional errors to make
the output even more clearer. You could also check out some issues
and see if you could get some common errors people had with s2i.

I hope that helps,
Maciej

From Ben:
yeah looking at the closed issues on the source-to-image repo is a great idea.

**Comment by soltysh** [comment]
Don't forget about your initial experience with s2i, all the questions and doubts you were having when doing your first s2i build :wink:

**Comment by gabemontero** [comment]
@soltysh Absolutely ;-) .... though I will say that so far my questions/doubts have not been with the mechanics of using s2i (i.e. items for a debug guide) but more the higher level concepts in the README.md.  Now, some of that most certainly stems from my inexperience with Docker / OpenShift in general.  But as I'm going through this, I'm wondering if some dialogue not just of the s2i process, but how the output produced from running s2i ties in with what customer then do when say manipulating their templates or running oc new-app.  Not sure if I'm ready to articulate that yet (at least not without editing and review for sure), but that could be another thread on this work.

**Comment by gabemontero** [comment]
Here is the PR for the debug guide doc changes:  https://github.com/openshift/source-to-image/pull/242
