### ISSUE TITLE
Make output image optional

### ISSUE THREAD

**Issue by soltysh** [openshift/source-to-image#146]
This comes from here: https://github.com/openshift/origin/pull/1119#discussion-diff-25241156. Generally speaking the idea is to stress test the building process itself without actually producing/committing image. STI currently requires that image and we should not especially when that PR gets into origin.

**Comment by bparees** [comment]
@soltysh are you working on this or do you want me to take a crack at it since it's my downstream change that's affected?

**Comment by soltysh** [comment]
@bparees I haven't started working on it yet, but if you don't mind I'll do it but don't tell @mfojtik, we're competing in number of commits in STI :wink:

**Comment by bparees** [comment]
@danmcp looks like the source-to-image repo teams need adjusting too, I can't assign @soltysh.

**Comment by danmcp** [comment]
@bparees Should be fixed

**Comment by soltysh** [comment]
PR is [here](https://github.com/openshift/source-to-image/pull/147).
