### ISSUE TITLE
support "additive" scripts for STI process

### ISSUE THREAD

**Issue by thoraxe** [openshift/source-to-image#154]
Currently, when customizing the STI scripts, one must take the original script and then add to it.

It would be nice if we supported some kind of additive mechnaism. Either by indicating it in the script, or by having a script of the same name with a number (eg: ##-assemble [happens before assemble] and assemble-## [happens after assemble])

**Comment by mfojtik** [comment]
this logic can be done today by modifying the assemble script to source other scripts.

**Comment by soltysh** [comment]
I don't see any value in that, especially that when you want different behavior you already have the option to modify all the scripts.

**Comment by bparees** [comment]
@mfojtik not sure how your approach would work.  The user would have to first create their own assemble script, and then they couldn't source in the original (image) assemble script because it would be difficult for them to know where to source it from (and in some cases it won't even be present to be sourced)

@soltysh not clear to me what you're objecting to.

**Comment by thoraxe** [comment]
@soltysh The value is that I might want to "add" something extra (eg: calling out to external systems) at the end of the assemble process. But if I copy the current builder image script, when the builder image gets updated, I need to know how to find the updated script, and keep track of when it is updated.

**Comment by soltysh** [comment]
IMHO the amount of work being done in those script is mostly minimal, meaning if you decide to change it or expand it, I'd suggest you take full control over the script.

**Comment by thoraxe** [comment]
Minimal is not zero. And expecting the end user to maintain our build scripts just because they want to add a single curl statement is unreasonable. It is also a regression from V2.

**Comment by soltysh** [comment]
@thoraxe for notifications I'd suggest to use [callbackURL](https://github.com/openshift/source-to-image/blob/master/docs/cli.md#callback-url)

**Comment by thoraxe** [comment]
@soltysh that was a simple example. It is not the only example or use case. Not having an "additive" model means we have gone from an extensible system to a less flexible system.

**Comment by bparees** [comment]
@soltysh I agree with @thoraxe, our current mechanism for modifying assemble/run behavior leaves something to be desired.  Whether this is a priority or not depends on whether we find that users really need to customize those scripts frequently and the nature of those customizations, but if they are needed, additive is the right way to go.

**Comment by soltysh** [comment]
OK, I feel convinced :bowtie:

**Comment by soltysh** [comment]
trelloed: https://trello.com/c/WpdJNDz7/524-as-an-sti-user-i-d-like-to-extend-the-default-scripts

**Comment by bparees** [comment]
closing due to tracking in trello.
