### ISSUE TITLE
An error occurred: non-zero (13) exit code from openshift/wildfly-8-centos

### ISSUE THREAD

**Issue by wangzhezhe** [openshift/source-to-image#155]
when i testing the command : stil build , according to the readme.md I got the follwing error:
sti build git://github.com/bparees/openshift-jee-sample openshift/wildfly-8-centos test-jee-app
I0317 14:39:07.592323 26821 sti.go:111] Building test-jee-app
Cloning into '/tmp/sti424670445/upload/src'...
remote: Counting objects: 29, done.
remote: Compressing objects: 100% (19/19), done.
remote: Total 29 (delta 1), reused 29 (delta 1), pack-reused 0
Receiving objects: 100% (29/29), 22.84 KiB | 12.00 KiB/s, done.
Resolving deltas: 100% (1/1), done.
Checking connectivity... done.
F0317 14:39:55.761126 26821 main.go:201] An error occurred: non-zero (13) exit code from openshift/wildfly-8-centos

anyone could give me some suggestions? thank you!

**Comment by bparees** [comment]
works for me, can you confirm that
1) you're using the latest STI code?
2) docker pull openshift/wildfly-8-centos so you're using the latest STI builder image? (sti does not pull by default, but if you specify --forcePull=true it will)
3) run with --loglevel=5  for more verbose output

in sum, if you can make sure you're on the latest code level (or at least download the latest release) and run:
sti build git://github.com/bparees/openshift-jee-sample openshift/wildfly-8-centos test-jee-app --forcePull=true --loglevel=5

that would help a lot, thanks!

**Comment by wangzhezhe** [comment]
Thans for your suggestions !
I used the  command : go get github.com/openshift/source-to-image  to get the src yesterday the sti version is : sti v0.1-100-gaded451
I was just using the --loglevel=5 flag it seems that some problem with maven ， I'm a little confused with that , could you give me some suggestions , thank you !:

sti build git://github.com/bparees/openshift-jee-sample openshift/wildfly-8-centos test-jee-app --forcePull=true --loglevel=5
I0318 09:03:06.918150 05261 docker.go:163] Pulling image openshift/wildfly-8-centos
I0318 09:03:19.370800 05261 sti.go:111] Building test-jee-app
I0318 09:03:19.371012 05261 clone.go:26] Cloning into /tmp/sti571938123/upload/src
Cloning into '/tmp/sti571938123/upload/src'...
remote: Counting objects: 29, done.
remote: Compressing objects: 100% (19/19), done.
remote: Total 29 (delta 1), reused 29 (delta 1), pack-reused 0
Receiving objects: 100% (29/29), 22.84 KiB | 0 bytes/s, done.
Resolving deltas: 100% (1/1), done.
Checking connectivity... done.
I0318 09:03:20.875596 05261 docker.go:157] Image openshift/wildfly-8-centos available locally
I0318 09:03:20.875638 05261 docker.go:205] Image contains STI_SCRIPTS_URL set to 'https://raw.githubusercontent.com/openshift/wildfly-8-centos/master/.sti/bin'
I0318 09:03:21.253434 05261 download.go:75] Downloaded 'https://raw.githubusercontent.com/openshift/wildfly-8-centos/master/.sti/bin/assemble'
I0318 09:03:21.491028 05261 download.go:75] Downloaded 'https://raw.githubusercontent.com/openshift/wildfly-8-centos/master/.sti/bin/run'
I0318 09:03:21.495735 05261 docker.go:157] Image openshift/wildfly-8-centos available locally
I0318 09:03:21.495862 05261 docker.go:205] Image contains STI_SCRIPTS_URL set to 'https://raw.githubusercontent.com/openshift/wildfly-8-centos/master/.sti/bin'
I0318 09:03:21.738066 05261 download.go:75] Downloaded 'https://raw.githubusercontent.com/openshift/wildfly-8-centos/master/.sti/bin/save-artifacts'
I0318 09:03:21.738201 05261 sti.go:181] Using assemble from https://raw.githubusercontent.com/openshift/wildfly-8-centos/master/.sti/bin
I0318 09:03:21.738221 05261 sti.go:181] Using run from https://raw.githubusercontent.com/openshift/wildfly-8-centos/master/.sti/bin
I0318 09:03:21.738233 05261 sti.go:181] Using save-artifacts from https://raw.githubusercontent.com/openshift/wildfly-8-centos/master/.sti/bin
I0318 09:03:21.738254 05261 sti.go:119] Clean build will be performed
I0318 09:03:21.738266 05261 sti.go:122] Performing source build from git://github.com/bparees/openshift-jee-sample
I0318 09:03:21.738277 05261 sti.go:130] Building test-jee-app
I0318 09:03:21.738286 05261 sti.go:309] Using image name openshift/wildfly-8-centos
I0318 09:03:21.738314 05261 sti.go:313] No .sti/environment provided (no evironment file found in application sources)
I0318 09:03:21.738484 05261 tar.go:133] Adding to tar: /tmp/sti571938123/upload/scripts/assemble as scripts/assemble
I0318 09:03:21.738605 05261 tar.go:133] Adding to tar: /tmp/sti571938123/upload/scripts/run as scripts/run
I0318 09:03:21.738692 05261 tar.go:133] Adding to tar: /tmp/sti571938123/upload/scripts/save-artifacts as scripts/save-artifacts
I0318 09:03:21.739569 05261 tar.go:133] Adding to tar: /tmp/sti571938123/upload/src/.sti/scripts/assemble.ignore as src/.sti/scripts/assemble.ignore
I0318 09:03:21.739666 05261 tar.go:133] Adding to tar: /tmp/sti571938123/upload/src/.sti/scripts/run.ignore as src/.sti/scripts/run.ignore
I0318 09:03:21.739726 05261 tar.go:133] Adding to tar: /tmp/sti571938123/upload/src/README.md as src/README.md
I0318 09:03:21.739797 05261 tar.go:133] Adding to tar: /tmp/sti571938123/upload/src/pom.xml as src/pom.xml
I0318 09:03:21.739921 05261 tar.go:133] Adding to tar: /tmp/sti571938123/upload/src/src/main/java/.gitkeep as src/src/main/java/.gitkeep
I0318 09:03:21.740034 05261 tar.go:133] Adding to tar: /tmp/sti571938123/upload/src/src/main/resources/.gitkeep as src/src/main/resources/.gitkeep
I0318 09:03:21.740140 05261 tar.go:133] Adding to tar: /tmp/sti571938123/upload/src/src/main/webapp/images/jbosscorp_logo.png as src/src/main/webapp/images/jbosscorp_logo.png
I0318 09:03:21.740240 05261 tar.go:133] Adding to tar: /tmp/sti571938123/upload/src/src/main/webapp/index.html as src/src/main/webapp/index.html
I0318 09:03:21.740402 05261 tar.go:133] Adding to tar: /tmp/sti571938123/upload/src/src/main/webapp/snoop.jsp as src/src/main/webapp/snoop.jsp
I0318 09:03:21.743517 05261 docker.go:157] Image openshift/wildfly-8-centos available locally
I0318 09:03:21.743572 05261 docker.go:242] Both scripts and untarred source will be placed in '/tmp'
I0318 09:03:21.743595 05261 docker.go:277] Creating container using config: {Hostname: Domainname: User: Memory:0 MemorySwap:0 CpuShares:0 CpuSet: AttachStdin:false AttachStdout:true AttachStderr:false PortSpecs:[] ExposedPorts:map[] Tty:false OpenStdin:true StdinOnce:true Env:[] Cmd:[/bin/sh -c tar -C /tmp -xf - && /tmp/scripts/assemble] Dns:[] Image:openshift/wildfly-8-centos Volumes:map[] VolumesFrom: WorkingDir: Entrypoint:[] NetworkDisabled:false OnBuild:[]}
I0318 09:03:21.793504 05261 docker.go:284] Attaching to container
I0318 09:03:21.798064 05261 docker.go:332] Starting container
I0318 09:03:21.886568 05261 docker.go:342] Waiting for container
I0318 09:03:21.901483 05261 sti.go:371] Found pom.xml... attempting to build with 'mvn -e package -Popenshift -DskipTests'
I0318 09:03:22.087198 05261 sti.go:371] Apache Maven 3.0.5 (r01de14724cdef164cd33c7c8c2fe155faf9602da; 2013-02-19 13:51:28+0000)
I0318 09:03:22.087531 05261 sti.go:371] Maven home: /usr/local/apache-maven-3.0.5
I0318 09:03:22.087770 05261 sti.go:371] Java version: 1.7.0_75, vendor: Oracle Corporation
I0318 09:03:22.087990 05261 sti.go:371] Java home: /usr/lib/jvm/java-1.7.0-openjdk-1.7.0.75-2.5.4.2.el7_0.x86_64/jre
I0318 09:03:22.088294 05261 sti.go:371] Default locale: en_US, platform encoding: ANSI_X3.4-1968
I0318 09:03:22.089557 05261 sti.go:371] OS name: "linux", version: "3.13.0-24-generic", arch: "amd64", family: "unix"
I0318 09:03:23.111946 05261 sti.go:371] [INFO] Scanning for projects...
I0318 09:03:23.194690 05261 sti.go:371] [INFO]                                                                         
I0318 09:03:23.194878 05261 sti.go:371] [INFO] ------------------------------------------------------------------------
I0318 09:03:23.194892 05261 sti.go:371] [INFO] Building SampleApp 1.0
I0318 09:03:23.194952 05261 sti.go:371] [INFO] ------------------------------------------------------------------------
I0318 09:03:23.366386 05261 sti.go:371] Downloading: http://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-resources-plugin/2.5/maven-resources-plugin-2.5.pom
[INFO] ------------------------------------------------------------------------
I0318 09:04:03.476590 05261 sti.go:371] [INFO] BUILD FAILURE
I0318 09:04:03.476608 05261 sti.go:371] [INFO] ------------------------------------------------------------------------
I0318 09:04:03.476628 05261 sti.go:371] [INFO] Total time: 40.382s
I0318 09:04:03.476661 05261 sti.go:371] [INFO] Finished at: Wed Mar 18 01:04:03 UTC 2015
I0318 09:04:03.541803 05261 sti.go:371] [INFO] Final Memory: 6M/55M
I0318 09:04:03.541954 05261 sti.go:371] [INFO] ------------------------------------------------------------------------
I0318 09:04:03.544298 05261 sti.go:371] [ERROR] Plugin org.apache.maven.plugins:maven-resources-plugin:2.5 or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.apache.maven.plugins:maven-resources-plugin:jar:2.5: Could not transfer artifact org.apache.maven.plugins:maven-resources-plugin:pom:2.5 from/to central (http://repo.maven.apache.org/maven2): repo.maven.apache.org: Name or service not known: Unknown host repo.maven.apache.org: Name or service not known -> [Help 1]
I0318 09:04:03.544403 05261 sti.go:371] [ERROR] 
I0318 09:04:03.544497 05261 sti.go:371] [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
I0318 09:04:03.544606 05261 sti.go:371] [ERROR] Re-run Maven using the -X switch to enable full debug logging.
I0318 09:04:03.544681 05261 sti.go:371] [ERROR] 
I0318 09:04:03.544843 05261 sti.go:371] [ERROR] For more information about the errors and possible solutions, please read the following articles:
I0318 09:04:03.545055 05261 sti.go:371] [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginResolutionException
I0318 09:04:03.558189 05261 sti.go:371] Aborting due to error code 1 from mvn package
I0318 09:04:03.621052 05261 docker.go:348] Container exited
I0318 09:04:03.628846 05261 cleanup.go:24] Removing temporary directory /tmp/sti571938123
I0318 09:04:03.628885 05261 fs.go:99] Removing directory '/tmp/sti571938123'
F0318 09:04:03.634406 05261 main.go:201] An error occurred: non-zero (13) exit code from openshift/wildfly-8-centos

**Comment by bparees** [comment]
It looks like your container is unable to reach repo.maven.apache.org.

On your system, can you run  "docker run -it centos /bin/bash"  and then from within the prompt run "ping repo.maven.apache.org"?  (also confirm you can ping it directly from your host).

it seems like perhaps something is broken in your docker networking that's preventing containers from eaching remote sites, which obviously will prevent the maven build from succeeding since it needs to download dependencies.  (In fact it looks like a DNS lookup failure... are you running a local DNS server?  what's in your /etc/resolv.conf on your host?)

**Comment by wangzhezhe** [comment]
It' worked , it's maybe the network problems.
Thanks for your patience!

**Comment by bparees** [comment]
no problem, glad you got it working.
