### ISSUE TITLE
Send output to stdout, not stderr

### ISSUE THREAD

**Issue by goldmann** [openshift/source-to-image#156]
Currently everything is sent to `stderr`. The console output should be sent to `stdout` instead. Only errors should be sent to `stderr`.

**Comment by soltysh** [comment]
Yeah, I'd like that too, see [here](https://github.com/openshift/source-to-image/blob/master/cmd/sti/main.go#L181-L183). I guess I need to work on a PR to glog.

**Comment by smarterclayton** [comment]
glog won't accept PRs.  We probably need to switch to a different library in our code that expects to run in these contexts (glog isn't really intended for the "display output to end users" use case).  A good starting point would be implementing the core static glog API against log (including V) as a drop in package replacement for glog.

**Comment by soltysh** [comment]
@smarterclayton maybe before implementing that, we could spent some time and investigate other logging libraries like https://github.com/Sirupsen/logrus or https://github.com/op/go-loggin or others (?), I remember the first being mentioned upstream.

**Comment by smarterclayton** [comment]
All of those bring more complexity which we don't have time for.  I also don't want to move away from glog on the server..

**Comment by soltysh** [comment]
Also see [this comment from origin](https://github.com/openshift/origin/issues/1647#issuecomment-100244784).

**Comment by bparees** [comment]
@smarterclayton we any closer to moving away from glog or otherwise gaining this capability in a logging tool?

**Comment by bparees** [comment]
@jim-minter we've moved to using a glog wrapper in s2i which should make this possible now (if it hasn't already fixed this problem)

**Comment by jim-minter** [comment]
@bparees 

Is the general intention here:
relevant container output (stdout, stderr) typically goes to s2i stdout
arbitrary s2i logging goes to s2i stderr
?

Are logging prefixes wanted or not wanted on the container output bit?

**Comment by bparees** [comment]
@jim-minter 
logging prefix on container output behavior should stay the same.  I believe the current behavior is you don't get logging prefixes on it unless you specify over a certain loglevel (because if you specify a high enough loglevel, we punt all logging to glog).

as for the general intention, in an ideal world:
s2i info/debug goes to stdout
s2i warn/error goes to stderr
container stdout goes to stdout
container stderr goes to stderr

**Comment by geoberle** [comment]
what is the status on this?
i can see that build output in openshift 3.10 is showing up in aggregated logging as loglevel "err".

**Comment by acrozes** [comment]
On OpenShift 3.11, I find some errors like this on: 
```
    "message": "Push successful\n",
    "level": "err",
```
Extract from : 
```
{
  "_index": "project.xl-prod.fb892726-a6d3-11e9-8831-005056b07bff.2019.07.15",
  "_type": "com.redhat.viaq.common",
  "_id": "MzBjMzg2MjItZ...",
  "_version": 1,
  "_score": null,
  "_source": {
    "docker": {
      "container_id": "3d5eb6fab0562..."
    },
    "kubernetes": {
      "container_name": "sti-build",
      "namespace_name": "xl-prod",
      "pod_name": "xld-production-000-php-3-build",
      "pod_id": "37397d1c.....",
      "labels": {
        "openshift_io/build_name": "xld-production-000-php-3"
      },
      "host": "....",
      "master_url": "https://kubernetes.default.svc.cluster.local",
      "namespace_id": "fb892726-...."
    },
    "message": "Push successful\n",
    "level": "err",
    "hostname": "....",
    "pipeline_metadata": {
      "collector": {
        "ipaddr4": "10....",
        "ipaddr6": "fe80....",
        "inputname": "fluent-plugin-systemd",
        "name": "fluentd",
        "received_at": "2019-07-15T11:25:39.562394+00:00",
        "version": "0.12.43 1.6.0"
      }
    },
    "@timestamp": "2019-07-15T11:25:23.118798+00:00",
    "viaq_msg_id": "MzBjMzg2...."
  },
  "fields": {
    "@timestamp": [
      1563189923118
    ],
    "pipeline_metadata.collector.received_at": [
      1563189939562
    ]
  },
  "highlight": {
    "level": [
      "@kibana-highlighted-field@err@/kibana-highlighted-field@"
    ],
    "message": [
      "@kibana-highlighted-field@Push@/kibana-highlighted-field@ @kibana-highlighted-field@successful@/kibana-highlighted-field@\n"
    ]
  },
  "sort": [
    1563189923118
  ]
}
```

Is it linked with this issues ?

**Comment by adambkaplan** [comment]
@geoberle I'm in the process of moving s2i's log tool from glog to [klog](https://github.com/kubernetes/klog), which will give us this capability.

**Comment by spolti** [comment]
can we reopen this?
