### ISSUE TITLE
Add support for STI config file to exists in GIT repo

### ISSUE THREAD

**Issue by mfojtik** [openshift/source-to-image#158]
I think this will help to have much cleaner user experience with STI command line, where the user don't need to know all possible options/docker image names/etc to just trigger the STI build.

I'm proposing that this command:

```
sti build https://github.com/user/repo
```

will clone the GIT repo, then check if there is 'sti.json' (naming TBD) file and prefill the STI build options automatically (reusing the `--use-config` logic)

**Comment by mfojtik** [comment]
FYI, this is more like future feature proposal, not need to be done now (as the STI is not stable itself anyway).

**Comment by soltysh** [comment]
Let's stick to what you already proposed [here](https://github.com/openshift/source-to-image/blob/master/pkg/config/config.go#L15):wink: But generally :+1:

**Comment by bparees** [comment]
so would you have an sti.json in the root of the repo and the sti.json would specify a contextDir?  or would contextDir still have to be passed to sti explicitly and we'd look for sti.json in that contextDir?

**Comment by mfojtik** [comment]
@bparees everything will be set in sti.json (or .stifile) you just do `sti build <repo>`

**Comment by bparees** [comment]
@mfojtik this means i can only have one sti.json per repo.  so i can't have multiple projects in a single repo and use contextDir to pick specific ones.

**Comment by soltysh** [comment]
@bparees actually you could have both, either you'd specify `contextDir` in that case it'll be only one per repo, or you don't in which case we'll do default to current and you can still use `--context-dir` flag to point to that dir in the repo in which all the other options (builder image, name, etc.) are defined. At least that's my understanding.

**Comment by bparees** [comment]
@soltysh that definitely wasn't my interpretation of the proposal since that would mean a two-phase processing of options:

1) process options (including --contextDir)
2) clone the repo
3) if --contextDir is set, change to contextDir
3) check for sti.json in current directory
4) process sti.json options if present
5) change to contextDir from sti.json if it had one
6) continue build.

**Comment by soltysh** [comment]
@bparees yeah, maybe I went to far with that. It's still open discussion :wink: right?

**Comment by mfojtik** [comment]
@bparees I think the approach I proposed will work for >80% of cases (where users have just one application in GIT repo). For the next 20% they can either not support it or have some default stifile and use contextDir manually.

**Comment by mfojtik** [comment]
btw. it also makes me things about if 'contextDir' is the proper name for this option and if it should not be 'sourceDir' or 'sourcePath'

**Comment by bparees** [comment]
@mfojtik yeah that's fine, i just want it clearly stated how those scenarios would play out/interact.

**Comment by gabemontero** [comment]
OK ... Ben and I are conferring as I type.  To confirm / close the discussion, I'm going to
1) leverage a sti.json file that sits in <repo root>/.sti/cfg
2) format is the same as .stifile ... (Ben want to move away from the file name, so we are not reusing it here)
3) you can specify a contextDir in that file
4) if --context-dir is specified on the cmd line, that overrides the setting in sti.json, but we still look for the sti.json off the root of the repo, not the context-dir location

**Comment by gabemontero** [comment]
@bparees @mfojtik hey guys - quick question:  I'm seeing in the sti code that the git cloning of the source repo today is done off of Config.WorkingDir/upload/src (or upload/tmp in the case of the context dir before the copy).  For the src repo cloning to be done as part of the form "sti build <src repo url>" becoming allowing with this issue, do we want to follow that same pattern, or was the thought that we clone in the current dir?

**Comment by bparees** [comment]
>  For the src repo cloning to be done as part of the form "sti build " becoming allowing with this issue

hm?

**Comment by bparees** [comment]
and I would not expect this change to affect cloning.  it just affects what you look for (for config parameters) after you've done the clone.

**Comment by gabemontero** [comment]
ok ... yes, upon reflection,  my question is fundamentally grounded in *where* I insert the examination of the new file.  I think I've connected a couple of dots with this exchange - reworking my prototype - thx.

**Comment by gabemontero** [comment]
Though my previous insertion point avoided changes to the min num of param checks ... still, it may be the lesser pain point to move the search for the s2i.json file.

**Comment by gabemontero** [comment]
@bparees Parsing the s2i.json at the point of the code where sti clones the source repo today won't work as the code is constructed.  My old friend strategies.GetStrategy(cfg) comes into play.  It needs config.BuilderImage set (which we ultimately want to get from the s2i.json), so it can get the docker image and inspect the image's OnBuild flag.

The code then constructs a separate builder based on whether it is ONBUILD or not.

Based on the doc, I believe we want to support Docker's "ONBUILD" as part of sti.

It seems like a Chicken and the egg scenario ... I don't see a way around the extra git clone, but am welcome to suggestions.

**Comment by bparees** [comment]
if i understand you correctly you're saying we work with the builder image parameter before we do the git clone?

**Comment by gabemontero** [comment]
Yes that is correct.

**Comment by bparees** [comment]
hm.  refactor!  :)

how bad does the refactor look like it would be?

**Comment by soltysh** [comment]
You're gonna have to extract the `Prepare`, it's already a separate interface @mfojtik did. Currently both sti and onbuild use the implementation of `Prepare` from sti and call them directly in `Build` method. Maybe we should change that and the code which is getting strategy and runs the build should invoke Prepare, Build and Clean. This way we'll be able to modify parts of the actual build process per strategy, still keeping consistency, I hope.

**Comment by mfojtik** [comment]
closing as this is being trelloed :-) @gabemontero will provide link to trello card, also @gabemontero can you link this issue to trello so we don't loose the discussion...

**Comment by gabemontero** [comment]
Trello card link:  https://trello.com/c/4kdTqLc7/641-r-d-into-what-sti-build-related-parameters-are-useful-to-store-into-a-build-s-source-repo

And this issue is linked in that trello card as well.

Thanks everyone.
