### ISSUE TITLE
Need to show output of assemble script run in default loglevel

### ISSUE THREAD

**Issue by mfojtik** [openshift/source-to-image#159]
As the output of assemble is most like the most important thing end-users will want to see we should display it by default (or have special option for that --output-assemble?).

In Origin we should show this output, nothing else is important for the end user (if the end user is not debugging issue in STI itself)

**Comment by soltysh** [comment]
:+1:

**Comment by mfojtik** [comment]
@bparees - want to cleanup the Build logs in Origin :-)

**Comment by bparees** [comment]
@mfojtik the request actually came from @smarterclayton but yes...  the only thing i'd add is that it's probably worth printing out where we pulled the various scripts from.  That's pretty commonly useful information that shouldn't require special debug settings to see, imho.  If someone thinks they're using assemble from their repo and they're not, it'd be nice to be able to quickly see that.

**Comment by mfojtik** [comment]
STI now prints only assemble output/errors
