### ISSUE TITLE
Does sti support the building from a war file?

### ISSUE THREAD

**Issue by wangzhezhe** [openshift/source-to-image#162]
Hi, I want to know if sti support the building from a war file to an image. I only find the examples about building from the  source code into an image. But I found in this page : https://github.com/openshift/openshift-pep/blob/master/openshift-pep-013-openshift-3.md
in the " Build " section , it says:
"Example: post a WAR file to a source-to-images build that results in that WAR being deployed"
Could you give me some suggestions that how to build a war file to an image by sti build ? thank you!

**Comment by bparees** [comment]
the existing wildfly STI image supports two things:
1) supply a source repo containing a pom.xml that produces a war file.
  - in this case the resulting war file will be deployed in the resulting image
2) supply a "source" repo containing a war file pre-built
  - in this case the war file in the repo will be deployed in the resulting image.

either way, this is controlled by the assemble script logic and not by STI itself.   you can see the logic here:
https://github.com/openshift/wildfly-8-centos/blob/master/.sti/bin/assemble#L169
https://github.com/openshift/wildfly-8-centos/blob/master/.sti/bin/assemble#L200

does this answer your question?

**Comment by wangzhezhe** [comment]
Thanks for your suggestions! 
It seems that the .war file should be put in the ‘development’ directory?
I have tested the basic example just like:
sti build /home/wangzhe/Downloads/test openshift/wildfly-8-centos  test-jee-app9 --forcePull=true --loglevel=5
（I have already put a .war (an simple java web example) file which could run normally by tomcat in the /home/wangzhe/Downloads/test/deployments)
the image was built successfuly 
then i'm trying to use:
docker run  --rm -i -p 8080:8080 -t test-jee-app9
it seems the .war file could not be deployed successfully 
could you give me some suggestions? Thank you!
......
......

04:49:21,245 ERROR [org.jboss.msc.service.fail] (MSC service thread 1-3) MSC000001: Failed to start service jboss.undertow.deployment.default-server.default-host./book.UndertowDeploymentInfoService: org.jboss.msc.service.StartException in service jboss.undertow.deployment.default-server.default-host./book.UndertowDeploymentInfoService: Failed to start service
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.run(ServiceControllerImpl.java:1904) [jboss-msc-1.2.2.Final.jar:1.2.2.Final]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [rt.jar:1.7.0_75]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [rt.jar:1.7.0_75]
	at java.lang.Thread.run(Thread.java:745) [rt.jar:1.7.0_75]
Caused by: java.lang.IllegalArgumentException: UT010012: Listener class class com.sun.faces.application.WebappLifecycleListener must implement at least one listener interface
	at io.undertow.servlet.api.ListenerInfo.<init>(ListenerInfo.java:41)
	at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService.addListener(UndertowDeploymentInfoService.java:1163)
	at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService.createServletConfig(UndertowDeploymentInfoService.java:748)
	at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService.start(UndertowDeploymentInfoService.java:245)
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.startService(ServiceControllerImpl.java:1948) [jboss-msc-1.2.2.Final.jar:1.2.2.Final]
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.run(ServiceControllerImpl.java:1881) [jboss-msc-1.2.2.Final.jar:1.2.2.Final]
	... 3 more

04:49:21,314 ERROR [org.jboss.as.controller.management-operation] (Controller Boot Thread) JBAS014613: Operation ("deploy") failed - address: ([("deployment" => "book.war")]) - failure description: {"JBAS014671: Failed services" => {"jboss.undertow.deployment.default-server.default-host./book.UndertowDeploymentInfoService" => "org.jboss.msc.service.StartException in service jboss.undertow.deployment.default-server.default-host./book.UndertowDeploymentInfoService: Failed to start service
    Caused by: java.lang.IllegalArgumentException: UT010012: Listener class class com.sun.faces.application.WebappLifecycleListener must implement at least one listener interface"}}
04:49:21,348 INFO  [org.jboss.as.server] (ServerService Thread Pool -- 31) JBAS018559: Deployed "book.war" (runtime-name : "book.war")
04:49:21,351 INFO  [org.jboss.as.controller] (Controller Boot Thread) JBAS014774: Service status report
JBAS014777:   Services which failed to start:      service jboss.undertow.deployment.default-server.default-host./book.UndertowDeploymentInfoService: org.jboss.msc.service.StartException in service jboss.undertow.deployment.default-server.default-host./book.UndertowDeploymentInfoService: Failed to start service

04:49:21,370 INFO  [org.jboss.as] (Controller Boot Thread) JBAS015961: Http management interface listening on http://0.0.0.0:9990/management
04:49:21,370 INFO  [org.jboss.as] (Controller Boot Thread) JBAS015951: Admin console listening on http://0.0.0.0:9990
04:49:21,371 ERROR [org.jboss.as] (Controller Boot Thread) JBAS015875: WildFly 8.1.0.Final "Kenny" started (with errors) in 6884ms - Started 783 of 842 services (3 services failed or missing dependencies, 102 services are lazy, passive or on-demand)
04:49:21,680 INFO  [org.hibernate.validator.internal.util.Version] (MSC service thread 1-4) HV000001: Hibernate Validator 5.1.0.Final
04:49:21,785 INFO  [org.jboss.as.server.deployment] (MSC service thread 1-3) JBAS015877: Stopped deployment book.war (runtime-name: book.war) in 202ms
04:49:21,866 INFO  [org.jboss.as.server] (DeploymentScanner-threads - 2) JBAS018558: Undeployed "book.war" (runtime-name: "book.war")
04:49:21,880 INFO  [org.jboss.as.controller] (DeploymentScanner-threads - 2) JBAS014774: Service status report
JBAS014775:    New missing/unsatisfied dependencies:
      service jboss.deployment.unit."book.war".component."com.sun.faces.application.WebappLifecycleListener".START (missing) dependents: [service jboss.deployment.unit."book.war".deploymentCompleteService, service jboss.undertow.deployment.default-server.default-host./book] 
      service jboss.deployment.unit."book.war".component."com.sun.faces.config.ConfigureListener".START (missing) dependents: [service jboss.deployment.unit."book.war".deploymentCompleteService, service jboss.undertow.deployment.default-server.default-host./book] 
      service jboss.deployment.unit."book.war".component."com.sun.faces.taglib.html_basic.ColumnTag".START (missing) dependents: [service jboss.deployment.unit."book.war".deploymentCompleteService, service jboss.undertow.deployment.default-server.default-host./book] 
      service jboss.deployment.unit."book.war".component."com.sun.faces.taglib.html_basic.CommandButtonTag".START (missing) dependents: [service jboss.deployment.unit."book.war".deploymentCompleteService, service jboss.undertow.deployment.default-server.default-host./book] 
      service jboss.deployment.unit."book.war".component."com.sun.faces.taglib.html_basic.CommandLinkTag".START (missing) dependents: [service jboss.deployment.unit."book.war".deploymentCompleteService, service jboss.undertow.deployment.default-server.default-host./book] 
      service jboss.deployment.unit."book.war".component."com.sun.faces.taglib.html_basic.DataTableTag".START (missing) dependents: [service jboss.deployment.unit."book.war".deploymentCompleteService, service jboss.undertow.deployment.default-server.default-host./book] 
      service jboss.deployment.unit."book.war".component."com.sun.faces.taglib.html_basic.FormTag".START (missing) dependents: [service jboss.deployment.unit."book.war".deploymentCompleteService, service jboss.undertow.deployment.default-server.default-host./book] 

...
...

**Comment by bparees** [comment]
Yes the deployments directory is the correct place to put the war file, it appears you did that correctly as it looks like wildfly picked up the war:
04:49:21,866 INFO org.jboss.as.server JBAS018558: Undeployed "book.war" (runtime-name: "book.war")

I don't have any specific advice to offer you on the particular error your application is getting, it looks like either a configuration error (might need to provide a custom standalone.xml in your app) or a missing modules (you can also supply modules in your app source repo)

**Comment by wangzhezhe** [comment]
Thans for your suggesion , it maybe the conflict of the package in the app , now it's worked !

**Comment by bparees** [comment]
Great!
