### ISSUE TITLE
git clone, sti create, make results in failure

### ISSUE THREAD

**Issue by ianmiell** [openshift/source-to-image#165]
```
$ git clone https://github.com/openshift/source-to-image
$ cd source-to-image/
$ make
docker build -t test .
Sending build context to Docker daemon 14.34 kB
Sending build context to Docker daemon 
Step 0 : FROM openshift/base-centos7
# Executing 4 build triggers
Trigger 0, COPY ./.sti/bin/ /usr/local/sti
Step 0 : COPY ./.sti/bin/ /usr/local/sti
 ---> Using cache
Trigger 1, COPY ./contrib/ /opt/openshift
Step 0 : COPY ./contrib/ /opt/openshift
INFO[0000] contrib/: no such file or directory          
Makefile:5: recipe for target 'build' failed
make: *** [build] Error 1
```

Adding a contrib folder works. If adding the folder as part of create is the solution, I can code this.

Before I do this, have I misunderstood something though?

**Comment by soltysh** [comment]
@ianmiell thanks for trying out STI! Looking at your output I'm guessing these are not all steps you did. Above output suggests you tried building STI, which should work without any problems, I just did that:
```
$ git clone https://github.com/openshift/source-to-image
$ cd source-to-image/
$ make
hack/build-go.sh
++ Building go targets for linux/amd64: cmd/sti
++ Placing binaries
$
```
But that part of the output:
```
Step 0 : FROM openshift/base-centos7
# Executing 4 build triggers
```
suggests you're trying to create a builder image based on our [openshift/base-centos7](https://github.com/openshift/sti-base/) image. Which requires having `contrib` directory like we do have it in our builder images (see [sti-python](https://github.com/openshift/sti-python) or [sti-ruby](https://github.com/openshift/sti-ruby)). Can you explain me in more detail what are you trying to achieve?

**Comment by soltysh** [comment]
@ianmiell do you have any update on this issue? If it's not applicable anymore, can you please close it?

**Comment by bparees** [comment]
closing due to age+no response, feel free to reopen.
