### ISSUE TITLE
README.md still makes reference to --clean

### ISSUE THREAD

**Issue by cianclarke** [openshift/source-to-image#169]
https://github.com/openshift/source-to-image/blame/master/README.md#L92
    
    If a save-artifacts script exists, a prior image already exists, and the --clean option is not used, the workflow is as follows:
    
I'm not sure how this line should read, as the operation seems to have been flipped too? --clean=true is --incremental=false - but should probably update README. Would be good to also

**Comment by bparees** [comment]
thanks, clarified it here:
https://github.com/openshift/source-to-image/pull/170
