### ISSUE TITLE
must override run and assemble scripts together

### ISSUE THREAD

**Issue by bparees** [openshift/source-to-image#173]
if you only supply one or the other, the resulting image fails to build.

**Comment by bparees** [comment]
@soltysh I thought we had an issue for this but i couldn't find one..feel free to close if you have one.

**Comment by soltysh** [comment]
I have an open PR for that #167, but it's far from being ready, as I've find some bugs in it, it's on top of my todo list.

**Comment by soltysh** [comment]
@bparees can you close this one?
