### ISSUE TITLE
environment variables can't contain commas

### ISSUE THREAD

**Issue by jmtd** [openshift/source-to-image#174]
Since you split the env command-line argument on ',', the environment variable values themselves can't contain commas. I hit this trying to pass "-P some-repo,some-other-repo" to maven via `MAVEN_ARGS`.

**Comment by mfojtik** [comment]
Good catch. Is this broken also when you quote them ?

**Comment by mfojtik** [comment]
@bparees we are still broken at this:

π ~/sandbox/ruby sti build --loglevel=5 -e "MAVEN_ARGS='-P some-repo,some-other-repo'" file:///home/mfojtik/sandbox/ruby openshift/ruby-20-centos7 foo
I0519 14:20:51.410089 17228 util.go:34] Using mi@mifo.sk credentials for pulling openshift/ruby-20-centos7
I0519 14:20:51.410222 17228 main.go:239] An error occurred: malformed env string: some-other-repo'

This is a problem in our parser where we treat the ',' as delimiter between environment variables

**Comment by mfojtik** [comment]
@bparees @jmtd I was looking into how to fix this and it does not seems trivial (we will have to honor quotes inside env segments, deal with single vs. double vs. no quotes, etc... @jmtd can you use the `.sti/environment` file in your source code repository to set those variables? That way should work.

For STI I think we will have to implement -E <file> option where you can pass the `environment` file in cases where just simple command line arguments is failing.

@bparees does it sound reasonable?

**Comment by bparees** [comment]
@mfojtik could we just take multiple -e args instead of a comma separated list?

**Comment by mfojtik** [comment]
@bparees i'm not sure if cobra can handle that

**Comment by bparees** [comment]
@mfojtik if it can't, -E seems reasonable.

This will break if you create an openshift buildconfig w/ STI strategy env values with commas, right?  That seems like the bigger issue at the moment and adding -E won't fix that (unless we do more work to turn the env var list into a file in openshift)

**Comment by mfojtik** [comment]
@bparees I just tried to mock STI and set Environment to:

```go
			req.Environment = map[string]string{
				"MAVEN_OPTS": "-P foo,bar,test",
			}
```

and it works, so this is only command line parsing problem and it is not affecting the Source strategy in OpenShift.

**Comment by bparees** [comment]
@mfojtik cool, marking p3 then.
