### ISSUE TITLE
Set the WORKDIR to the path where the application code lives

### ISSUE THREAD

**Issue by rhcarvalho** [openshift/source-to-image#175]
It would be useful to have the `WORKDIR` set to the path where your application code lives in images created with STI.

That way, it would be possible to call scripts you might have in your code base passing its relative path to `docker exec` or `osc exec`.

`docker exec -it <container> bash` would start in the "right" directory.

If there is no opposition to this idea, I could implement this myself given a pointer to where to start :smile: 
[pkg/create/templates/docker.go](https://github.com/openshift/source-to-image/blob/master/pkg/create/templates/docker.go)?

**Comment by bparees** [comment]
templates would be one place, you'll always want to update our existing Dockerfiles for our STI images.  or better, set it in the sti-base Dockerfile since it should be common to all the downstream images.

**Comment by rhcarvalho** [comment]
@bparees it turns out that [the WORKDIR is set in the base image](https://github.com/openshift/sti-base/blob/ad0585fad74260dd32f858a307beb84c42ec5cbd/Dockerfile#L58), and `docker run/exec ... pwd` on images generated by `sti` produces the expected output:

```bash
$ sti build git://github.com/pmorie/simple-ruby openshift/ruby-20-centos7 test-ruby-app
$ docker run --rm -it test-ruby-app pwd
/opt/openshift/src
```

So the problem seems to be within `osc exec` / `kubectl exec`. I'm looking into that.

**Comment by bparees** [comment]
@rhcarvalho so this can be closed?

**Comment by rhcarvalho** [comment]
@bparees yes, closed. `kubectl exec` is documented to set the working directory for the command to root ('/'), just don't know why (yet).
