### ISSUE TITLE
Move the complete doc over to the real site

### ISSUE THREAD

**Issue by thesteve0** [openshift/source-to-image#176]
Please move the contents from the readme.md over to the real site

http://docs.openshift.org/latest/creating_images/sti.html

This way all your good work can be seen by the rest of the world

**Comment by bparees** [comment]
what do you feel should be on that page that isn't already there?

frankly I think there's probably already too much there...  STI deserves its own doc as it is its own project, and openshfit should simply be referencing that doc.  What we have in place now was a compromise.

@soltysh

**Comment by thesteve0** [comment]
We cleared this up in IRC. They are same doc, I was just fooled by formatting. I agree that if this is a standalone tool then the docs should live here and linked from the main doc site. I would say you still need a more detailed walk through on how to construct an STI image. My doc should help with that.
