### ISSUE TITLE
Convert STI_SCRIPTS_URL environment variable into LABEL

### ISSUE THREAD

**Issue by mfojtik** [openshift/source-to-image#183]
Currently, we use `ENV STI_SCRIPTS_URL image://...` in our Docker images. This variable points into default location for the STI scripts used for the STI build. I think it would be nice to switch this from the ENV variable to LABEL instructions. There are several benefits of doing that:

* We can namespace (`openshift.io/sti-scripts-url`)
* UI would be able to import this and offer user a text box where they can change the default location to a custom one
* We will have one less ENV variable in Docker images

@bparees @soltysh thoughts?

**Comment by soltysh** [comment]
I'm not sure at this point we could replace env with proposed label, but definitely we can support both, where the label would take precedence, if both defined.

**Comment by mfojtik** [comment]
@soltysh yeah, although I'm not sure if we want to keep this backward compatible (we already require Docker 1.6).

**Comment by soltysh** [comment]
If so we'd have to do this before this sprint ends, @bparees any objections?

**Comment by bparees** [comment]
if we're not going to keep backwards compatibility, we need to go tell the middleware guys to do this in all their images...   i'm not really convinced this should be a label though.  it's easier to consume as an env variable, isn't it?

**Comment by soltysh** [comment]
@bparees only sti uses that value, so it does make sense to be label rather than env. Env are meant to be consumed inside the image, whereas labels by the tools using those images, that's at least my understanding. Based on that `STI_SCRIPTS_URL` ideally fits into label category.

**Comment by bparees** [comment]
@soltysh yeah ok i was thinking we used it differently.  in anycase we need to support both w/ label taking precedence.

**Comment by bparees** [comment]
also update STI-base to use this.

**Comment by soltysh** [comment]
@mfojtik please close this since #198 got merged.
