### ISSUE TITLE
Switch to dashed case from the camelCase in sti CLI

### ISSUE THREAD

**Issue by mfojtik** [openshift/source-to-image#187]
Since origin also now use dashed syntax, we should switch our options as well, so instead of `--forcePull` just `--force-pull`. Same for other options...

@bparees @soltysh should be easy fix and should be done before we release 'sti' standalone (or somebody package it ;-)

**Comment by soltysh** [comment]
:+1:

**Comment by bparees** [comment]
ok w/ me.
