### ISSUE TITLE
0.5 - Linux only release?

### ISSUE THREAD

**Issue by Maxim-Filimonov** [openshift/source-to-image#192]
Hi is there a reason why [last release](https://github.com/openshift/source-to-image/releases/tag/v0.5) is linux only? All previous ones where available for mac and windows too.

**Comment by mfojtik** [comment]
@Maxim-Filimonov we tried to build Windows && Max binaries, but we have some problems with Go cross-compiler. This should be there as well soon, sorry for trouble.

**Comment by Maxim-Filimonov** [comment]
@mfojtik ah ok thanks. I have tried to build it locally but as I don't have Go installed on mac, building it inside docker linux container causes the same errors with cross platform build :(

**Comment by bparees** [comment]
new release with windows + mac binaries available here:
https://github.com/openshift/source-to-image/releases/tag/v0.5.1
