### ISSUE TITLE
Docker caching and incremental build

### ISSUE THREAD

**Issue by Maxim-Filimonov** [openshift/source-to-image#196]
Hi,
I'm wondering am I holding it wrong or have I found a problem with sti. I have the following images:
Base image -> ruby x version and all other deps like imagemagick and etc. Based on Dockerfile. Built by docker build in seconds.
Test image -> build by STI based on base image. Contains all gems from gemfile.
Staging image -> build by STI based on base image. Excludes test and development gems from gemfile, precompiles assets for staging. 
Production image -> build by STI based on base image. Excludes test and development gems from gemfile, precompiles assets for production. 

Sti allowed me to make process of building staging and production image significantly faster but at the end of the day I need to push those images to registry(docker hub). And that is where I found a problem.  

If I look at our staging/production image I have a bunch of layers from base image and one giant layer (442MB) from sti:
```
IMAGE               CREATED             CREATED BY                                      SIZE
6b2883b78afc        20 minutes ago      /bin/sh -c tar -C /tmp -xf - && /tmp/scripts/   442.5 MB
```
 I'm ok with pushing this layer once BUT it gets regenerated EVERY time I run it. So even if building of the image is quite fast pushing it to the registry and then pulling it takes more time especially as number of servers grows. 
Is there a way to cache this layer somehow and build on top of it ?

**Comment by soltysh** [comment]
@Maxim-Filimonov I'm assuming you're building the `save-artifacts` on your own. Since you're using the incremental build there are two elements that come into play when looking at the size of the resulting image, specifically the final layer that STI adds. The first is the artifacts you get from previous image and the second your new dependencies. You can verify what exactly gets into your new image from `save-artifacts` by using `--save-temp-dir` and looking at the working dir STI creates and check how many dependencies gets there, maybe that's too big. I'm not aware of any other files that STI would add into the image. Could you provide us with exact steps to reproduce that situation?

**Comment by Maxim-Filimonov** [comment]
Ok I think I'm not being clear. My problem is really not the size of the image. Example:
When I add a new Ruby gem I would expect to push only difference between old bundle and new bundle with a new gem installed. Currently, I need to push the whole bundle all over again.
Moreover, even if i don't add any new gems I need to push new bundle as its one giant layer which gets regenerated every time.
Thinking of solution:
Im thinking that removing bundle install from sti and installing it inside base image instead should help as base image will be cached.
For assets precompilation I then just need to cache one artifact - tmp/cache/assets folder as having this folder from previous build makes a very big difference in speed.

**Comment by Maxim-Filimonov** [comment]
Sti scripts https://gist.github.com/Maxim-Filimonov/8a0407ba1d905c931ebb

**Comment by bparees** [comment]
Yeah, unfortunately we need to be measured about how many "common bundles" we install in the ruby image we provide.  However you are more than welcome to take our image(dockerfile) and add a layer that adds the bundles you want, and use that as your custom STI ruby builder, to avoid this problem.  That's part of the intended flexibility of STI.

Unfortunately there's no way, given how STI is architected, to create the "built application layer" as anything other than a single layer (we have no way to download your dependencies, commit a layer, and then perform the rest of the build and commit a final layer).  Doing so would require multiple docker run/commit steps to perform each layer.

**Comment by bparees** [comment]
@Maxim-Filimonov I don't think there's anything additional we can do here, did my comment answer your question/clarify why it works the way it does?

**Comment by Maxim-Filimonov** [comment]
Yeah all good thx

**Comment by Maxim-Filimonov** [comment]
I had some more thoughts about this one and it might be possible to do what I was trying to speed up bundler without increasing image size that much.
I was thinking of the following flow:
- bundle install (part of assemble)
- save bundler gem cache not /bundle folder
- remove bundle cache folder as we don't need it to be part of final image
- docker commit final image
Incremental build
- restore bundle cache
- bundle install using cache (will only add new gems to /bundle)
- save bundler gem cache as newer cache for future builds
- remove bundle cache folder as we don't need it to be part of final image
- docker commit final image
I presume that this last step would still produce giant layer of 200 MB. But at least that is less then 400MB(cache + gems)
@bparees do you think it's possible to implement with current set of scripts?

**Comment by bparees** [comment]
I don't understand how your incremental flow works....
Where are you saving the bundler gem cache to, given that you remove it so it's not a part of the final image? and where are you restoring it from in the incremental build?

incremental builds can help with the build speed, but i thought your primary concern was avoiding having the gems in the same layer as the app code because that necessitates pushing a large layer on every build.

The simple idea of cleaning up the gem cache before committing the image seems reasonable enough if that cache is really a separate copy of the gems from what the application is using but it seems odd that that would be the case....  i'm not a bundler expert.  @mfojtik ?

**Comment by Maxim-Filimonov** [comment]
Yeah it is still split from app source already. There are two conflicting problems:
- Build speed
- Size of layer to push
The faster we make the build the bigger the layer becomes because we are increasing the diff. The middle ground would be to remove the artefacts folders (vendor/cache) from the container before we commit to as it is not required for running the app anyway. However, as we need vendor/cache it to speed up `bundle install` we need to restore it just before we run `bundle install` and then remove it again before we commit.

My point is to remove bundler cache after it is saved to tar but before the image is committed.
For gist on bundler: 
http://bundler.io/v1.1/bundle_install.html:
```
While installing gems, Bundler will check vendor/cache and then your system's gems. If a gem isn't cached or installed, Bundler will try to install it from the sources you have declared in your Gemfile.
```
Cache is essentially a local copy of gems zipped.
For example in my current image: 
```
du -hd1 /root/bundle/ruby/2.1.0/
288M	/root/bundle/ruby/2.1.0/gems
824K	/root/bundle/ruby/2.1.0/build_info
888K	/root/bundle/ruby/2.1.0/specifications
28M	/root/bundle/ruby/2.1.0/extensions
38M	/root/bundle/ruby/2.1.0/cache
168K	/root/bundle/ruby/2.1.0/bin
4.0K	/root/bundle/ruby/2.1.0/doc
355M	/root/bundle/ruby/2.1.0/
```

**Comment by bparees** [comment]
There is no "after it's saved to tar" unfortunately.  When you do an incremental build, the saved artifacts are being restored from the previous version of the application image.  The flow is...  

first run:
1) STI starts a container using the base builder image (eg ruby-20-centos7) and tells it to run the assemble script
2) assemble executes, pulling down any dependencies, builds app, produces app image containing both.
3) STI commits the container with one new layer(that new layer has your deps and your app logic), this is your application image.


second run(incremental):
1) start a container using the app image created above, run save-artifacts script inside that container.
2) save-artifacts archives content from the image (eg dependencies) and outputs it
3) STI receives that output
4) STI starts a new container using the base builder image and injects your source+the content from (3).
5) assemble script runs, does not need to download deps if they were included in what was injected as part of (4).

I suppose you could write a set of scripts in which:
1) assemble uploads the artifacts it wants to save to an external location(eg scp server) after it pulls deps down
2) save-artifacts fetches them from that location and outputs them as if it was extracting them from the application image

would that work for you?  maybe that's what you were proposing and i just missed it. apologies if so.

**Comment by bparees** [comment]
(The summary point i'm trying to make is the default incremental implementation assumes the deps you want to reuse exist in the previous application image you are incrementing on, so if you remove the deps from the app image before committing it, you will have nothing to restore/reuse later, unless you do the external storage idea).

**Comment by Maxim-Filimonov** [comment]
Hm... I see yeah it becomes quite problematic then. I'll close this for now as I think it's enough explanation of how it works. Thanks @bparees for your patience
