### ISSUE TITLE
UID isolation

### ISSUE THREAD

**Issue by soltysh** [openshift/source-to-image#199]
Per @smarterclayton comment on my recent PR, I'm opening issue to verify if following comment is still valid (from https://github.com/openshift/source-to-image/blob/master/test/integration/images/sti-fake/Dockerfile)
```
RUN mkdir -p /sti-fake/src && \
# FIXME: The 'default' user has conflicting UID (1000). This should be fixed in
#        how source-to-image handles UID's during isolation.
#
    deluser default
```

**Comment by soltysh** [comment]
I've tested this without this line as well as with other images, namely `openshift/python-33-centos7` the is no problem. I'm guessing this is a leftover from the time we were doing bind-mounts to copy the sources of the application. Since we currently stream it with tar, the resulting files are created with permissions of the user defined in the dockerfile. @bparees @smarterclayton @csrwng @mfojtik correct me if I'm wrong, if so I suggest removing this comment as it's not valid anymore.

**Comment by bparees** [comment]
@soltysh sounds plausible to me.

**Comment by csrwng** [comment]
@soltysh I'm fine with removing that line. Doesn't seem like it's needed.

**Comment by soltysh** [comment]
Closing per #179.
