### ISSUE TITLE
Add ONBUILD integration tests

### ISSUE THREAD

**Issue by soltysh** [openshift/source-to-image#203]
Currently we don't have **ANY** integration tests for onbuild strategy. We should have a couple at least!

**Comment by ewolinetz** [comment]
It also looks like when we do a `make test` we do not run our integration tests along with the other tests.  

[centos@ip-10-155-13-188 source-to-image]$ make test
hack/test-go.sh  
. . .
?   	github.com/openshift/source-to-image/test/integration	[no test files]

**Comment by mfojtik** [comment]
@ewolinetz @soltysh @bparees we can close this now?

**Comment by soltysh** [comment]
I think so.
