### ISSUE TITLE
Remove "sti" from the LABEL

### ISSUE THREAD

**Issue by mfojtik** [openshift/source-to-image#205]
Should be "source". Also the namespace should be without "openshift".

@bparees @soltysh FYI

**Comment by soltysh** [comment]
If we do, it would be good to own that namespace/domain, maybe. That's the preferred way of dealing with this. But :+1:

**Comment by bparees** [comment]
you can use s2i for the label.   io.s2i.location

how's that?

but again if we're doing this, let's get it done before 3.0 ships so we don't have to support the existing label definition.

**Comment by soltysh** [comment]
Deal it'll be io.s2i.lcation and io.s2i.scripts. And yes we're aware of
that, that's why we created this issue to have it ready today before
updating sti in origin.  Btw if we promote s2i name should we also rename
our binary to s2i?

**Comment by bparees** [comment]
i'd really like to minimize the amount of time we're spending updating examples/doc/etc on this, so i'd suggest not renaming the binary.
