### ISSUE TITLE
Review code in cmd/sti/main.go#newCmdBuild to extract what might be useful to have in origin.

### ISSUE THREAD

**Issue by soltysh** [openshift/source-to-image#206]
Per [this comment](https://github.com/openshift/source-to-image/pull/204#discussion_r31258661), we should review the code in cmd/sti/main.go#newCmdBuild and extract as much as we can from there into separate package that we'll be able to reduce the amount of duplication in code in S2I and origin.

**Comment by coreydaley** [comment]
@bparees 
The only code that I see in newCmdBuild that MIGHT be useful to factor out into something reusable is https://github.com/openshift/source-to-image/blob/master/pkg/cmd/cli/cmd/build.go#L100-L123

So, with that being said:
- Do you see other code that would be useful?
- Is it worth it?
- Is this github issue still relevant?

**Comment by bparees** [comment]
not worth it.
