### ISSUE TITLE
Permission denied when using the STI scripts from application repo

### ISSUE THREAD

**Issue by jhadvig** [openshift/source-to-image#211]
When doing the STI build manually with an app repository which contains app specific STI scripts, user will hit and permission issue when running the built image.
`permission denied
FATA[0001] Error response from daemon: Cannot start container 287fcc0b96584f370ca012f4ca339d37a40f61f684e86f9ef4c0a620c325eb85: [8] System error: permission denied `

I've tested this scenario with OpenShift Origin using STI build and I didn't hit the issue. 
It's cause by the fact that we are storing the STI scripts in the `/tmp/` dir.

@mfojtik @bparees @soltysh I know we spoke about this issue. 
Putting it here so we keep track of it.

**Comment by mfojtik** [comment]
@jhadvig so if running the image in OpenShift Pod is not an issue, then I think we should mark this as post-3.0 (and probably trello this)

**Comment by mfojtik** [comment]
@jhadvig is this still happening?

**Comment by jhadvig** [comment]
@mfojtik I couldn't reproduce this issue. Closing this one.
