### ISSUE TITLE
Add sti rebuild command

### ISSUE THREAD

**Issue by mfojtik** [openshift/source-to-image#219]
Since we now have labels set for the output images, we can easily add the `sti rebuild <image>` command. If the <image> has the S2I labels set, we know what is the source and what was the builder image. 

Just to clarify what `sti rebuild my-app-image` will do:

* Pull the image (of not available locally)
* Read the labels (if exists)
* Create `Config{}` for build
* Build the image using the ref,source-location and the recorded builder image name
* Tag the new output image

This command can help users to rebuild their application locally when the builder image is updated for example. Also, since we don't control the dependencies installed during assemble, the rebuild will attempt to update the dependencies installed. I also think that we should enable the incremental build by default when we doing rebuild to speed it up.

@soltysh proposed to add `--latest-version` option that will cause to ignore the `ref` or `commitID` labels. I'm fine with that as long as we are not over-complicating this simple command :-)

**Comment by mfojtik** [comment]
@bparees @soltysh

**Comment by soltysh** [comment]
Yeah, my suggestion was the `--latest-version` would only ignore `commitID`, the `ref` would still be the same.

**Comment by bparees** [comment]
i like it.

**Comment by mfojtik** [comment]
Included in https://github.com/openshift/source-to-image/releases/tag/v1.0.1
