### ISSUE TITLE
rename sti binary to s2i

### ISSUE THREAD

**Issue by bparees** [openshift/source-to-image#244]
Need to 
- [ ] have build produce an s2i binary instead of sti binary
- [ ] have build produce a symlink sti that points to s2i
- [ ] add logic to the CLI processing so that if the binary is invoked with the "sti" name, print a deprecation warning
- [ ] update remaining doc to say s2i.
- [ ] update image tests to use "s2i" instead of "sti" invocation.

**Comment by bparees** [comment]
@gabemontero @soltysh fyi.

**Comment by soltysh** [comment]
You have my full support in doing this, I'll buy you kofola for that :wink:

**Comment by bparees** [comment]
Vinea?

**Comment by soltysh** [comment]
Deal, it can be even both :smile:

**Comment by soltysh** [comment]
btw. @bparees do you have somebody interested in doing this?

**Comment by bparees** [comment]
@soltysh i kinda thought i might get to it, but no, no one has explicitly raised their hand.

**Comment by soltysh** [comment]
Then I am, I still want to keep my no. 1 s2i commiter :crown: Besides I initiated that change some time ago, and I want to finish that. That will make @thesteve0 especially happy :smile:

**Comment by mfojtik** [comment]
this also includes updating all our images tests :-)

**Comment by soltysh** [comment]
This is GH magic, I can see @mfojtik comment in my inbox, but no sign of it
on gh issue, lol.
@bparees can you add updating image tests to the list of actions?

**Comment by bparees** [comment]
He must have deleted his comment.

**Comment by mfojtik** [comment]
I deleted it because I realized that it is already noted in @bparees checklist :-)

**Comment by soltysh** [comment]
It wasn't explicitly.
