### ISSUE TITLE
Tar exclusions are not configurable

### ISSUE THREAD

**Issue by vbehar** [openshift/source-to-image#246]
Hi,

it seems like the tar processing use a defaultExclusionPattern (for .git metadata), but this is not configurable.

It would be nice to be able to configure the exclusionPattern, for example using a --exclude flag in the sti build command.

Thanks,
Vincent

**Comment by bparees** [comment]
dupe of https://github.com/openshift/source-to-image/issues/197 ?

**Comment by vbehar** [comment]
Yes indeed, I'll close this one
