### ISSUE TITLE
Option to suppress "You are using <source> location that is not valid GIT repository" warning

### ISSUE THREAD

**Issue by functionalprogrammer** [openshift/source-to-image#251]
Building from local source issues a warning:
`You are using <source> location that is not valid GIT repository. The source code information will not be stored into the output image. Use this image only for local testing and development`
For those of us who don't use git (we're people too!) there's no alternative. It would be nice to have an option to suppress the warning to keep noise out of the build log.

**Comment by mfojtik** [comment]
@functionalprogrammer problem is that without labels that are added when using the GIT repository some functions does not work right:

1) `sti rebuild` won't work
2) OpenShift will not recognize the labels, etc..

One solution would be to leverage the `-q` option that will turn off this warning.

**Comment by soltysh** [comment]
@functionalprogrammer does #252 fix your problem? If so please close this issue.

**Comment by functionalprogrammer** [comment]
I actually need the rest of the build output, so `-q` isn't really an option for me. Not a huge deal though, I wouldn't complain if this went to the bottom of the list :-)

**Comment by bparees** [comment]
@mfojtik we should make sure we're sending warnings to stderr and build output to stdout.  @functionalprogrammer could then filter that way.

**Comment by soltysh** [comment]
@bparees we are sending all output to stderr (see #156), this should be fixed with the new logging system we were talking about some time ago.

**Comment by mfojtik** [comment]
@functionalprogrammer @soltysh @bparees we added this message to warn a user that using local folders won't produce the same image in terms of metadata than a build using GIT source. Some functions like `sti rebuild` won't work correctly. 

The real solution for people that don't use GIT is to add support for more SCM which is planned (there is a Trello card for that). So then less folks should see this warning.

**Comment by bparees** [comment]
as long as it's going to stderr it shouldn't be a problem since you can filter w/ appropriate redirect/piping.  @functionalprogrammer ?

**Comment by bparees** [comment]
@functionalprogrammer closing since we haven't heard from you but if you have a reason why filtering based on stderr/stdout isn't sufficient, feel free to reopen.

**Comment by bparees** [comment]
oops, realized we are sending everything to stderr still.  reopening.

**Comment by mfojtik** [comment]
@bparees I would suggest to open a new issue for "Sanitize usage of stderr and stdout by S2I"

**Comment by soltysh** [comment]
@mfojtik there already is one #156

**Comment by functionalprogrammer** [comment]
No longer getting this warning, so closing.
