### ISSUE TITLE
"tag" in sti command --help causes confusion

### ISSUE THREAD

**Issue by nak3** [openshift/source-to-image#269]
For example...

~~~
$ sti rebuild --help
...
Usage: 
  sti rebuild <image> [<new-tag>] [flags]
~~~

~~~
$ sti build --help
...
Usage: 
  sti build <source> <image> [<tag>] [flags]
~~~

It seems that `<tag>` and `<new-tag>` means image name. However, in general docker, "tag" means `latest`, `v3` and so on.

**Comment by nak3** [comment]
`$ docker build` also has `--tag` option to add Repository name. So it may be not wrong. 
Is it just me or it causes confusion?

**Comment by bparees** [comment]
The syntax follows docker's build syntax which uses the "-t" tag argument
to tag the result image of a docker build.

Tag can mean either what you described, or the entire name of the image.

Ben Parees | OpenShift

**Comment by nak3** [comment]
Thank you. I understand. It looks like no problem. Please feel free to close this issue.
