### ISSUE TITLE
.bowerrc file is getting skipped from project root

### ISSUE THREAD

**Issue by nitintutlani** [openshift/source-to-image#270]
It appears s2i is skipping dot files like .gitignore, .bowerrc etc. I have not tested this exhaustively but I was not able to use .bowerrc until I renamed it to bowerrc and then renamed it back during assemble.

**Comment by bparees** [comment]
@gabemontero can you take a look at this?  sounds like maybe we aren't using the right args when we tar up the src to inject it into the builder image.

@nitintutlani can you provide the exact command line you're running so we can try it with your repository and builder image?

**Comment by gabemontero** [comment]
@bparees will do

**Comment by nitintutlani** [comment]
@bparees I have a fairly simple html/js website and an openshift source strategy buildConfig. Inside .sti/bin/assemble script as expected the source is delivered inside `tmp/src/*` but all dot files are missing including .bowerrc . There really is no command I am running in particular. Unfortunately this particular work is in a private repo.

**Comment by gabemontero** [comment]
and internet search of "tar hidden file" unveiled a common theme of appending a dot ( `.`) to the dir path.

For example:  http://www.digitesters.com/linux-include-hidden-files-in-tar-archive/

If our go based tar implementation holds to this behavior, I believe the solution here could be a simple one - append a dot to the directory parameter that serves as the source for the tar file.

I'll try an experiment and see if it holds.

**Comment by gabemontero** [comment]
Hmm ... actually, some of the search links say just specifying the dir, without say a `*` wildcard, should also include dot/hidden files.  And my experiments with both the current form and adding a `.` including files like .gitignore.

@nitintutlani could you re-run `sti` with the `--save-temp-dir=true" option?  In the `/tmp/sti<random number>` directory there should be a tar file called `tar<random number>`.  Could you then run `tar tvf ` on that file and tell us if the dot files in question are listed?

thanks

**Comment by nitintutlani** [comment]
As per this log: `I0820 11:24:52.274283 20065 tar.go:133] Adding to tar: /tmp/sti008846339/upload/src/.bowerrc as src/.bowerrc`, `/bowerrc` file is inside the tmp/src folder.
There is a bug in my code. Due to presence of artifacts I could not move the entire `src` folder. I need to move regular files and hidden files in two steps:
```
mv /tmp/src/* ${APP_ROOT}/.
mv /tmp/src/.* ${APP_ROOT}/.
```
Thanks for your support and sorry for trouble.
