### ISSUE TITLE
Add --use-local-image option

### ISSUE THREAD

**Issue by mfojtik** [openshift/source-to-image#273]
The `--force-pull=false` seems pretty confusing if somebody wants to do local development and don't want S2I to pull images from external registries. I would suggest to add `--use-local-image` to be more explicit.  We don't need to change anything in `Config`. If user set this option, it will be just an alias for `--force-pull=false`.

**Comment by mfojtik** [comment]
@soltysh @goldmann @bparees FYI

**Comment by mfojtik** [comment]
```console
13:52 < mfojtik> i propose adding new option
13:52 < mfojtik> supplementary to --force-pull
13:52 < mfojtik> 1) it will act just as --force-pull=false
13:52 < mfojtik> 2) it will fail if image not found
13:52 < mfojtik> 3) it won't even attempt to connect to external registry

```

**Comment by soltysh** [comment]
:+1:

**Comment by bparees** [comment]
just setting force-pull to false will not have all the behaviors you describe, specifically it will not prevent pulling images from remote registries if they are not present locally.

**Comment by bparees** [comment]
so you'd have to add other new logic.

**Comment by mfojtik** [comment]
@bparees reason why I think this is important is to support the CI/CD flows that users do with the S2I tool, where they build the image elsewhere (or locally) and then they use `s2i` binary to build the application image they test.

We should have option that turns `s2i` into mode that it won't even attempt to call remote registry.

**Comment by bparees** [comment]
@mfojtik ok that makes sense.  but you can't just have it be an alias for "force-pull=false" then, you need to actually go change a lot of logic where we do things like CheckAndPull.

**Comment by soltysh** [comment]
@bparees maybe that's a good chance to clean the logic around force-pull, we'll deprecate it and educate users about the new flag. Even at the cost of having slightly different behavior.

**Comment by bparees** [comment]
@soltysh force pull has value.  there are three distinct options here:
1) always pull (force pull)
2) pull if not present (what you get today w/ force pull =false)
3) never pull (what @mfojtik is proposing).

we can't get rid of (1).

**Comment by soltysh** [comment]
@bparees in that case instead of adding additional boolean flag, how about refactoring this into `--pull-policy`, witch values `always`, `never`, `ifnotpresent`?

**Comment by soltysh** [comment]
I just realized I've seen those values somewhere :wink: and I did, [here](https://github.com/kubernetes/kubernetes/blob/master/pkg/api/types.go#L869-L871)

**Comment by mfojtik** [comment]
@bparees assign this to me pls :-)

**Comment by bparees** [comment]
@mfojtik please describe what you plan to implement, as we've discussed a couple variations in this thread.

**Comment by mfojtik** [comment]
@bparees the pull-policy option seems most reasonable to me. It will match the kubernetes style and also fixes the problem with pulling (--pull-policy=never will trigger the behavior we want here)
