### ISSUE TITLE
Rename sti leftovers

### ISSUE THREAD

**Issue by soltysh** [openshift/source-to-image#275]
This is a followup task to #244 and #250. I'm copying here the notes from my PR regarding what still needs to be changed (in that particular order):

* [x] change `.sti/` directory to `.s2i/` directory
* [x] change `/tmp/sti/` to `/tmp/s2i` or other not using `/tmp` directory
* [ ] change internals to use s2i everywhere

**Comment by mfojtik** [comment]
@soltysh 

1) We will have to support both .sti and .s2i at least for some time

**Comment by soltysh** [comment]
Yes, I'm aware of that.

**Comment by rhcarvalho** [comment]
Related issue (/tmp): #211

**Comment by php-coder** [comment]
I see that https://github.com/openshift/source-to-image/blob/master/docs/builder_image.md#s2i-builder-image-requirements uses `sti`: "... should be aware of the two basic requirements for the best possible **sti** performance"

**Comment by bparees** [comment]
@mfojtik I think the work you did recently should be sufficient to close this?

**Comment by soltysh** [comment]
From quick glimpse:
- [ ] .sticonfig 
- [ ] some docs leftovers
- [ ] .sti/environment

All addressed in #408 . The remaining stuff are only internals, but that will be done over time, I guess.

**Comment by mfojtik** [comment]
@bparees I hope so + what @soltysh said. will close this as soon as #408 gets merged.

**Comment by bparees** [comment]
#408 merged.
