### ISSUE TITLE
build image fails on run ALLOWED_UIDS

### ISSUE THREAD

**Issue by mwiora** [openshift/source-to-image#279]
moving from openshift/origin to sti - https://github.com/openshift/origin/issues/4409:

# DESCRIPTION

today I've been running a fresh installation of openshift using the ansible cookbook and got the new openshift origin 1.0.5 version.
Everything seems fine (existing docker images are getting deployed), but for the builder-part the process seems currently not working. It requires the specification of an UserID.

This is the oc logs build output.
The same happens when initiating the build either from web console as well as from command line using the admin credentials.

cheers,
Matthias

# ENV
```
# oc version
oc v1.0.5-4-g3eee7d2-dirty
kubernetes v1.1.0-alpha.0-1605-g44c91b1
```

# REPRODUCE
```
oc new-app wildfly~http://openshift-code.domain.tld/root/some_visualizer.git --name=some3
``` 

# ISSUE:

```
[root@oc-master ~]# oc logs some3-1-build
I0828 11:39:41.279331       1 sti.go:74] The value of ALLOWED_UIDS is [1-]
I0828 11:39:41.286395       1 docker.go:211] Image openshift/wildfly-8-centos@sha256:457764eea8327d00ebb99686bc3a22f602f3f75e57e9f953c80d0af2de4b1884 available locally
I0828 11:39:41.286471       1 sti.go:96] Creating a new S2I builder with build config: "Builder Image:\t\topenshift/wildfly-8-centos@sha256:457764eea8327d00ebb99686bc3a22f602f3f75e57e9f953c80d0af2de4b1884\nSource:\t\t\thttp://openshift-code.domain.tld/root/some_visualizer.git\nOutput Image Tag:\t172.30.155.100:5000/dry1/some3:latest\nEnvironment:\t\tOPENSHIFT_BUILD_NAMESPACE=dry1,OPENSHIFT_BUILD_SOURCE=http://openshift-code.domain.tld/root/some_visualizer.git,OPENSHIFT_BUILD_NAME=some3-1\nIncremental Build:\tdisabled\nRemove Old Build:\tdisabled\nForce Pull:\t\tdisabled\nQuiet:\t\t\tdisabled\nLayered Build:\t\tdisabled\nDocker Endpoint:\tunix:///var/run/docker.sock\n"
I0828 11:39:41.293608       1 docker.go:211] Image openshift/wildfly-8-centos@sha256:457764eea8327d00ebb99686bc3a22f602f3f75e57e9f953c80d0af2de4b1884 available locally
F0828 11:39:41.302923       1 builder.go:47] Build error: image "openshift/wildfly-8-centos@sha256:457764eea8327d00ebb99686bc3a22f602f3f75e57e9f953c80d0af2de4b1884" must specify a user that is numeric and within the range of allowed users
```

reinstalled the whole environment - the same happens again.
the issue does not occur when using https://github.com/openshift/nodejs-ex#master and the node.js builder image

**Comment by mfojtik** [comment]
This seems more like a origin bug when parsing the ALLOWED_UIDS.... The `1-` means the container is not allowed to run as root. @soltysh can you take a look?

**Comment by mwiora** [comment]
info: getting the current sti-master-branch and running "s2i build http://openshift-code.domain.tld/root/some3_visualizer.git openshift/wildfly-8-centos some3_visualizer" the image is being build fine.

@all: where are these ALLOWED_UIDS defined?

**Comment by mfojtik** [comment]
We should:

* Fail the build immediately when this happen (can't run as root). The builder should not even be created.
* Give users much more helpful information about how to fix this (presumably something is wrong in the ansible configuration that disallows running build containers as root).

**Comment by mwiora** [comment]
the question is, why this build must be run as root - actually I see no reason for this - which are the circumstances when a build must be run with such privileges?

**Comment by mfojtik** [comment]
@mwiora running the build manually (with `s2i build`) and in OpenShift are two different things :-) OpenShift have security policies defined that prevents you running container as root (they run with random user ID). The build is a special case, I don't think we currently support running builds as non-root. I don't know where exactly is this behavior configured, but @soltysh or @csrwng or @liggitt should know.

**Comment by mfojtik** [comment]
@mwiora it must build as root because it is creating container on the node and need to have access to the host/hode docker socket...

**Comment by mwiora** [comment]
@mfojtik - thank you very much for these explenations! I hope we'll be able to find the mysterious switch soon!

**Comment by mwiora** [comment]
already logged in origin issue:
workaround found on https://trello.com/c/eGlfwXcs/603-3-prevent-sti-builder-images-from-running-as-root-build-security

I had to run:
```
oc edit scc privileged -n default
```
and add the last line.
```
users:
- system:serviceaccount:default:router
- system:serviceaccount:default:registry
- system:serviceaccount:openshift-infra:build-controller
- system:serviceaccount:sample01:builder
```
while sample01 is my project name...

**Comment by mfojtik** [comment]
@mwiora nice one!

**Comment by soltysh** [comment]
I'll leave that to @csrwng, iirc he was reworking s2i to allow building as non-root.

**Comment by bparees** [comment]
@csrwng pretty sure you documented this but i'm not seeing it offhand... can you confirm/provide the link here and i think we can close this?

**Comment by csrwng** [comment]
https://docs.openshift.org/latest/creating_images/guidelines.html#openshift-specific-guidelines under "Support arbitrary user ids"

**Comment by csrwng** [comment]
@mwiora if possible, you should create a builder image that specifies a non-root default user. This is a new requirement in release 1.0.5.

**Comment by soltysh** [comment]
@csrwng looking at the attached output @mwiora  is using our sti-wildfly image, which has that [user set to 1001](https://github.com/openshift/sti-wildfly/blob/master/8.1/Dockerfile#L44), unless @mwiora is using an older image where that was not specified yet.

**Comment by csrwng** [comment]
@soltysh sorry didn't notice that. Yes, it looks like it's an outdated image. @mwiora pls make sure that you pull the latest sti-wildfly image.

**Comment by liggitt** [comment]
The build pod is created by the build controller, which is already in the privileged SCC... you shouldn't need to add a particular builder service account.

**Comment by mwiora** [comment]
@soltysh @csrwng actually I'm using the latest checked in version, which is being pulled by the ansible script (run by 4:00 PM UTC). By default it would be helpful for newbies to be able to use the provided image without any customizations. Maybe it would be possible to merge the latest version of the sti-image to the origin bundle.

**Comment by soltysh** [comment]
You're right, they should be usable without any customization and that's the case for other images. We need to check sti-wildfly then, there must be some bug in that case.

**Comment by mwiora** [comment]
1+

**Comment by csrwng** [comment]
@mwiora I see the issue, the image streams json file was referring to the wrong image (which had 'widfly' as the user, instead of a numeric user). @bparees fixed it recently: https://github.com/openshift/origin/pull/4343

**Comment by mwiora** [comment]
@csrwng thx!

**Comment by soltysh** [comment]
@mwiora if that solves your problem can you please close the issue?

**Comment by mwiora** [comment]
works like a charm with the updated templates. would be great when merged to the current master branch.

**Comment by vikaschoudhary16** [comment]
Encountered same issue on ocp v3.5.5.9. Though @liggitt point makes sense that build controller is already in privileged users but still, got builder pod running only after adding :

> system:serviceaccount:<project-name>:builder

as @mwiora suggested above.

**Comment by wuxinglec** [comment]
> sample01

https://docs.okd.io/latest/admin_guide/manage_scc.html#enable-images-to-run-with-user-in-the-dockerfile

Grant all authenticated users access to the anyuid SCC:

$ oc adm policy add-scc-to-group anyuid system:authenticated

use this command can work fine!
