### ISSUE TITLE
Execution of GIT requires better error messages

### ISSUE THREAD

**Issue by mfojtik** [openshift/source-to-image#281]
```console
I0904 19:47:00.331072 00001 docker.go:228] Pulling image openshift/ruby-22-centos7:latest
I0904 19:47:03.711546 00001 sti.go:123] Preparing to build app
I0904 19:47:03.712248 00001 clone.go:28] Cloning into /tmp/sti147089431/upload/src
I0904 19:47:08.722384 00001 clone.go:30] Git clone failed: exit status 128
I0904 19:47:08.722431 00001 cleanup.go:23] Removing temporary directory /tmp/sti147089431
I0904 19:47:08.722443 00001 fs.go:99] Removing directory '/tmp/sti147089431'
I0904 19:47:08.722754 00001 main.go:353] An error occurred: exit status 128
```

I have no idea what is going on ;-)

**Comment by mfojtik** [comment]
@bparees @soltysh

**Comment by mfojtik** [comment]
(for the record, `git clone --recursive` failed because the image I was calling `git` does not have `bash` installed (it is scratch image) and `git submodule` is a bash wrapper.

**Comment by soltysh** [comment]
Big fat :+1: for this! Somebody just recently was asking about `Git clone failed: exit status 128` error and we don't provide more information about what happened. I'd propose buffering output and printing it only if git failed. This should save us from polluting the output by default, yet having an option to provide detailed output when it fails.

**Comment by mfojtik** [comment]
@soltysh I think this should come by hand with the refactoring of how we execute Git (and how we deal with SCM in general).

**Comment by mfojtik** [comment]
https://github.com/openshift/source-to-image/pull/284 fixed here.
