### ISSUE TITLE
Add Atomic labels

### ISSUE THREAD

**Issue by mfojtik** [openshift/source-to-image#287]
@hhorak @vpavlin @rhatdan 

As we discussed, we need to be able to add the Atomic INSTALL/RUN/etc labels when we build the application from the source code. I will leave this issue open for you guys as we need to know:

* What labels we need to add (INSTALL, UNINSTALL, RUN, all of them?)
* What will be the template for systemd unit files for applications produced by the S2I build?
* What will be the format of the labels?

We can help with implementing this (as we already adding OpenShift specific labels to the output images), but we need to know the answers for above questions.

**Comment by vpavlin** [comment]
ad systemd unit files - I wouldn't use them by default. Let's keep the usage of `--privileged` and changes to the host as minimal as possible

What do you mean by format?

**Comment by mfojtik** [comment]
@vpavlin I mean how the labels should look like: https://github.com/openshift/mysql/pull/83

**Comment by hhorak** [comment]
> @vpavlin I mean how the labels should look like: openshift/mysql#83

This one is now deprecated with favor of https://github.com/openshift/mysql/pull/92 (I'm about to close the former), but the interesting discussion was happening there, that's right.

Anyway, this is a not-yet-tested example how a very simple generic label can look like without the systemd and any extra setup stuff:
```
LABEL INSTALL="bash -c 'docker create --restart=on-failure:5 --name \"\${NAME}\" \"$@\" \"${IMAGE}\"' --"
LABEL RUN="bash -c 'docker run --name \"\${NAME}\" \"$@\" \"\${IMAGE}\"' --"
```
Inspired by working example: https://github.com/openshift/mysql/pull/92.

@hanzz you've looked about atomic labels for build images, what do you think?

**Comment by hhorak** [comment]
The only thing these labels do is to pass all unknown arguments as docker arguments, not as `CMD args` (which would do atomic by default). And setting some restart count limit.

**Comment by hhorak** [comment]
> The only thing these labels do is to pass all unknown arguments as docker arguments, not as CMD args (which would do atomic by default). And setting some restart count limit.

I'm actually thinking about whether this wouldn't be better default for `atomic`, since it seems to be more common to me. @rhatdan ?

**Comment by mfojtik** [comment]
@vpavlin I thought you want to "install" the image you build using S2I as it contains your application (wordpress for example). I don't see too much sense to just `docker run` it as I can do this manually without `atomic` command, right?

**Comment by vpavlin** [comment]
Yes, I want to install the container - that's why @hhorak has the `--restart` option there, right?

You can always replace atomic commands with docker run/create/stop... but that means you need to remember a bunch of commands..for bunch of containers...

**Comment by mfojtik** [comment]
@hhorak
