### ISSUE TITLE
Symlink artifacts extracted as zero byte files

### ISSUE THREAD

**Issue by nitintutlani** [openshift/source-to-image#290]
In reference to Bug #87 , symbolic links are restored only as zero byte files. I have setup a small github project `https://github.com/nitintutlani/s2iSymlinks` to help reproduce this:

First time build:
```
$ s2i build --incremental=false --force-pull=false https://github.com/nitintutlani/s2iSymlinks centos:centos7 test --loglevel=5
```
The assemble script generates two files `src/content.txt` and `src/content.lnk`. Resulting image works well.
```
$ docker run --rm -it test cat /tmp/src/content.lnk
Content shown from symbolic link
$ docker run --rm -it test
Content shown from symbolic link
```
content.txt has valid content:
```
$ docker run --rm -it test cat /tmp/src/content.txt
```

The `save-artifacts` should preserve two files content.txt and content.lnk.

Subsequent build:
```
$ s2i build --incremental=true --force-pull=false https://github.com/nitintutlani/s2iSymlinks centos:centos7 test --loglevel=5 --save-temp-dir=true
```
This time fails.
```
$ docker run --rm -it test cat /tmp/src/content.lnk
$ docker run --rm -it test
```
However content.txt is restored well:
```
$ docker run --rm -it test cat /tmp/src/content.txt
```
Npm install, composer install and many other time taking process produce symbolic links. Please review and guide how to make artifacts work properly.

**Comment by gabemontero** [comment]
I've managed to confirm the problem using the example from @nitintutlani 

Once I wrap up a couple of in-flight fixes, I'll circle to this next ... @csrwng @soltysh - might want to pick each of your respective brains on this one when time permits.

thanks.

**Comment by soltysh** [comment]
@gabemontero I'm all ears when you need me :smile:

**Comment by php-coder** [comment]
I'm here to fix this issue :) @gabemontero how I can help you?

**Comment by gabemontero** [comment]
thx @soltysh 
and thx @php-coder - I'll let you know.

**Comment by php-coder** [comment]
@mfojtik Could you merge it or tell me what I should fix also? Thanks!
