### ISSUE TITLE
s2i help <cmd> prints no extra topics

### ISSUE THREAD

**Issue by php-coder** [openshift/source-to-image#303]
At the end of output of any `s2i help <cmd>` command I see the empty list of additional help topics:

```
[vagrant@openshiftdev sti-php]$ ./s2i help version
Display version

Usage: 
  s2i version [flags]
Flags:
  -h, --help=false: help for version

Global Flags:
      --ca="": Set the path of the docker TLS ca file
      --cert="": Set the path of the docker TLS certificate file
      --key="": Set the path of the docker TLS key file
      --loglevel=0: Set the level of log output (0-5)
  -U, --url="unix:///var/run/docker.sock": Set the url of the docker socket to use

Additional help topics:


[vagrant@openshiftdev sti-php]$
```

If there is no "additional help topics" why do we print these useless lines?

I'm using source-to-image-v1.0.2-00d1cb3-linux-amd64

**Comment by bparees** [comment]
that's coming out of cobra (the library we we use to handle CLI args).  We use the same thing for openshift but i don't see openshift printing the additional help topics line.  might be worth looking at the difference between the two, perhaps there's a setting we should be using in s2i to avoid it.

it's also possible we just need to update the cobra dep in s2i.

**Comment by soltysh** [comment]
It would be good to see how we do this in origin and apply the same pattern in here as well.

**Comment by php-coder** [comment]
This is bug in cobra (https://github.com/spf13/cobra/issues/113) that was fixed at the end of the August. We don't have this bug in origin because there we are using version from October. In `s2i` we are using version from May. I'm going to update cobra in s2i to the same version as we have in origin.

**Comment by bparees** [comment]
+1

**Comment by soltysh** [comment]
@php-coder please make sure not to use a newer version of spf13/cobra than the one in origin and k8s.

**Comment by php-coder** [comment]
@soltysh Yes, they are the same:
```
$ grep -A1 cobra source-to-image/Godeps/Godeps.json origin/Godeps/Godeps.json 
source-to-image/Godeps/Godeps.json:			"ImportPath": "github.com/spf13/cobra",
source-to-image/Godeps/Godeps.json-			"Rev": "d732ab3a34e6e9e6b5bdac80707c2b6bad852936"
--
origin/Godeps/Godeps.json:			"ImportPath": "github.com/spf13/cobra",
origin/Godeps/Godeps.json-			"Rev": "d732ab3a34e6e9e6b5bdac80707c2b6bad852936"
```

**Comment by bparees** [comment]
not sure why this didn't close when the PR merged, but it's fixed so i'm closing it.

thanks @php-coder!

**Comment by soltysh** [comment]
@bparees github is searching for certain phrases [like those](https://help.github.com/articles/closing-issues-via-commit-messages/), the PR had a fix for xyz, but rather it should be fixes xyz, I guess.

**Comment by bparees** [comment]
yeah i figured the syntax was probably not quite right.
