### ISSUE TITLE
s2i build should print a warning when s2i scripts are in a wrong dir

### ISSUE THREAD

**Issue by jhadvig** [openshift/source-to-image#306]
I've seen several times (mostly in QA TCs) that they put s2i scripts in a wrong path, usually in `.sti/` and not `.sti/bin/`. We should detect that and print a warning in that case, to make debugging easier for users.
@soltysh @mfojtik @bparees thoughts ?

**Comment by mfojtik** [comment]
+1

**Comment by soltysh** [comment]
I wonder how complicated the code would be if we'd pick both `.sti/` and `.sti/bin` like you proposed on IRC. But the warning has big fat :+1: from my side.

**Comment by mfojtik** [comment]
don't that will cause inconsistency :-)

**Comment by soltysh** [comment]
Yeah, that's the other thing I'm a bit worried as well.

**Comment by jhadvig** [comment]
Agreed, I think it would be better to have it on one place. What if user would have different run script in both of those directions. Which one would have priority ?
Warning is enough I think :)

**Comment by mfojtik** [comment]
@jhadvig I assume this is only the case when you have s2i scripts in the source repository
