### ISSUE TITLE
Makefile: misleading example about enabling verbose mode

### ISSUE THREAD

**Issue by php-coder** [openshift/source-to-image#308]
In `Makefile` there is an example of running tests in verbose mode:

```Makefile
# Build and run tests.
#
# Args:
#   WHAT: Directory names to test.  All *_test.go files under these
#     directories will be run.  If not specified, "everything" will be tested.
#   TESTS: Same as WHAT.
#   GOFLAGS: Extra flags to pass to 'go' when building.
#
# Example:
#   make check
#   make test
#   make check WHAT=pkg/build GOFLAGS=-v
check test: verify
        STI_COVER="-cover -covermode=atomic" STI_RACE="-race" hack/test-go.sh $(WHAT) $(TESTS)
.PHONY: check test
```

But when I'm trying to run command `make check WHAT=pkg/tar GOFLAGS=-v` it doesn't enable verbose mode and works as usual.

I suggest to: remove this comment or fix the scripts to make it work.

Known workaround: `./hack/test-go.sh pkg/tar -v`

**Comment by php-coder** [comment]
CC @soltysh

**Comment by soltysh** [comment]
I'll take care of than along with fixing/aligning s2i Makefile to origin.
