### ISSUE TITLE
s2i on Windows fails with E1020 

### ISSUE THREAD

**Issue by myfear** [openshift/source-to-image#314]
D:\temp\test>s2i build git://github.com/bparees/openshift-jee-sample openshift/wildfly-8-centos test-jee-app
W1020 08:43:10.926903 07004 docker.go:330] The 'io.s2i.destination' label is deprecated. Use "io.openshift.s2i.destination" instead.
E1020 08:43:11.095424 07004 util.go:85] /bin/sh: usrlocalstiassemble: command not found
E1020 08:43:11.233442 07004 fs.go:103] Error removing directory 'C:\Users\meisele\AppData\Local\Temp\sti292704367': remove C:\Users\meisele\AppDa
ta\Local\Temp\sti292704367\upload\src\.git\objects\pack\pack-efabe02dcd36d820e628c92fadd90f6d773b3fee.idx: Access is denied.

D:\temp\test>s2i version
s2i v1.0.2

**Comment by bparees** [comment]
can you rerun with --loglevel=5 ?

**Comment by bparees** [comment]
also please use the "openshift/wildfly-81-centos7" image instead, though i don't expect it to resolve the access denied issue.

**Comment by bparees** [comment]
i've also just created a new release of s2i (v1.0.3), it might be worth using that release instead, though again i don't think it will resolve this particular issue.

**Comment by myfear** [comment]
d:\temp\test>s2i build git://github.com/bparees/openshift-jee-sample openshift/wildfly-8-centos test-jee-app --loglevel=5
I1020 20:34:49.531757 09736 docker.go:228] Pulling image openshift/wildfly-8-centos:latest

Builder Image:          openshift/wildfly-8-centos
Source:                 git://github.com/bparees/openshift-jee-sample
Output Image Tag:       test-jee-app
Incremental Build:      disabled
Remove Old Build:       disabled
Force Pull:             ←[1menabled←[0m
Quiet:                  disabled
Layered Build:          disabled
Docker Endpoint:        tcp://vagrant.f8:2375

I1020 20:34:54.917940 09736 docker.go:228] Pulling image openshift/wildfly-8-centos:latest
I1020 20:34:57.989331 09736 sti.go:123] Preparing to build test-jee-app
I1020 20:34:57.998832 09736 clone.go:28] Cloning into C:\Users\meisele\AppData\Local\Temp\sti128951035\upload\src
I1020 20:35:05.151740 09736 docker.go:211] Image openshift/wildfly-8-centos:latest available locally
I1020 20:35:05.154240 09736 docker.go:317] Image contains io.openshift.s2i.scripts-url set to 'image:///usr/local/sti'
I1020 20:35:05.159241 09736 download.go:57] Using image internal scripts from: image:///usr/local/sti/assemble
I1020 20:35:05.164242 09736 download.go:57] Using image internal scripts from: image:///usr/local/sti/run
I1020 20:35:05.187745 09736 docker.go:211] Image openshift/wildfly-8-centos:latest available locally
I1020 20:35:05.189745 09736 docker.go:317] Image contains io.openshift.s2i.scripts-url set to 'image:///usr/local/sti'
I1020 20:35:05.194745 09736 download.go:57] Using image internal scripts from: image:///usr/local/sti/save-artifacts
I1020 20:35:05.198746 09736 sti.go:198] Using assemble from image:///usr/local/sti
I1020 20:35:05.202746 09736 sti.go:198] Using run from image:///usr/local/sti
I1020 20:35:05.207247 09736 sti.go:198] Using save-artifacts from image:///usr/local/sti
I1020 20:35:05.212248 09736 ignore.go:58] .s2iignore file does not exist
I1020 20:35:05.216248 09736 sti.go:131] Clean build will be performed
I1020 20:35:05.220249 09736 sti.go:134] Performing source build from git://github.com/bparees/openshift-jee-sample
I1020 20:35:05.224749 09736 sti.go:144] Running S2I script in test-jee-app
I1020 20:35:05.228750 09736 sti.go:344] Using image name openshift/wildfly-8-centos
I1020 20:35:05.234250 09736 sti.go:348] No .sti/environment provided (no environment file found in application sources)
I1020 20:35:05.243252 09736 tar.go:133] Adding to tar: C:\Users\meisele\AppData\Local\Temp\sti128951035\upload\src\.git\HEAD as src\.git\HEAD
I1020 20:35:05.248252 09736 tar.go:133] Adding to tar: C:\Users\meisele\AppData\Local\Temp\sti128951035\upload\src\.git\config as src\.git\config

I1020 20:35:05.262254 09736 tar.go:133] Adding to tar: C:\Users\meisele\AppData\Local\Temp\sti128951035\upload\src\.git\description as src\.git\d
escription
I1020 20:35:05.279756 09736 tar.go:133] Adding to tar: C:\Users\meisele\AppData\Local\Temp\sti128951035\upload\src\.git\hooks\applypatch-msg.samp
le as src\.git\hooks\applypatch-msg.sample
I1020 20:35:05.294258 09736 tar.go:133] Adding to tar: C:\Users\meisele\AppData\Local\Temp\sti128951035\upload\src\.git\hooks\commit-msg.sample a
s src\.git\hooks\commit-msg.sample
I1020 20:35:05.309760 09736 tar.go:133] Adding to tar: C:\Users\meisele\AppData\Local\Temp\sti128951035\upload\src\.git\hooks\post-update.sample
as src\.git\hooks\post-update.sample
I1020 20:35:05.322762 09736 tar.go:133] Adding to tar: C:\Users\meisele\AppData\Local\Temp\sti128951035\upload\src\.git\hooks\pre-applypatch.samp
le as src\.git\hooks\pre-applypatch.sample
I1020 20:35:05.338264 09736 tar.go:133] Adding to tar: C:\Users\meisele\AppData\Local\Temp\sti128951035\upload\src\.git\hooks\pre-commit.sample a
s src\.git\hooks\pre-commit.sample
I1020 20:35:05.358766 09736 tar.go:133] Adding to tar: C:\Users\meisele\AppData\Local\Temp\sti128951035\upload\src\.git\hooks\pre-push.sample as
src\.git\hooks\pre-push.sample
I1020 20:35:05.380269 09736 tar.go:133] Adding to tar: C:\Users\meisele\AppData\Local\Temp\sti128951035\upload\src\.git\hooks\pre-rebase.sample a
s src\.git\hooks\pre-rebase.sample
I1020 20:35:05.398771 09736 tar.go:133] Adding to tar: C:\Users\meisele\AppData\Local\Temp\sti128951035\upload\src\.git\hooks\prepare-commit-msg.
sample as src\.git\hooks\prepare-commit-msg.sample
I1020 20:35:05.430275 09736 tar.go:133] Adding to tar: C:\Users\meisele\AppData\Local\Temp\sti128951035\upload\src\.git\hooks\update.sample as sr
c\.git\hooks\update.sample
I1020 20:35:05.436276 09736 tar.go:133] Adding to tar: C:\Users\meisele\AppData\Local\Temp\sti128951035\upload\src\.git\index as src\.git\index
I1020 20:35:05.447778 09736 tar.go:133] Adding to tar: C:\Users\meisele\AppData\Local\Temp\sti128951035\upload\src\.git\info\exclude as src\.git\
info\exclude
I1020 20:35:05.455279 09736 tar.go:133] Adding to tar: C:\Users\meisele\AppData\Local\Temp\sti128951035\upload\src\.git\logs\HEAD as src\.git\log
s\HEAD
I1020 20:35:05.463280 09736 tar.go:133] Adding to tar: C:\Users\meisele\AppData\Local\Temp\sti128951035\upload\src\.git\logs\refs\heads\master as
 src\.git\logs\refs\heads\master
I1020 20:35:05.477281 09736 tar.go:133] Adding to tar: C:\Users\meisele\AppData\Local\Temp\sti128951035\upload\src\.git\logs\refs\remotes\origin\
HEAD as src\.git\logs\refs\remotes\origin\HEAD
I1020 20:35:05.484282 09736 tar.go:133] Adding to tar: C:\Users\meisele\AppData\Local\Temp\sti128951035\upload\src\.git\objects\pack\pack-efabe02
dcd36d820e628c92fadd90f6d773b3fee.idx as src\.git\objects\pack\pack-efabe02dcd36d820e628c92fadd90f6d773b3fee.idx
I1020 20:35:05.491283 09736 tar.go:133] Adding to tar: C:\Users\meisele\AppData\Local\Temp\sti128951035\upload\src\.git\objects\pack\pack-efabe02
dcd36d820e628c92fadd90f6d773b3fee.pack as src\.git\objects\pack\pack-efabe02dcd36d820e628c92fadd90f6d773b3fee.pack
I1020 20:35:05.498284 09736 tar.go:133] Adding to tar: C:\Users\meisele\AppData\Local\Temp\sti128951035\upload\src\.git\packed-refs as src\.git\p
acked-refs
I1020 20:35:05.505785 09736 tar.go:133] Adding to tar: C:\Users\meisele\AppData\Local\Temp\sti128951035\upload\src\.git\refs\heads\master as src\
.git\refs\heads\master
I1020 20:35:05.514286 09736 tar.go:133] Adding to tar: C:\Users\meisele\AppData\Local\Temp\sti128951035\upload\src\.git\refs\remotes\origin\HEAD
as src\.git\refs\remotes\origin\HEAD
I1020 20:35:05.521287 09736 tar.go:133] Adding to tar: C:\Users\meisele\AppData\Local\Temp\sti128951035\upload\src\.sti\scripts\assemble.ignore a
s src\.sti\scripts\assemble.ignore
I1020 20:35:05.527788 09736 tar.go:133] Adding to tar: C:\Users\meisele\AppData\Local\Temp\sti128951035\upload\src\.sti\scripts\run.ignore as src
\.sti\scripts\run.ignore
I1020 20:35:05.534289 09736 tar.go:133] Adding to tar: C:\Users\meisele\AppData\Local\Temp\sti128951035\upload\src\README.md as src\README.md
I1020 20:35:05.539289 09736 tar.go:133] Adding to tar: C:\Users\meisele\AppData\Local\Temp\sti128951035\upload\src\pom.xml as src\pom.xml
I1020 20:35:05.546290 09736 tar.go:133] Adding to tar: C:\Users\meisele\AppData\Local\Temp\sti128951035\upload\src\src\main\java\.gitkeep as src\
src\main\java\.gitkeep
I1020 20:35:05.553291 09736 tar.go:133] Adding to tar: C:\Users\meisele\AppData\Local\Temp\sti128951035\upload\src\src\main\resources\.gitkeep as
 src\src\main\resources\.gitkeep
I1020 20:35:05.560792 09736 tar.go:133] Adding to tar: C:\Users\meisele\AppData\Local\Temp\sti128951035\upload\src\src\main\webapp\images\jbossco
rp_logo.png as src\src\main\webapp\images\jbosscorp_logo.png
I1020 20:35:05.566793 09736 tar.go:133] Adding to tar: C:\Users\meisele\AppData\Local\Temp\sti128951035\upload\src\src\main\webapp\index.html as
src\src\main\webapp\index.html
I1020 20:35:05.572293 09736 tar.go:133] Adding to tar: C:\Users\meisele\AppData\Local\Temp\sti128951035\upload\src\src\main\webapp\snoop.jsp as s
rc\src\main\webapp\snoop.jsp
I1020 20:35:05.592796 09736 docker.go:211] Image openshift/wildfly-8-centos:latest available locally
W1020 20:35:05.595296 09736 docker.go:330] The 'io.s2i.destination' label is deprecated. Use "io.openshift.s2i.destination" instead.
I1020 20:35:05.598797 09736 docker.go:317] Image contains io.openshift.s2i.scripts-url set to 'image:///usr/local/sti'
I1020 20:35:05.602797 09736 docker.go:370] Base directory for STI scripts is '/usr/local/sti'. Untarring destination is '/opt/openshift/destinati
on'.
I1020 20:35:05.608798 09736 docker.go:497] Creating container using config: {Hostname: Domainname: User: Memory:0 MemorySwap:0 CPUShares:0 CPUSet
: AttachStdin:false AttachStdout:true AttachStderr:false PortSpecs:[] ExposedPorts:map[] Tty:false OpenStdin:true StdinOnce:true Env:[] Cmd:[/bin
/sh -c tar -C /opt/openshift/destination -xf - && \usr\local\sti\assemble] DNS:[] Image:openshift/wildfly-8-centos:latest Volumes:map[] VolumesFr
om: WorkingDir: MacAddress: Entrypoint:[] NetworkDisabled:false SecurityOpts:[] OnBuild:[] Labels:map[]}
I1020 20:35:06.042353 09736 docker.go:508] Attaching to container
I1020 20:35:06.050354 09736 docker.go:514] Starting container
I1020 20:35:06.474408 09736 docker.go:448] Waiting for container
E1020 20:35:06.527915 09736 util.go:85] /bin/sh: usrlocalstiassemble: command not found
I1020 20:35:06.914964 09736 docker.go:450] Container wait returns with 127 and <nil>
I1020 20:35:06.918464 09736 docker.go:457] Container exited
I1020 20:35:33.806879 09736 cleanup.go:23] Removing temporary directory C:\Users\meisele\AppData\Local\Temp\sti128951035
I1020 20:35:33.808879 09736 fs.go:99] Removing directory 'C:\Users\meisele\AppData\Local\Temp\sti128951035'
E1020 20:35:33.920393 09736 fs.go:103] Error removing directory 'C:\Users\meisele\AppData\Local\Temp\sti128951035': remove C:\Users\meisele\AppDa
ta\Local\Temp\sti128951035\upload\src\.git\objects\pack\pack-efabe02dcd36d820e628c92fadd90f6d773b3fee.idx: Access is denied.
I1020 20:35:33.924894 09736 main.go:353] An error occurred: non-zero (13) exit code from openshift/wildfly-8-centos

**Comment by myfear** [comment]
It's the same with both images.

**Comment by myfear** [comment]
Re-Tested with the 1.0.3

I1020 20:43:24.393136 03580 docker.go:460] Waiting for container
E1020 20:43:24.701675 03580 util.go:85] /bin/sh: usrlibexecs2iassemble: command not found
I1020 20:43:25.152232 03580 docker.go:462] Container wait returns with 127 and <nil>
I1020 20:43:25.152732 03580 docker.go:469] Container exited
I1020 20:43:53.641350 03580 cleanup.go:23] Removing temporary directory C:\Users\meisele\AppData\Local\Temp\sti065246935
I1020 20:43:53.641850 03580 fs.go:99] Removing directory 'C:\Users\meisele\AppData\Local\Temp\sti065246935'
E1020 20:43:53.752864 03580 fs.go:103] Error removing directory 'C:\Users\meisele\AppData\Local\Temp\sti065246935': remove C:\Users\meisele\AppDa
ta\Local\Temp\sti065246935\upload\src\.git\objects\pack\pack-efabe02dcd36d820e628c92fadd90f6d773b3fee.idx: Access is denied.
I1020 20:43:53.753364 03580 main.go:354] An error occurred: non-zero (13) exit code from openshift/wildfly-81-centos7

**Comment by arielcarrera** [comment]
Same problem.

**Comment by bparees** [comment]
@arielcarrera this issue was closed as resolved, can you open a new issue w/ recreate steps and logs?

**Comment by arielcarrera** [comment]
ok Ben!
