### ISSUE TITLE
s2i gives misleading error message when Docker env is not set.

### ISSUE THREAD

**Issue by myfear** [openshift/source-to-image#315]
When the Docker Env are NOT set, the error message from s2i is misleading:

D:\temp\test>s2i build git://github.com/bparees/openshift-jee-sample openshift/wildfly-8-centos test-jee-app
W1020 08:38:12.251626 09916 strategies.go:44] An error occurred when pulling openshift/wildfly-8-centos: unable to get openshift/wildfly-8-centos
:latest. Attempting to use local image.
E1020 08:38:12.253626 09916 main.go:343] An error occurred: unable to get metadata for openshift/wildfly-8-centos:latest
E1020 08:38:12.256626 09916 main.go:344] Suggested solution: check image name
E1020 08:38:12.257626 09916 main.go:350] If the problem persists consult the docs at https://github.com/openshift/source-to-image/tree/master/doc
s.Eventually reach us on freenode #openshift or file an issue at https://github.com/openshift/source-to-image/issues providing us with a log from
 your build using --loglevel=3

I suggest to check for the env variables and give a better user feedback about the problem.

**Comment by bparees** [comment]
sorry, what docker env variables?  I don't have a windows system handy to play with here.

**Comment by myfear** [comment]
E.g. DOCKER_HOST

I was testing with a docker-machine build setup and unless those
environment variables haven't been set, I always got the error.

M

**Comment by mfojtik** [comment]
@bparees I saw this issue before, it is the message we print out. We suggest to check the image name which does not help here.

**Comment by mfojtik** [comment]
@bparees the same message we show when you stop the docker service for example... checking the image name does not help here ;-) I working on PR
