### ISSUE TITLE
Exercise the s2i.exe binary

### ISSUE THREAD

**Issue by mfojtik** [openshift/source-to-image#338]
Since there are people using s2i.exe and we now officially build it and publish it, we should do some minimal smoke test for that binary to see if the build works.

This is a prototype:  https://gist.github.com/mfojtik/8bc7aa9e8b9cdd9d76bd

What this does is it pulls the tianon/wine:64 Docker image and then mount the directory with the `s2i.exe` into it. It start the container and then you can execute the `s2i.exe`. And it works, I mean the binary is execute and you will see the usage.

The problem is building :-) Since on Windows, there is no support for UNIX sockets (except cygwin) the build will fail as we need to set `DOCKER_HOST=tcp://addr:port`.
This is good, because OSX users will have to do the same, so this test will also verify s2i works well on OSX.

Now the problem is that we don't run Docker listening on TCP by default and I don't think changing that just to run the test is doable. So there are few possible solutions to this:
- Use `socat` to proxy the UNIX socket mounted into container to TCP service
- Compile the windows binary of S2I with cygwin.dll (`LoadLibrary("cygwin.dll") -> GetProcAddress("socket", "recv", "send")`) as cygwin knows how to deal with sockets (this won't help OSX)

**Comment by mfojtik** [comment]
@soltysh @bparees

**Comment by mfojtik** [comment]
The `socat` way is broken currently: https://bugzilla.redhat.com/show_bug.cgi?id=1280291

**Comment by soltysh** [comment]
How about nc:
```
nc -l 1234 | nc -U /var/run/docker.sock
```

**Comment by mfojtik** [comment]
@soltysh it will produce the same bug I think

**Comment by bparees** [comment]
@jim-minter related to the questions you were asking me about testing the docker socket changes you've made.

**Comment by jim-minter** [comment]
Wow, a wine docker image is pretty far out. I'll be happy to have a crack at this!

**Comment by bparees** [comment]
@jim-minter honestly for starters we might want to just pursue running tests in a windows VM launched on ec2 or something, as part of our s2i CI job.

**Comment by jim-minter** [comment]
@bparees ok, I now have a windows build that passes unit and integration tests, and I have a VM image that I can build automatically and run all this on (although it needs access to a docker daemon running somewhere else) (https://github.com/jim-minter/packer-windows/tree/local). What are the next steps to get this integrated into our CI system?

**Comment by bparees** [comment]
@jim-minter somewhat depends on the steps required, but you can start by looking at this: https://github.com/openshift/vagrant-openshift/blob/master/lib/vagrant-openshift/action/run_sti_tests.rb

those commands are invoked on the ec2 instance that we launch from our jenkins master.

We probably need to talk through the exact steps you need to be able to do to launch the VM.

**Comment by jim-minter** [comment]
Windows support merged and CI testing enabled.
