### ISSUE TITLE
The api/types.go#Config struct is getting fat

### ISSUE THREAD

**Issue by mfojtik** [openshift/source-to-image#344]
This struct https://github.com/openshift/source-to-image/blob/master/pkg/api/types.go#L36 is getting bigger and bigger as we add new features and expose new options. We should refactor this and break it into logical pieces where we can. I can see that we can break it into:

* Image related options (ImageConfig)
* Pull options (PullConfig)
* Build options (BuildConfig)(!!! ;-)
* etc...

This will be only internal change, but will make the Config smaller and allow passing just relevant configuration to various functions, without worrying about functions modify config field that they should not see.

**Comment by mfojtik** [comment]
@soltysh @bparees

**Comment by soltysh** [comment]
What else can I add, :+1: to the idea

**Comment by bparees** [comment]
this will either happen as a natural part of someone's refactor, or not happen at all.
