### ISSUE TITLE
New integration tests

### ISSUE THREAD

**Issue by soltysh** [openshift/source-to-image#347]
This came out from the discussion in #345, the proposal is test should take the s2i binary, pass options I want, wait for the result and verify it.

@mfojtik

**Comment by mfojtik** [comment]
+1

The framework should be able to pickup ./hack/test-stirunimage.sh and make it go test. Basically we need:

1) Invoke s2i binary with provided options
2) Verify the build pass properly or with error we expected
3) Verify the result image contains what we want

This should allow passing custom S2I scripts with different content so we can test various cases of how s2i scripts can be invoked and what they can run.

**Comment by bparees** [comment]
we've got integration tests now.
