### ISSUE TITLE
Allow limiting resources in S2I

### ISSUE THREAD

**Issue by mfojtik** [openshift/source-to-image#364]
We should be able to tweak the resource limit configuration for containers that s2i run via the RunContainerOptions. We can set some sane defaults to CPU, Memory and Storage and allow to override them via Config/CLI options.

In OpenShift we can introspect the CGROUPS in the Pod that starts the builds and copy the values to container we start using Docker. It is not ideal (we should really use kubelet driver) but at least forbid to do crazy things in assemble.

**Comment by mfojtik** [comment]
@csrwng @bparees what do you think?

**Comment by csrwng** [comment]
imho, I'd rather invest effort into preparing for the use of kube as a back-end. For example, we could break out the code to assemble (run + commit) as a separate binary with tar input. (Or as a different invocation of the s2i command -- like 's2i build' invokes -> 's2i assemble'). That way the command to use for assemble can be passed to the 's2i build' command as an argument.

**Comment by bparees** [comment]
the right answer for openshift is to run the assemble container under openshift management.

whether this is interesting for standalone s2i users or not, maybe but definitely not a priority.

**Comment by csrwng** [comment]
@bparees is there value though in preparing for that by splitting out the assemble part in the current s2i?

**Comment by bparees** [comment]
i don't think we have the design concrete enough to start that right now.

**Comment by bparees** [comment]
s2i now respects cgroup limits passed in as part of the config.  it's not exposed on on the CLI but i'm having a hard time justifying exposing it on the cli, so i think we can close this.
