### ISSUE TITLE
Build test-images test flake

### ISSUE THREAD

**Issue by soltysh** [openshift/source-to-image#369]
Sometimes our test end with `You do not have necessary test images, be sure to run 'hack/build-test-images.sh' beforehand.` This is one example of such error: https://ci.openshift.redhat.com/jenkins/job/merge_pull_requests_sti/247/console . It would be good to nail down the reason for that.

**Comment by mfojtik** [comment]
@soltysh can be closed now?

**Comment by soltysh** [comment]
It's still valid, the linked issue is one proof of that.

**Comment by bparees** [comment]
this turned out to be an issue in our jenkins infrastructure.
