### ISSUE TITLE
Need better documentation how to install and use s2i

### ISSUE THREAD

**Issue by mfojtik** [openshift/source-to-image#372]
Currently, we suggest to compile s2i from sources in README.md https://github.com/openshift/source-to-image#installation

However, there is no need to do this if you just want to use the S2I, you can just grab the latest binary from the Releases page and unpack it into /usr/local/bin or somewhere into PATH.

We should mention that as the first installation method and prevent confused users installing Go, dealing with gopath and getting the GIT master version of s2i which might be broken.

**Comment by eliskasl** [comment]
In Fedora, there is also the s2i RPM.

**Comment by wanghaoran1988** [comment]
How about create a spec file in this repo , andd using tito to make rpm pakcage ?

**Comment by bparees** [comment]
rpm is platform specific and we're not looking to distribute this in that way, i think pointing people to the release page is more appropriate.
