### ISSUE TITLE
When using contextDir, the `.s2i/bin/*` is not detected properly

### ISSUE THREAD

**Issue by mfojtik** [openshift/source-to-image#393]
When using the contextDir and have the S2I scripts inside the context dir (examples/master/.s2i/bin and contextDir is "examples/master") then S2I does not detect them properly and use the image scripts instead.

**Comment by mfojtik** [comment]
@bparees adding high prio to this one as this is breaking the S2I Jenkins scenario a little but and also Origin as we use to refer to "add s2i script to your repo and we will use them" and this bug breaks that statement.

**Comment by bparees** [comment]
@mfojtik does this actually break in openshift?  we do context dir a little differently there, it might work.

**Comment by mfojtik** [comment]
@bparees this should be now fixed in both origin and here.
