### ISSUE TITLE
tar file is closed before further usage

### ISSUE THREAD

**Issue by rassie** [openshift/source-to-image#397]
Apparently, when using source upload with `--inject` the `tar` file is created from two different directories under `/tmp`. However, the file is being closed just after the injection step, so that the actual source and the scripts cannot be written. 

`s2i --loglevel 5 --inject "/home/user/.m2/repository/:/root/.m2/repository/" build . app-builder app:latest` produces the following output:

```
...
I0125 17:12:51.152699 08557 tar.go:255] Adding to tar: /tmp/s2i-323596458/xmlpull/xmlpull/1.1.3.1/xmlpull-1.1.3.1.pom.sha1 as xmlpull/xmlpull/1.1.3.1/xmlpull-1.1.3.1.pom.sha1
I0125 17:12:51.152778 08557 tar.go:255] Adding to tar: /tmp/s2i-323596458/xpp3/xpp3_min/1.1.4c/_remote.repositories as xpp3/xpp3_min/1.1.4c/_remote.repositories
I0125 17:12:51.152845 08557 tar.go:255] Adding to tar: /tmp/s2i-323596458/xpp3/xpp3_min/1.1.4c/xpp3_min-1.1.4c.jar as xpp3/xpp3_min/1.1.4c/xpp3_min-1.1.4c.jar
I0125 17:12:51.152910 08557 tar.go:255] Adding to tar: /tmp/s2i-323596458/xpp3/xpp3_min/1.1.4c/xpp3_min-1.1.4c.jar.sha1 as xpp3/xpp3_min/1.1.4c/xpp3_min-1.1.4c.jar.sha1
I0125 17:12:51.152961 08557 tar.go:255] Adding to tar: /tmp/s2i-323596458/xpp3/xpp3_min/1.1.4c/xpp3_min-1.1.4c.pom as xpp3/xpp3_min/1.1.4c/xpp3_min-1.1.4c.pom
I0125 17:12:51.153013 08557 tar.go:255] Adding to tar: /tmp/s2i-323596458/xpp3/xpp3_min/1.1.4c/xpp3_min-1.1.4c.pom.sha1 as xpp3/xpp3_min/1.1.4c/xpp3_min-1.1.4c.pom.sha1
E0125 17:12:51.455001 08557 tar.go:210] Error writing header for Chart.Doughnut.js: io: read/write on closed pipe
I0125 17:12:51.455061 08557 tar.go:255] Adding to tar: /tmp/sti168046264/upload/src/app.client/bower_lib/Chart.js/src/Chart.Line.js as src/app.client/bower_lib/Chart.js/src/Chart.Line.js
E0125 17:12:51.455066 08557 tar.go:210] Error writing header for Chart.Line.js: io: read/write on closed pipe
I0125 17:12:51.455088 08557 tar.go:255] Adding to tar: /tmp/sti168046264/upload/src/app.client/bower_lib/Chart.js/src/Chart.PolarArea.js as src/app.client/bower_lib/Chart.js/src/Chart.PolarArea.js
E0125 17:12:51.455091 08557 tar.go:210] Error writing header for Chart.PolarArea.js: io: read/write on closed pipe
I0125 17:12:51.455111 08557 tar.go:255] Adding to tar: /tmp/sti168046264/upload/src/app.client/bower_lib/Chart.js/src/Chart.Radar.js as src/app.client/bower_lib/Chart.js/src/Chart.Radar.js
E0125 17:12:51.455113 08557 tar.go:210] Error writing header for Chart.Radar.js: io: read/write on closed pipe
I0125 17:12:51.455152 08557 tar.go:255] Adding to tar: /tmp/sti168046264/upload/src/app.client/bower_lib/Cookies/.bower.json as src/app.client/bower_lib/Cookies/.bower.json
E0125 17:12:51.455156 08557 tar.go:210] Error writing header for .bower.json: io: read/write on closed pipe
...
```

(I have no idea where the "Adding to tar" message for `Chart.Doughnut.js` went, probably another symptom of something weird happening asynchronously)

**Comment by mfojtik** [comment]
CC @php-coder

**Comment by php-coder** [comment]
@rassie Thank you for the report!

I'm trying to reproduce the error, but, looks like I'm missing something important. Could you provide a bit more details? For instance, from where `upload/src/*` files came from? Maybe more logs, show files hierarchy, etc.

**Comment by php-coder** [comment]
I'm able to reproduce it now, BTW.

**Comment by rassie** [comment]
Thanks, was going to prepare a minimal test case for you today or tomorrow, but that's probably obsolete now.

**Comment by mfojtik** [comment]
@rassie is Chart.Doughnut.js file being injected or it is something you have in your source?

**Comment by rassie** [comment]
It's in the source.

**Comment by mfojtik** [comment]
@rassie if you don't do injection, does it work? (want to see if this is related to streaming two tars asynchronously or streaming the source is somehow broken)

**Comment by rassie** [comment]
Yes, it works without the injection

**Comment by php-coder** [comment]
@rassie We're suspecting that the cause is that target directory (`/root/.m2/repository`) doesn't exist. Is it true?

**Comment by rassie** [comment]
Probably, I'm not creating it explicitely.

**Comment by mfojtik** [comment]
@rassie OK, the destination directory has to exists, we are not creating it. So you will have to create it in your image before build. The error you see is different one, but still a bug. When we start streaming the sources and the injection failed (because of destinationDir does not exists) we remove the container as the build should fail. Unfortunately, we start streaming the sources in parallel, which will error as the container is gone (that explains the pipe closed error). 

So to fix your problem, just make sure the directory where you are injecting exists. The subdirectories inside that injected dir are created properly, only the destinationDir must exists (we cannot create it automatically as we don't have permissions to).
