### ISSUE TITLE
Bump vendored docker to match origin

### ISSUE THREAD

**Issue by rhcarvalho** [openshift/source-to-image#398]
If we bump it to https://github.com/docker/docker/commit/2b27fe17a1b3fb8472fde96d768fa70996adf201, we can get rid of [some code](https://github.com/openshift/origin/blob/90ef4d7c23a5b942e01d85411f3345e904bb5bc2/Godeps/_workspace/src/github.com/openshift/source-to-image/pkg/docker/util.go#L148-L163) that [is implemented upstream](https://github.com/docker/docker/blob/2b27fe17a1b3fb8472fde96d768fa70996adf201/pkg/parsers/parsers.go#L71-L89).

I would like to do that, given some guidelines on how we use Godeps and knowing whether we're carrying any patches for docker/docker in S2I.

**Comment by rhcarvalho** [comment]
@bparees or @mfojtik please assign this to me.

**Comment by rhcarvalho** [comment]
Aha, actually those functions are not exactly the same, our version returns a digest as a separate return value.
Anyway, there's a lot of very similar implementations of parsers to split repository and tag...

**Comment by mfojtik** [comment]
@rhcarvalho do we need to do something here?

**Comment by rhcarvalho** [comment]
@mfojtik, yes, as the description says.
