### ISSUE TITLE
no way to set incremental image pull policy explicitly

### ISSUE THREAD

**Issue by bparees** [openshift/source-to-image#412]
pull policy used to pull the previous image is tied to the pull policy for the builder image.

**Comment by Mangirdaz** [comment]
For now forcepull (in OSEv3.2) does not work with incremental build. From code and description i assume this will enable these two to work together?

**Comment by bparees** [comment]
What do you mean incremental does not work with forcepull today?

this feature simply enables you to set a cluster wide default such that all builds will, by default, use incremental builds.

**Comment by Mangirdaz** [comment]
Still debugging on this, but one of the clients started complaining that incremental builds stopped working when they added this to the template. 

if incremental is set build maven builds copy paste .m2 data into new container. And if they added forcepull: true it apparently stopped doing incremental ones.

But still need to confirm this one before raising new ticket...

**Comment by bparees** [comment]
ok, keep us posted, but it *should* work.

**Comment by Mangirdaz** [comment]
Will do. I suspect that previous build was failed so it defaulted to build from scratch, despite the fact we had one n-2 build running. But at this point its my assumption before debugging.
