### ISSUE TITLE
Generate Bash completion scripts

### ISSUE THREAD

**Issue by elyscape** [openshift/source-to-image#415]
It would be nice to have Bash completion scripts for the s2i binary. This shouldn't be too difficult, given that [Cobra](https://github.com/spf13/cobra) is used for the CLI interface and [Cobra offers a Bash completion generator](https://github.com/spf13/cobra/blob/master/bash_completions.md).

**Comment by mfojtik** [comment]
@elyscape sorry for this to take so long, I will have a look tomorrow and provide bash completetions (we already have that for oc and openshift commands, s2i should be no different).

**Comment by elyscape** [comment]
No worries. Thanks for your help on this!

**Comment by mfojtik** [comment]
@elyscape it is being merged now... several options:

1) Use `s2i genbashcompletion` will give you up-to-date completion for the current `s2i` binary
2) You can download generated completion (see contrib/bash) folder.

**Comment by elyscape** [comment]
Fantastic. Thanks for your help!
