### ISSUE TITLE
The --env option should be allowed to be used more than once.

### ISSUE THREAD

**Issue by GrahamDumpleton** [openshift/source-to-image#417]
At present the ``--env`` option has that if wanting to set more than one variable, they need to be squashed into the one string and ``--env`` supplied only once. If you supply ``--env`` more than once it results in anything attempted to be set by prior ``--env`` being dropped and ignored

With ``.s2i/bin/assemble`` containing:

```
#!/bin/bash

env
```

and grabbing a handy S2I builder and running:

```
$ s2i build . grahamdumpleton/warp0-debian8-python27 xxx --env VARIABLE1=XXXXXXXX --env VARIABLE2=YYYYYYYYY | grep VARIABLE
I0229 20:40:25.623001 04019 install.go:236] Using "assemble" installed from "<source-dir>/.s2i/bin/assemble"
I0229 20:40:25.623144 04019 install.go:236] Using "run" installed from "image:///usr/local/s2i/bin/run"
I0229 20:40:25.623177 04019 install.go:236] Using "save-artifacts" installed from "image:///usr/local/s2i/bin/save-artifacts"
VARIABLE2=YYYYYYYYY
```

you can see that only the variable set by the last ``--env`` is passed through.

A related issue is that the fact that multiple values have to be passed in with one ``--env`` means you can't have values for variables which include a comma.

In fact attempting to do so triggers a bug in s2i, with it exiting straight away before doing anything and not giving any sort of message as to what was wrong.

```
$ s2i build . grahamdumpleton/warp0-debian8-python27 xxx --env VARIABLE1=XXXXXXXX --env VARIABLE2="YYYYYYYYY,ZZZZZ"
```

It just exits and dies and gives back prompt straight away.

Another parsing stuff is where you have '=' in the value.

```
$ s2i build . grahamdumpleton/warp0-debian8-python27 xxx --env VARIABLE1=XXXXXXXX --env VARIABLE2="=YYYYYYYYY"
```

Again also just exits straight away without a message.

It is going to be hard to fix this broken behaviour with embedded '=' and ',' know because of reliance on squashing more than one variable together, rather than using multiple ``--env`` options.

This issue likely relates to https://github.com/openshift/origin/issues/7326. So probably whole host of characters in values that are not allowed including quotes as well like in other issue.

**Comment by mfojtik** [comment]
agree, this is a bug. The env should be list. @GrahamDumpleton Have you tried:

`s2i build . foo xxx --env FOO=bar,BLA=foo` ?

**Comment by GrahamDumpleton** [comment]
I know comma separated list of key=value as documented does work. That is what am currently having to use, which makes for really long lines in my shell scripts. :-)

**Comment by mfojtik** [comment]
@GrahamDumpleton yeah, we should unify how you can pass multiple options. The `--inject` already use that pattern, we should do the same for `--env`. I will try to look this week :-)
