### ISSUE TITLE
Provide option for s2i to ignore .git and use local directory.

### ISSUE THREAD

**Issue by GrahamDumpleton** [openshift/source-to-image#418]
As far as I can tell, if you point ``s2i`` at a directory which is a git checkout, it always goes and checks out head of default branch from the git repository and ignores the source code in the current local directory. I cannot see an option which says don't go do that.

If that is the case, can we have a ``--no-git`` or ``--no-vcs`` option so that it will always use the file system directory it is told to use. It is a bit of a pain to have to copy a git checkout directory to another location and remove the ``.git`` directory just to make it work wth local sources.

If there is an option and I am blind, or there is some other way of doing this which doesn't entail making copies of everything, can you let me know.

**Comment by bparees** [comment]
s2i build --ref=foo

but that still requires you have an actual commit you want to use, and not
uncommitted code.


On Mon, Feb 29, 2016 at 4:55 AM, Graham Dumpleton <notifications@github.com>
wrote:

> As far as I can tell, if you point s2i at a directory which is a git
> checkout, it always goes and checks out head of default branch from the git
> repository and ignores the source code in the current local directory. I
> cannot see an option which says don't go do that.
>
> If that is the case, can be have a --no-git or --no-vcs option so that it
> will always use the file system directory it is told to use. It is a bit of
> a pain to have to copy a git checkout directory to another location and
> remove the .git directory just to make it work wth local sources.
>
> If there is an option and I am blind, or there is some other way of doing
> this, can you let me know.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openshift/source-to-image/issues/418>.
>



-- 
Ben Parees | OpenShift

**Comment by GrahamDumpleton** [comment]
I want it simply to be everything in the directory, regardless of whether committed or not, or even if added to git for it to track.

FWIW, where I used to work I had a middle ground for a system I had for running tests. I didn't want everything in the directory to be added as there could be lots of temporary crap. Instead I wrote up a system which would take what was committed, plus what had been added to the git index but not yet committed. This allowed me to specify what local changes were picked up but without creating a horrible commit history that I would have to rebase to get rid of before pushing. Not asking for this variation here though.

**Comment by bparees** [comment]
yup, i got it and it makes sense.

**Comment by bparees** [comment]
I think maybe this will have fixed your issue? 
https://github.com/openshift/source-to-image/pull/428

if you specify --copy we'll do a filesystem copy instead of a git clone, so that should get the current content.  can you give it a shot and confirm?

**Comment by GrahamDumpleton** [comment]
I can't verify this until a release is made as not been building binaries myself.

**Comment by bparees** [comment]
i'll try to cut a release today.

**Comment by bparees** [comment]
@GrahamDumpleton new release: https://github.com/openshift/source-to-image/releases/tag/v1.0.6

**Comment by bparees** [comment]
@GrahamDumpleton bump

**Comment by GrahamDumpleton** [comment]
Confirmed that ``--copy`` appears to work as anticipated in 1.0.6.
