### ISSUE TITLE
Is S2I production ready?

### ISSUE THREAD

**Issue by alpined** [openshift/source-to-image#420]
Our info-sec guidelines prohibit us from putting any type of compiler/build-tool in a production environment (for obvious reasons). How can we build a minimalist image with solely required components?

Why do we need GCC for running a nodejs app? I think extra stuff makes the image bigger; this one is 438.7 MB.

Source Repository: https://github.com/sudhaker/my-node-app.git

[sudhaker@dell-cs24-n2 ~]$ oc get pods
NAME                       READY     STATUS      RESTARTS   AGE
my-node-app-1-30mmo        1/1       Running     0          52s
my-node-app-1-build        0/1       Completed   0          2m
mysql-56-centos7-1-jo8ws   1/1       Running     0          20h

[sudhaker@dell-cs24-n2 ~]$ oc rsh my-node-app-1-30mmo

bash-4.2$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-redhat-linux/4.8.5/lto-wrapper
Target: x86_64-redhat-linux
Configured with: ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-linker-hash-style=gnu --enable-languages=c,c++,objc,obj-c++,java,fortran,ada,go,lto --enable-plugin --enable-initfini-array --disable-libgcj --with-isl=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/isl-install --with-cloog=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/cloog-install --enable-gnu-indirect-function --with-tune=generic --with-arch_32=x86-64 --build=x86_64-redhat-linux
Thread model: posix
**gcc version 4.8.5 20150623 (Red Hat 4.8.5-4) (GCC)**
bash-4.2$

**Comment by sudhaker** [comment]
Command used was : oc new-app https://github.com/sudhaker/my-node-app.git -l app=my-node-app
Environment: Openshift Origin / v1.1.2

Thanks,

**Comment by bparees** [comment]
Your question isn't really about s2i, it's about particular s2i images.

If you want an s2i image w/o certain content, you can take a look at our dockerfiles and strip out anything you don't want:

our base image:
https://github.com/openshift/sti-base/blob/master/Dockerfile
the nodejs image (built on top of the base image):
https://github.com/openshift/sti-nodejs/blob/master/0.10/Dockerfile

and then build your image (perhaps combining those two dockerfiles into a single one for simplicity).

**Comment by sudhaker** [comment]
Agree BEN! And that for the suggestion. Will try to build some basic & minimalist build images and share.

**Comment by mfojtik** [comment]
@sudhaker the reason why we install `gcc` is that some nodejs modules might require C extension compilation during install. Same for ruby (nokogiri) and python (i'm sure something exists). So we treat it as a "common" requirement for all images. Since the `sti-base` image will almost always exists in the cluster nodes (if you use one of the official builders), the 'framework' (nodejs, ruby, etc...) layers are relatively small.

**Comment by sudhaker** [comment]
Michal - It's not about storage. Having gcc & build-tools in production container is big no-no for security reasons.

I do agree with Ben that S2I is just a tool and reported security flaw is coming from S2I templates which can be tweaked to cover the rough corners.

Cheers,
Sudhaker

**Comment by mnagy** [comment]
@sudhaker out of curiosity, what are the security reasons?

**Comment by sudhaker** [comment]
It's easier to paste 40 lines of C code on a remote-shell and build binary on a compromised dmz-host to extend the attack than moving the binary to the dmz-host through multiple hops. I won't do any more follow-up on this thread as the discuss can go pretty long.
