### ISSUE TITLE
Need more docs: What do I need to do to feed logs to EFK?

### ISSUE THREAD

**Issue by alberttwong** [openshift/source-to-image#453]
I'm building community s2i images for common runtimes I see in the field.   What do I need to do to Dockerfile/s2i files to feed logs to EFK?

**Comment by bparees** [comment]
Shouldn't have to do anything, just make sure the image outputs to stdout.

@jcantrill please confirm?

**Comment by jcantrill** [comment]
@alberttwong The EFK stack will pick up any log messages that are written to the recommended docker log output which is stdout.  That being said, there was a long discussion that I can not seem to find about how to gather other logs  which might be generated (e.g. Wildfly access logs) other then those that go to stdout.  I would suggest providing some indicator of the log source if you wish to distinguish one type of log message from the others.

**Comment by alberttwong** [comment]
Do you know if EFK picks up stderr?   I also agree that we need more than just stdout.   

>>I would suggest providing some indicator of the log source if you wish to distinguish one type of log message from the others.

What would you suggest?

**Comment by jcantrill** [comment]
The stack will pick up anything that would see coming from 'docker log'.  Docker AFAIK merges the stdout and stderr streams.

With regards to the indicator, if you are using something like log4j, you can specify the log pattern which means the options are about anything.  This means if its an http access log, you could preface all log messages with 'http-access'

**Comment by bparees** [comment]
housekeeping: can we close this and move it to an origin issue if there are still things to discuss?

**Comment by bparees** [comment]
closing, please open an issue against https://github.com/openshift/origin if you need more info.
