### ISSUE TITLE
Need more docs: What do I need to do to enable connectivity to monitoring metrics?

### ISSUE THREAD

**Issue by alberttwong** [openshift/source-to-image#454]
I'm building community s2i images for common runtimes I see in the field.   What do I need to do to Dockerfile/s2i files to enable connectivity to monitoring?   Also I'm under the assumption that the monitoring metrics I currently see in OSE is hawkular.

**Comment by bparees** [comment]
This really belongs as an openshift/origin issue, it's not an s2i question.

@jcantrill any doc you can point to for how to enable images to record metric data?

**Comment by jcantrill** [comment]
Are we referring here to monitoring application metrics?  These cards are identified for figuring out app metrics: https://trello.com/c/4rtRqsQS/192-5-r-d-application-level-metrics-hawkular, and https://trello.com/c/ZQTYWrCD/154-8-support-application-level-metrics-hawkular-evg

They have been in a holding pattern for a while now as we sort through various existing bugs.

**Comment by alberttwong** [comment]
I see....  it doesn't quite say how to do it. 

how about heapster?    Can I assume that there will be some base container monitoring and I don't have to do that on the s2i/image layer?

**Comment by jcantrill** [comment]
@alberttwong The cards are there identify how to do applications metrics; ... the 'how' is still a work in progress.  I'm not certain what you are asking with regards to heapster.  As far as base monitoring, I imagine it will depend on the type of application but since this is still a work in progress, it is yet to be determined. @mwringe do you have any additional info you can add to this thread?

**Comment by mwringe** [comment]
@alberttwong the origin-metrics setup will automatically monitor any containers deployed in the cluster, mainly this has to do with cpu and memory metrics (but there will be support for network metrics soon). This is what Heapster provides in terms of monitoring. Heapster should also be able to handle very low numbers of custom application metrics (eg 3-4) if you want to expose metrics that way.

**Comment by bparees** [comment]
housekeeping: can we close this and move it to an origin issue if there are still things to discuss?

**Comment by mwringe** [comment]
Unless we get some more information about the issue, I think we should close this.

**Comment by bparees** [comment]
closing, @alberttwong please open an issue against https://github.com/openshift/origin if you need to discuss further.
