### ISSUE TITLE
No .git directory in source dir

### ISSUE THREAD

**Issue by MartinRumanek** [openshift/source-to-image#457]
My assemble script expects git repo (because my gradle build calls some git commands), not only the source code (without a .git directory).

 I've tried command build with param "--save-temp-dir=true"

```
s2i build --incremental=true --save-temp-dir=true https://github.com/MartinRumanek/kramerius.git kramerius-builder kramerius 
```

and the path /tmp/s2i269878825/upload/src is ok (with .git directory), but inside the builder image directory .git doesn't exist.

```
$ s2i version
s2i v1.0.5-55-gfb6df26
```

**Comment by bparees** [comment]
yes, s2i presently explicitly excludes the .git directory.  This has come up a couple times (not sure if we have another issue open for it @mfojtik @gabemontero ?)

I think we should do one of two things:
1) add a flag to disable this behavior
2) update the .s2iignore logic to operate as an override:  if you have a .s2iignore file, then we only ignore things in that file and do not do the default "ignore .git" behavior.

I think (1) is my preference.

**Comment by mfojtik** [comment]
@bparees +1 for 1)

**Comment by gabemontero** [comment]
To the historical angle @bparees alluded to, the closest thing to this that I worked was #367, where we added the force copy option to preserve empty directories.

I haven't tried it yet, but It is conceivable that could prove to be a workaround for preserving the .git directory as well (with of course requiring that you clone the repo *before* running `s2i` and pass the resulting local directory as your source destination).

I'll see where the exclusion of .git occurs in the code and/or attempt it myself, unless @MartinRumanek or someone beats me to trying it.

Based on the results, let's revisit whether we still want to do (1).

**Comment by bparees** [comment]
> I'll see where the exclusion of .git occurs in the code and/or attempt it myself, unless @MartinRumanek or someone beats me to trying it.

the exclusion logic happens during the tarring for sending into the container, so i'm 99% confident it'll take effect regardless of the copy/clone strategy.

**Comment by gabemontero** [comment]
ok thx for the quick intel @bparees  - i'll start on the new option

**Comment by gabemontero** [comment]
In looking at the code, there is already a [setter](https://github.com/openshift/source-to-image/blob/master/pkg/tar/tar.go#L90-L92) for the regular expression used to exclude files, where the default regex covers the [.git's](https://github.com/openshift/source-to-image/blob/master/pkg/tar/tar.go#L27).

So I'm thinking the new flag should be a bit more generic, and simple expose the regexp used for tar filtering, where the user can set it to an empty string in order to allow anything (including the .git's), or filter additional files besides .git, etc.

Thoughts?

**Comment by bparees** [comment]
sounds reasonable to me.
