### ISSUE TITLE
What is the best way to execute dockerfile "entrypoint" command

### ISSUE THREAD

**Issue by alberttwong** [openshift/source-to-image#469]
My s2i run script has `ENTRYPOINT ["dnx", "-p", "source/project.json", "Microsoft.AspNet.Server.Kestrel", "--server.urls", "http://0.0.0.0:5000"]` and I get the follow error

```
bash-3.2$ docker run -t -p 5000:5000 aspnet-app
/usr/libexec/s2i/run: line 12: ENTRYPOINT: command not found
```

What is the best way to execute entrypoint?   I don't think I should put it back into the dockerfile unless you think so.   I'm thinking of converting the entrypoint command to a normal shell command.   Thoughts?

**Comment by bparees** [comment]
Runs scripts are she'll scripts, not dockerfiles, so using docker syntax
like ENTRYPOINT doesn't make sense...

Ben Parees | OpenShift

**Comment by alberttwong** [comment]
sounds good.
