### ISSUE TITLE
s2i tool does not check if run user 1001 (for CDK and OpenShift)

### ISSUE THREAD

**Issue by alberttwong** [openshift/source-to-image#470]
## I was a bit surprised that the s2i tool doesn't warn you.

Most of these images have "USER 1001" (which is the default user) for this reason. I don't know why this is only checked by OpenShift; perhaps it's worth an issue against S2I to at least warn that a privileged security context will be needed on OpenShift.

**Comment by bparees** [comment]
it's an openshift requirement and not an s2i requirement, so it's debatable whether the s2i tooling should be reporting about openshift requirements, given that s2i is intended to be usable w/o openshift.

**Comment by alberttwong** [comment]
maybe we should extend the example since many of use the s2i tool to build for OSE.

**Comment by bparees** [comment]
@alberttwong that's fair.

**Comment by alberttwong** [comment]
Here's a working s2i that is running non-root.  We also tested it against the CDK. 

https://github.com/openshift-s2i/s2i-aspnet/pull/5

**Comment by PI-Victor** [comment]
i'd like to take care of this, but i'm unsure where this conversation is going.
which example should i extend? or should this be, after all, in s2i?

**Comment by bparees** [comment]
s2i create (which bootstraps an example) already uses non-root, this is probably talking about the sample here:  https://github.com/openshift/source-to-image/blob/master/examples/nginx-app

so @PI-Victor the fix would be to update that sample to run as non-root.

**Comment by alberttwong** [comment]
I think generally speaking, we should try to create the best example as possible for people to base their s2i.   That was my intent when building asp-net s2i.

**Comment by bparees** [comment]
@alberttwong i don't explicitly disagree, but there's also a fine line between trying to teach them the minimum set of concepts related to s2i, and trying to teach them all the best practices particularly around things related to openshift.

**Comment by bparees** [comment]
@coreydaley please add this to the work you're doing refactoring the s2i example/doc.

**Comment by coreydaley** [comment]
Linked to #688

**Comment by coreydaley** [comment]
Fixed via #688
