### ISSUE TITLE
example s2i should contain best practices (generation of template, liveiness and readiness probe, resource and quota limits)

### ISSUE THREAD

**Issue by alberttwong** [openshift/source-to-image#472]
generation of template so that all users can create a java/aspnet/nodejs/etc etc project and  implementations of liveiness and readiness probe and resource and quota limits

**Comment by bparees** [comment]
those are openshift/k8s concepts which do not belong in s2i documentation.

openshift/k8s provides examples of templates/readiness probes/liveness probes/etc:

https://github.com/openshift/origin/blob/master/examples/quickstarts/cakephp-mysql.json

**Comment by alberttwong** [comment]
where would you put that type of recommendation?  I built the aspnet s2i image using the example contained in the repo.   I found this to be incomplete.   https://github.com/openshift/s2i-base is also incomplete.

**Comment by bparees** [comment]
It sounds like a candidate for this doc:
https://github.com/openshift/openshift-docs/blob/master/creating_images/guidelines.adoc

something about recommending you 
1) provide a recommended readiness and liveness probe definition
2) ideally provide a template that will stand up your image in a deployment config.

Can you either open an issue against that repo (and tag me) or if you're feeling inclined, start a PR against that doc and tag me to review it?

**Comment by alberttwong** [comment]
Can we link https://github.com/openshift/openshift-docs/blob/master/creating_images/guidelines.adoc to the s2i example or the sti-base?
