### ISSUE TITLE
ENTRYPOINT in S2I builder image can interfere with assemble run.

### ISSUE THREAD

**Issue by GrahamDumpleton** [openshift/source-to-image#475]
If one is making an S2I builder by extending an existing Docker image, if the base image has an existing `ENTRYPOINT` specified (and which has to be retained to allow direct use of the image still), this may interfere with the `assemble` phase and specifically the ability to send files into the container for `assemble` using `tar`.

An example of how it can be broken is if the `ENTRYPOINT` command took the `CMD` value and used it to the configure some sort of mini supervisor and then ran the supervisor, which in turn ran the command. This could die because of the expectation that what is being run is a long running demonised process, or simply because the `CMD` would effectively be run in background, it would have its standard input closed, which for the case of `tar` means it could not read the files being sent in.

To be safe, `s2i` when running the `assemble` phase should override any existing `ENTRYPOINT`.

When running `docker run`, if it has an existing `ENTRYPOINT` you can't from memory just supply `--entrypoint ''` as it will actually try and run the supplied argument (empty string) still.

It may therefore be necessary to use `--entrypoint env` as a way of chaining the execution of the command you actually want run.

**Comment by bparees** [comment]
@mfojtik can you remember any reason we aren't doing this today when we run the assemble container? i'm a bit surprise we aren't.

**Comment by mfojtik** [comment]
@bparees i thought we already override entrypoint to /bin/sh, if we don't then it is a bug. I will have a look.

**Comment by GrahamDumpleton** [comment]
The only way I could solve my problem was to comment out ``ENTRYPOINT`` in the ``Dockerfile``, so doesn't appear to be overridden.

**Comment by mfojtik** [comment]
@GrahamDumpleton thanks! I will send a PR to fix this today.

**Comment by bparees** [comment]
thanks @mfojtik!

**Comment by bparees** [comment]
i had to revert this here https://github.com/openshift/source-to-image/pull/482

because we were committing images with "env" as the entrypoint which resulted in our post-commit tests failing because they couldn't find bundle because the scl enablement stuff didn't happen with that entrypoint.

we can revisit this after the merge queue is fixed, but basically we need to not commit the changed entrypoint.

**Comment by GrahamDumpleton** [comment]
Using ``/bin/env`` on this was wrong choice. Should have been ``/usr/bin/env``. There is no ``/bin/env`` on Debian systems. Generally ``/usr/bin/env`` exists everywhere though. See #559

**Comment by bparees** [comment]
As far as I'm concerned between this and the original reversion,  this is evidence this feature is a mistake.  Overriding entrypoints is always going to be risky.

**Comment by GrahamDumpleton** [comment]
We should remove the ``oc rsync`` feature as well then, after all it will not work if the image doesn't contain either ``rsync`` or the correct ``tar``.

This change only affects the very specific use case of where the entry point is overridden. The rule simply becomes that if you do that, then your image needs to have ``/usr/bin/env``. It is already probably going to be a rare corner case and in all probability ``/usr/bin/env`` would exist. The mistake here was simply not researching properly what is the more standard path for ``env`` that works every where.

**Comment by bparees** [comment]
/bin/env is the correct path on busybox and /usr/bin/env doesn't exist there (doesn't even have a /usr/bin folder), so this is still going to be broken for a set of people.

and your comparison to rsync is flawed.  oc rsync being broken by edge case logic with unforeseen consequences does not completely break the product for a user.

**Comment by GrahamDumpleton** [comment]
Is it a rule that ``assemble`` should ignore any arguments given it?

The only other option would be to actually set the ``Entrypoint`` as the ``assemble`` script and set the ``CMD`` as empty string, with additional ``CMD`` options removed.

So long as ``assemble`` always ignores arguments that should be fine.

If concerned that may in the future want to allow command line arguments to be passed to ``assemble`` for some reason, then use a dummy argument such as ``--build``. Would still be ignored for now, but later on if allow ``assemble`` to take arguments, then``--build`` argument would mean default behaviour of building application for image.

Only other choice is that there is a documented official environment variable passed in just for the build which identifies that this is a S2I build. Any existing ``Entrypoint`` command could then detect that and change behaviour such that all it does is execute the ``CMD`` it is given. I at least can deal with that, although everyone else would potentially be out of luck if they are trying to create an S2I image which builds on an existing base image.

If there is no reliable solution then means I may have to consider dropping support for S2I and OpenShift for my own Docker image build system, or have to supply multiple duplicate images where the only difference is no ``Entrypoint`` or ``CMD``, to cope with S2I not being able to reliably override them. Rather not have to deal with the extra work of maintaining the latter and the confusing it would generate.

**Comment by bparees** [comment]
There is no current definition of what an assemble script should do with args, since we don't submit any args to an assemble script today.  Setting the entrypoint directly to the assemble script might work, I'm not sure why we didn't do that originally, it may have had to do with logic we were using to handle scl enablement, but that doesn't appear to be the case anymore.

> If there is no reliable solution then means I may have to consider dropping support for S2I and OpenShift for my own Docker image build system, or have to supply multiple duplicate images where the only difference is no Entrypoint or CMD, to cope with S2I not being able to reliably override them.

i'd like to better understand the use case that requires your images to have a particular entrypoint.  Are these images that are intended to be run standalone, in addition to being used as s2i builders?  If so, what do they do when run standalone?

**Comment by mfojtik** [comment]
Isn't `assemble` taking the standard input for streaming sources? Also I think we are wrapping the script itself to deal with injected files (wait for upload/remove after).

I think it would be better practice to use the environment variables to parametrize the assemble script than use the command args (at least it is more auditable in OpenShift web console ;-).

**Comment by GrahamDumpleton** [comment]
@mfojtik we are not suggesting using command args to do anything. We only talking about whether it would be guaranteed that ``assemble`` would never take any arguments. Knowing it would always ignore arguments gets around the ``env`` problem in that ``assemble`` can be set as the entry point. In doing this though, it will always get at least one argument as the ``CMD`` will get passed as argument even if it is set to an empty string.

As to why they may have entry point and ``CMD``, they might for example be a database application which starts up with some default configuration. The image might at the same time be S2I enabled to take configuration files from a repo and override or customise default setup based on that. The entry point might be a script which ensures that certain environment variables are always setup properly even if a shell is being executed or some other command, based on configuration files added into the container. It might even scl_enable packages. People don't generally use the ``ENV``, ``BASH_ENV`` and ``PROMPT_COMMAND`` hack you use and instead use entry point.

**Comment by slaskawi** [comment]
@GrahamDumpleton Just in case you were looking for a workaround for this issue, here it is:
https://github.com/jboss-dockerfiles/infinispan/pull/49/files#diff-d0463d5d7460c28597180b6a29b001b8R6

The idea is to check whether a script in ENTRYPOINT was invoked with assembly script parameters. If so, just pass everything into `exec`.

@bparees @mfojtik Since the change has been reverted, may I ask to reopen this issue?

**Comment by bparees** [comment]
yes i'll reopen it, but we need to make sure whatever solution we come up with addresses the problem we encountered previously:

```
because we were committing images with "env" as the entrypoint which resulted in our post-commit tests failing because they couldn't find bundle because the scl enablement stuff didn't happen with that entrypoint.

we can revisit this after the merge queue is fixed, but basically we need to not commit the changed entrypoint.
```

**Comment by megakoresh** [comment]
I hit this for example with flyway image, which is intended to run as a replacement for command line tool, and by default simply prints usage information. This is definitely a problem when using s2i for single-run type of images instead of those running daemons.
