### ISSUE TITLE
Add option to stop after source injection and not run assemble.

### ISSUE THREAD

**Issue by GrahamDumpleton** [openshift/source-to-image#479]
When writing your own assemble scripts, debugging problems when working with sample injected code can be a pain. It would be good to have an extra options to allow you to inject code only but not run assemble. One can then run the image manually with a shell and run `assemble` by hand. Option could be called `--inject-only`.

**Comment by bparees** [comment]
can't you just provide an override assemble that does an exit 0?

**Comment by GrahamDumpleton** [comment]
I suggested this change after having talked to someone who had tried to create their own S2I builder and given up in the end as debugging issues was just too hard or non obvious. In OpenShift there is no way to get into the builder container when it is running, nor is there a way like there is for ``oc debug`` to start a builder pod, but leave you in a shell. For the builder pod you could copy the files in but not run assemble to allow such an equivalent, just open up the shell after copying.

I figured that getting an ``oc debug`` variant for builders was going to be unlikely, so figured that having an option to ``s2i`` to make it easier would have to suffice, and reasonable since is only S2I builders who would need it, although would still need to point them at using the ``s2i`` command directly rather than just using OpenShift.

Your suggestion of using an assemble script which just exits, means that someone would need to create that script (will it work for filesystem and not just Git repository) and then refer to it with the ``--scripts-url`` option to ``s2i``. So required an extra step.

The point of the option was just to make it a bit more obvious rather than relying on a non obvious trick. That one could use ``s2i`` directly and override scripts using ``--scripts-url`` was a total unknown to the person trying to develop their own S2I builder. If things aren't obvious and rely on tricks, it isn't providing a good experience. If not going to provide an obvious option, then it would be necessary to expand on current documentation and explain tricks like this and how to debug builders.

**Comment by bparees** [comment]
You can just put the scripts in your app repo. You don't need to specify a
scripts url. If users don't understand that, we have a docs problem. It's a
core part of the functionality (overriding scripts).

Not to mention if you're debugging your own image, you can build your
assemble script with the immediate exit yourself. That was cartridge
building 101 in v2.

Ben Parees | OpenShift

**Comment by GrahamDumpleton** [comment]
I may not be able to add a ``.s2i`` directory into the repo from which files are being pulled.This is because it need not be a S2I builder which is creating a web application from application code, but a SaaS application builder where all the repo is being used for is data input files, such as Jupyter Notebooks, possibly even coming from a public repository and not my own. In that case needing to add a ``.s2i`` directory into the repo with the data files is a worse option than using a scripts URL to separate debug variants of scripts.

As to exiting from the S2I builder scripts itself, that is a clumsy way of doing it where the scripts are a part of a S2I base image. If that is the only option there is going to be, I guess I would have no choice. Means the workflow is going to have be, run ``s2i`` with special environment variable. The ``assemble`` script sees environment variable and exits without doing anything. Then run the image with a shell. Manually unset the environment variable so running ``assemble`` again will not just see it exit again. Run the ``assemble`` script. I think I will just create a repo with an ``assemble`` script which exits and uses the script URL, easier.

**Comment by bparees** [comment]
moved to trello: https://trello.com/c/IQkmHKTF
