### ISSUE TITLE
s2i gives error for building the example ngnix-app

### ISSUE THREAD

**Issue by LalatenduMohanty** [openshift/source-to-image#506]
Steps to reproduce:

* git clone https://github.com/openshift/source-to-image.git
* cd source-to-image/examples/nginx-app
*  wget https://github.com/openshift/source-to-image/releases/download/v1.0.9/source-to-image-v1.0.9-f9ff77d-linux-amd64.tar.gz
* tar xvzf source-to-image-v1.0.9-f9ff77d-linux-amd64.tar.gz
* `s2i  build test/ nginx-centos7 nginx-app`
```
# s2i  build test/ nginx-centos7 nginx-app
I0524 18:11:40.117146 26391 docker.go:354] Image "nginx-centos7:latest" not available locally, pulling ...
E0524 18:11:46.771267 26391 main.go:342] An error occurred: unable to get nginx-centos7:latest
E0524 18:11:46.771302 26391 main.go:343] Suggested solution: check image name, or if using local image add --force-pull=false flag
E0524 18:11:46.771326 26391 main.go:349] If the problem persists consult the docs at https://github.com/openshift/source-to-image/tree/master/docs. Eventually reach us on freenode #openshift or file an issue at https://github.com/openshift/source-to-image/issues providing us with a log from your build using --loglevel=3
```

**Comment by php-coder** [comment]
Hello, thank you for the report!

Looks like you've followed the steps from [the instruction](https://github.com/openshift/source-to-image/tree/master/examples), right? I see that you missed one step when you're building `nginx-centos7` image:
> The next step is to create the builder image. In the nginx-app directory issue docker build -t nginx-centos7 .
This will create a builder image from the current Dockerfile.
