### ISSUE TITLE
RunC compatibility?

### ISSUE THREAD

**Issue by ryanj** [openshift/source-to-image#514]
Is RunC compatibility outside the scope of this project?  
Would it make sense to include a go lib to translate the image input or output?

**Comment by bparees** [comment]
image translation feels outside the scope.  supporting runc natively seems reasonable.

**Comment by PI-Victor** [comment]
@bparees is this hard to implement? i'd be interested in it

**Comment by bparees** [comment]
Extremely.

Ben Parees | OpenShift

**Comment by bparees** [comment]
opened in trello: https://trello.com/c/Eigu8zz3
