### ISSUE TITLE
Example of multi-step s2i build is needed

### ISSUE THREAD

**Issue by hemmop** [openshift/source-to-image#515]
From the README:

> For compiled languages like Java, C, or Golang, the dependencies necessary for compilation might dramatically outweigh the actual runtime artifacts. To keep runtime images slim, S2I enables multiple-step build processes, where a binary artifact such as an executable or Java WAR file is created in the first builder image, extracted, and injected into an second image that simply places the executable in the correct location for execution.

Please provide an example how to take advantage of this possibility (including the needed BuildConfig).

**Comment by php-coder** [comment]
We are working on this feature right now. Link to related Trello card: https://trello.com/c/MWUAjl6k/237-13-extended-builds-separate-mvn-vs-jboss-evg

I will add links to the documentation when this feature will be implemented, pass api/code reviews and merged.

**Comment by bparees** [comment]
@php-coder the readme is referring to the ability to do it manually today by building the first image, extracting the wars from that image, and then doing a second build.  so it is something we could document, but it probably does make sense to wait for your feature and document the first class support.

**Comment by wstrange** [comment]
I am somewhat confused as to the current state of s2i - including this feature.

I gather some significant changes are coming in the "extended build" PR that will change how multi-step images are built?   Is that PR expected to merge soon?

Any examples of a multi step tomcat / maven build would be really appreciated.

**Comment by bparees** [comment]
the PR should merge in the next few days, to be followed shortly by doc.  The syntax will look roughly like:

`s2i build . some/mavenimage your/outputappimage --runtime-image=some/tomcatimage`

where mavenimage is an image that contains maven and an assemble script that knows how to invoke a maven build against source code.

and some/tomcatimage is an image that contains tomcat and an "assemble-runtime" script that knows how to take inputs(in this case a war file that is being extracted from the maven assemble step) and put them in the right deployment directory for tomcat to find them.

**Comment by wstrange** [comment]
Thanks Ben - I will keep an eye on the PR

**Comment by cbeldacap** [comment]
Are there any news about the multi-staging s2i images?

thnx in advance

**Comment by bparees** [comment]
@cbeldacap the feature i alluded to above has merged in the s2i cli but we also decided  it isn't the direction we really want to go in, so we are generally downplaying the capability and not inclined to add more features/capabilities related to it.
