### ISSUE TITLE
Migrate fsouza/go-dockerclient to docker/engine-api

### ISSUE THREAD

**Issue by mfojtik** [openshift/source-to-image#516]
See: https://github.com/openshift/origin/issues/9320

**Comment by mfojtik** [comment]
@bparees FYI

**Comment by bparees** [comment]
@mfojtik any idea how big an effort this is?  (how different are the apis?)

**Comment by mfojtik** [comment]
@bparees there are some minor differences, but I think it will be mostly mechanical changes (sed/vim). Also S2I has already Docker interface, we just need to switch to call engine-api methods. (I think it would be ~5 in trello points, as we will have to plumb tests as well).

**Comment by bparees** [comment]
closing in deference to https://trello.com/c/l1sHwlvu/987-convert-to-docker-engine-apis
