### ISSUE TITLE
s2i fails with "Unable to load docker config" if HttpHeaders exists in ./docker/config.json

### ISSUE THREAD

**Issue by jupierce** [openshift/source-to-image#520]
When HttpHeaders is present in .docker/config.json (e.g. https://gist.github.com/jupierce/d0a063b2903056c2388412164280fb18) s2i fails with error:

Unable to load docker config
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x4ecef6]
goroutine 1 [running]:
panic(0x919820, 0xc820012100)
/usr/lib/golang/src/runtime/panic.go:481 +0x3e6
github.com/openshift/source-to-image/pkg/docker.GetImageRegistryAuth(0x0, 0x7ffc5e7ed2c6, 0x19, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
/home/jupierce/go/src/github.com/openshift/source-to-image/_output/local/go/src/github.com/openshift/source-to-image/pkg/docker/util.go:49 +0x3c6
main.newCmdBuild.func1(0xc82013e3c0, 0xc8201387e0, 0x3, 0x3)
/home/jupierce/go/src/github.com/openshift/source-to-image/_output/local/go/src/github.com/openshift/source-to-image/cmd/s2i/main.go:109 +0x895
github.com/spf13/cobra.(*Command).execute(0xc82013e3c0, 0xc8201386c0, 0x3, 0x3, 0x0, 0x0)
/home/jupierce/go/src/github.com/openshift/source-to-image/Godeps/_workspace/src/github.com/spf13/cobra/command.go:547 +0x85a
github.com/spf13/cobra.(*Command).Execute(0xc82013e000, 0x0, 0x0)
/home/jupierce/go/src/github.com/openshift/source-to-image/Godeps/_workspace/src/github.com/spf13/cobra/command.go:630 +0x46a
main.main()
/home/jupierce/go/src/github.com/openshift/source-to-image/_output/local/go/src/github.com/openshift/source-to-image/cmd/s2i/main.go:392 +0x7e0

HttpHeaders described here: https://docs.docker.com/v1.8/reference/commandline/cli/

**Comment by bparees** [comment]
guessing we need to bump fsouza/docker-client to fix this.

**Comment by wstrange** [comment]
I am seeing the same panic  with a fresh build of s2i (as of Jul 13)

**Comment by bparees** [comment]
@wstrange are you able to clean up your config.json to get around it?  @jupierce fixed it by removing this block from his config.json:
https://gist.github.com/jupierce/d0a063b2903056c2388412164280fb18#file-gistfile1-txt-L44

**Comment by bparees** [comment]
i guess not based on your other issue
