### ISSUE TITLE
Callback URL doesn't invoked when build fails

### ISSUE THREAD

**Issue by php-coder** [openshift/source-to-image#522]
[Callback URL section](https://github.com/openshift/source-to-image/blob/master/docs/cli.md#callback-url) a bit outdated:
- `labels` field is missing
- description of `success` says that this field `indicating the result of the build process (true or false)` but this callback never gets executed if build failed. It only executed for a successful builds and hence this field always has value `true` (I'm not sure whether it's a bug in the code or documentation)

**Comment by php-coder** [comment]
@bparees What's about 2nd point? Should I correct documentation or code?

**Comment by bparees** [comment]
the code should be fixed.

**Comment by php-coder** [comment]
From another hand, [the short description of the `--callback-url` parameter](https://github.com/openshift/source-to-image/blob/master/docs/cli.md#s2i-build) says "URL to be invoked after a successful build".

**Comment by bparees** [comment]
code should be fixed and that flag should be changed to say "after a build"

**Comment by rhcarvalho** [comment]
> the code should be fixed.

I never used this flag myself, at least not knowingly. Are we changing the old behavior of the flag? Any concerns with breaking people who could be relying in the old behavior?

**Comment by bparees** [comment]
> Are we changing the old behavior of the flag? Any concerns with breaking people who could be relying in the old behavior?

we're changing it to do what we always claimed it did, so while it is potentially a breaking change, it's also a bug fix.  in any case i'm pretty sure the number of people using this feature approaches 0.
