### ISSUE TITLE
Introspect options to "s2i build" from S2I Builder Image?

### ISSUE THREAD

**Issue by jawnsy** [openshift/source-to-image#527]
Hey,

Just forwarding this question from @amsokol here. Please help us assess it and re-tag as a feature request or close with an explanation as appropriate.

I think the use case in this scenario is to get the Git URL and context directory. This could be applicable to s2i-go since, by convention, the folder structure on disk should match the GitHub URL and context dir.

For example, if we wanted to build Sam Ghods' yaml library: `https://github.com/ghodss/yaml` - then the corresponding directory structure on disk should be something like: `/opt/go/src/github.com/ghodss/yaml/...` (where `/opt/go/` is the `GOPATH`) and we would use a `go install` command to build and install resulting binaries to `/opt/go/bin`.

Jonathan

Original text of Alexander's comment:

> When I create OpenShift app based on my OpenShift template I provide git url and context dir via ENV variables to “assemble” script implicitly for user.
> But it doesn’t work for “s2i build”.
> Yes, I know I can manually provide git url and context dir via “--env” but it's workaround.
> Could you please ask guys from s2i team is it possible to get git url and context dir inside “assemble” script?
> There is no any documentation how to get “s2i build” options inside “assemble” script.

**Comment by bparees** [comment]
it's true that we don't currently expose any of the s2i arguments to the assemble script.

i'm not explicitly averse to exposing them as env variables, though any env variables we provide to the container will also be included in the committed image.  in some cases (eg --ref) that may be desirable, in other cases it may not be, which means we'd probably need at a minimum, to make this an option (--includeArgs or something).

Would be happy to consider a PR for this.

**Comment by coreydaley** [comment]
@jawnsy Are you still interested in creating a pull request for this enhancement or should we go ahead and close this issue?

**Comment by bparees** [comment]
even if this were contributed i would not want to support the fallout from it.
