### ISSUE TITLE
The `--recursive` has the opposite action as expected

### ISSUE THREAD

**Issue by lbriais** [openshift/source-to-image#530]
The default config of `s2i` to clone repositories recursively (`--recursive`) is supposed to be set to true.  
Actually it is not the case, even passing explicitly `--recursive=true`.

But if you pass  `--recursive=false`, then __it is actually recursive__ !

I believe this option should be named `--disable-submodules` with a default to false. It would be much more consistent with the behaviour and the code too (as in the code it looks like it is referred to as `DisableRecursive`)...

**Comment by bparees** [comment]
i agree we should introduce a --disable-submodules flag w/ a default of false, when set to true we'll either use --recursive or submodule init logic depending whether --ref was also specified, and we'll remove the recursive flag.
