### ISSUE TITLE
error: Unable to load docker config  - when running nginx example

### ISSUE THREAD

**Issue by wstrange** [openshift/source-to-image#539]
Running:
s2i build test/ nginx-centos7 nginx-app

results in:

```
error: Unable to load docker config
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x112944]

goroutine 1 [running]:
panic(0x52a3c0, 0xc8200100c0)
	/usr/local/Cellar/go/1.6.2/libexec/src/runtime/panic.go:481 +0x3e6
github.com/openshift/source-to-image/pkg/docker.GetImageRegistryAuth(0x0, 0x7fff5fbff9d0, 0xd, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/warren/src/go/src/github.com/openshift/source-to-image/_output/local/go/src/github.com/openshift/source-to-image/pkg/docker/util.go:49 +0x3c4
main.newCmdBuild.func1(0xc82013a3c0, 0xc8201401b0, 0x3, 0x3)
	/Users/warren/src/go/src/github.com/openshift/source-to-image/_output/local/go/src/github.com/openshift/source-to-image/cmd/s2i/main.go:118 +0xa1f
github.com/spf13/cobra.(*Command).execute(0xc82013a3c0, 0xc820140090, 0x3, 0x3, 0x0, 0x0)
	/Users/warren/src/go/src/github.com/openshift/source-to-image/Godeps/_workspace/src/github.com/spf13/cobra/command.go:547 +0x85a
github.com/spf13/cobra.(*Command).Execute(0xc82013a000, 0x0, 0x0)
	/Users/warren/src/go/src/github.com/openshift/source-to-image/Godeps/_workspace/src/github.com/spf13/cobra/command.go:630 +0x46a
main.main()
	/Users/warren/src/go/src/github.com/openshift/source-to-image/_output/local/go/src/github.com/openshift/source-to-image/cmd/s2i/main.go:410 +0x8ac
```

This looks the same as  https://github.com/openshift/source-to-image/issues/520 
But I dont have HttpHeaders in my docker config

**Comment by bparees** [comment]
can you paste/gist your config.json?  (stripping actual auth values of course)

**Comment by wstrange** [comment]
@bparees  It looks something like this:

'''
{
        "auths": {
                "https://appengine.gcr.io": {
                        "auth": xxxx=",
                        "email": "not@val.id"
                },
                "https://asia.gcr.io": {
                        "auth": "xxxxxx",
                        "email": "not@val.id"
                },
                "https://b.gcr.io": {
                        "auth": "xxxxxx",
                        "email": "not@val.id"
                },
                "https://bucket.gcr.io": {
                        "auth": "X3Rva2VuOnlhMjkuYVFMR3ZtZzg3b3psS1hfWWVNdDgtdXhqM0NFY3lNMGJZUThCTVZ5dmlhZ0tOTDB5WFNsYlVPMTlKZDJrY2U5SWV6YzNJek0=",
                        "email": "not@val.id"
                },
                "https://eu.gcr.io": {
                        "auth": "xxxxx=",
                        "email": "not@val.id"
                },
                "https://gcr.io": {
                        "auth": "xxxxx",
                        "email": "not@val.id"
                },
                "https://index.docker.io/v1/": {
                        "auth": "xxxxx",
                        "email": "warren.strange@gmail.com"
                },
                "https://us.gcr.io": {
                        "auth": "xxxxxxxxx=",
                        "email": "not@val.id"
                }
        },
}

'''

**Comment by wstrange** [comment]
Facepalm

I edited out the HttpHeaders entry, but left a trailing comma

It looks like removing the HttpHeaders entry solved this problem


I will close this issue since it looks like a dupe of #520

**Comment by bparees** [comment]
thanks. i'm working on updating the fsouza dependency in hopes that a newer version handles this.
