### ISSUE TITLE
Docs:  How does s2i differ from something like the fabric8 docker plugins?

### ISSUE THREAD

**Issue by wstrange** [openshift/source-to-image#540]
One thing that is not clear to me - and perhaps could be addressed in the documentation.

How does using s2i differ from using something like the fabric8 maven docker plugin?

It looks like both can produce the same result:  They both take source code and build a final docker container with that source. The fabric8 approach builds the artifact outside of a container (no builder container to speak of), but in theory it creates repeatable builds.   The plugin injects the artifacts (war file, etc.) into the final container - much like s2i does. 

Why would I want to use one vs the other?

**Comment by bparees** [comment]
as far as i know the maven docker plugin is still ultimately writing a dockerfile and executing a docker build, which is not what s2i does, the advantages of the s2i approach (not doing a docker build) are enumerated in the readme here:
https://github.com/openshift/source-to-image/blob/master/README.md#goals

in particular see the sections on speed and security.

the maven plugin also presumes you are working in a maven tool chain, s2i is agnostic to such things.

i'm also pretty sure the maven docker plugin is targeted at producing images for fabric, again s2i is agnostic.

So if fabric is your target, it makes sense to use it, if not, s2i is probably more flexible/appropriate.

@jstrachan maybe you can offer more background on the fabric8 maven plugin side.

**Comment by wstrange** [comment]
I'm still not connecting the dots...

What does "not doing a docker build" mean?

Doesn't s2i execute docker commands to build an image?

If I examine the nginx example using docker history, I don't think I see a difference in the image layers  vs, what I would get if I just built the container directly. 

What would really help me (and perhaps others?) is to show the same image being built two different ways (old school, and using s2i) - to illustrate the difference. 

I do get the build vs. runtime image thing (no build tools needed in final runtime image). This seems to be the key value prop?

Maybe a more complex example (tomcat?) would illustrate the use case better.

**Comment by bparees** [comment]
Write a dockerfile that does:
FROM centos(or some tomcat image)
ADD mysource
RUN mvn package
RUN mv mywar /tomcat/deployments

You will get an image with 3 new layers on top of what centos had.
In addition, you can write more docker commands in that dockerfile like:
USER root
RUN some_superuser_command
RUN yum install
etc to perform privileged actions during your "build" process.

When you use s2i, only one additional layer is added, we are not writing a dockerfile, we are not performing a docker build. We are starting a new container, running commands within that container (the assemble script) and committing that container as a new image (which adds the 1 new layer).

And the assemble script can be enforced to run as a controlled(non-root) user so unless you have permission to sudo, you're not performing privileged actions, so if you use s2i with a source repo and a known builder image (assuming you don't override the assemble script), you are asserting more control over the types of actions that were taken to create the application image, compared to writing a Dockerfile where someone can yum install/curl download anything from anywhere.

The build vs runtime thing is definitely not the key value proposition, that's actually a brand new feature we've just delivered.

I actually just did a community briefing that covers s2i and the value proposition in detail, the recording should be posted soon, i'll put the link to it in this issue once it goes live, I think it may address more of your questions (and we can link it from the s2i doc).

@dmueller2001 can you link the s2i community briefing here once it's available?

**Comment by wstrange** [comment]
Ahh , OK - so looking more carefully at the nginx example I can see one layer added to the base image. 

Those first 2-3 paragraphs might be helpful in the README

**Comment by bparees** [comment]
@wstrange here's the briefing i mentioned:
https://www.youtube.com/watch?v=flI6zx9wH6M

i'll add it in the readme.

**Comment by wstrange** [comment]
Awesome - watching it now!
