### ISSUE TITLE
Environment and EnvironmentSpec duplication

### ISSUE THREAD

**Issue by php-coder** [openshift/source-to-image#545]
I've found that S2I has two exactly the same structures for representing environment variable: [`Environment`](https://github.com/openshift/source-to-image/blob/9350cd1ef8afc9c91dcdc96e1d972cbcc6f36181/pkg/scripts/environment.go#L14-L18) and [`EnvironmentSpec`](https://github.com/openshift/source-to-image/blob/9350cd1ef8afc9c91dcdc96e1d972cbcc6f36181/pkg/api/types.go#L238-L242).

I think that we don't need to have both and one of them should be superseded by another.

**Comment by bparees** [comment]
yeah i can't imagine why, let's collapse them.
