### ISSUE TITLE
rebase script broken by latest changes

### ISSUE THREAD

**Issue by PI-Victor** [openshift/source-to-image#549]
@bparees as @php-coder found out, we are not adding the pkg/run package when we bump origin.
do we remove the package or the exception in the script?
exception:https://github.com/openshift/source-to-image/blob/master/hack/rebase-to-origin.sh#L29

and variable.
https://github.com/openshift/source-to-image/pull/543/files#diff-234f90ce9afdfa35fbed6beda2f55c53R14

currently this is broken, so we shouldn't bump origin.

**Comment by php-coder** [comment]
The dependency on `github.com/openshift/source-to-image/pkg/run` package was added in PR #543 I suggest to move this constant to somewhere else and leave rebasing script as-is.

**Comment by bparees** [comment]
yeah, agreed, we can move the constant somewhere else.
