### ISSUE TITLE
s2i scripts with `*.sh` suffix are not recognized

### ISSUE THREAD

**Issue by jhadvig** [openshift/source-to-image#564]
When having a custom s2i script in my application repo, that has `.sh` suffix it wont be recognized. 

The thing is that decent percentage of the users(me including) will create the scripts with the `.sh` suffix automatically since they will see that its a bash script.

**Comment by mfojtik** [comment]
sounds useful for me, especially for windows users ;-)

**Comment by jhadvig** [comment]
Was said by a Mac user :monkey:

**Comment by mfojtik** [comment]
@jhadvig mac is bsd ;-)

**Comment by php-coder** [comment]
BTW, when you're using `ONBUILD` directive, you should provide a script that will be used as an entrypoint and in this case [S2I supports `.sh` suffix](https://github.com/openshift/source-to-image/blob/9227a4f113f838bff0db24150cd85b134aa29fdc/pkg/build/strategies/onbuild/entrypoint.go#L14-L19) for it.

**Comment by bparees** [comment]
We doc the filename to use, I don't want to create a list of possible filenames. And if you provided both, which one would you expect us to run?  And it doesn't have to be a bash script, any executable file is acceptable.
