### ISSUE TITLE
Not compilable with go 1.4

### ISSUE THREAD

**Issue by miminar** [openshift/source-to-image#579]
Master branch seems to be used in fork_ami jobs which may run with go1.4 image. Using this image, the compilation fails:

```
+ vagrant build-sti --binary-only
Running ssh/sudo command '
pushd /data/src/github.com/openshift/source-to-image
  commit_id=`git rev-parse $(git rev-parse --abbrev-ref HEAD)`
  git_status=$(git status --porcelain)
  if [ -f ~/sync/source-to-image ]
  then
    previous_commit_id=$(cat ~/sync/source-to-image)
  fi
  if [ "$previous_commit_id" != "$commit_id" ] || [ -n "$git_status" ]
  then
    
echo "Performing source-to-image build..."
set -e
hack/build-go.sh

  else
    echo "Commit ID: $commit_id"
    echo "Previous Commit ID: $previous_commit_id"
    echo "Git Status: $git_status"
    echo "No update for source-to-image, $(git rev-parse --abbrev-ref HEAD)"
  fi
  mkdir -p ~/sync
  echo -n $commit_id > ~/sync/source-to-image
popd
        ' with timeout 14400. Attempt #0
/data/src/github.com/openshift/source-to-image ~
Performing source-to-image build...
++ Building go targets for linux/amd64: cmd/s2i
_output/local/go/src/github.com/openshift/source-to-image/pkg/docker/docker.go:21:2: cannot find package "github.com/docker/docker/pkg/stdcopy" in any of:
	/usr/lib/golang/src/github.com/docker/docker/pkg/stdcopy (from $GOROOT)
	/data/src/github.com/openshift/source-to-image/_output/local/go/src/github.com/docker/docker/pkg/stdcopy (from $GOPATH)
	/data/src/github.com/openshift/source-to-image/vendor/src/github.com/docker/docker/pkg/stdcopy
```

See the failing job at https://ci.openshift.redhat.com/jenkins/job/fork_ami/288/consoleFull.

Either the jenkins script need to use some older version having dependencies in `Godeps` directory or the vendor directory needs to contain `src -> .` symlink.

In case of the former, the openshift/source-to-image repository should have `enterprise-3.2` branch or something similar. In case of the latter, the `GOPATH` needs to be prepended with `/data/src/github.com/openshift/source-to-image/vendor`.

**Comment by bparees** [comment]
does the fork ami job even need to be building s2i?  what does it need it for?

**Comment by miminar** [comment]
> does the fork ami job even need to be building s2i? what does it need it for?

I'm not sure, it doesn't seem to be needed by build script at https://ci.openshift.redhat.com/jenkins/job/fork_ami/configure .

**Comment by bparees** [comment]
@miminar ok i've commented out the s2i related bits of that job, if we need an s2i fork ami we can just build the s2i binary manually and give it to QE, we really don't need an AMI process for it.

let me know if your AMI build is successful/functional now and if so we can close this.

**Comment by miminar** [comment]
@bparees thanks! I got it working using `S2I_FORK_ID=miminar`, `S2I_BRANCH=enterprise-3.2`
and `S2I_REPO=source-to-image` with the `  vagrant build-sti --binary-only` in place. But let me try without it next time.

**Comment by miminar** [comment]
@bparees The build succeeded. Thanks! Closing now.
