### ISSUE TITLE
Option for production image

### ISSUE THREAD

**Issue by majgis** [openshift/source-to-image#588]
I was surprised to find the the builder image is committed for use in production.
My expectation was that the builder image would produce the build artifacts which would then be copied into a separate production image, along with the run script.

What are your thoughts on providing an additional option for specifying a separate image for production, in which case the builder image is used exclusively for building?

I agree it would add build time, but for those of us who care more about the lighter weight and security of the image being used in production, we could specify an additional step be added to the process.

**Comment by bparees** [comment]
that's extended builds: https://github.com/openshift/source-to-image/blob/master/docs/runtime_image.md

**Comment by bparees** [comment]
@php-coder fyi
