### ISSUE TITLE
oci runtime error: exec: "/bin/env": stat /bin/env: no such file or directory

### ISSUE THREAD

**Issue by Silvanoc** [openshift/source-to-image#589]
source-to-image version: **1.1.1**
host distribution: Debian
distribution base image: **Debian**

# Error

I'm trying to build a Maven application directly with the Docker image "maven:latest" and I'm getting following error message:
`An error occurred: API error (404): {"message":"oci runtime error: exec: \"/bin/env\": stat /bin/env: no such file or directory"}
`

# Diagnosis

If I use another image based on `maven:latest` only with `RUN ln -s /usr/bin/env /bin/env` it works like a charm.

Therefore it's obvious that the only issue is that **the path where the executable env is expected to be doesn't exist** in the image I'm using. I tried to found out if the path is being used somewhere in the code, but I couldn't find it.

# Others

Might it be a "distribution-dependency" on *Centos*-based images?

In Centos-based systems the executable *env* appears to be found in `/bin/env` (and a symbolic link to it exists in `/usr/bin/env`).

But the image `maven:latest` is Debian-based and the only place where the executable *env* can be found in Debian systems is `/usr/bin/env`.

The [Filesystem Hierarchy Standard](http://refspecs.linuxfoundation.org/fhs.shtml) doesn't appear to specify where the executable *env* should be placed, but a Google search gives me the impression that `/usr/bin/env` is a more common place than `/bin/env`.

**Comment by php-coder** [comment]
It should be fixed in the next release (see https://github.com/openshift/source-to-image/pull/560).

**Comment by bparees** [comment]
this has been fixed already: https://github.com/openshift/source-to-image/pull/560

we also fixed it to override only in special cases where it was necessary:
https://github.com/openshift/source-to-image/pull/575

just haven't done a new release yet.  i'll try to put one together today.

**Comment by Silvanoc** [comment]
Thank you for the quick replies!
