### ISSUE TITLE
Run - Startup script question

### ISSUE THREAD

**Issue by gfvirga** [openshift/source-to-image#599]
Does anyone know how the openshift/base-centos7 image call the /usr/local/sti/run in the container startup? 
I am building our internal custom image to have apache, php55 and shibd...
We am trying to start shibboleth (shibd) using the user (shibd) not the default, because we don't want the openshift developers to have read access to the shibboleth ssl .crt and keys.

**Comment by bparees** [comment]
the base image doesn't call anything.  the base image just provides some common tools/packages that many of our s2i images use.

as for how the run script from the s2i image itself gets invoked, when you "s2i build" a new application image, the resulting image has the run script set as the container command.  It will run as whatever use the image defaults to.  (or a different user if you run "docker run -u SOMEUSER yourimage")

**Comment by gfvirga** [comment]
Thanks for your quick response.

I was able to start a container with httpd running as the default user and then manually running `docker exec -u shibd -it <container id> shibd` and then start shibboleth as shibd. 
`[root@baleia ~]# docker exec -it romantic_hawking ps -ef
UID        PID  PPID  C STIME TTY          TIME CMD
default      1     0  0 19:49 ?        00:00:00 httpd -D FOREGROUND
default     25     1  0 19:49 ?        00:00:00 /usr/bin/cat
default     26     1  0 19:49 ?        00:00:00 /usr/bin/cat
default     27     1  0 19:49 ?        00:00:00 httpd -D FOREGROUND
default     29     1  0 19:49 ?        00:00:00 httpd -D FOREGROUND
default     32     1  0 19:49 ?        00:00:00 httpd -D FOREGROUND
default     35     1  0 19:49 ?        00:00:00 httpd -D FOREGROUND
default     39     1  0 19:49 ?        00:00:00 httpd -D FOREGROUND
default     41     1  0 19:49 ?        00:00:00 httpd -D FOREGROUND
default     43     1  0 19:49 ?        00:00:00 httpd -D FOREGROUND
default     44     1  0 19:49 ?        00:00:00 httpd -D FOREGROUND
shibd       70     0  1 19:50 ?        00:00:00 shibd -f -F
default     87     0  0 19:50 ?        00:00:00 ps -ef`

But we were looking for something more automated than having to do it manually, that way we could make the image available in openshift for anyone to use on demand.

**Comment by bparees** [comment]
if you want the image to run as shibd, then author the image to have a "USER shidb" line at the end of the dockerfile.

and author your s2i run script to run whatever you want the image to start when the image starts.

however if you intend to run the image on openshift, you should not rely on your processes running a a particular user.  Containers on openshift are assigned a random uid and your image should tolerate running with that random uid, not assuming it will run as a particular uid:

https://docs.openshift.org/latest/creating_images/guidelines.html#openshift-origin-specific-guidelines

(see: support abitrary user ids)

**Comment by gfvirga** [comment]
Ben, thank you so much for this info. 
We will hopefully find a solution for this.
