### ISSUE TITLE
1.1.2 does not work with git submodules

### ISSUE THREAD

**Issue by mikz** [openshift/source-to-image#606]
# Steps to reproduce

s2i version 1.1.2
git version 2.10.0

* git clone https://github.com/3scale/s2i-openresty
* make test

## Result

> ERROR: An error occurred: lstat .../3scale/s2i-openresty/test/test-app/.git/objects: not a directory

## Expected result

successful build

## More info

`test/test-app/.git` is a file with following contents:

> gitdir: ../../.git/modules/test/test-app

It is standard git submodule. 
Version 1.1.1 was working just fine.
git version 2.10.0

## Workaround

```sh
cd test/test-app
rm .git
ln -s ../../.git/modules/test/test-app .git
```

**Comment by jim-minter** [comment]
Taking a look. @mikz, btw your Dockerfile at https://github.com/3scale/s2i-openresty is broken. It requires the EPEL repo to be added to it.

**Comment by mikz** [comment]
@jim-minter thanks. Figured that out yesterday (https://github.com/openresty/openresty-packaging/issues/8), but haven't merged it to master yet. Fill fix it ASAP.

**Comment by jim-minter** [comment]
I think this regression is probably caused by #552.
