### ISSUE TITLE
Use common parser for DockerImageReference

### ISSUE THREAD

**Issue by legionus** [openshift/source-to-image#614]
Recently `origin` and S2I use their own implementations of `ParseDockerImageReference`. Right now S2I started to use `github.com/docker/distribution/reference` as parser and `origin` started use parser based on same module. I think it would be better to use the same parser for `DockerImageReference` to avoid differences in behavior in the future.

I made a [module](https://github.com/openshift/origin/tree/master/pkg/image/reference) without dependencies on `origin`. It can be used in both repositories. If the parser will be changed, we will not need to synchronize our parsers any more.

https://github.com/openshift/source-to-image/pull/594
https://github.com/openshift/origin/pull/11245

**Comment by deads2k** [comment]
@legionus @jim-minter this introduced a cyclical dependency between source-to-image and origin.  Since we flatten the vendor tree in origin, the cycle meant we couldn't move or eliminate our package (we had no need for it to be exposed in openshift).
