### ISSUE TITLE
custom s2i scripts loses its executable permission when image built on MS-Windows

### ISSUE THREAD

**Issue by jperville** [openshift/source-to-image#620]
# Summary

When building image with s2i on MS-Windows host
And when the code features a custom `.s2i/bin/run` script.
Then that script is injected in the image without executable permission

As a consequence, the image produced by `s2i build` is unbootable.
# Context
- trying to run `s2i build` on MS Windows host with the latest "docker toolbox" (version 1.12.2)
- using s2i version 1.1.1 (as long as version 1.1.2 suffers from #603)
# How to reproduce

Run the following commands on Linux first, then on MS-Windows with the latest "docker toolbox" installed.

``` sh
git clone https://github.com/openshift/ruby-hello-world.git
cd ruby-hello-world

mkdir -p .s2i/bin
echo -e '#!/bin/sh\n\nexec bundle exec ruby app.rb' | tee .s2i/bin/run
chmod +x .s2i/bin/run
git add .s2i/bin/run
git commit -m "Add .s2i/bin/run"

s2i build . centos/ruby-22-centos7 ruby-hello-world          

docker run --rm ruby-hello-world
```

On Linux host, the last `docker run` command boots the image as expected.
On Windows host, the last `docker run` command fails with the following output:

``` sh
Lambda@perfect-dev MINGW64 ~/ruby-hello-world (master)
$ docker run --rm ruby-hello-world
/usr/bin/container-entrypoint: line 2: /tmp/scripts/run: Permission denied
/usr/bin/container-entrypoint: line 2: exec: /tmp/scripts/run: cannot execute: Permission denied
```

It is easy to verify that the problem is that the CMD is not executable:

``` sh
Lambda@perfect-dev MINGW64 ~/ruby-hello-world (master)
$ docker run --rm ruby-hello-world ls -l /tmp/scripts/run
-rw-r--r-- 1 default root 38 Oct 21 14:24 /tmp/scripts/run
```

On Linux host, the CMD is executable, as expected:

``` sh
jp440p:ruby-hello-world(41m|master?) $ docker run --rm -ti ruby-hello-world ls -l /tmp/scripts/
total 12
-rwxr-xr-x 1 default root   40 Oct 21 14:18 run
```

**Comment by bparees** [comment]
@jim-minter seems related to the other windows work you're already doing.
