### ISSUE TITLE
s2i should not include the .s2iignore in the final image.

### ISSUE THREAD

**Issue by GrahamDumpleton** [openshift/source-to-image#621]
The `.s2iignore` file can be used to indicate files that should not be copied from the source directory into the image when it is being created. In doing this, `s2i` should remove the `.s2iignore` file as well after it is done.

Original source directory contained:

```
8 -rw-r--r--    1 graham  staff   132 25 Oct 14:19 .htaccess
8 -rw-r--r--    1 graham  staff    10 25 Oct 14:26 .s2iignore
8 -rw-r--r--    1 graham  staff   815 25 Oct 13:15 503.html
8 -rw-r--r--@   1 graham  staff   687 25 Oct 14:40 README.md
```

with the `.s2iignore` file containing:

```
README.md
```

When `s2i build` was run, relevant lines in the log file were:

```
I1025 15:15:50.691897   12240 ignore.go:74] .s2iignore lists a file spec of README.md
I1025 15:15:50.691908   12240 ignore.go:106] using globspec /var/folders/0p/4vcv19pj5d72m_bx0h40sw340000gp/T/s2i888197727/upload/src/README.md
I1025 15:15:50.691926   12240 ignore.go:112] Glob result /var/folders/0p/4vcv19pj5d72m_bx0h40sw340000gp/T/s2i888197727/upload/src/README.md
I1025 15:15:50.691940   12240 ignore.go:41] attempting to remove file /var/folders/0p/4vcv19pj5d72m_bx0h40sw340000gp/T/s2i888197727/upload/src/README.md
```

So the `README.md` file got removed as required, but then the `.s2iignore` file is left behind.

```
I1025 15:15:50.694453   12240 tar.go:308] Adding to tar: /var/folders/0p/4vcv19pj5d72m_bx0h40sw340000gp/T/s2i888197727/upload/src/.htaccess as src/.htaccess
I1025 15:15:50.913890   12240 tar.go:308] Adding to tar: /var/folders/0p/4vcv19pj5d72m_bx0h40sw340000gp/T/s2i888197727/upload/src/.s2iignore as src/.s2iignore
I1025 15:15:50.914038   12240 tar.go:308] Adding to tar: /var/folders/0p/4vcv19pj5d72m_bx0h40sw340000gp/T/s2i888197727/upload/src/503.html as src/503.html
```

The final directory in the image ended up containing:

```
4 -rw-rw-r-- 1 default root  132 Oct 25 04:15 .htaccess
4 -rw-rw-r-- 1 default root   10 Oct 25 04:15 .s2iignore
4 -rw-rw-r-- 1 default root  815 Oct 25 04:15 503.html
```

Was expected that `.s2iignore` would be automatically removed as there is no point keeping it.

If want to replicate try:

```
s2i build https://github.com/getwarped/httpd-site-maintenance.git getwarped/s2i-httpd-server mysite --loglevel 9
```

Look in directory `/opt/app-root/htdocs` for what was copied in.

**Comment by jim-minter** [comment]
@GrahamDumpleton, I'm not sure I agree.  The flip side to this is: the .s2iignore file was checked in to the git repository, so it should therefore be placed in the container.  If you really don't want the .s2iignore file there, you can append the text ".s2iignore"  to the .s2iignore file, or you could use the --exclude option to s2i instead.

**Comment by GrahamDumpleton** [comment]
The ``.s2i`` directory is also part of the git repository but the way ``s2i` deals with it it doesn't end up in the set of source files the builder is presented with in the ``/tmp/src/ directory. Thus there is already precedent for not passing through files which relate to the S2I build process.

I can't see any good reason for the ``.s2iignore`` file to be preserved as it relates to the S2I process and is not part of the application code. It is likely to cause more problems by keeping it as the mere existence of an unexpected file in the resulting image could upset whatever the S2I builder does. Making the user manually adding ``.s2iignore`` to itself is an extra unnecessary step.

**Comment by jim-minter** [comment]
I'm still not convinced.  I don't see that an .s2i directory is treated specially today - if it exists in the git repo, it is copied up to the container just like any other directory.  Also, the .s2iignore functionality mirrors the Docker .dockerignore functionality and behaves in the same way today.  There may be value in keeping it that way.

**Comment by GrahamDumpleton** [comment]
It is not correct that the ``.s2i`` directory is not treated in a special way. The ``.s2i/bin`` directory is never copied across into the image.

Anyway, forget it. Just realised that the whole way S2I works is a bigger security risk than I thought for certain class of S2I builders. Am going to have to incorporate additional security measures in the S2I builder to get around how ``s2i`` itself works.

**Comment by php-coder** [comment]
Maybe we can document this behavior explicitly? Because, it wasn't obvious to me too.

**Comment by GrahamDumpleton** [comment]
You also then need to document that ``.s2iignore`` file cannot be used to exclude the ``.s2i`` directory itself as that will stop the ``.s2i/environment`` file from working. Not even checked whether it breaks ``.s2i/bin``.

Now the ``.s2i/bin`` directory is excluded from the final files that could end up in the ``src`` directory for some S2I builders. The ``.s2i/environment`` file cannot be excluded if you still want to use it.

This can have consequences if the ``.s2i/environment`` file contained sensitive information and the purpose of the S2I builder was to make the files copied in available in some way for download.

Imagine for example an S2I builder for a HTTPD web server which served up all the files copied in. If the ``.s2i/environment`` existed then a external user could download it, and if that had sensitive information in it, then a user could get it.

Thus the S2I builder itself needs to ensure they remove the ``.s2i`` directory themselves and ensure it is not copied into the directory of files being served up. It would be wise for the S2I builder to also ensure it doesn't copy the ``.s2iignore`` file as you can't rely on a user to remember to add ``.s2iignore`` to itself.

**Comment by GrahamDumpleton** [comment]
BTW, when will support for ``.s2iignore`` even make it into OpenShift. Doesn't appear to be in Origin 1.3.

**Comment by bparees** [comment]
> You also then need to document that .s2iignore file cannot be used to exclude the .s2i directory itself as that will stop the .s2i/environment file from working. Not even checked whether it breaks .s2i/bin.

I suppose that is because .s2i/environment is not considered part of the build inputs if you told us to .s2iignore it.  Does seem the docs could be clearer on that point.  As you suspect, I'm sure it causes s2i to ignore any run/assemble scripts in your repo as well.

> Now the .s2i/bin directory is excluded from the final files that could end up in the src directory for some S2I builders. The .s2i/environment file cannot be excluded if you still want to use it.

I think we're in a tough spot on this.  We say we'll put the contents of your repo into the assembly container.  Special casing "everything except the .s2i folder" starts to feel dubious.  I think if you have sensitive information then .s2i/environment is not for you, or you need a custom assemble script that removes the file from the container before it gets committed.  But again, documentation could be improved.

You can also use the -E flag to pass an environment file to s2i, rather than making it part of your repo, in which case it will not appear as a file inside the application image.  But of course that requires to you maintain the file outside your source repo.


> BTW, when will support for .s2iignore even make it into OpenShift. Doesn't appear to be in Origin 1.3.

probably never.  the existence of .s2iignore itself is a symptom of s2i the CLI tool doing more than it should (git clone).  s2i really should have simply taken a local directory and built your app image from it, rather than taking on the responsibility of git cloning (and filtering) the source files.

when it comes to openshift, there are a number of potential inputs (source/git, from images, secrets, etc), and those are valid regardless of build type (docker vs s2i), so if we were going to do any sort of exclude/filtering feature in openshift, we'd allow you define the filters as part of the input content definition (eg the source/git info) rather than as part of an s2i strategy definition.

**Comment by GrahamDumpleton** [comment]
So in effect I can never use ``.s2iignore`` feature and need to implement my own filter file as part of the S2I builder if that sort of functionality is important.

**Comment by bparees** [comment]
> So in effect I can never use .s2iignore feature and need to implement my own filter file as part of the S2I builder if that sort of functionality is important.

if you intend to port the repo back and forth between standalone s2i environments and openshift environments, that's correct.  Again, the real answer here is that s2i shouldn't have taken on this responsibility in the first place, but now that it did the best we can do is deprecate it for a while before removing it.

> It perhaps then needs to also be clarified in the documentation that .s2iignore is not used when using S2I as part of OpenShift.

yes, should probably be noted in the openshift documentation about these sort of specific differences from the behavior of the cli tool.
