### ISSUE TITLE
Payload field that is sending to the remote server is always empty

### ISSUE THREAD

**Issue by php-coder** [openshift/source-to-image#629]
[Callback URL documentation](https://github.com/openshift/source-to-image/blob/master/docs/cli.md#callback-url) says that `payload` field contains "a string containing all build messages". During during fixing #522 I found that this field is always empty:
```
POST / HTTP/1.1
Host: 127.0.0.1:8888
User-Agent: Go-http-client/1.1
Content-Length: 216
Content-Type: application/json
Accept-Encoding: gzip

{"labels":{"io.k8s.display-name":"my-test-app","io.openshift.s2i.build.image":"java:8","io.openshift.s2i.build.source-location":"/data/src/github.com/openshift/source-to-image/s2i-test"},"payload":"","success":true}
```

**Comment by php-coder** [comment]
@bparees Do you know how we can collect all build messages? We're logging them via `glog` and they're printed to the stdout/stderr. Show we create another one special logger? Or how it's going to be?

**Comment by bparees** [comment]
@php-coder collect them where?

**Comment by php-coder** [comment]
@bparees In the [`Message` field of the `Result` object](https://github.com/openshift/source-to-image/blob/917c667e603d917e6f493d96ad615a3c85138c80/pkg/api/types.go#L326-L327).

**Comment by bparees** [comment]
I think you should just set a message for each execution step indicating success/failure and the error.  i don't think it needs to be an exact replica of what you'd see on stderr/stdout from the CLI.

(I doubt anyone is even using this feature, it's another "never should have been implemented" idea.)

**Comment by PI-Victor** [comment]
nope, nobody uses that. i can confirm it. just as result.success isn't that used as well (one or two places, the rest looks for result == nil of err != nil ). i wanted to use that instead of buildinfo in the beginning.

**Comment by PI-Victor** [comment]
by the way, can we deprecate fields like that? since we don't use them and they aren't of any value?
or something like:
```
// Messages is a list of messages from build process. 
// NOTE: Field deprecated, will be removed in a future version
Messages []string
```

**Comment by bparees** [comment]
@PI-Victor we can, but we don't have a great process in place for ultimately removing them.  In this case, making it "work" is probably the path of least resistance.

**Comment by php-coder** [comment]
>edit: i actually fixed the result.success, forgot about that.

How it was broken?

**Comment by PI-Victor** [comment]
@php-coder it wasn't broken. but rather not implemented for layered strategy for example. i know we check one place for success = true, otherwise i don't know where else we do it.
we also don't use it in origin. we only check for err when we get the build result.

**Comment by PI-Victor** [comment]
ok, i can make it work, the question is, what "messages" should the build process surface. are we talking about failures or just just something else (we have glog in place for that already) the api docs arent' very specific.

**Comment by PI-Victor** [comment]
nvm about my previous comment.

**Comment by bparees** [comment]
@coreydaley let's just drop the field and change the doc.  i doubt anyone is even using this callback feature anyway.
