### ISSUE TITLE
Integration tests: test that builds take a reasonable amount of time

### ISSUE THREAD

**Issue by rhcarvalho** [openshift/source-to-image#652]
From https://github.com/openshift/source-to-image/pull/648#discussion_r90856995

Tests that take too long (e.g. more than `DefaultDockerTimeout`), might indicate synchronization issues or other subtle bugs.

We should also introduce a test for a build that runs longer than the docker timeout, to ensure none of our timeout-based logic will fail a build when it is proceeding normally (but takes a long time to clone source, or commit the image, or some other step), from: https://github.com/openshift/source-to-image/pull/648#discussion_r90856704

**Comment by bparees** [comment]
i don't see us getting to this and if it were an issue i'd sort of expect to see it show up in the form of test flakes given all the builds we run as part of tests.
