### ISSUE TITLE
docker-engine deprecated

### ISSUE THREAD

**Issue by bparees** [openshift/source-to-image#659]
(sigh)

see: https://github.com/openshift/origin/issues/12212

hopefully this move is more straightforward than the last one.

**Comment by jim-minter** [comment]
I don't propose to touch this until kubernetes has moved.  Then we can do origin and source-to-image at the same time.

**Comment by bparees** [comment]
closing, if circumstances eventually force us to move then we will move, until then we won't pursue it.
