### ISSUE TITLE
Add more information to STI callback payload

### ISSUE THREAD

**Issue by csrwng** [openshift/source-to-image#66]
Include builder image, source repo, date, time, image tag

**Comment by bparees** [comment]
@mfojtik given that you just added a bunch of this information as labels, you want to add it to the callback too?

**Comment by mfojtik** [comment]
@rhcarvalho what is the state of this? I can take care if this if you want.

**Comment by rhcarvalho** [comment]
@mfojtik haven't started on it. Feel free to take it back, I still have other issues assigned to me ;)

**Comment by bparees** [comment]
this is super low priority, please find something else to do... even docs work would be more important than this.  I'm not aware of anyone using the s2i callback feature, and if anything we're trying to strip down the amount of stuff s2i can do, not add to it.
