### ISSUE TITLE
S2I test/run issues 

### ISSUE THREAD

**Issue by marc-despland** [openshift/source-to-image#661]
Hello 

I used ```s2i create``` to generate the skeleton of a S2I image project. But when i run the make test i have several issues :

A small one : as the cid_file is empty at the beginning, ```docker inspect``` display usage warning, so i have add some quotes around $(cat $cid_file) like in other functions

A "big" one: the tests failed because after stopping the container, the script try to remove the image ... but the container was not removed yet, so i have add a wait loop like in an other function

[The pact of the test/run script s2i-test-run-patch.txt](https://github.com/openshift/source-to-image/files/651790/s2i-test-run-patch.txt)

[A link to my S2I image](https://github.com/marc-despland/s2i-angular2)

**Comment by bparees** [comment]
Thanks, we'll take a look at it.

**Comment by coreydaley** [comment]
I am working on revamping the skeleton into a working application, and updating the information in the docs folder, but it will take me a few.

**Comment by coreydaley** [comment]
Linked to #688

**Comment by coreydaley** [comment]
Fixed via #688
