### ISSUE TITLE
Document installation using "go get"

### ISSUE THREAD

**Issue by jawnsy** [openshift/source-to-image#667]
The current installation instructions discuss downloading and extracting a release tarball.  Many applications deliver themselves using `go get`, which is convenient as it provides a built-in mechanism for updating (`go get -u`) and works across many platforms (since it compiles on the target system).

These instructions work today:

1. Set `GOPATH=/home/user/go` (this happens by default if no GOPATH is set)
1. Add `GOPATH/bin` to `PATH`
1. Run `go get github.com/openshift/source-to-image/cmd/s2i`

`s2i` is then downloaded, built, and installed in `GOPATH/bin`, and can subsequently be updated using `go get -u`.  Other projects can be installed like this; for example, ginkgo is installed using: `go get github.com/onsi/ginkgo/ginkgo` and caddy is installed using: `go get github.com/mholt/caddy/caddy`

It should also work cross-platform, as long as the right version of `go` is available (our build scripts already require it anyways).

**Comment by jawnsy** [comment]
@bparees WDYT? Happy to submit a PR if you think this is a good idea. We can either supplement or replace the current install instructions.

**Comment by bparees** [comment]
> @bparees WDYT? Happy to submit a PR if you think this is a good idea. We can either supplement or replace the current install instructions.

@jawnsy sounds fine to me.

**Comment by coreydaley** [comment]
@jawnsy 

I just ran `go get github.com/openshift/source-to-image/cmd/s2i `and it downloaded, installed into $GOPATH/bin and I was able to run it without issue.  Maybe it did not work like that before for some reason?

Can you please check it / try it again and see what results you get?

Maybe what is needed is just a docs update to add this installation method?

**Comment by jawnsy** [comment]
@coreydaley Yeah it was just a suggestion to add it to the docs, but I never got around to doing it :neutral_face:
