### ISSUE TITLE
Bump Go version dependency

### ISSUE THREAD

**Issue by jawnsy** [openshift/source-to-image#668]
In the installation instructions, we specify that we have a dependency on Go 1.4 or newer. However, according to the [upstream release policy](https://golang.org/doc/devel/release.html), only the latest version (currently 1.7) and its immediate predecessor (1.6) receive security support.

> Each major Go release obsoletes and ends support for the previous one. For example, if Go 1.5 has been released, then it is the current release and Go 1.4 and earlier are no longer supported. We fix critical problems in the current release as needed by issuing minor revisions (for example, Go 1.5.1, Go 1.5.2, and so on).
>
> As a special case, we issue minor revisions for critical security problems in both the current release and the previous release. For example, if Go 1.5 is the current release then we will issue minor revisions to fix critical security problems in both Go 1.4 and Go 1.5 as they arise. See the security policy for more details.

As a result, it may be a good idea to increase the dependency to 1.6.

**Comment by bparees** [comment]
i don't think we even build properly on 1.4 anymore, it's just outdated doc, thanks for catching it.
