### ISSUE TITLE
Unable to run s2i build with local .git directory

### ISSUE THREAD

**Issue by aelmadho** [openshift/source-to-image#674]
I am currently testing the ability to create a runnable image from an existing git repo, that is cloned into my workstation.  

Running "s2i build" fails everytime there is a local .git directory in my code tree, once I move out the .git directory, it is able to execute assemble to create the image.

Is there an ability to run s2i build with a cloned code tree?

--
Ahmeds-MacBook-Pro-3:deos aelmadhoun$ s2i build . ubuntu:latest bla2cd  --loglevel=6
I0104 17:47:21.221146    7805 main.go:68] Running S2I version "v1.1.3"
I0104 17:47:21.250719    7805 docker.go:515] Using locally available image "ubuntu:latest"
I0104 17:47:21.251764    7805 main.go:147]
Builder Image:			ubuntu:latest
Source:				.
Output Image Tag:		bla2cd
Environment:
Labels:
Incremental Build:		disabled
Remove Old Build:		disabled
Builder Pull Policy:		if-not-present
Previous Image Pull Policy:	if-not-present
Quiet:				disabled
Layered Build:			disabled
Docker Endpoint:		tcp://192.168.64.8:2376

I0104 17:47:21.271982    7805 docker.go:515] Using locally available image "ubuntu:latest"
I0104 17:47:21.282437    7805 docker.go:515] Using locally available image "ubuntu:latest"
I0104 17:47:21.282457    7805 docker.go:724] warning: Image sha256:104bec311bcdfc882ea08fdd4f5417ecfb1976adea5a0c237e129c728cb7eada does not contain a value for the io.openshift.s2i.scripts-url label
I0104 17:47:21.282502    7805 scm.go:21] DownloadForSource .
I0104 17:47:21.284240    7805 git.go:208] makePathAbsolute .
I0104 17:47:21.284269    7805 git.go:211] makePathAbsolute new path /Users/aelmadhoun/Documents/workspace/luma/deos err <nil>
I0104 17:47:21.284277    7805 scm.go:28] return from ParseFile file exists true proto specified false use copy false
I0104 17:47:21.284282    7805 scm.go:40] new source from parse file /Users/aelmadhoun/Documents/workspace/luma/deos
I0104 17:47:21.285840    7805 git.go:208] makePathAbsolute /Users/aelmadhoun/Documents/workspace/luma/deos
I0104 17:47:21.286354    7805 sti.go:178] Preparing to build bla2cd
I0104 17:47:21.288922    7805 git.go:208] makePathAbsolute /Users/aelmadhoun/Documents/workspace/luma/deos
I0104 17:47:21.288935    7805 clone.go:36] Downloading "file:///Users/aelmadhoun/Documents/workspace/luma/deos" ...
I0104 17:47:21.288941    7805 clone.go:44] Cloning sources and all Git submodules (recursive) into "/var/folders/cf/yfgx91qs3hs3zsh4n7gybq8w0000gn/T/s2i302912151/upload/src"
I0104 17:47:21.479578    7805 cleanup.go:33] Removing temporary directory /var/folders/cf/yfgx91qs3hs3zsh4n7gybq8w0000gn/T/s2i302912151
I0104 17:47:21.479596    7805 fs.go:159] Removing directory '/var/folders/cf/yfgx91qs3hs3zsh4n7gybq8w0000gn/T/s2i302912151'
E0104 17:47:21.486239    7805 main.go:358] An error occurred: failed to install [assemble run]
E0104 17:47:21.486252    7805 main.go:359] Suggested solution: provide URL with Source-To-Image scripts with -s flag or check the image if it contains io.openshift.s2i.scripts-url label set
E0104 17:47:21.486259    7805 main.go:365] If the problem persists consult the docs at https://github.com/openshift/source-to-image/tree/master/docs. Eventually reach us on freenode #openshift or file an issue at https://github.com/openshift/source-to-image/issues providing us with a log from your build using --loglevel=3

**Comment by bparees** [comment]
by default, s2i will attempt to "git clone" your repo, even if it's a local repo.  That means if you haven't committed all your changes, what s2i builds will not match what is in the local directory.

To get s2i to instead use exactly what is in the local directory (regardless of what is committed or not), pass `--copy`.

**Comment by aelmadho** [comment]
Thanks @bparees appreciate your response.  I would have expected s2i to build what I have on my local directory regardless of its commit state.  From a user experience perspective, I would think that perhaps s2i should detect a local folder, and simply copy blindly what we are trying to build and create an image out of.

I will leave this to the community to decide if anything needs to be done here, I am now able to proceed with --copy, but it would be nice not to have to pass that in.

**Comment by bparees** [comment]
>  I would have expected s2i to build what I have on my local directory regardless of its commit state. 

i understand, but s2i is, for better or worse, primarily git-centric, so if it detects your local directory is a git repo, it attempts to treat it as one, by building what is committed in that repo.  (if it's not a git repo, then it falls back to just building whatever is in the directory).  

>  From a user experience perspective, I would think that perhaps s2i should detect a local folder, and simply copy blindly what we are trying to build and create an image out of.

i don't fundamentally disagree with you, but at this point it's a backwards compatibility problem if we were to change the behavior.  It's also what allows you to do things like pass --ref to build a specific commit of the repo.  (which, again, there are other ways to solve outside of s2i, but it's behavior we're somewhat stuck with at this point).
