### ISSUE TITLE
Is it possible to use s2i with docker-compose?

### ISSUE THREAD

**Issue by luiscoms** [openshift/source-to-image#689]
Is it possible to create a service in docker-compose that build the image with s2i script?

**Comment by bparees** [comment]
I'm not familiar w/ the docker-compose service component, but in general s2i requires the docker socket be available to the context in which it is invoked.  As long as it is, you can use it (so for example you can start a container that contains the s2i binary and bind-mount your host's docker socket into that container.  That container can then invoke the s2i binary to perform an image build (and if it wants, also push the output image somewhere).  That's effectively how openshift s2i builds work.

**Comment by abdennour** [comment]
@luiscoms , if your mind contains this idea #1063  , please vote there.
