### ISSUE TITLE
How to reuse artifacts tar?

### ISSUE THREAD

**Issue by cars10** [openshift/source-to-image#703]
Is there a way to reuse the artifacts tar? 
In my usecase i want to build multiple incremental images at once. It seems that every build extracts the artifacts again - is there a way to reuse them instead of having them fetched each time?

**Comment by coreydaley** [comment]
@cars10 
You need to include code within your s2i assemble script that will restore the artifacts, just like you have to include code within your save-artifacts script to create the artifacts tar.  

You can see simple example here: https://github.com/openshift/source-to-image/blob/master/examples/nginx-centos7/s2i/bin/assemble#L16

**Comment by cars10** [comment]
Thats what i already do. I have a `save-artifacts` script and restore these in my assemble script. But each build does that step again - i asked if i can save that tar and reuse it. An example:

In my usecase i need to build ~20 slightly different images per release of the app. The first image installs my dependencies and the next 19 reuse the artifacts - but the "save artifacts" step is done during *each* of the builds. It would be cool if the first one would save the artifacts and all the others could reuse that exact tar file instead of creating it again each time.

**Comment by coreydaley** [comment]
@cars10 
That sounds like logic that you would have to somehow build into your save-artifacts and assemble scripts.

**Comment by cars10** [comment]
Okay, thanks. I thought there might be a built-in way that i did not find in the docs,

**Comment by bparees** [comment]
@cars10 there's no way to do exactly what you want (essentially use a common "previous image" as the artifact source for multiple different new builds), what i'd suggest instead is one of two options:

1) Add your common dependencies to a new layer on top of the s2i builder image.  Then use that new image as your s2i builder image for all your builds.  That way all the deps will already exist in the image for all your builds and won't need to be downloaded.

2) use the "-v" argument to mount a volume containing your dependencies into the assemble container (note that unless your assemble script copies them somewhere off the volume, they will not be in the final image, so you'll have to determine what you need to do if they are needed at runtime as well as compile time).

3) if you're using s2i within openshift, you can use the "input from image" mechanism to provide dependencies from an external image, as part of the inputs made available to your builds: https://docs.openshift.org/latest/dev_guide/builds/build_inputs.html#image-source

Hope that helps.

**Comment by cars10** [comment]
Thanks for the additional input. I do not use openshift, but i will have a look at options 1 and 2 - might help me.   (In general this is not even a serious issue, but it would save me some time during builds.)

**Comment by bparees** [comment]
(--inject might be another option for you, similar to option (2).  Note that again the injected files get truncated prior to commit, so if you need the content at runtime you'll need to copy the files elsewhere as part of your assemble script)
