### ISSUE TITLE
Support to set shell for internal commands

### ISSUE THREAD

**Issue by cars10** [openshift/source-to-image#704]
Disclaimer: I know that there is no official support for ubuntu or anything else besides RHEL and Centos. 

Some commands are hardcoded to use `/bin/sh`. That defaults to bash functionality on both RHEL and centos so you do not run into problems when `source`ing files like in https://github.com/openshift/source-to-image/blob/openshift-1.4/pkg/build/strategies/sti/sti.go#L550 .

Using s2i with debian based images results in failures in the specific line, because `/bin/sh` defaults to dash, and dash does not support `source`. It would be nice if we could set the default shell in some way - currently i override `/bin/sh` with `/bin/bash` in my image, but that is a bad solution.

**Comment by coreydaley** [comment]
It would seem to me that re-linking /bin/sh to /bin/bash in this case would be the correct solution, as customizing the image/system for the applications that it will run make sense.  Maybe have that command in your Dockerfile?  

http://askubuntu.com/questions/141928/what-is-difference-between-bin-sh-and-bin-bash

**Comment by cars10** [comment]
Thats exactly what i do at the moment - the dockerfile for my image overrides `/bin/sh` with `/bin/bash` via `ln -sf /bin/bash /bin/sh` . But i am wondering if this could have any drawbacks - a way to customize the shell would certainly be nicer.

**Comment by coreydaley** [comment]
@cars10 
I wouldn't think that it would have drawbacks, I believe that most shell scripts expect to be bash scripts, and dash seems to be a relatively newer default on ubuntu/debian.

**Comment by bparees** [comment]
The thing being sourced in that code is not your assemble script, it's a script we generate.  Your assemble script is just executed, so it'll run with whatever shell it declares (and it doesn't have to be a shell script, could just be an executable binary).

So the fix here is to replace "source" with "." which should be supported by dash.

**Comment by coreydaley** [comment]
Closed via #708

**Comment by cars10** [comment]
Works perfectly. Thanks again!

**Comment by bparees** [comment]
cool, you're welcome!
