### ISSUE TITLE
docs/debugging-s2i.md: subheaders displaying could be better

### ISSUE THREAD

**Issue by php-coder** [openshift/source-to-image#710]
On page https://github.com/openshift/source-to-image/blob/master/docs/debugging-s2i.md#providing-s2i-scripts I see that subheaders started from hashes:
```
####Interfacing With tar
####Dowloading / Finding The Scripts
####ONBUILD
```
Looks like wrong wiki dialect is using here to express headers.

**Comment by bparees** [comment]
fixed, just needed a space between the hashes and the text.

**Comment by php-coder** [comment]
Thanks!
