### ISSUE TITLE
'Checking if image' log twice

### ISSUE THREAD

**Issue by helio-frota** [openshift/source-to-image#714]
Hi, the log is running twice:

```
...
Checking if image "bucharestgold/centos7-s2i-nodejs-candidate:6.10.0" is available locally ...
Checking if image "bucharestgold/centos7-s2i-nodejs-candidate:6.10.0" is available locally ...
...
```
https://travis-ci.org/bucharest-gold/origin-s2i-nodejs#L1666-L1667

We are using the 1.1.5 released version.

https://github.com/bucharest-gold/origin-s2i-nodejs/issues/68

**Comment by bparees** [comment]
we check for the image at various times, it's a utility method.

**Comment by helio-frota** [comment]
thanks !
