### ISSUE TITLE
Allow --assemble-user to be specified as a label on the builder image

### ISSUE THREAD

**Issue by yuvipanda** [openshift/source-to-image#722]
This would simplify setup for a builder I am building, since otherwise I've to explicitly instruct users to run it with '--assemble-user root` when using it.

If this is considered something that the user is explicitly supposed to opt into, that seems ok to me too, though.

**Comment by bparees** [comment]
by default s2i runs the assemble script with the default user is for your image, is not that sufficient?

**Comment by yuvipanda** [comment]
I'd like the default user to be the user that the container is *run* as default, while I'd like a different one for building. Build as root with a controlled assemble script, run as non-root, essentially.

**Comment by TheMidgardWatcher** [comment]
Hi guys, I have same question - Is it possible to run some commands inside assemble/run scripts as root user?

**Comment by bparees** [comment]
@TheMidgardWatcher the scripts run as the default user for your image.  if it's root, they'll run as root (note that when running on openshift, there are additional restrictions that may prevent this).

in theory you may also be able to sudo from within your script, depending again on the constraints placed on the container environment.

**Comment by adambkaplan** [comment]
This is supported with the `io.openshift.s2i.assemble-user` label.
https://github.com/openshift/source-to-image/blob/master/docs/builder_image.md#assemble
