### ISSUE TITLE
Automatic incremental builds?

### ISSUE THREAD

**Issue by jwendell** [openshift/source-to-image#726]
Does it make sense to have automatic incremental builds whenever it is possible?
For example, cache the maven downloaded artifacts (.m2/repository) for an java app?

This way we can speed up builds for apps that were not primarily designed to run on Openshift (i.e., without .s2i/save-artifacts script)

**Comment by bparees** [comment]
incremental builds have their caveats, namely that you can end up w/ stale dependencies if you don't realize your dependencies are getting reused from your previous application image.  For this reason we think it's best not to enable them by default.  The default behavior will get you the most "correct/unsurprising" behavior, though not necessarily the fastest/most efficient experience.
