### ISSUE TITLE
s2i released builds don't seem to work under alpine linux

### ISSUE THREAD

**Issue by yuvipanda** [openshift/source-to-image#727]
I'm trying to build a small docker container image that would have s2i in it (so I can use it to build my own containers in my k8s cluster). So I download the latest amd64 release from the releases page, and then try to build the docker image thus:

```
FROM alpine:3.5

RUN apk add --no-cache git

ADD s2i /usr/local/bin/s2i
```

This however, does not work. If I attempt to run s2i inside this, I get 
```
yuvipanda@courage:~/code/s2i-image$ docker run -it yuvipanda/s2i /bin/sh
/ # s2i
/bin/sh: s2i: not found
```

And when trying to run it with strace, I get:

```
/ # strace -s1000 -f /usr/local/bin/s2i 
execve("/usr/local/bin/s2i", ["/usr/local/bin/s2i"], [/* 6 vars */]) = -1 ENOENT (No such file or directory)
writev(2, [{iov_base="strace: exec: No such file or directory", iov_len=39}, {iov_base="\n", iov_len=1}], 2strace: exec: No such file or directory
) = 40
writev(2, [{iov_base="", iov_len=0}, {iov_base=NULL, iov_len=0}], 2) = 0
getpid()                                = 11
exit_group(1)                           = ?
+++ exited with 1 +++
```

The file itself exists
```
/ # ls -lh /usr/local/bin/
total 10384
-rwxr-xr-x    1 root     root       10.1M Mar 20 17:01 s2i
```

So not entirely sure what's going on.

**Comment by yuvipanda** [comment]
(I'm not tied to alpine linux, I just want a small s2i image that works :))

**Comment by yuvipanda** [comment]
Upon further investigation, it seems to be because the s2i binary is not statically linked, but dynamically linked to libraries that aren't present in alpine. Is it possible to produce a statically linked binary too?

**Comment by yuvipanda** [comment]
A build produced with the following patch:

```
yuvipanda@courage:~/code/source-to-image$ git diff
diff --git a/hack/common.sh b/hack/common.sh
index 97cfc4e8..49217f2a 100755
--- a/hack/common.sh
+++ b/hack/common.sh
@@ -87,9 +87,10 @@ s2i::build::build_binaries() {
     for platform in "${platforms[@]}"; do
       s2i::build::set_platform_envs "${platform}"
       echo "++ Building go targets for ${platform}:" "${targets[@]}"
-      go install "${goflags[@]:+${goflags[@]}}" \
+      CGO_ENABLED=0 go install "${goflags[@]:+${goflags[@]}}" \
           -pkgdir "${S2I_OUTPUT_PKGDIR}" \
           -ldflags "${version_ldflags}" \
+          -tags netgo -a -v \
           "${binaries[@]}"
       s2i::build::unset_platform_envs "${platform}"
     done
``

makes it work on alpine (and produces a static binary). I don't know enough go yet to understand the negative aspects of this static binary tho.

**Comment by bparees** [comment]
the primary consequence should just be filesize.  did you compare the filesize of the static s2i binary w/ the non-static one?

if it's not too big i'd be ok w/ this change.  if it is big, we can produce both binaries.

**Comment by yuvipanda** [comment]
Thanks, @bparees! I made a PR - the size difference is actually positive on the static built side. Dynamically linked master is 12343360 bytes (about 12MB) while the statically linked one is just 10544875 bytes (under 11MB)

**Comment by yuvipanda** [comment]
Note: It turns out I don't have to set the netgo tag.

**Comment by bparees** [comment]
weird.  thanks!

**Comment by yuvipanda** [comment]
w00t, thanks @bparees for the merge!
