### ISSUE TITLE
permission issue

### ISSUE THREAD

**Issue by RobinsChens** [openshift/source-to-image#732]
File jar:file:/wildfly/modules/system/layers/base/org/picketbox/main/picketbox-4.9.6.Final.jar!/auth.confcannot be read.

when i deploy war to /wildfly/standalone/deployments, then print out the error

**Comment by bparees** [comment]
Can you please provide the full log output and steps for recreating your issue?

**Comment by bparees** [comment]
closing due to lack of information to investigate this further.  please reopen if you can provide additional details.
