### ISSUE TITLE
Add ansible-container to s2i

### ISSUE THREAD

**Issue by bbaassssiiee** [openshift/source-to-image#737]
We would like to use ansible-container as s2i build in openshift. Given that my project has ./ansible/assemble and ./ansible/run it could pull roles from Galaxy/git for better re-use.

**Comment by bbaassssiiee** [comment]
Feature idea

**Comment by bparees** [comment]
You're asking for an s2i-ansible builder image?

**Comment by bparees** [comment]
@jmrodri you might want to fill @bbaassssiiee in on the work you guys are doing for the ansible broker, i think it might be more suitable.

**Comment by bbaassssiiee** [comment]
https://github.com/sterburg/s2i-ansible-container
Maybe something like this, but then in the GUI of OpenSHift under 
https://127.0.0.1:8443/console/project/my-project/create?tab=fromCatalog

**Comment by bparees** [comment]
you can put any image you want into that GUI yourself by creating a suitable imagestream for the image in question.  If you want it available to everyone, create the imagestream in the openshift namespace.  

here's an example of the Ruby imagestream which makes Ruby available in the catalog:
https://github.com/openshift/origin/blob/master/examples/image-streams/image-streams-centos7.json#L6-L82

**Comment by bparees** [comment]
That said, I still think the work @jmrodri is doing is probably a better way to run ansible playbooks than using an s2i build to layer the playbook into a run-once image (assuming that's what the s2i image is doing).

**Comment by bparees** [comment]
I think i've addressed how to make the image available in the openshift console, closing this issue.
