### ISSUE TITLE
ENTRYPOINT not overridden for runtime images

### ISSUE THREAD

**Issue by cainj13** [openshift/source-to-image#739]
When I use a separate builder + runtime image, if the runtime image has an ENTRYPOINT defined, it is not overridden and the assemble-runtime script fails.  For example, here's my s2i output when I attempt to drop a Java .war on the docker.io/jboss/keycloak:3.1.0.CR1 image:

```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 03:29 min
[INFO] Finished at: 2017-05-04T19:22:47+00:00
[INFO] Final Memory: 26M/149M
[INFO] ------------------------------------------------------------------------
'src/target/my-artifact.war' -> '/tmp/my-artifact.war'
Artifact has been assembled and placed in the /tmp directory as my-artifact.war
=========================================================================

  JBoss Bootstrap Environment

  JBOSS_HOME: /opt/jboss/keycloak

  JAVA: /usr/lib/jvm/java/bin/java

  JAVA_OPTS:  -server -Xms64m -Xmx512m -XX:MetaspaceSize=96M -XX:MaxMetaspaceSize=256m -Djava.net.preferIPv4Stack=true -Djboss.modules.system.pkgs=org.jboss.byteman -Djava.awt.headless=true

=========================================================================

19:22:49,284 INFO  [org.jboss.modules] (main) JBoss Modules version 1.5.1.Final
WFLYSRV0073: Invalid option '/bin/sh'

```

That ^ image has an ENTRYPOINT defined of:

`ENTRYPOINT [ "/opt/jboss/docker-entrypoint.sh" ]`

Which attempts server startup (as you can see above).  Shouldn't s2i be overriding this?

**Comment by jim-minter** [comment]
Hi @cainj13 , please can you provide more detail? E.g. the actual s2i command you ran, full s2i output, a simple reproducer if at all possible? It's taking me a while to build a reproducer and I'd sooner be working from the same starting point that you are.  Cheers.

**Comment by bparees** [comment]
s2i doesn't override the entrypoint, it sets the cmd.  see:  https://github.com/openshift/source-to-image/issues/475

**Comment by bparees** [comment]
Unfortunately s2i overrides the CMD and not the ENTRYPOINT so your image must either

1) not specify an entrypoint or
2) specify and entrypoint that will defer to invoking the arguments it receives from the CMD, e.g.: 
https://github.com/sclorg/s2i-base-container/blob/master/core/root/usr/bin/container-entrypoint
(can be wrapped such that if $@ is empty, it runs other logic instead)
