### ISSUE TITLE
issues with s2i scala in Openshift 3

### ISSUE THREAD

**Issue by cmmehta** [openshift/source-to-image#740]
I am trying to run s2i build to have image creation for scala. Every time I am getting errors as - 
 **_An error occurred: unable to get metadata
Suggested solution: check image name
Details: Error: No such image:_**

Pls advise

**Comment by bparees** [comment]
can you run the s2i build with --loglevel=5 and provide the full logs?

**Comment by bparees** [comment]
the command line you're invoking would be helpful also so we can see the exact image you're using as the builder image.

**Comment by bparees** [comment]
closing due to lack of details, please reopen if you're able to provide the requested data to investigate this.
