### ISSUE TITLE
Failed to build the examples/nginx-centos7 on openshift

### ISSUE THREAD

**Issue by YannMoisan** [openshift/source-to-image#745]
I'm trying to build the example nginx images in openshift.

Here is the command `oc new-build https://github.com/openshift/source-to-image --context-dir=examples/nginx-centos7 --name=nginx-centos7 --to=nginx-centos7:latest`

But I got this error

```
chown: cannot access '/opt/app-root': No such file or directory
error: build error: The command '/bin/sh -c chown -R 1001:1001 /opt/app-root' returned a non-zero code: 1
```

I guess it's because the docker build command is not run by root. 
Any workaround ?

**Comment by coreydaley** [comment]
@YannMoisan I believe from previously looking at that issue that line needs to be removed from the DockerFile since that directory doesn't exist anymore (it did previously in this example).  I'll throw together a PR here shortly.

**Comment by YannMoisan** [comment]
It fixes the issue. Thx !
