### ISSUE TITLE
New Feature Request: Add context directory environment variable to output images

### ISSUE THREAD

**Issue by amsokol** [openshift/source-to-image#747]
Dear All,

Could you please add source context directory environment variable to output images.
OPENSHIFT_BUILD_SOURCE and context directory are necessary for Golang build to get root package of Golang application.

Thanks,
Aleksandr

**Comment by bparees** [comment]
How would putting it in the output image help, since the application is already built at that point?

I'm a bit confused as to what you're doing/trying to do.

**Comment by amsokol** [comment]
Dear @bparees,

I'm really sorry.
It's my mistake.
This request is for OpenShift team.
Issue is closed.
Sorry again.

Thanks,
Aleksandr
