### ISSUE TITLE
The seems to be an issue with a maximum directory size during source upload

### ISSUE THREAD

**Issue by fortinj66** [openshift/source-to-image#749]
There appears to be an issue with the total size/length of a directory uploaded by s2i.  Source files with a path that is too long gets truncated to just the filename and loses any path information.

Here is the example source (without the git stuff):

```
./1234567890/test1.java
./1234567890/1234567890/test2.java
./1234567890/1234567890/1234567890/test3.java
./1234567890/1234567890/1234567890/1234567890/test4.java
./1234567890/1234567890/1234567890/1234567890/1234567890/test5.java
./1234567890/1234567890/1234567890/1234567890/1234567890/1234567890/test6.java
./1234567890/1234567890/1234567890/1234567890/1234567890/1234567890/1234567890/test7.java
./1234567890/1234567890/1234567890/1234567890/1234567890/1234567890/1234567890/1234567890/test8.java
./1234567890/1234567890/1234567890/1234567890/1234567890/1234567890/1234567890/1234567890/1234567890/test9.java
./1234567890/1234567890/1234567890/1234567890/1234567890/1234567890/1234567890/1234567890/1234567890/1234567890/test10.java
./1234567890/1234567890/1234567890/1234567890/1234567890/1234567890/1234567890/1234567890/1234567890/1234567890/1234567890/test11.java

```

after running s2i I get this in the /tmp directory on the target image:
```
/tmp/yum.log
/tmp/test9.java
/tmp/test8.java
/tmp/test11.java
/tmp/test10.java
/tmp/src/.gitignore
/tmp/src/1234567890/test1.java
/tmp/src/1234567890/1234567890/test2.java
/tmp/src/1234567890/1234567890/1234567890/test3.java
/tmp/src/1234567890/1234567890/1234567890/1234567890/test4.java
/tmp/src/1234567890/1234567890/1234567890/1234567890/1234567890/test5.java
/tmp/src/1234567890/1234567890/1234567890/1234567890/1234567890/1234567890/test6.java
/tmp/src/1234567890/1234567890/1234567890/1234567890/1234567890/1234567890/1234567890/test7.java
/tmp/ks-script-O2SqLk
/tmp/hsperfdata_root/114


```

Note that the files test8.java, test9.java, test10.java, test11.java are not where they belong and appear to have lost their proper path

I am using the latest s2i and Centos7 as my build and image platforms...

**Comment by coreydaley** [comment]
Can you run this with --loglevel 5 and paste the output here or use pastebin?

**Comment by fortinj66** [comment]
Here you go:  https://pastebin.com/7NdfqdVU

It looks like the files are being added to the tar but the end processing is screwy...

**Comment by coreydaley** [comment]
Is there any chance you can tar up your test files and scripts and post them?  if not can we at least get your assemble script.

**Comment by fortinj66** [comment]
[s2i.tar.gz](https://github.com/openshift/source-to-image/files/1011480/s2i.tar.gz)

This should have everything in it.  The johntest directory contains the Makefile to create the s2i image and the email directory contains the source I was testing with...

**Comment by fortinj66** [comment]
This failed with a real source tree.  The above is just a testcase I was able to recreate the issue with

**Comment by coreydaley** [comment]
Can you also post the output of 's2i version'

**Comment by fortinj66** [comment]
[johnf@majeftest-sb01 s2i]$ ./s2i version
s2i v1.1.6

The executable I'm using is included in the tarball

**Comment by coreydaley** [comment]
Are you using Linux or OS X? (and what version)

**Comment by fortinj66** [comment]
[johnf@majeftest-sb01 etc]$ cat redhat-release
CentOS Linux release 7.3.1611 (Core)

**Comment by coreydaley** [comment]
@fortinj66 I am unable to replicate this issue on Fedora 25, or Centos (the same one you are using).

Here is the procedure that I am following (using the tar.gz you sent):

- tar -xvzf s2i.tar.gz
- cd johntest
- make
- cd ..
- ./sti --loglevel 5 build email-processor-micro johntest johntest-app

Here is the output: https://pastebin.com/NCKWzyXB

You can see that all files are present.

is there any other  information you can give us that might help us find the issue?  is there any chance the un tar process is running out of memory/disk space/ resources?

**Comment by coreydaley** [comment]
Your output that you posted shows that it is checking out HEAD for the git repo, are all of those files in HEAD? Is that the correct branch etc for all of the files?

**Comment by fortinj66** [comment]
What version of docker are you using?

[johnf@majeftest-sb01 etc]$ docker -v
Docker version 1.12.6, build 3a094bd/1.12.6

This is 100% reproducible on my side on this server.  Let me try another to see what happens

**Comment by fortinj66** [comment]
This is a new repo with just this test in it and everything added and commited.  No other branches created

**Comment by coreydaley** [comment]
[corey@li1315-97 ~]$ docker -v
Docker version 1.12.6, build 3a094bd/1.12.6

[corey@li1315-97 ~]$ cat /etc/redhat-release 
CentOS Linux release 7.3.1611 (Core)

**Comment by fortinj66** [comment]
memory/cpu/filesystems are fine with plenty of resources...

**Comment by fortinj66** [comment]
did you run yours as root or as a normal user?

**Comment by coreydaley** [comment]
root, but i can fix my groups and do it as a user.  which did you run yours as?

**Comment by fortinj66** [comment]
try it as a regular user...

**Comment by coreydaley** [comment]
Just ran it as a regular user, same result, it worked for me.  Can you verify that all of your files that you are testing with have the correct permissions/owners?

**Comment by coreydaley** [comment]
Were you able to replicate the issue on another virtual machine?

**Comment by fortinj66** [comment]
They're all owned by me with the same permissions as you should have...  access to /tmp is also good...

**Comment by coreydaley** [comment]
If you exec into your container and look at the tmp directory, what is there?
What if you run the find /tmp command manually in the container?

**Comment by fortinj66** [comment]
I was not able to recreate this on another server...

And here is the even odder thing...  The process is now working on the original server.  Except for logging out I haven't changed anything...  And I had logged out before (and rebooted) and still had the issue.

I also tested with the original real source and it also completed successfully...

I'm baffled...  Lets call it a non-issue for the time being

**Comment by fortinj66** [comment]
Thank you so much for working through this...  I try my best to resolve this type of stuff myself before I ask for help...

--John

**Comment by coreydaley** [comment]
Weird, 
Feel free to re-open this issue if you encounter it again or find more information.

**Comment by fortinj66** [comment]
will do...
