### ISSUE TITLE
Any docs about bind mounts using template?

### ISSUE THREAD

**Issue by ruifortes** [openshift/source-to-image#751]
Hello.
Any docs o example how to use [bind mounts](https://github.com/openshift/source-to-image/pull/461) on templates?
Thanks

**Comment by bparees** [comment]
what do you mean by templates?

**Comment by bparees** [comment]
if you are referring to openshift templates and doing s2i builds within openshifts:  bind mounts are not available in that environment because it would give you access to files on the node host.

**Comment by ruifortes** [comment]
Yes, openshift templates
What do you mean by "access to files on the node host"?
Access to "all" files in the host? Access only the mounted host folder?
If it's just access to the folder what is the problem?
Sorry If I'm missing something obvious cause I'm new to all this container technology.

**Comment by bparees** [comment]
Since you choose what folder to mount, you can access any folder on the host by choosing to mount it.

**Comment by bparees** [comment]
So if your query is specifically about bind mounts for builds the answer is its not possible. If you want to bind mount into an application pod, it's possible but only with very privileged permissions and it's probably not what you want to be doing.

**Comment by ruifortes** [comment]
Hi.
Thanks for bearing with me.
I having some trouble understanding the security issues here.

If its possible to mount a host folder in a regular pod (through DeploymentConfig) why not in the build pod (buildconfig)?

I would like to use a host folder in the build pod has the yarn cache.
Is there other way to avoid downloading all node modules in each deployment?

I understand that if just the source code changes s2i would use existing artifacts and won't downoad all modules again.

What I don't understand is what happens if the actual package.json "dependencies" change. Would build still be able to use artifacts?

If not using yarn and having it's cache persisted could be very useful

Again, sorry if I'm beeing dense but I'm still strugling to wrap my head arround openshift and container technology

**Comment by ruifortes** [comment]
I guess [Mount local directories for s2i builds #948](https://github.com/minishift/minishift/issues/948) is relevant

**Comment by bparees** [comment]
> If its possible to mount a host folder in a regular pod (through DeploymentConfig) why not in the build pod (buildconfig)?

the build pod runs with higher privileges than pods run by users, it would be able to mount and access more things than a normal pod can.

> I would like to use a host folder in the build pod has the yarn cache.
Is there other way to avoid downloading all node modules in each deployment?

There are several options to provide dependencies to your build without downloading them in each build:

1) you can use incremental builds in which the dependencies which were downloaded in the previous build are reused in the subsequent build: https://docs.openshift.org/latest/dev_guide/builds/build_strategies.html#incremental-builds  (you will need to provide a save-artifacts script to your s2i build to do this)

2) you can put your dependencies into an image and provide the image as an additional build input source:  https://docs.openshift.org/latest/dev_guide/builds/build_inputs.html#image-source

> I understand that if just the source code changes s2i would use existing artifacts and won't downoad all modules again.

not exactly.  first you need to be using an s2i builder image that implements save-artifacts (or providing your own save-artifacts script).  Secondly incremental builds are not the default behavior so you need to explicitly choose them.

> What I don't understand is what happens if the actual package.json "dependencies" change. Would build still be able to use artifacts?

The package.json dependencies will still be processed.  The only difference when reusing dependencies is that if your dependency download tool is smart enough to recognize the dependency is already available locally, it won't be downloaded.  If there are new dependencies required that do not exist locally, they should still be downloaded.
