### ISSUE TITLE
Blank lines in .s2iignore causes the entire src folder to be left out of the build

### ISSUE THREAD

**Issue by donkeybanana** [openshift/source-to-image#752]
**Reproducing the issue**

Given the `.s2iignore` file:

```
# Git
./.git
  
# Build dependencies
./node_modules
```

Running `s2i` with `--loglevel 5` provides the following output (separation added for emphasis):

```
I0604 18:23:22.784547   14379 ignore.go:77] .s2iignore lists a file spec of ./.git
I0604 18:23:22.784552   14379 ignore.go:109] using globspec /var/folders/fv/bc1r74fj6xg9d0ryt0p1f10c0000gn/T/s2i195532081/upload/src/.git
I0604 18:23:22.784564   14379 ignore.go:115] Glob result /var/folders/fv/bc1r74fj6xg9d0ryt0p1f10c0000gn/T/s2i195532081/upload/src/.git

I0604 18:23:22.784568   14379 ignore.go:77] .s2iignore lists a file spec of
I0604 18:23:22.784571   14379 ignore.go:109] using globspec /var/folders/fv/bc1r74fj6xg9d0ryt0p1f10c0000gn/T/s2i195532081/upload/src
I0604 18:23:22.784577   14379 ignore.go:115] Glob result /var/folders/fv/bc1r74fj6xg9d0ryt0p1f10c0000gn/T/s2i195532081/upload/src

I0604 18:23:22.784580   14379 ignore.go:77] .s2iignore lists a file spec of ./node_modules
I0604 18:23:22.784586   14379 ignore.go:109] using globspec /var/folders/fv/bc1r74fj6xg9d0ryt0p1f10c0000gn/T/s2i195532081/upload/src/node_modules
```

Blank lines are clearly not being skipped, while comments are. This is extremely confusing, given this behaviour is not present with `.dockerignore` and `.gitignore`, at least one of which most developers will be familiar with.

**Suggested behaviour**

Given this entire ecosystem is based around the use of docker, `.s2iignore` should at least match that of `.dockerignore`. From https://docs.docker.com/engine/reference/builder/#dockerignore-file:

> Matching is done using Go’s filepath.Match rules. A preprocessing step removes leading and trailing whitespace and eliminates . and .. elements using Go’s filepath.Clean. Lines that are blank after preprocessing are ignored.

**Debug**

```
% docker version
Client:
 Version:      17.03.1-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Tue Mar 28 00:40:02 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.03.1-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Fri Mar 24 00:00:50 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

```
% s2i version
s2i v1.1.6-dirty
```

**Comment by bparees** [comment]
@donkeybanana thanks for the bug report, agree we should be stripping empty lines.
