### ISSUE TITLE
Use of Custom Assemble file by simply placing in .s2i/bin/assemble (OpenShift feature) 

### ISSUE THREAD

**Issue by djohnston89** [openshift/source-to-image#767]
Hey,

With OpenShift s2i, simply placing an assemble file in .s2i/bin will automatically overwrite the default assemble script. 

How can this be done with the command line s2i (we're running s2i build on a Jenkins slave instead of OpenShift)?

**Comment by bparees** [comment]
same way.  if your git repo (or directory) that you're building with "s2i build" contains a .s2i/bin folder and scripts, they will be used.

**Comment by bparees** [comment]
note that there's currently a bug in s2i when using scripts from the app repo.  If you use the latest release (1.1.7) you'll be fine, but you'll hit the bug if you use master.

**Comment by bparees** [comment]
(fix for the aforementioned issue is here: https://github.com/openshift/source-to-image/pull/768 )

**Comment by bparees** [comment]
closing since i think i've answered your question but let me know if you're still having issues.
