### ISSUE TITLE
Specify which network to use while constructing the image

### ISSUE THREAD

**Issue by rikatz** [openshift/source-to-image#776]
We're using s2i outside openshift, for some of our local projects.

What happens is that we have a different Network that can access internet (other than the default bridge network), and when we run the s2i command, it creates a Docker Container for this build inside this default network. This doesn't allow our s2i process (that makes some pip/python installs from internet) happen.

How can we specify a docker network other than the default Bridge?

Thanks

**Comment by bparees** [comment]
right now i don't think it's possible, we'd have to add a flag to s2i to allow specifying the network to use.  In the meantime, I believe it is possible to change the configuration of the bridge network, would it be possible for you to do that instead?  (apparently docker does not allow you to change the default network, unfortunately)

**Comment by rikatz** [comment]
Hi @bparees thank you for your answer.

I've opened a PR that allows you to specify which network should be used, instead of the default flow.

Thank you!
