### ISSUE TITLE
How to get application image into OpenShift registry?

### ISSUE THREAD

**Issue by magick93** [openshift/source-to-image#780]
Hi

I am using s2i on my laptop to build an application image, so that it can run on a remote OpenShift environment.

I have been told that s2i does everything - does the build, and pushes image into OpenShift registry.

But how do I tell s2i how to reach the OpenShift registry? Is there a parameter that I should pass in when running the build, eg `s2i --remoteRegistry=http...`?

Or do I need to use `docker push`?

Or if I do `oc import-image <application-image>` will that move my s2i built image to OpenShift?

**Comment by bparees** [comment]
The s2i cli tool does not push the image to the registry, it just builds it and then you use docker push to push it.

You can use s2i from within openshift, in which case yes, the built image will be pushed somewhere you specify (usually the openshift registry) (see: https://docs.openshift.org/latest/dev_guide/builds/index.html and related sections/links)

But if you're running it standalone on your laptop, it's up to you to docker login to a registry and docker push there.  To login to the openshift registry, you can follow these instructions to get your token:

https://docs.openshift.org/latest/install_config/registry/accessing_registry.html#access-logging-in-to-the-registry

Pushing the image into the openshift registry will be sufficient to create an imagestream for it, so there's no need to run oc import-image.

**Comment by johnreytanquinco** [comment]
Hi @bparees - where to find my OpenShift registry value? Thanks!

**Comment by bparees** [comment]
@johnreytanquinco it depends how your cluster is setup.  Normally you're going to need a route to the registry configured, so it would be the route.  If you don't have a route, and you're a cluster admin, you'll want to set one up.  The registry service will be in the default project, so you can see it with "oc get services -n default", but the service will only be accessible from within the cluster network, hence the need for a route (oc expose)

**Comment by johnreytanquinco** [comment]
Ah. that's perfect! `oc get services -n default` is what I did to show the list of services.
