### ISSUE TITLE
Adding custom s2i builder to OpenShift?

### ISSUE THREAD

**Issue by magick93** [openshift/source-to-image#781]
We are using a custom s2i (https://github.com/universityofadelaide/s2i-shepherd-drupal) - and to simplify the workflow, it would be good if we can add this to OpenShift.

I have read 
https://docs.openshift.com/container-platform/3.3/creating_images/custom.html 
https://docs.openshift.com/enterprise/3.1/creating_images/s2i.html but couldnt see how to add custom s2i builders to OpenShift.

Any help is appreciated.

Thanks

**Comment by bparees** [comment]
@magick93 to add a builder to openshift you need to define an imagestream for it:

https://github.com/openshift/origin/blob/master/examples/image-streams/image-streams-centos7.json#L6-L50

And the imagestream needs to indicate the image is a builder:
https://github.com/openshift/origin/blob/master/examples/image-streams/image-streams-centos7.json#L23

you'll need to create the imagestream in the openshift namespace (oc create -f yourimagestream.json -n openshift)

once you do that it will show up in the webconsole as an available builder image.
