### ISSUE TITLE
S2I Build error due to read: connection reset by peer

### ISSUE THREAD

**Issue by reddyrocks** [openshift/source-to-image#782]
I am running s2i build on Jenkins slave that has s2i mixin and it used to work fine for most of the builds but all of a sudden, I am seeing a new error.
I0801 17:18:20.244127 9638 docker.go:948] Removing container "12f9115bbf9dff39984dee60326c9f05bf6a146d64bb6a46f24f79624e5ddd19" ...
I0801 17:18:20.487410 9638 docker.go:952] Removed container "12f9115bbf9dff39984dee60326c9f05bf6a146d64bb6a46f24f79624e5ddd19"
I0801 17:18:20.487840 9638 cleanup.go:33] Removing temporary directory /tmp/s2i478542863
I0801 17:18:20.487901 9638 fs.go:159] Removing directory '/tmp/s2i478542863'
I0801 17:18:20.488082 9638 sti.go:624]
E0801 17:18:20.495194 9638 main.go:368] An error occurred: waiting for container "12f9115bbf9dff39984dee60326c9f05bf6a146d64bb6a46f24f79624e5ddd19" to stop: An error occurred trying to connect: Post http://jenkins.host.com/containers/12f9115bbf9dff39984dee60326c9f05bf6a146d64bb6a46f24f79624e5ddd19/wait: read tcp :
ip1 to ip2 read: connection reset by peer

Let me know, if there is any way to solve this ???

Note:
I have replaced our actual hostname of jenkins with "host" and ip address with "ip1 and ip2".

**Comment by bparees** [comment]
Can you please explain your scenario and configuration in more detail?  It sounds like you're doing an s2i build from within a jenkins slave?  is this running on openshift?  Can you share the buildconfig and the rest of the log?

**Comment by reddyrocks** [comment]
Okay here is what I am doing, I have my s2i running on a jenkins slave and when I am trying to build docker image using source code and base docker image to deploy on to openshift.  I cannot share the full log down here as it is has some confidential data  but the scenario is this.
I0809 18:07:28.951022     325 tar.go:320] Adding to tar: /tmp/s2i325905238/upload/src/src/main/resources/META-INF/beans.xml as src/src/main/resources/META-INF/beans.xml
I0809 18:07:28.951210     325 tar.go:320] Adding to tar: /tmp/s2i325905238/upload/src/src/main/resources/log4j.properties as src/src/main/resources/log4j.properties
I0809 18:07:28.951559     325 tar.go:320] Adding to tar: /tmp/s2i325905238/upload/src/src/test/java/com/optum/propel/mailreceiver/TestMyApp.java as src/src/test/java/com/optum/propel/mailreceiver/TestMyApp.java
I0809 18:07:29.381948     325 docker.go:1033] Waiting for container "c3a01ca621cb3873fcfe6fbda9a8cf490d82ec2bf0ebb614c3b9a786997fbb04" to stop ...
I0809 18:12:30.642545     325 docker.go:948] Removing container "c3a01ca621cb3873fcfe6fbda9a8cf490d82ec2bf0ebb614c3b9a786997fbb04" ...
I0809 18:12:31.015870     325 docker.go:952] Removed container "c3a01ca621cb3873fcfe6fbda9a8cf490d82ec2bf0ebb614c3b9a786997fbb04"
I0809 18:12:31.016256     325 cleanup.go:33] Removing temporary directory /tmp/s2i325905238
I0809 18:12:31.016297     325 fs.go:159] Removing directory '/tmp/s2i325905238'
I0809 18:12:31.016633     325 sti.go:624] 
E0809 18:12:31.019744     325 main.go:368] An error occurred: waiting for container "c3a01ca621cb3873fcfe6fbda9a8cf490d82ec2bf0ebb614c3b9a786997fbb04" to stop: An error occurred trying to connect: Post http://jenkins.company.com:30303/containers/c3a01ca621cb3873fcfe6fbda9a8cf490d82ec2bf0ebb614c3b9a786997fbb04/wait: read tcp 172.17.0.20:42094->10.175.253.23:30303: read: connection reset by peer

**Comment by bparees** [comment]
How are you running the jenkins slave?  How are you making the docker socket available to the jenkins slave?

does this fail for all s2i builds?  can you try running a basic s2i build instead and giving me the full logs for that? ie:

```
s2i build https://github.com/openshift/ruby-hello-world centos/ruby-22-centos7 hello-world-app --loglevel=5
```

**Comment by bparees** [comment]
closing due to lack of information.
