### ISSUE TITLE
Allow installing RPMs from configured builder image repos

### ISSUE THREAD

**Issue by akostadinov** [openshift/source-to-image#786]
Hello, IMO it's ultimate to allow installing list of RPMs from the already configured repositories in a builder image. We can't bloat builder images with everything, on the other hand many apps will miss dependencies.

Originally I filed [bug 1470866](https://bugzilla.redhat.com/show_bug.cgi?id=1470866) and you can see it for one specific use case. In short tried to create a `sopel` IRC bot app with python s2i but failed for missing the `enchant` package. I don't think one image can cover all use case, on the other hand asking users to support their own s2i images moves the burden where we don't want, requires users to use external infrastructure, follow good security hygiene, etc. etc.
Thus adding ability to install standard RPM packages will greatly improve UX and the service OpenShift provides.

Regards

**Comment by bparees** [comment]
if your image runs as root your assemble script will run as root and can install all the rpms it wants.

however that image may or may not be allowed to run as an s2i builder on your openshift cluster.

**Comment by akostadinov** [comment]
Can't we figure out a way to install packages as non-root? Presently there is no good solution for Online where root execution would not be allowed AFAIK.

**Comment by bparees** [comment]
if you were to find a way (such as described here: https://superuser.com/questions/209808/how-can-i-install-an-rpm-without-being-root) then you wouldn't need s2i to do anything, you can put whatever non-root package installation logic you want into your assemble script.

**Comment by akostadinov** [comment]
I think the idea is to make app builds as seemless as possible. If user is to create a builder image or setup env with a complicated script, then a lot of the benefits to use s2i would be lost. IMO it's OpenShift job to just take a list of packages and deal with the details in whatever way.

**Comment by bparees** [comment]
Disagree. Among other things, package management is image/distribution
specific. It is beyond s2i's scope to manage all the myriad ways software
can be installed into an image. Its responsibilities with respect to that
end at the assemble script.

Ben Parees | OpenShift

**Comment by akostadinov** [comment]
I think for UX it's important to allow package installations, especially for languages relying a lot on local libraries a lot like python. Putting the burden on the user to take care of the myriads of ways native packages can be installed on different base operating systems is IMO not a solution. I think we want to save users from that burden as part of the OpenShift project.

Provided we build images based on CentOS and Red Hat Enterprise Linux, I think we should be able to develop a solution. Is your disagreement that such solution should be part of the s2i project or that such feature is not needed at all?

**Comment by bparees** [comment]
> I think for UX it's important to allow package installations, especially for languages relying a lot on local libraries a lot like python. 

then write a python s2i builder image that solves the problem for python.

> Putting the burden on the user to take care of the myriads of ways native packages can be installed on different base operating systems is IMO not a solution.

it's an intractable problem.

> Provided we build images based on CentOS and Red Hat Enterprise Linux, I think we should be able to develop a solution. Is your disagreement that such solution should be part of the s2i project or that such feature is not needed at all?

both.  S2I is designed with limited power to provide a constrained environment intentionally, it's not intended to replace the full power provided by dockerfiles.  If you want to do arbitrary things, you do a docker build.

I'll refer you to the summary of s2i goals/advantages here:
https://docs.openshift.org/latest/architecture/core_concepts/builds_and_image_streams.html#source-build

including:
```
Operational efficiency | By restricting build operations instead of allowing arbitrary actions, as a Dockerfile would allow, the PaaS operator can avoid accidental or intentional abuses of the build system.
```

and:
```
User efficiency | S2I prevents developers from performing arbitrary yum install type operations, which could slow down development iteration, during their application build.
```

**Comment by bparees** [comment]
in other words, these restrictions are features, not bugs/limitations.

**Comment by akostadinov** [comment]
"restricting build operations instead of allowing arbitrary actions", installing a package from already configured repos is not an arbitrary operation and is under control of the PaaS operator. I think it will unleash the power of Red Hat technology for OpenShift Online users.
Even though you disagree, thank you for taking the time for this conversation.
