### ISSUE TITLE
s2i build error: Invalid reference format

### ISSUE THREAD

**Issue by saikrishnareddygudipati** [openshift/source-to-image#789]
Hello everyone,

I am running into an s2i build error invalid reference format and I couldn't find any solution for this. can  you guys help me out in solving this ???. 

I0810 16:51:38.781182     320 sti.go:369] error: Execution of post execute step failed
I0810 16:51:38.781208     320 docker.go:948] Removing container "bcc0f25b8e884536e242e132b755a723cc63ee49d1f09c5587cdbae7aa3cee7e" ...
I0810 16:51:38.800286     320 docker.go:952] Removed container "bcc0f25b8e884536e242e132b755a723cc63ee49d1f09c5587cdbae7aa3cee7e"
I0810 16:51:38.800796     320 cleanup.go:33] Removing temporary directory /tmp/s2i524513920
I0810 16:51:38.800830     320 fs.go:159] Removing directory '/tmp/s2i524513920'
E0810 16:51:38.808576     320 main.go:358] An error occurred: building ptf-pick-controller-1-0- failed when committing the image due to error: invalid reference format
E0810 16:51:38.808604     320 main.go:359] Suggested solution: check the build output for errors
I0810 16:51:38.808615     320 main.go:361] # _Details: invalid reference format
E0810 16:51:38.808623     320 main.go:365] If the problem persists consult the docs at https://github.com/openshift/source-to-image/tree/master/docs. Eventually reach us on freenode #openshift or file an issue at https://github.com/openshift/source-to-image/issues providing us with a log from your build using --loglevel=3

**Comment by bparees** [comment]
closing due to lack of information.
