### ISSUE TITLE
fix-permissions: Permission denied

### ISSUE THREAD

**Issue by magick93** [openshift/source-to-image#801]
Hello

Im trying to make a custom s2i image for compiling c++ projects.

But I am running into permission issues when Openshift pulls in the git repo of source. 

Im trying to solve this by using the `fix-permissions` bash script. 
But I get permission errors running this:

`/bin/sh: 1: /usr/local/s2i/bin/fix-permissions: Permission denied` 

Does anyone know what the problem might be?

**Dockerfile**

```
FROM i386/ubuntu:17.04



ENV STI_SCRIPTS_PATH="/usr/local/s2i/" \
    PATH=$PATH:"/usr/local/s2i/" 


ENV SUMMARY="Platform for compiling cpp applications on 32bit containers" \
    DESCRIPTION=""

LABEL summary="$SUMMARY" \
      description="$DESCRIPTION" \
      io.k8s.description="$DESCRIPTION" \
      io.k8s.display-name="C++ Builder  \
      io.openshift.expose-services="50051:http" \
      io.openshift.tags="builder,cpp" \
      io.openshift.s2i.scripts-url="image:///usr/local/s2i/" \
      io.openshift.s2i.destination="/tmp" \
      name="i386/ubuntu:17.04" \
      version="7.0" \
      release="1"
      
    
ENV DEBIAN_FRONTEND noninteractive


RUN apt-get update && apt-get install -y \
  build-essential autoconf libtool \
  git \
  pkg-config \
  g++ \
  flex \
  bison \
  libc6-dev \
  xz-utils \
  wget \
  cmake \
  zlib1g-dev \
  libc-ares-dev \
  libssl-dev \
  && apt-get clean
  

USER root
 
RUN mkdir cppproject && chmod 755 cppproject && $STI_SCRIPTS_PATH/bin/fix-permissions $STI_SCRIPTS_PATH* && \
    $STI_SCRIPTS_PATH/bin/fix-permissions cppproject && \
    chown -R 1001:0 $STI_SCRIPTS_PATH* && \
    chown -R 1001:0 cppproject



USER 1001
RUN whereis assemble
CMD [ "/usr/local/s2i/assemble" ]
```

**Comment by bparees** [comment]
sounds like your fix-permissions script might not be executable?

you're getting that error when doing the docker build?

**Comment by magick93** [comment]
Yes, am getting this while doing docker build.
And yes, youre right  - I had forgotten to give the script executable permissions.

Is it recommended to use the fix-permissions script in the dockerfile or `assemble`?

**Comment by bparees** [comment]
It was intended for use during assemble.  But you can use it anytime you find it useful.
