### ISSUE TITLE
 user that is numeric and within the range of allowed users

### ISSUE THREAD

**Issue by magick93** [openshift/source-to-image#807]
Hello

I have created a custom s2i image. However when I try to use this in OpenShift, the compilation of the source code never occurs. Instead I get:

```

I0927 21:22:48.857202       1 docker.go:503] Using locally available image "172.30.1.121:5000/mt4/s2i-cpp-@sha256:770207022c0..."
--
  | F0927 21:22:49.213796       1 helpers.go:119] error: build error: image "172.30.1.121:5000/mt4/s2i-cpp@sha256:770207022c021c677f8050f56c782bafd4a3e8d4baff7710662d2eb0bb8b8ae9" must specify a user that is numeric and within the range of allowed users
```

However my dockerfile looks like this:

```
FROM i386/ubuntu:17.04



ENV STI_SCRIPTS_PATH="/usr/local/s2i" 
ENV PATH=$PATH:$STI_SCRIPTS_PATH



ENV SUMMARY="Platform for building a Wine $WINE_VERSION and $GRPC_RELEASE_TAG applications on 32bit containers" 

LABEL summary="$SUMMARY" \
      description="$DESCRIPTION" \
      io.k8s.display-name="C++ Builder" \
      io.openshift.expose-services="50051:http" \
      io.openshift.tags="builder,wine,grpc,cpp" \
      io.openshift.s2i.scripts-url="image:///usr/local/s2i/bin/" \
      io.openshift.s2i.destination="/tmp" \
      name="i386/ubuntu:17.04" \
      version="7.0" \
      release="1" 
      
    
ENV DEBIAN_FRONTEND noninteractive

COPY s2i $STI_SCRIPTS_PATH


RUN apt-get update && apt-get install -y \
  build-essential autoconf libtool \
  git \
  pkg-config \
  g++ \
  flex \
  bison \
  libc6-dev \
  xz-utils \
  wget \
  cmake \
  && mkdir -p $STI_SCRIPTS_PATH/ \
  && chmod 755 $STI_SCRIPTS_PATH/* \
  && chmod +x /usr/local/s2i/bin/fix-permissions
  



WORKDIR ../../
USER root




RUN mkdir cppproject && chmod 755 cppproject &&  \
    chown -R 1001:0 $STI_SCRIPTS_PATH* && \
    chown -R 1001:0 cppproject \
    && ./usr/local/s2i/bin/fix-permissions cppproject  \
    





USER 1001

CMD /usr/local/s2i/bin/assemble
```

**Comment by bparees** [comment]
it looks correct to me, i'd ask you to confirm that the image that openshift is running is indeed the correct one (did you have an earlier version of your image that did not specify USER 1001?).

you can check by doing a docker pull 172.30.1.121:5000/mt4/s2i-cpp@sha256:770207022c021c677f8050f56c782bafd4a3e8d4baff7710662d2eb0bb8b8ae9

and then a docker inspect 172.30.1.121:5000/mt4/s2i-cpp@sha256:770207022c021c677f8050f56c782bafd4a3e8d4baff7710662d2eb0bb8b8ae9

(you'll have to do this from one of the nodes of your cluster since the ip address is a cluster network ip).

**Comment by bparees** [comment]
also i'm not sure why you're copying s2i into this image.

**Comment by magick93** [comment]
yes I double checked the sha - it the correct s2i builder being used.

> also i'm not sure why you're copying s2i into this image.
Im copying a local s2i folder that contains the assemble etc scripts.

Its a completely fresh s2i image - not extending from any existing s2i image.

**Comment by bparees** [comment]
> Its a completely fresh s2i image - not extending from any existing s2i image.

that doesn't matter. you don't need s2i inside an s2i builder image.  it's not used.  only your assemble script and run scripts are going to be executed.

Where did your cluster come from?  perhaps your administrator has it locked down in an unusual way such that 1001 is not within the allowed uids.

are you able to use any of the existing s2i builder images on this cluster, within your project?

**Comment by bparees** [comment]
> yes I double checked the sha - it the correct s2i builder being used.

did you double check that when you docker inspect the image, it reports the default user as 1001?

e.g.
```
        "Config": {
            "Hostname": "dd49828a9324",
            "Domainname": "",
            "User": "1001",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
```

**Comment by magick93** [comment]
Ok. Yes inspect shows it defaults to `root`:

```
"Config": {
            "Hostname": "212005838a29",
            "Domainname": "",
            "User": "root",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
```

**Comment by bparees** [comment]
So you have not built what you think you've built. :)

**Comment by magick93** [comment]
Its more confusing!
I have two project. And have built the same s2i project in both
And got different results.

**Comment by bparees** [comment]
you must have pushed different images to the different projects.

**Comment by magick93** [comment]
I found the problem. I had an extra `\` in my installs section of the dockerfile.

Thanks for your help @bparees
