### ISSUE TITLE
Build and run as different users

### ISSUE THREAD

**Issue by accursoft** [openshift/source-to-image#81]
I would like the built image to run with a more restricted user than the one which performed the build. This could be supported by running `assemble` as a non-default user, or by changing the image's default user after assembly.

It can be done now with `docker run -u`, but it would be nice to support this automatically.

**Comment by accursoft** [comment]
`--assemble-user` changes the image's default user, so `docker run` will still use the same user as assemble.

**Comment by wanghaoran1988** [comment]
if we specify the --assemble-user option when do sti build with the language images openshift provided, the build will failed, since the images are using default user 1001, and the src path directory inside of the images like :/opt/app-root/src is owned by user 1001 . so , there is a problem here.

**Comment by mfojtik** [comment]
@accursoft good catch, I have to take the User from the builder image and specify that user when committing the container after build. The `Config.User` will then be set to 1001 (which is the openshift s2i image default user), however the `Config.ContainerConfig.User` will be set to `--assemble-user` (there is no way in docker to change that other than 're-running' the container and committing it. 

With https://github.com/openshift/source-to-image/pull/354 you should docker run the built image and it will run using the original builder id.

**Comment by mfojtik** [comment]
@wanghaoran1988 that is correct, however you might have builder image that will allow assemble to run only as user X and the run the final image as user Y. The OpenShift image are not build that way. However, you can try to build using `--assemble-user=root` (which is how I'm testing this).

**Comment by accursoft** [comment]
Should `save-artifacts` also run as `assemble-user`? This tripped me up when `cd ~` went to the wrong directory, but it could also cause issues if the artifacts can't be read by the run-time user.

**Comment by mfojtik** [comment]
@accursoft probably yes, because the save-artifacts is reading stuff created by assemble. Currently the assemble script has to make it readable for the default image user.
