### ISSUE TITLE
Error executing 's2i build' at Windows. Looks like newline \r is inserted into filename

### ISSUE THREAD

**Issue by ErikLundJensen** [openshift/source-to-image#810]
When using version source-to-image-v1.1.7-226afa1-windows-amd64 at Window 7 then I get an error which looks like newline is not handled probably.

An extra \r is inserted into the filename.
Is this a known bug?

s2i build http://bitbucket-devtools.192.168.99.101.nip.io/scm/dem/demo-jenkins.git openshift/jenkins-2-centos7 demo-jenkins
Your branch is up-to-date with 'origin/master'.
---> Copying repository files ...
---> Installing Jenkins 7 plugins using /opt/openshift/plugins.txt ...
Creating initial locks...
Locking maven:2.17
Locking
Locking blueocean:1.2.4
Locking
**mkdir: cannot create directory '/opt/openshift/plugins/\r.lock': File exists**
Failed to install plugins.
Build failed
ERROR: An error occurred: non-zero (13) exit code from openshift/jenkins-2-centos7

**Comment by ErikLundJensen** [comment]
A work-a-round is to remove all empty lines from the plugins.txt however after that the download fails as an extra \r is inserted in the download filename:

Downloading plugin: maven from https://updates.jenkins-ci.org/download/plugins/maven/2.17
/maven.hpi

Really looks like the plugs.txt have to have unix line-ending.

**Comment by bparees** [comment]
Yeah this doesn't sound like an s2i bug, s2i is just sending the file as it exists on disk (which it got from a git clone).

Where did you get your plugins.txt from?

**Comment by ErikLundJensen** [comment]
I wrote the plugins.txt in Eclipse running at Windows.

**Comment by bparees** [comment]
> I wrote the plugins.txt in Eclipse running at Windows.

well that's why it has windows newlines in it then...  use a tool to strip them, e.g. https://sourceforge.net/projects/dos2unix/

(not an endorsement of any particular tool).

**Comment by ErikLundJensen** [comment]
You are right, it must be the script that handles the plugins.txt file here:
https://github.com/openshift/jenkins/tree/master/2/contrib/jenkins/install-plugins.sh

Please close this issue.
