### ISSUE TITLE
image dotnet/dotnet-20-rhel7:latest not found

### ISSUE THREAD

**Issue by wangchong666** [openshift/source-to-image#815]
> ./s2i build git://github.com/redhat-developer/s2i-dotnetcore --context-dir=2.0/test/asp-net-hello-world dotnet/dotnet-20-rhel7 dotnet-sample-app

> pulling image error : Error: image dotnet/dotnet-20-rhel7:latest not found
ERROR: An error occurred: unable to get dotnet/dotnet-20-rhel7:latest
ERROR: Suggested solution: check image name, or if using local image add --pull-policy=never flag
ERROR: If the problem persists consult the docs at https://github.com/openshift/source-to-image/tree/master/docs. Eventually reach us on freenode #openshift or file an issue at https://github.com/openshift/source-to-image/issues providing us with a log from your build using --loglevel=3

>

**Comment by bparees** [comment]
unless your docker daemon lists registry.access.redhat.com as a default registry, you need to specify the full path to the image:
registry.access.redhat.com/dotnet/dotnet-20-rhel7

(and though those images are not currently secured, you should only be using them w/ an appropriate subscription. there is no centos version available currently).
