### ISSUE TITLE
`s2i usage` prints in odd streams

### ISSUE THREAD

**Issue by TomasTomecek** [openshift/source-to-image#823]
```
$ s2i usage punchbag
I1107 14:50:55.488423 08625 install.go:251] Using "usage" installed from "image:///usr/libexec/s2i/usage"
This is the punchbag S2I image:
To use it, install S2I: https://github.com/openshift/source-to-image
...
```

I'm not interest in the log line, so I expected that `-q` would disable it:

```
$ s2i usage punchbag -q
I1107 14:54:11.321471 12941 install.go:251] Using "usage" installed from "image:///usr/libexec/s2i/usage"
```

Hm, that's the exact opposite of what I want. Would it be possible to change that behaviour?

One way to solve this is doing:
```
$ s2i usage punchbag 2>/dev/null
This is the punchbag S2I image:
To use it, install S2I: https://github.com/openshift/source-to-image
...
```
Which I guess is okay, but I would still prefer a s2i-native solution where I don't have to tinker around my shell.

**Comment by bparees** [comment]
s2i usage just outputs the usage script from your image.

i'm not seeing the log line that you're seeing, perhaps the log level has been changed in a newer s2i version:

```
$  s2i usage centos/ruby-22-centos7
This is a S2I ruby-2.2 centos base image:
To use it, install S2I: https://github.com/openshift/source-to-image

Sample invocation:

s2i build https://github.com/sclorg/s2i-ruby-container.git --context-dir=2.2/test/puma-test-app/ centos/ruby-22-centos7 ruby-sample-app


You can then run the resulting image via:
docker run -p 8080:8080 ruby-sample-app
```

**Comment by TomasTomecek** [comment]
perhaps the log level has been changed in a newer s2i version

Seems so, this s2i from git master.

**Comment by bparees** [comment]
@TomasTomecek what i ran was master.

**Comment by TomasTomecek** [comment]
Hm, I don't understand then.

**Comment by TomasTomecek** [comment]
I do now: the issue is present in older version and fixed in the new one.
