### ISSUE TITLE
go-md2man dependency breaks s2i-base build on rhel7

### ISSUE THREAD

**Issue by nnachefski** [openshift/source-to-image#825]
### get and install the s2i tool
wget https://github.com/openshift/source-to-image/releases/download/v1.1.8/source-to-image-v1.1.8-e3140d01-linux-386.tar.gz
tar -xzvf source-to-image-v1.1.8-e3140d01-linux-386.tar.gz 
cp s2i /usr/bin

### install make and gcc
yum -y install make libtool

### git clone the s2i base 
cd ~
git clone https://github.com/sclorg/s2i-base-container.git
cd s2i-base-container
git submodule update --init
make build VERSIONS=core TARGET=rhel7

> mkdir -p core/root
> go-md2man -in "core/README.md" -out "core/root/help.1"
> /bin/sh: **go-md2man: command not found**
> 
> yum provides go-md2man
> No matches found

### I want to build custom s2i images on RHEL7, but i cannot.  I dont want to tell the customer to install a CentOS box just to do s2i builds.

**Comment by bparees** [comment]
this isn't a source to image issue.  please open your issue against the s2i-base-container repo.
