### ISSUE TITLE
s2i - committing the image due to error: invalid reference format

### ISSUE THREAD

**Issue by jainmnsh** [openshift/source-to-image#826]
Hello, 
I am getting an error when Building image using s2i tool. : invalid reference format error while doing build using s2i. I have attached following information. 

s2i v1.1.7-dirty
Docker version 17.06.2-ce, build cec0b72
OS : macOs 10.12.6
s2i build <github-->nodejs application > registry.access.redhat.com/rhscl/nodejs-6-rhel7:latest  my/loadTesting --loglevel=3

ERROR
I1110 09:43:14.441094   19514 sti.go:683] npm WARN sync-load-test@1.0.0 No description
I1110 09:43:14.441417   19514 sti.go:683] npm WARN sync-load-test@1.0.0 No repository field.
I1110 09:43:15.519345   19514 docker.go:1065] Invoking PostExecute function
I1110 09:43:15.521015   19514 postexecutorstep.go:66] Skipping step: store previous image
I1110 09:43:15.521031   19514 postexecutorstep.go:115] Executing step: commit image
I1110 09:43:15.523350   19514 postexecutorstep.go:520] Checking for new Labels to apply... 
I1110 09:43:15.523361   19514 postexecutorstep.go:528] Creating the download path '/var/folders/lt/0_hwh4g90bs4tfbn8m8jqx8w0000gr/T/s2i194844790/metadata'
I1110 09:43:15.777989   19514 postexecutorstep.go:536] unable to download and extract 'image_metadata.json' ... continuing
I1110 09:43:15.783153   19514 docker.go:1099] Committing container with dockerOpts: {Reference:my/loadTesting Comment: Author: Changes:[] Pause:false Config:0xc4203af200}, config: {Hostname: Domainname: User:1001 AttachStdin:false AttachStdout:false AttachStderr:false ExposedPorts:map[] Tty:false OpenStdin:false StdinOnce:false Env:[] Cmd:[/usr/libexec/s2i/run] ArgsEscaped:false Image: Volumes:map[] WorkingDir: Entrypoint:[container-entrypoint] NetworkDisabled:false MacAddress: OnBuild:[] Labels:map[io.openshift.s2i.build.commit.date:Fri Nov 10 07:00:02 2017 -0800 version:6 authoritative-source-url:registry.access.redhat.com io.openshift.s2i.build.commit.ref:dev com.redhat.dev-mode.port:DEBUG_PORT:5858 vcs-ref:7173d2ef184d571a5dda71794217f3ceae27d270 architecture:x86_64 com.redhat.component:rh-nodejs6-docker release:14.11 io.k8s.display-name:Node.js 6 distribution-scope:public description:Node.js 6 available as docker container is a base platform for building and running various Node.js 6 applications and frameworks. Node.js is a platform built on Chrome's JavaScript runtime for easily building fast, scalable network applications. Node.js uses an event-driven, non-blocking I/O model that makes it lightweight and efficient, perfect for data-intensive real-time applications that run across distributed devices. io.openshift.s2i.scripts-url:image:///usr/libexec/s2i io.s2i.scripts-url:image:///usr/libexec/s2i build-date:2017-10-18T13:20:42.554292 summary:Platform for building and running Node.js 6 applications io.openshift.s2i.build.image:registry.access.redhat.com/rhscl/nodejs-6-rhel7:latest io.openshift.s2i.build.commit.author:Manish Jain <jainmnsh@yahoo.com> io.openshift.s2i.build.commit.id:d9c7f4489ee2867e71349060c34f9b5f7d4aa5a9 io.openshift.expose-services:8080:http com.redhat.deployments-dir:/opt/app-root/src io.openshift.tags:builder,nodejs,nodejs6 com.redhat.build-host:ip-10-29-120-69.ec2.internal io.k8s.description:Node.js 6 available as docker container is a base platform for building and running various Node.js 6 applications and frameworks. Node.js is a platform built on Chrome's JavaScript runtime for easily building fast, scalable network applications. Node.js uses an event-driven, non-blocking I/O model that makes it lightweight and efficient, perfect for data-intensive real-time applications that run across distributed devices. name:rhscl/nodejs-6-rhel7 vcs-type:git url:https://access.redhat.com/containers/#/registry.access.redhat.com/rhscl/nodejs-6-rhel7/images/6-14.11 io.openshift.s2i.build.commit.message:preprod 1900 users list (#11) io.openshift.s2i.build.source-location:git@github.com:TkeITMobility/TCSyncLoadTesting.git com.redhat.dev-mode:DEV_MODE:false vendor:Red Hat, Inc.] StopSignal:}
I1110 09:43:15.783578   19514 sti.go:435] error: Execution of post execute step failed
I1110 09:43:16.258006   19514 cleanup.go:33] Removing temporary directory /var/folders/lt/0_hwh4g90bs4tfbn8m8jqx8w0000gr/T/s2i194844790
I1110 09:43:16.258402   19514 fs.go:236] Removing directory '/var/folders/lt/0_hwh4g90bs4tfbn8m8jqx8w0000gr/T/s2i194844790'
I1110 09:43:16.264385   19514 main.go:165] Build failed
E1110 09:43:16.264406   19514 errors.go:266] An error occurred: building my/loadTesting failed when committing the image due to error: invalid reference format
E1110 09:43:16.264410   19514 errors.go:267] Suggested solution: check the build output for errors
I1110 09:43:16.264415   19514 errors.go:269] Details: invalid reference format
E1110 09:43:16.264634   19514 errors.go:273] If the problem persists consult the docs at https://github.com/openshift/source-to-image/tree/master/docs. Eventually reach us on freenode #openshift or file an issue at https://github.com/openshift/source-to-image/issues providing us with a log from your build using --loglevel=3

**Comment by csrwng** [comment]
Hi @jainmnsh, 
What is the purpose of the redirect in your command line? 
```
s2i build nodejs application > registry.access.redhat.com/rhscl/nodejs-6-rhel7:latest my/loadTesting --loglevel=3
```

**Comment by jainmnsh** [comment]
@csrwng sorry, typo while reporting the command. I meant "nodejs application repo" but my issue is resolved after i change the casing of new image . from "my/loadTesting" to "my/loadtesting" and it worked. thanks for your help.

**Comment by csrwng** [comment]
@jainmnsh thx, good to know.

**Comment by csrwng** [comment]
Investigating whether we should guard against tags with upper case letters

**Comment by csrwng** [comment]
So I reproduced the behavior on Docker for Mac 17.09 and 1.13.1 (last version before CE). Both failed committing the image.

@bparees do you think it's worth validating in the s2i build command whether you're passing something with uppercase letters ?

**Comment by bparees** [comment]
Depends.  On linux we get a nice error already:
```
Build failed
ERROR: An error occurred: building hello-world-apP failed when committing the image due to error: repository name must be lowercase
```

but if that has changed on docker 17, then yes it probably is since the error that @jainmnsh got is pretty obscure.

**Comment by bparees** [comment]
I guess the short answer is yes, let's just do the validation.  it's easy and will save diagnosing this again in the future if we can't count on docker to report a good error.
