### ISSUE TITLE
make test fails on osx high Sierra

### ISSUE THREAD

**Issue by antonin07130** [openshift/source-to-image#835]
Hi I tried the test script, my s2i image seems to work but when I run the make test script I get the following errors :
```
IMAGE_NAME=nginx-alpine-s2i-candidate test/run
readlink: illegal option -- z
usage: readlink [-n] [file ...]
readlink: illegal option -- z
usage: readlink [-n] [file ...]
mktemp: illegal option -- -
usage: mktemp [-d] [-q] [-t prefix] [-u] template ...
       mktemp [-d] [-q] [-u] -t prefix 

[...]

Build failed
ERROR: An error occurred: stat /test-app: no such file or directory
S2I image 'nginx-alpine-s2i-candidate' test FAILED (exit code: 1)
^Cmake: *** [test] Interrupt: 2

```

https://github.com/openshift/source-to-image/blob/60a42d774045e6b1ec5c5aabee9c0ec6d1bbd7e6/examples/nginx-centos7/test/run#L17

**Comment by antonin07130** [comment]
Also I modified the make script to take into account corporate proxy when building an image. I guess this is a frequent use case.

**Comment by csrwng** [comment]
@antonin07130 please install coreutils using brew:
```
brew install coreutils
```
This will give you the GNU version of readlink and mktemp (as greadlink and gmktemp)

**Comment by antonin07130** [comment]
thanks @csrwng I try that right now.
Also, I am creating this s2i image from a git repo, and I've noticed that the test scripts changes my git properties (user.email user.name).

**Comment by coreydaley** [comment]
@antonin07130 Did @csrwng 's suggestion resolve your issue?
