### ISSUE TITLE
Chained builds question

### ISSUE THREAD

**Issue by magick93** [openshift/source-to-image#842]
Hello

I'm trying to figure out how to deploy Keycloak along with one or more custom themes.

I can deploy Keycloak as a docker image, using one of the images on https://hub.docker.com/r/jboss/keycloak-openshift/tags/

Is it possible to then have an image stream that would take source (for a custom theme) from git, build the theme, and copy it into a new image, based on the above docker keycloak image?

**Comment by bparees** [comment]
yes, that's basically what chained builds are for:
https://docs.openshift.org/latest/dev_guide/builds/advanced_build_operations.html#dev-guide-chaining-builds

you would use the first build (either an s2i or docker build) to produce an image containing the theme.

you'd then use the second build (probably a dockerbuild) to add the theme (from the first image) to the second image (via a dockerfile).

(also this question would be more appropriate in the origin repository)
