### ISSUE TITLE
How to build an S2I image and running as a "Privileged Container" in OpenShift

### ISSUE THREAD

**Issue by eliu** [openshift/source-to-image#845]
I create a s2i builder imagestream into openshift and now for some reason I need s2i to build the repo as a `privileged` container. But I didn't find proper ways to do that.

Right now, i have to waiting for the build process finished and see the warning of the pod then manually edit YAML adding privileged as true in order to make it work.

**Comment by marthanda93** [comment]
Please run below command on master
**oc edit scc privileged**
Add the following under **users**:
`   - system:serviceaccount:My_Project:My_SVCACCT
`

Then u can use below code in yml file 
```
securityContext:
  privileged: true
```

**Comment by eliu** [comment]
Please see my OP and I got no problem to do setup after s2i builder finishes to build. My question is how to finish this setup during the building process of the s2i builder. It is possible to do that? or i have to do this each time a new app / deployment is created by s2i builder.

**Comment by bparees** [comment]
please open this issue against openshift origin. 

also it's very unclear what you did/are trying to do.  Please provide exact steps and resource yaml where appropriate so we can follow what you have done.
