### ISSUE TITLE
incremental build failing with "ERROR: Error reading next tar header: archive/tar: invalid tar header"

### ISSUE THREAD

**Issue by simbo1905** [openshift/source-to-image#850]
I have an s2i with a [save-artifacts](https://github.com/UniqKey/s2i-nginx-php7-container/blob/master/7.1/s2i/bin/save-artifacts) that matches the [documented example](https://github.com/openshift/source-to-image/blob/master/docs/builder_image.md#save-artifacts). When I run s2i multiple times with:

```
s2i --incremental=true build https://github.com/simbo1905/hello-composer.git uniqkey/s2i-nginx-php71:latest hello-composer
```

It outputs:

```
ERROR: Error reading next tar header: archive/tar: invalid tar header
ERROR: Error extracting tar stream
WARNING: Clean build will be performed because of error saving previous build artifacts
```

I am using: 

```
Docker version 17.12.0-ce, build c97c6d6
s2i v1.1.8
```

If I log into the builder image with `docker run -it uniqkey/s2i-nginx-php71:latest /bin/bash` then check the save-artifacts and run it then it does create a valid tar: 

```
bash-4.2$ ls -al /usr/libexec/s2i/save-artifacts
-rwxr-xr-x 1 root root 280 Feb 27 20:38 /usr/libexec/s2i/save-artifacts
bash-4.2$ cat  /usr/libexec/s2i/save-artifacts
#!/bin/bash

# Besides the tar command, all other output to standard out must 
# be surpressed.  Otherwise, the tar stream will be corrupted.
pushd ${HOME} >/dev/null
if [ -d vendor ]; then
    # all deps contents to tar stream
    tar cf - vendor composer.phar
fi
popd >/dev/nullbash-4.2$ pwd
/opt/app-root/src
bash-4.2$ cd $HOME
bash-4.2$ mkdir vendor
bash-4.2$ echo whatever >> composer.phar
bash-4.2$ /usr/libexec/s2i/save-artifacts > saved.tar
bash-4.2$ tar tf saved.tar 
vendor/
composer.phar
bash-4.2$ 
```

**Comment by bparees** [comment]
yeah i've reproduced this but i don't understand it yet:

After building the image once, running:
`docker run -it --entrypoint=/usr/libexec/s2i/save-artifacts hello-composer | tar -tvf -`

reports an invalid tar error and extracts a single partial file (Exception.php, but not even the whole file).

I'm pretty baffled since, as you show, if you actually run the image there's no trouble manually tarring up that content, so i'm not sure why it should be any different as i invoked it above.

simplifying it even further:
` docker run -it --entrypoint=tar hello-composer cf - vendor | tar -tvf -`

also fails.

This feels like something that has changed in docker's stdout streaming behavior (it is cutting off the content)

**Comment by bparees** [comment]
sorry, the `--entrypoint=tar` failures appear to have been caused by the `-it` flags.

`docker run  --entrypoint=tar hello-composer cf - vendor composer.phar | tar -tvf -`

appears to work ok. still investigating.

**Comment by bparees** [comment]
ah, I see the issue.

your entrypoint for your image is printing content.

```
$ docker run -it hello-composer /bin/sh
Can't read /etc/scl/conf/nginx, nginx is probably not installed.
```

which ends up in the tar stream.  Fix your image entrypoint to not print anything (your "run", "assemble", and "usage" scripts can print stuff, but your entrypoint itself should not)

**Comment by bparees** [comment]
ah, well it's not your entrypoint, i think it's scl enablement logic that gets invoked when "/bin/bash" gets invoked in your save-artifacts script.

so you have a few options.  One is to get rid of these env vars in your image, which will stop it trying to enable the package (but if your app needs that package, that won't work):

```
            "BASH_ENV=/opt/app-root/etc/scl_enable",
            "ENV=/opt/app-root/etc/scl_enable",
            "PROMPT_COMMAND=. /opt/app-root/etc/scl_enable",
```

Another option might be to use "/bin/sh" in your save-artifacts, as i believe that will not respect those env vars, but i'm not sure.

Another would be to make scl happy by creating an /etc/scl/conf/nginx file of course.

**Comment by simbo1905** [comment]
Adding `>> /dev/null` to the end of the last line of `scl_enable` worked. Incremental compile now works on a large private repo with 111 deps saving 3 minutes. Thanks! 

Thanks for the suggestions about scl. It came with the repo that I forked and I am not convinced it is adding anything so will look into removing it.

Thanks again!

**Comment by bparees** [comment]
> Adding >> /dev/null to the end of the last line of scl_enable worked. Incremental compile now works on a large private repo with 111 deps saving 3 minutes. Thanks!

awesome!

@sspeiche ^^^ :)

**Comment by sspeiche** [comment]
very awesome!
