### ISSUE TITLE
assemble and run scripts appear to run as different users

### ISSUE THREAD

**Issue by lance** [openshift/source-to-image#853]
I am seeing some strange behavior when using s2i builder images within minishift. I am not sure if this is a problem with s2i or minishift, tbh. 

When the `/usr/libexec/s2i/assemble` script is run, it is executed as `uid=1001(default) gid=0(root) groups=0(root)`. This is fine and makes sense for the ultimate runtime instance, because that's the same user/group as the runtime user.

But the `/usr/libexec/s2i/run` script runs as a different user: `uid=1000120000 gid=0(root) groups=0(root),1000120000`.

This is causing problems for me, because for certain cases, files need to be read/written on the filesystem during the `run` script. But these end up owned by `1000120000` with group defaulting to `-r`. At runtime I end up with failures due to incorrect permissions because `1001` can't write files owned by `1000120000` with `044` permissions set.

**Comment by bparees** [comment]
it's expected behavior.

your assemble script runs as the default user for the builder image (whatever the last USER line in your dockerfile indicates).

your application image, when run on openshift, gets assigned a random uid.

The standard workaround is to chmod og+rwx such files (during assembly), and make them owned by the root group.

see: https://github.com/sclorg/s2i-base-container/blob/master/core/root/usr/bin/fix-permissions

**Comment by lance** [comment]
Yeah - we're doing the `chmod` stuff in `assemble`. But it doesn't really resolve the issue for me. It's a little more complicated than what you describe. In `assemble` we run `npm install --only=production` in order to keep the image size small and as secure as possible. There is no need to install development dependencies in the normal case. But, if the user has set `DEV_MODE=true` or `NODE_ENV=development` in the deployment config, then we install the development dependencies. Since we handle the `chmod` correctly in `assemble` the installation is not a problem. But we end up with different dependencies having different owners and permissions. This has occasionally been a problem. So far, I think we can work around it, but it does pose some issues.

On a related note, is it possible to set the `umask` for the "random" user in `assemble`?

**Comment by lance** [comment]
Just to be clear... 

> if the user has set `DEV_MODE=true` or `NODE_ENV=development` in the deployment config, then we install the development dependencies.

We install the dev dependencies during `/usr/libexec/s22i/run`.

**Comment by bparees** [comment]
> At runtime I end up with failures due to incorrect permissions because 1001 can't write files owned by 1000120000 with 044 permissions set.

I don't know how you are ending up with both uid 1001 and uid 100120000 at runtime.

Either the files were created during assemble time, by user uid 1001, or they were installed at runtime, by uid 100120000.

It sounds like you're saying that at runtime, uid 100120000 installs the deps(via the run script), but at that point nothing is running as uid 1001, so your statement that 1001 is being denied permissions(again, at runtime) does not make sense.

> On a related note, is it possible to set the umask for the "random" user in assemble?

no, but the random user can set their own umask in the run script, before you start installing dependencies as that user.

> We install the dev dependencies during /usr/libexec/s22i/run.

so again, those dependencies should be owned/read/writable by the runtime user.  I don't know how you have a process running as uid 1001 trying to access those files, at runtime, when the container is running as uid 100120000

**Comment by lance** [comment]
>> At runtime I end up with failures due to incorrect permissions because 1001 can't write files owned by 1000120000 with 044 permissions set.

> I don't know how you are ending up with both uid 1001 and uid 100120000 at runtime.
>
> Either the files were created during assemble time, by user uid 1001, or they were install ed at runtime, by uid 100120000.
>
> It sounds like you're saying that at runtime, uid 100120000 installs the deps(via the run script), but at > that point nothing is running as uid 1001, so your statement that 1001 is being denied permissions(again, at runtime) does not make sense.

Yes I misspoke and was incorrect - because this stuff is complicated and sometimes it's easy to not see exactly what the problem is. I appreciate your continued patience.

But the fact remains that assemble writes files as `1001`, and run writes them as `10012000` (or whatever random ID). I have worked around a few issues related to this, there is only one remaining. It is somewhat minor, I admit, but should illustrate why I care about umask.

During `assemble`, we install node and ensure everything that should be, is writable: https://github.com/bucharest-gold/centos7-s2i-nodejs/blob/master/s2i/assemble#L61

During `run`, we just start the app if we're in production mode, but if `DEV_MODE=true` has been set in the deployment config - so after the build/assemble steps occur - we need to further install some development dependencies, such as those in the user's `devDependencies` in `package.json`, and also we install `nodemon` if it is not already available. Both the `npm install` and `npx nodemon` calls here have NPM itself doing some checking of the write permissions in it's `.config` directory.

When I open a terminal to a running instance of an app where `DEV_MODE=true` has been set in the deployment config, I will see entries such as this in the `.config` dir.

```sh
h-4.2$ ls -l .config/configstore/
total 8
-rw------- 1 1000120000 root 55 Mar  1 16:11 update-notifier-nodemon.json
-rw--w---- 1 default    root 55 Mar  1 16:09 update-notifier-npm.json
sh-4.2$
```

As I write this, I realize that I can improve things to some degree by adding `+r` to my `chmod` command in `assemble`. But now, at run time we have this other file with `0600` permissions owned by the runtime user. That file is put there with the call to `npx` in `run`. But I'm not always going to know what files these processes write, and blindly/recursively doing chmod on a directory of files only some of which I own produces errors.

I think I can work around all of this. But it perhaps might be nice to have a pre-`run` hook that is executed as user `1001` so that runtime dependencies which could be conditionally installed during `run` (e.g. in `DEV_MODE`) are installed as the `default(1001)` user.

Maybe this should just be a feature request.

**Comment by bparees** [comment]
> But it perhaps might be nice to have a pre-run hook that is executed as user 1001 so that runtime dependencies which could be conditionally installed during run (e.g. in DEV_MODE) are installed as the default(1001) user.

so two things:

1) this isn't really an s2i topic at this point.  Your concerns are with how openshift runs images (it runs them as a random uid by default, and you need special permissions to be able to choose what user to run as)
2) due to (1), such a pre-run hook really isn't likely to be implemented in openshift (and it can't be implemented in s2i since s2i isn't responsible for running your image and has no control of what uid it runs as).

Anyway I appreciate the challenge you're facing, permission issues are definitely tricky given the openshift "random assigned uid" runtime behavior, but I think i've covered all the tools in our toolbox for handling it.

**Comment by lance** [comment]
@bparees ok - thanks for taking the time to discuss it. I think I can work this out, and just having this little chat has helped me to figure out some next steps. 👍
