### ISSUE TITLE
GitHub clone failing

### ISSUE THREAD

**Issue by cvschleich** [openshift/source-to-image#854]
Hello! I've tried a number of times to get the S2I working with my private GitHub repository. I've followed a few tutorials, and have thus far failed to successfully have it clone. I have my deploy key at github, and it's configured as the source secret in OpenShift, but still fails. Here's a level 5 log excerpt:

`I0302 16:13:58.914761       1 builder.go:74] redacted build: {"kind":"Build","apiVersion":"v1","metadata":{"name":"teamtextingalpha-4","namespace":"teamtextingalpha","selfLink":"/apis/build.openshift.io/v1/namespaces/teamtextingalpha/builds/teamtextingalpha-4","uid":"b187054b-1e34-11e8-84c7-122631632f42","resourceVersion":"2292019676","creationTimestamp":"2018-03-02T16:13:50Z","labels":{"app":"teamtextingalpha","buildconfig":"teamtextingalpha","openshift.io/build-config.name":"teamtextingalpha","openshift.io/build.start-policy":"Serial"},"annotations":{"openshift.io/build-config.name":"teamtextingalpha","openshift.io/build.number":"4"},"ownerReferences":[{"apiVersion":"build.openshift.io/v1","kind":"BuildConfig","name":"teamtextingalpha","uid":"07aa9014-1e33-11e8-9f6d-1250f17a13c8","controller":true}]},"spec":{"serviceAccount":"builder","source":{"type":"Git","git":{"uri":"https://github.com/cvschleich/WebTexting.git","ref":"master"},"sourceSecret":{"name":"repo-at-github"}},"strategy":{"type":"Source","sourceStrategy":{"from":{"kind":"DockerImage","name":"registry.access.redhat.com/rhscl/nodejs-4-rhel7@sha256:8301eefce7dd846a943b4b01f351b1baadee28c897ce38bf4564c87c6d0c9c45"},"env":[{"name":"BUILD_LOGLEVEL","value":"5"}],"forcePull":true}},"output":{"to":{"kind":"DockerImage","name":"172.30.208.107:5000/teamtextingalpha/teamtextingalpha:latest"},"pushSecret":{"name":"builder-dockercfg-dhrxq"}},"resources":{},"postCommit":{},"nodeSelector":null,"triggeredBy":[{"message":"Manually  triggered"}]},"status":{"phase":"New","outputDockerImageReference":"172.30.208.107:5000/teamtextingalpha/teamtextingalpha:latest","config":{"kind":"BuildConfig","namespace":"teamtextingalpha","name":"teamtextingalpha"},"output":{}}}
I0302 16:13:58.930521       1 builder.go:85] Master version "v3.7.23", Builder version "v3.7.23"
I0302 16:13:58.931089       1 scmauths.go:29] Finding auth for "..3983_02_03_16_13_52.190249061"
I0302 16:13:58.931100       1 scmauths.go:29] Finding auth for "..data"
I0302 16:13:58.931105       1 scmauths.go:29] Finding auth for "ssh-privatekey"
I0302 16:13:58.931111       1 scmauths.go:32] Found SCMAuth "ssh-privatekey" to handle "ssh-privatekey"
I0302 16:13:58.931121       1 scmauths.go:47] Setting up SCMAuth "ssh-privatekey"
I0302 16:13:58.931965       1 sshkey.go:30] Adding Private SSH Auth:
#!/bin/sh
ssh -i /var/run/secrets/openshift.io/source/ssh-privatekey -o StrictHostKeyChecking=false "$@"

Cloning "https://github.com/cvschleich/WebTexting.git " ...
I0302 16:13:58.932744       1 source.go:167] git ls-remote --heads https://github.com/cvschleich/WebTexting.git 
I0302 16:13:58.932763       1 repository.go:385] Executing git ls-remote --heads https://github.com/cvschleich/WebTexting.git 
I0302 16:13:59.353941       1 repository.go:453] Error executing command: exit status 128
I0302 16:13:59.354056       1 source.go:173] remote: Repository not found.
fatal: Authentication failed for 'https://github.com/cvschleich/WebTexting.git/' 
F0302 16:13:59.463665       1 helpers.go:120] error: failed to fetch requested repository "https://github.com/cvschleich/WebTexting.git " with provided credentials
`

Any idea what I'm doing wrong?

Thanks!

**Comment by bparees** [comment]
how did you create your source secret?  the most likely issue is that your secret data is not correct.

**Comment by cvschleich** [comment]
Tried a couple of different ways.

From: https://blog.openshift.com/private-git-repositories-part-2a-repository-ssh-keys/
I used:

`ssh-keygen -C "openshift-source-builder/repo@github" -f repo-at-github -N ''`

Anything there look amiss?

**Comment by bparees** [comment]
I mean how did you actually turn the key into an openshift secret?

(i'm going to assume you've confirmed you can clone w/ that ssh key locally, but that would be worth validating as well of course)

**Comment by cvschleich** [comment]
Ah. Sorry about that. I followed the instructions as in the link above. Namely: 

> Click on the Create Secret button in the top right corner. This will bring up a form to enter in the details of the secret corresponding to the SSH private key.
> 
> On this form you need to set the following:
> 
> Ensure that the Secret Type is Source Secret.
> Set the Secret Name. In this case, we are using repo-at-github.
> Ensure that the Authentication Type is SSH Key.
> Upload or paste in the contents of the private key file. This is the file without the .pub extension. In this case, the repo-at-github file.
> Enable the Link secret to a service account option.
> Ensure that the Service Account is set to builder.

And yes, it clones locally just fine. Just reconfirmed. Thanks so much for your help!

**Comment by cvschleich** [comment]
Gah! I'm an idiot.

I was giving it the https link instead of the ssh link. Fixed and running now.

Thanks so much and sorry to bother you!

**Comment by bparees** [comment]
heh, cool :)
