### ISSUE TITLE
Documentation question: Enterypoint for S2I

### ISSUE THREAD

**Issue by atlasloewenherz** [openshift/source-to-image#858]
Hi Everyone,

i have the following situation, i have multiple docker based images, from down to top:

01: basic linux image built from scratch
02: based on 01-image adds a user under which the application server will runs
03: based on 02-image and installs JVM 
04: based on 03-image and installs ( application server)
05: based on 04-image and deploys artifacts pulled from central maven repos

I want to consider using S2I in my previously described pipline, but im in doubt about a couple of things:

a) where exactly the approach Builder Image should starts? 
Since all my Images outcome is a Docker Image that is the base for the next Image except the last Image. 
possible answer: 

- If i got the idea correctly i think the builder Image should be based on my 03-image and adds what ever required to compile the source code (maven) so i can use the builder Image to compile and deploy its outcome to the 04-Image 

b) do i need to create a builder Image for each Image of the above? i will then need to create five Builder Images for creating five images?

thanks for clarifying

ely

**Comment by bparees** [comment]
I'm a little unclear on what (4) does.  You say installs (application server). Is it also building/installing the application, or is that done in (5)?

The normal structure for an s2i builder is that the builder image contains:

1) the runtime for running an application (but not the application itself)
2) the compilation tools to build/assemble an application

so assuming you want to retain the layers you've defined, i'd expect your image to look like

1) basic linux image (not an s2i builder)
2) + user definition (not an s2i builder)
3) + JVM (not an s2i builder)
4) + app server (here's where i'd add the run/assemble scripts which make it an s2i builder)
5) + app code/dependencies (produced via s2i build performed using (4) and your app source)
