### ISSUE TITLE
Skeleton application for a builder image

### ISSUE THREAD

**Issue by cliveseldon** [openshift/source-to-image#859]
I would like users of my builder image to be able to create a correct source folder that will work with my builder image. I'm not sure of the best practice for this. I can create docs to help them but it would be great to be able to create a skeleton folder of appropriate type in the same way that ```s2i create``` does for builder images.

For context, I want to use s2i to allow users to wrap their machine learning models : https://github.com/SeldonIO/seldon-core/issues/113

For further context, for a python model they need to create a python file containing a class of the same name with a predict method, e.g.
```
from keras.models import load_model
    
class MnistClassifier(object): # The file is called MnistClassifier.py
    
    def __init__(self):
		""" You can load your pre-trained model in here. The instance will be created once when the docker container starts running on the cluster. """
        self.model = load_model('MnistClassifier.h5')
	    
    def predict(self,X,feature_names):
		""" X is a 2-dimensional numpy array, feature_names is a list of strings. 
		This methods needs to return a numpy array of predictions."""
        return self.model.predict(X)
```

Any advice appreciated.

**Comment by bparees** [comment]
We normally just host a sample git repo for a given s2i build image, and maybe have your usage script(the script your image entrypoint runs by default) point to it, eg:

```
$ docker run docker.io/centos/ruby-24-centos7

This is a S2I ruby-2.4 centos base image:
To use it, install S2I: https://github.com/openshift/source-to-image

Sample invocation:

s2i build https://github.com/sclorg/s2i-ruby-container.git --context-dir=2.4/test/puma-test-app/ centos/ruby-24-centos7 ruby-sample-app


You can then run the resulting image via:
docker run -p 8080:8080 ruby-sample-app
```

Where `https://github.com/sclorg/s2i-ruby-container.git --context-dir=2.4/test/puma-test-app/ ` is a sample app nested within the image repo.

Then people can just fork that sample repo.

Does that seem reasonable for your use case?

**Comment by cliveseldon** [comment]
Yes. That looks fine.  

Just was thinking if there was functionality similar to "s2i create" that a builder creator could define that would make it even easier if it was a command inside s2i, e.g. clone https://github.com/sclorg/s2i-ruby-container.git --context-dir=2.4/test/puma-test-app/  or --context-dir=2.4/test/rack-test-app/ to a destination folder.

Then a user could hack that created folder and simply run the build command again on that folder.

**Comment by bparees** [comment]
Yeah, but it would require putting an additional burden on s2i builder image authors to provide that functionality.  One of the goals of s2i was to enable it to work with any image (e.g. even if the image doesn't provide run/assemble scripts, the end user can provide their own scripts to be used with an existing non-s2i image).

So i think adding additional expectations on the behavior of an s2i builder image run counter to that, and I think a usage script that prints out the appropriate git clone command to run to clone a sample from github provides an almost as good experience with much less additional complexity in either the s2i binary, or the s2i builder image.

**Comment by cliveseldon** [comment]
OK. Thanks for the quick responses. Look forward to adding s2i to the project I work on.
