### ISSUE TITLE
using aws codecommit as remote git repo [in openshift]

### ISSUE THREAD

**Issue by adrianbader** [openshift/source-to-image#860]
I would like to use s2i to build an application from sources stored on aws codecommit. I would like to use ssh rather than https urls. So I need to create a secret in openshift with the certificates and I need to upload the public key to aws codecommit.
However, what I also need is to configure ssh to use the aws SSH key ID as user name; so to be able to access aws codecommit over ssh, not only the uploaded public key is needed but we also need to add e.g. 

    Host git-codecommit.*.amazonaws.com
      User APKAJIJ2J6NRHxxxxxxx
      IdentityFile ~/.ssh/id_rsa
  
to `~/.ssh/config`

How can this be done without modifying the base image?

**Comment by bparees** [comment]
can't you specify your git url as APKAJIJ2J6NRHxxxxxxx@git-codecommmit.foo.amazonaws.com and then provide your key as described here:
https://docs.openshift.org/latest/dev_guide/builds/build_inputs.html#source-secrets-ssh-key-authentication

?

In anycase cloning is not done by the builder image, so updating the image is not relevant.

**Comment by adrianbader** [comment]
Oh, thanks, I did not remember that I can specify the user in front. This works like a charm, I tested it.
