### ISSUE TITLE
Official logo

### ISSUE THREAD

**Issue by cliveseldon** [openshift/source-to-image#863]
Is there an official logo that can be used? I'd like to reference this project in a presentation.

**Comment by bparees** [comment]
I'm afraid we do not have an official logo currently.

/cc @sspeiche

**Comment by sspeiche** [comment]
For $20 we can have https://logojoy.com/s/18814874?type=banner&h=B1o6vOQaM :)
We'll see how the project progresses and whether we create a logo for it.
