### ISSUE TITLE
Apply .s2iignore for files that are copied as part of `--copy`

### ISSUE THREAD

**Issue by asottile** [openshift/source-to-image#867]
Hitting a bit of an edge case but hopefully there's an easy-ish fix for the copy step.

From reading [pkg/ignore/ignore.go](https://github.com/openshift/source-to-image/blob/57a644844c76dad4d42b7045e47e6b73e66d58d7/pkg/ignore/ignore.go#L21-L53) it seems that the way this happens right now is:

1. copy the source (or clone in the case of not `--copy`)
2. delete files in `.s2iignore`

I'm dealing with a particularly circular case where I'm attempting to build a docker image for a vagrant setup, while using vagrant to run s2i.  In short, the current build is trying to copy the vagrant image while inside of vagrant despite being in the `.s2iignore` -- this unsurprisingly fills up the disks.

The ideal case for me would be to apply the `.s2iignore` as a blacklist _during copying_ -- if this sounds acceptable I'd be willing to hack on a PR for this :)

**Comment by bparees** [comment]
yeah i guess i'd be ok w/ that if you want to submit a PR.

**Comment by nabilbendafi** [comment]
I tried to address this issue and provided a PR. 
It has been tested locally successfully : 
  - [x] Build locally without .s2iignore
  - [x] Build locally with .s2iignore targeting directories
  - [x] Build locally with .s2iignore targeting file
  - [x] Build using remote source (no impact)

Though I was not able to provide a proper unit test for it; any _help_ is welcome.
