### ISSUE TITLE
FATAL: unable to parse docker host `127.0.0.1` with DinD

### ISSUE THREAD

**Issue by cliveseldon** [openshift/source-to-image#871]
Using s2i with Docker-in-Docker I'm getting an error of FATAL: unable to parse docker host `127.0.0.1`

This is with the Argo project using a sidecar in kubernetes with their docker:17.10-dind  image

Any ideas?

**Comment by cliveseldon** [comment]
The issue seems to be with Docker-in-Docker the DOCKER_HOST env var was set to 127.0.0.1
The docker client seems to handle this ok.
If I change the environment var to tcp://127.0.0.1:2375 everything works again.
It seems the docker client library is strict in its parsing

https://github.com/docker/cli/blob/99bd7ed693c093b65f98e9f30a47faff9d7c059c/vendor/github.com/docker/docker/client/client.go#L361-L365

**Comment by bparees** [comment]
cool.
