### ISSUE TITLE
Multiple runtime artifacts provision is not working

### ISSUE THREAD

**Issue by ingcsmoreno** [openshift/source-to-image#872]
## What happen?
The **How to use a non-builder image for the final application image** document specifies that it's possible to set [multiple runtime artifacts](https://github.com/openshift/source-to-image/blob/master/docs/runtime_image.md#runtime-image-requirements) to be copied from _build_ container to _runtime_ container by passing the `runtime-artifacts` option a semicolon separated list of paths.

I executed a build with the following command:
```
s2i build /Users/Escanor/Git/AwesomeApp s2i/php:builder_7.1-1.8.2 service/awesomeapp:live --runtime-image s2i/php:run_7.1-1.8.2 --runtime-artifact "/var/www:./var;/etc/tokens" -v /tmp/tokens:/etc/tokens
```
## Expected Result
The build works, and both paths are copied into the runtime container.

## Actual Result
The following error occurred:
```
Error: invalid argument "/var/www:./var;/etc/tokens" for --runtime-artifact: invalid characters in filename: "/var/www:./var;/etc/tokens"
```

## Where?
I've (tried to) run the build on the following environments:

- Alpine Linux 3.4 and S2I v1.1.0
- MacOS High Sierra and S2I v1.1.5

Got the same result and error message in both cases.

## Extra info
After a quick inspection to the source code, I found the is a [path validation](https://github.com/openshift/source-to-image/blob/9a1bd4dcd19bca938c3f8aa09cf1748a1560554d/pkg/api/types.go#L26) that explicitly declares the semicolon as an invalid character.  

Shouldn't a paths split take place before this check?

**Comment by adambkaplan** [comment]
@bparees closing this issue (feature merged in origin)

**Comment by bparees** [comment]
I think it could have been closed when the fix was merged into the s2i repo actually.  We don't even support the runtime image/artifacts flow on openshift anymore and the issue was reported against the s2i cli invocation.  But either way, thanks for fixing it :)
