### ISSUE TITLE
s2i not work on windows

### ISSUE THREAD

**Issue by songpr** [openshift/source-to-image#876]
I've try s2i in windows here is command
`PS H:\> c:\app\s2i\s2i build https://github.com/sclorg/s2i-php-container.git --context-dir=7.1/test/test-app centos/php-
71-centos7 php-test-app`

Here is the out put
> Submodule 'common' (https://github.com/sclorg/container-common-scripts.git) registered for path 'common'
Cloning into 'C:/Users/Pornchai.R/AppData/Local/Temp/s2i669970723/upload/tmp/common'...
Submodule path 'common': checked out '0ed2139bd3ef4758cdc715ba4ebc3c45f648372e'
Build failed
**ERROR: An error occurred: fork/exec C:\app\Git\cmd\git.exe: The directory name is invalid.**

**Comment by bparees** [comment]
I suspect this might be an issue w/ the symlinks used in that repo not working well on windows, can you try it w/ a flat repo like https://github.com/sclorg/cakephp-ex ?

`s2i build https://github.com/sclorg/cakephp-ex centos/php-71-centos7 php-test-app`

alternatively you can try git-cloning the repo manually and using the "--copy" flag w/ s2i to point it to a local dir and not use git to retrieve the content.

**Comment by songpr** [comment]
Thanks a lot for your solutions.
I've try the flat repo and it just work!
I will try the copy solution and update again!!
