### ISSUE TITLE
Do not apply .s2iignore before assemble script when using separate builder and runtime images

### ISSUE THREAD

**Issue by donkeybanana** [openshift/source-to-image#877]
When following https://github.com/openshift/source-to-image/blob/master/docs/runtime_image.md, `.s2iignore` does not allow blacklisting of files at the runtime stage, only the build stage.

As such, blacklisting files such as `package.json` removes sources which are (potentially) required by the `assemble` script (see https://gist.github.com/donkeybanana/47454b0800af4bd01d5b1180da442d07 for a very-basic pseudo-example).

I consider the `.s2iignore` concept much more approachable and maintainable than maintaining an `assemble` script to remove the undesirable runtime sources, especially given the `assemble`(and `-runtime`) script(s) are currently baked into my builder and runtime images for completeness, and would therefore require a rebuild of said images.

**Comment by donkeybanana** [comment]
As a suggestion, given the post-build sources are shipped to the runtime image as an archive that could instead apply the rules in `.s2iignore`.

**Comment by donkeybanana** [comment]
I've started working on a PR at https://github.com/donkeybanana/source-to-image/tree/feature/post-assemble-s2iignore.

A couple of items I need clarification on to implement correctly:

- [ ] What loglevel and stream (`HEAD` is using `fmt.Fprintln(os.Stdout, ...`) should I be using to inform the user of the deferred `Ignore` invocation?
- [ ] Into which process should I be injecting the deferred `Ignore` invocation?

**Comment by bparees** [comment]
given that you already explicitly indicate what artifacts you want to copy out from the result of assembly, as inputs to runtime-assembly, is this really a common problem?

In general the extended build feature in s2i is something we're trying to de-invest in, so i'm reluctant to add more complexity to it here, though i'm willing to consider your PR if it does not add significant complexity.

**Comment by donkeybanana** [comment]
> given that you already explicitly indicate what artifacts you want to copy out from the result of assembly, as inputs to runtime-assembly, is this really a common problem?

This is the problem entirely: I absolutely **do not** want to maintain multiple ignores across multiple processes, especially not within contexts which have their own lifecycle, as I already mentioned above.

> I consider the .s2iignore concept much more approachable and maintainable than maintaining an assemble script to remove the undesirable runtime sources, especially given the assemble(and -runtime) script(s) are currently baked into my builder and runtime images for completeness, and would therefore require a rebuild of said images.

I think the addition of `.s2iignore` (along with `.dockerignore`) is a fair compromise as it lives with the code it is applying rules to, and is consumed as a build-time input as part of that code.

I do admit though, I probably present an edge-case here given the current uptake of OpenShift as a whole, let alone `s2i` and then the separate runtime image convention.

> In general the extended build feature in s2i is something we're trying to de-invest in

I was actually concerned about this given no support for UI-driven configuration of the runtime image within OpenShift (though it is configurable and respected via the YAML definition).

> though i'm willing to consider your PR if it does not add significant complexity

If you could help with answering my two queries in my previous comment I will give the PR a fair shot, as it will be a good exercise for me learning golang (this will be my first contribution to any golang project).

**Comment by bparees** [comment]
> I was actually concerned about this given no support for UI-driven configuration of the runtime image within OpenShift (though it is configurable and respected via the YAML definition).

The RuntimeImage field was actually removed from openshift s2i build options as of v3.7.  

We instead advise people to use chained builds if they want to create lightweight runtime images: https://docs.openshift.org/latest/dev_guide/builds/advanced_build_operations.html#dev-guide-chaining-builds

> What loglevel and stream (HEAD is using fmt.Fprintln(os.Stdout, ...) should I be using to inform the user of the deferred Ignore invocation?

i'm not exactly sure what you mean by "deferred ignore invocation", but generally glog.V(2) is appropriate for "stuff someone might care about if things aren't working as they expected, but they don't normally need to know about" and that output would go to stdout.

> Into which process should I be injecting the deferred Ignore invocation?

also not clear what is meant here... the existing ignore logic is performed as part of the main s2i process while it is shuffling the input files around.  I'd expect this logic to similarly reside in the s2i main process, between the time when we extract content from the builder image, and the time we inject it into the runtime image.

**Comment by donkeybanana** [comment]
> https://docs.openshift.org/latest/dev_guide/builds/advanced_build_operations.html#dev-guide-chaining-builds

Thanks for this. We do things like this within Docker (outside of OpenShift) but hadn't considered it a valid approach within OpenShift, given the documentation promoting S2I when I last read it (hence this feature request). I'd assumed not much had changed regarding the recommended approaches so missed these updated docs.

I'll go back to my team and consider the new recommendation(s).

> i'm not exactly sure what you mean by "deferred ignore invocation"

[This line](https://github.com/donkeybanana/source-to-image/commit/cadee396ca8568c0da4eae90158b2f578bae01c3#diff-77c4df2e21c6a783c0928af25a29ba8dR418) shows the original `Ignore` invocation, which is part a return statement. My intent is to defer this invocation under the set of circumstances outlined above (visible and implemented in that link).

In my question(s) I was merely fishing for information on what stage/module/file might contain a reasonable location where the deferred invocation may be placed (given my familiarity with this repo is close to zero, I'd rather start with a reasonable and informed attempt at my PR).

**Comment by bparees** [comment]
> This line shows the original Ignore invocation, which is part a return statement. My intent is to defer this invocation under the set of circumstances outlined above (visible and implemented in that link).

I understand now, but i'm not sure if it's a good idea since it fundamentally changes the behavior of .s2iignore (in that now all the content is supplied to the builder image).

I still don't understand why this is an issue since you explicitly tell s2i what files to copy from the builder image to the runtime image, so can't you just setup that copy in such a way that it does not include your undesired files?

As for where you should do the ignore on the runtime side, probably somewhere in here:
https://github.com/openshift/source-to-image/blob/master/pkg/build/strategies/sti/postexecutorstep.go#L176

or here:
https://github.com/openshift/source-to-image/blob/master/pkg/build/strategies/sti/postexecutorstep.go#L242

**Comment by donkeybanana** [comment]
Thanks for the hints, will take a look. I agree this would be a breaking change if it was default behaviour, as such I'll attempt to add a CLI flag for opt-in.

> I still don't understand why this is an issue since you explicitly tell s2i what files to copy from the builder image to the runtime image

I am trying my best to avoid maintaining yet another white/blacklist of files (in addition to `.s2iignore`, `.dockerignore`, etc). As already mentioned above, I know I could handle this behaviour in `assemble-runtime`, but my `s2i/bin` scripts are baked into my images (which are sat in a registry for all to use) to make them more atomic/portable which would require a rebuild.

One option I haven't explored is having the `s2i/bin` script pulled in remotely, but this would not solve the problem of having ignores spread across multiple files and therefore not satisfy my requirements.
