### ISSUE TITLE
make test is giving timeout

### ISSUE THREAD

**Issue by chargio** [openshift/source-to-image#881]
I've written a source to image builder for elixir.

When executing make build it creates a container that runs in docker. In order to test connectivity, you need to connect to localhost:container_port, but the code (at least in Mac OS) returns the exposed port (that is the internal port). The connection does time out even if the container is running properly.

I've fixed it changing the test/run script like this:

```bash
container_ip() {
  if [ ! -z "$DOCKER_HOST" ] && [[ "$OSTYPE" =~ 'darwin' ]]; then
    docker-machine ip
  elif [ -z "$DOCKER_HOST" ] && [[ "$OSTYPE" =~ 'darwin' ]]; then
    echo "localhost"
  else
    docker inspect --format="{{ .NetworkSettings.IPAddress }}" $(cat $cid_file)
  fi
}

container_port() {
  if [ ! -z "$DOCKER_HOST" ] && [[ "$OSTYPE" =~ 'darwin' ]]; then
    docker inspect --format="{{(index .NetworkSettings.Ports \"$test_port/tcp\" 0).HostPort}}" "$(cat "${cid_file}")"
  elif [ -z "$DOCKER_HOST" ] && [[ "$OSTYPE" =~ 'darwin' ]]; then
    docker inspect --format="{{(index .NetworkSettings.Ports \"$test_port/tcp\" 0).HostPort}}" "$(cat "${cid_file}")"
  else
    echo $test_port
  fi
}
```

The origina code does not include the elif, and thus returns a non valid value if running in docker in darwin. I've kept it this way as I don't know if the same thing should be done for other OS, changing the elif in to ` elif [ -z "$DOCKER_HOST" ]; then`

**Comment by bparees** [comment]
@adambkaplan can you confirm this issue/fix on mac?  it works fine for me on linux.

**Comment by adambkaplan** [comment]
@chargio I am having a separate issue on your s2i image. I'm getting the following error in your test/run script:

```
readlink: illegal option -- z
usage: readlink [-n] [file ...]

**Comment by chargio** [comment]
If you are using a Mac, it is quite possible that you need to install GNU versions of the tools to get the full functionality...

**Comment by adambkaplan** [comment]
@chargio I can confirm this fix works on Docker CE/EE for Mac - published ports are exposed to `localhost`. This is to ease development on Mac, as all Docker containers in CE/EE run in a virtual machine (hyperkit).
You'll likely need to add a similar `elif` statement to handle Windows - it uses Hyper-V to isolate the container environment.
