### ISSUE TITLE
s2i build completed successfully.but can not run hello-python image

### ISSUE THREAD

**Issue by luzhzhsoft** [openshift/source-to-image#888]
i clone s2i source code and compile it in linux. when i build as example say  ,build completed successfully.but when i run image  hello-python . it told me 
`/opt/app-root/etc/scl_enable: line 6: /opt/app-root/bin/activate: No such file or directory
---> Serving application with gunicorn (wsgi) ...
/usr/libexec/s2i/run: /opt/app-root/bin/gunicorn: /opt/app-root/bin/python3: bad interpreter: No such file or directory
/usr/libexec/s2i/run: line 88: /opt/app-root/bin/gunicorn: Success
`

**Comment by bparees** [comment]
can you give me the exact s2i command line invocation you ran?

**Comment by luzhzhsoft** [comment]
@bparees  
`go get github.com/openshift/source-to-image/cmd/s2i
cd src/github.com/openshift/source-to-image/cmd/s2i/
go build
./s2i build https://github.com/openshift/django-ex centos/python-35-centos7 hello-python
 docker run -p 8080:8080 hello-python`

my docker version is  1.12.6 and go version is go1.10.2 linux/amd64 。my system is centos

**Comment by bparees** [comment]
hm, works ok for me.  the first thing i'd check is whether you've got the latest centos/python-35-centos7 image pulled down.  The fact that scl enable completely failed makes me think there's something fundamentally broken about the centos/python-35-centos7 base image you built on top of.

**Comment by luzhzhsoft** [comment]
@bparees 
I'll try again later,thanks anyway
