### ISSUE TITLE
Question: Is there such a thing as s2i build dry run?

### ISSUE THREAD

**Issue by sohrab-** [openshift/source-to-image#896]
Is it possible to run s2i build _without_ actually producing an image? Like a dry-run of the s2i assemble phase?

I would love to use the same s2i image and scripts used for build to test our pull requests. 

Due to some unrelated issues, I cannot mount the source code as part of `docker run` and rather leverage the s2i mechanism to stream the source into the image.

**Comment by bparees** [comment]
not today, but you can certainly output to a dummy tag you don't care about and then `docker rmi` the image if you're worried about it being left around.

**Comment by sohrab-** [comment]
Thanks for the answer
