### ISSUE TITLE
running example in readme results in error

### ISSUE THREAD

**Issue by maxandersen** [openshift/source-to-image#897]
Just downloaded latest release 1.1.10 and when I run the first example in readme I get this error:

`./s2i build https://github.com/openshift/django-ex centos/python-35-centos7 hello-python                                    ⏎
error: Unable to load docker config: json: cannot unmarshal string into Go value of type docker.dockerConfig
pulling image error : open /var/lib/docker/tmp/GetImageBlob273107030: read-only file system
pulling image error : open /var/lib/docker/tmp/GetImageBlob429688298: read-only file system
ERROR: An error occurred: unable to get centos/python-35-centos7:latest
ERROR: Suggested solution: check image name, or if using local image add --pull-policy=never flag
ERROR: If the problem persists consult the docs at https://github.com/openshift/source-to-image/tree/master/docs. Eventually reach us on freenode #openshift or file an issue at https://github.com/openshift/source-to-image/issues providing us with a log from your build using --loglevel=3`

running on OSX if that matters.

**Comment by bparees** [comment]
1.1.11 is the latest release, fyi.  that's the one that has the --as-dockerfile arg.

**Comment by bparees** [comment]
@adambkaplan can you reproduce this error on your mac?

**Comment by bparees** [comment]
@maxandersen can you provide your redacted `.docker/config.json` and docker version info?

**Comment by maxandersen** [comment]
here is what is in 

~/.docker/config.json:

```
{
  "auths" : {

  },
  "credsStore" : "osxkeychain"
}
```

**Comment by adambkaplan** [comment]
@maxandersen please try logging into Docker (via `docker login` or the Docker CE menubar) first, as the auths object shouldn't be empty.

**Comment by maxandersen** [comment]
did docker login and now this is left:

```
s2i build https://github.com/openshift/django-ex centos/python-35-centos7 hello-python             ⏎
pulling image error : open /var/lib/docker/tmp/GetImageBlob172450595: read-only file system
pulling image error : open /var/lib/docker/tmp/GetImageBlob427829457: read-only file system
ERROR: An error occurred: unable to get centos/python-35-centos7:latest
ERROR: Suggested solution: check image name, or if using local image add --pull-policy=never flag
ERROR: If the problem persists consult the docs at https://github.com/openshift/source-to-image/tree/master/docs. Eventually reach us on freenode #openshift or file an issue at https://github.com/openshift/source-to-image/issues providing us with a log from your build using --loglevel=3
```

**Comment by adambkaplan** [comment]
@maxandersen please provide the version of Docker you are using, and try pulling the image by itself:

**Comment by maxandersen** [comment]
turns out I must have some corrupt docker install - probably caused by running out disk earlier in the day. closing this assuming that is the issue - will reopen if that doesn't fix it ;)

**Comment by maslick** [comment]
Same here (Mac OSX 10.14.3, brew, s2i v1.1.13-dirty, docker-machine version 0.16.1):
```
$ s2i build --copy . fabric8/s2i-java test:1.0
error: Unable to load docker config: json: cannot unmarshal string into Go value of type docker.dockerConfig
```
Docker config:
```
$ cat ~/.docker/config.json
{
  "stackOrchestrator" : "swarm"
}
```
