### ISSUE TITLE
How to use s2i with a golang base program?

### ISSUE THREAD

**Issue by zhanp** [openshift/source-to-image#915]
If I want to build a docker image for my golang base program, and there are more than one level packages in it. s2i always throw my base directory name away. What should I do?

**Comment by zhanp** [comment]
For example, my program looks like:

**Comment by zhanp** [comment]
For example, my program looks like:

**Comment by zhanp** [comment]
For example, my program looks like:

- app
-     package1
-     package2

And with s2i, files in app dir will be copy into `/tmp/src`, and I can't get the name `app`, and `import /app/package1` will fail.

**Comment by bparees** [comment]
It sounds like the dir you're losing is the repo name?  That is likely the case since I think we clone your repo and then inject the content that was in the repo, into the /tmp/src dir.

can you point me to your repo(or a sample one) and show me the s2i invocation you're using so we can be sure though?

One workaround could be to update the assemble script to recreate the top level dir and move the content into it before compilation, though I realize that sounds hacky.

**Comment by zhanp** [comment]
What about this? https://github.com/zhanp/go-110-centos7

I tried to make a s2i builder for golang 1.10, it can be used like:

```
git clone git@github.com:zhanp/go-110-centos7.git
cd go-110-centos7
make build
s2i build test/test-app go-110-centos7 test
```

It would be success because I set a env variable $GODIR to specify the dir name `test-app`, and I copy `/tmp/src/.` into `/go/src/$GODIR`, so that `import "test-app/package1"` is effective cuz golang enable to find `test-app` in `$GOPATH/src`.

I wonder if there is a cleverer way to do it, with no $GODIR config. Or you can just tell me how people always do. If there is a builder project for golang just like python's https://github.com/sclorg/s2i-python-container. That would be very cool.

THX!

**Comment by bparees** [comment]
There is an s2i-golang image, the repository for it is here:
https://github.com/sclorg/golang-container

Maybe move this issue to that repo?

**Comment by bparees** [comment]
(you can see the assemble script logic here: https://github.com/sclorg/golang-container/tree/master/1.10/s2i/bin)

**Comment by zhanp** [comment]
They specify env variables `IMPORT_URL ` or `INSTALL_URL ` just like what I did with `GODIR`, it might be the way that people always do. I think it could be helpful if s2i can provide this 2 env variables.

Still thank you for helping.
