### ISSUE TITLE
environmental variable error

### ISSUE THREAD

**Issue by sathiez** [openshift/source-to-image#918]
when I run image file, I get the below mentioned error 
"ImportError: libcublas.so.9.0: cannot open shared object file: No such file or directory" (i.e while importing tensorflow-gpu) 
my environment file looks like this:
.s2i/environment:
MODEL_NAME=MyModel
API_TYPE=REST
SERVICE_TYPE=MODEL
PERSISTENCE =0
LD_LIBRARY_PATH=/usr/local/cuda-9.0/lib64/

**Comment by bparees** [comment]
sounds like an image problem.  what image are you running?  can you provide recreate steps?

**Comment by sathiez** [comment]
I have created a Image file with s2i using "s2i build <src-folder> seldonio/seldon-core-s2i-python3:0.1 <ImageName>". In the source folder I placed my requirement.txt as below:

requirement.txt
tensorflow-gpu==1.10.1

**Comment by bparees** [comment]
You will need to take this issue up w/ the maintainer of the seldon-core-s2i-python image, this is not an s2i problem.
