### ISSUE TITLE
`--inject` requires container path to exist or "write unix /var/run/docker.sock: broken pipe"

### ISSUE THREAD

**Issue by jimklo** [openshift/source-to-image#936]
I've got a `create-react-app` that I've built and now want to copy the build contents into [rhscl/nginx-112-rhel7](https://github.com/sclorg/nginx-container/tree/master/1.12) through s2i customization.

For purpose of portability, I don't really want to intermingle the s2i overrides with my CRA app source, so it would make sense to me to be able to use the `--inject` to make the build files available during the assemble step and extend the assemble script to copy files from that location to the `/opt/app-root/src`, or possibly a different location based upon a custom nginx conf file.

However when I try to do this I get one of two errors:
```bash
$ s2i build --inject ../../familyapp/build:./foo . rhscl/nginx-112-rhel7 family-app 
I1015 17:09:10.125965 07574 install.go:251] Using "assemble" installed from "<source-dir>/.s2i/bin/assemble"
I1015 17:09:10.126168 07574 install.go:251] Using "run" installed from "image:///usr/libexec/s2i/run"
I1015 17:09:10.126192 07574 install.go:251] Using "save-artifacts" installed from "image:///usr/libexec/s2i/save-artifacts"
E1015 17:09:11.329123 07574 injection.go:98] Error occured during injecting "../../familyapp/build" to "/opt/app-root/src/foo": write unix /var/run/docker.sock: broken pipe
```
of I get the following error:

```bash
$ s2i build --inject ../foo:./bar . rhscl/nginx-112-rhel7 family-app 
I1015 17:10:29.654666 08083 install.go:251] Using "assemble" installed from "<source-dir>/.s2i/bin/assemble"
I1015 17:10:29.654770 08083 install.go:251] Using "run" installed from "image:///usr/libexec/s2i/run"
I1015 17:10:29.654787 08083 install.go:251] Using "save-artifacts" installed from "image:///usr/libexec/s2i/save-artifacts"
E1015 17:10:30.313904 08083 injection.go:95] The destination directory for "../foo" injection must exist in container ("/opt/app-root/src/bar")
```

A variation of this is when I try to use `/tmp/build` as a 'mount point' in the assembling container:
```bash
$ s2i build --inject ../../familyapp/build:/tmp/build . rhscl/nginx-112-rhel7 family-app 
I1015 17:11:29.512812 08287 install.go:251] Using "assemble" installed from "<source-dir>/.s2i/bin/assemble"
I1015 17:11:29.512940 08287 install.go:251] Using "run" installed from "image:///usr/libexec/s2i/run"
I1015 17:11:29.512958 08287 install.go:251] Using "save-artifacts" installed from "image:///usr/libexec/s2i/save-artifacts"
E1015 17:11:30.668125 08287 injection.go:98] Error occured during injecting "../../familyapp/build" to "/tmp/build": write unix /var/run/docker.sock: broken pipe
```

It's unclear to me if there's a bug or I'm just doing this wrong as it's entirely unclear to me what exactly `--inject` is supposed to do.  In any case, I would think I should be able to copy files into any location inside the image that the assemble user has permissions.

Additional info about the environment:

I'm doing this work within a RHEL 7.5 VM on VMWare Fusion.  The source files are located on my host computer (macOS Mojave) and shared via VMWare's folder sharing feature.  

I installed s2i using the `rhel-server-rhscl-7-rpms` RHSM channel with `yum install source-to-image`.

`s2i version` yields `unknown`.

**Comment by bparees** [comment]
The "directory must exist" error seems self-evident.  We don't copy files to target directories that don't exist.  The target directory must exist within your builder image.


> I'm doing this work within a RHEL 7.5 VM on VMWare Fusion. The source files are located on my host computer (macOS Mojave) and shared via VMWare's folder sharing feature.

can you simplify this setup a bit?  take some of the variables out of the equation?

I'd suggest you start by just running s2i within the VM itself, with the files also being local within the VM and not shared from elsewhere.  It's possible you're running into some sort of copy/permission error that's non-obvious.

also please run with --loglevel=5

**Comment by jimklo** [comment]
It works fine if I don't try to `--inject`.   Permissions seem to be fine across the mounted volume - same error either way.

> The "directory must exist" error seems self-evident. We don't copy files to target directories that don't exist. The target directory must exist within your builder image.

So that seems to make it very difficult to add files to customize an image.  If the builder image does not have a pre-existing folder that doesn't clash with the default stream, it pretty makes `--inject` somewhat useless?  It would seem that I would have then extend the builder image Dockerfile to create the folder then perform the action I want? That seems like a lot of extra ceremony just to copy files into a builder image for extension - or am I really missing something here?

> can you simplify this setup a bit? take some of the variables out of the equation?

Yes... I just copied to my home dir on the VM.

> also please run with --loglevel=5

Here's that logfile.
[s2i.log](https://github.com/openshift/source-to-image/files/2480997/s2i.log)

**Comment by jimklo** [comment]
> > So that seems to make it very difficult to add files to customize an image.
> 
> it's not the intent of the feature. the injections feature is for injecting temporary content that you want removed before the final application image is committed.
> 
> If you expect these files to be in your final application image, this is not the way to do it.
> 
> If you want to customize the image, you should simply use docker to extend the image w/ your additional files.

Alas, Docker (AFAIK) has a different but related problem. You cannot ADD/COPY from outside of the context directory.

So then if I'm treating this like a normal Dockerfile - am I using s2i build the image, or just a standard `docker build`?  I've read much of the frontmatter on s2i and watched the hour long Red Hat demo video.  I'm still a bit confused about how the Dockerfile and the s2i scripts are related during build.  If there's a Dockerfile in the context dir, does that get used along with any .s2i overrides? 

> 
> > If the builder image does not have a pre-existing folder that doesn't clash with the default stream, it pretty makes --inject somewhat useless?
> 
> Perhaps for your use case, but not for what it was designed for, which was to inject credentials you might need at application assembly time (such as to access a private maven repository), but do not want committed into the final application image that is produced.
> 
> it's described pretty well here:
> https://github.com/openshift/source-to-image/blob/master/docs/cli.md#injecting-directories-to-build
> 
> That's not to say it should be failing for you, but it sounds like it's not what you want anyway.
> 

That's fair.  The link just says 

> "If you want to inject files that should only be available during the build" 

which doesn't really delineate that it couldn't be used for the use case I'm attempting. I understand the truncation, and yes, it's not what I really want. 

> Based on the failure:
> 
> ```
> I1015 17:52:50.084746 13528 tar.go:193] Adding "/tmp/s2i-021027551" to tar ...
> I1015 17:52:50.084801 13528 tar.go:260] Adding to tar: /tmp/s2i-021027551/.DS_Store as .DS_Store
> I1015 17:52:50.084894 13528 tar.go:260] Adding to tar: /tmp/s2i-021027551/asset-manifest.json as asset-manifest.json
> I1015 17:52:50.084930 13528 tar.go:260] Adding to tar: /tmp/s2i-021027551/favicon.ico as favicon.ico
> I1015 17:52:50.084978 13528 tar.go:260] Adding to tar: /tmp/s2i-021027551/index.html as index.html
> I1015 17:52:50.085401 13528 tar.go:260] Adding to tar: /tmp/s2i-021027551/manifest.json as manifest.json
> I1015 17:52:50.085446 13528 tar.go:260] Adding to tar: /tmp/s2i-021027551/service-worker.js as service-worker.js
> I1015 17:52:50.085527 13528 tar.go:260] Adding to tar: /tmp/s2i-021027551/static/css/main.f8dd547e.css as static/css/main.f8dd547e.css
> I1015 17:52:50.085833 13528 tar.go:260] Adding to tar: /tmp/s2i-021027551/static/css/main.f8dd547e.css.map as static/css/main.f8dd547e.css.map
> I1015 17:52:50.142442 13528 tar.go:260] Adding to tar: /tmp/s2i-021027551/static/js/main.ca87bd42.js as static/js/main.ca87bd42.js
> E1015 17:52:50.643873 13528 injection.go:98] Error occured during injecting "../../familyapp/build" to "/tmp/build": write unix /var/run/docker.sock: broken pipe
> ```
> it seems likely we're having trouble reading one of the files, are any of the symlinks or otherwise unusual?

Nope.  Not that I'm aware of... the source files that would be injected are just a set of static files.

> also what version of s2i are you using?

Excellent question.  Best I can tell....
```bash
$ sudo yum list all | grep source-to-image
source-to-image.x86_64              1.0.9-1.el7      @rhel-server-rhscl-7-rpms  
```
because 
```bash
$ s2i version
s2i unknown
```
Bad RPM in the official RHEL rhscl repo?

**Comment by bparees** [comment]
> Bad RPM in the official RHEL rhscl repo?

possibly.  regardless it's older, i'd certainly prefer to investigate this on a newer version.  Can you download the latest release binaries from github and see if the issue occurs there:
https://github.com/openshift/source-to-image/releases/tag/v1.1.12

or clone the repo and build your own s2i binary from master.


> Alas, Docker (AFAIK) has a different but related problem. You cannot ADD/COPY from outside of the context directory.

i'm suggesting you'd build your own "s2i builder image" that includes these additional files you care about, and then use that new image as the builder image when you do s2i builds w/ your git repo.

Or you can add the additional files to your git repo, perhaps as a sub-module?

Or just copy the files into the same dir as your source code and use the "--copy" option which just copies content instead of git cloning it, so the files don't need to be in a repo, just exist locally.  (you'd need to customize the assemble script to move the files around appropriately).

> I'm still a bit confused about how the Dockerfile and the s2i scripts are related during build. If there's a Dockerfile in the context dir, does that get used along with any .s2i overrides?

No, the dockerfile won't be used for anything if you're doing an s2i build.

> which doesn't really delineate that it couldn't be used for the use case I'm attempting. I understand the truncation, and yes, it's not what I really want.

If you read on, it also says:

```
After the assemble script finishes, all files copied will be truncated and thus not available in the output image. The files are truncated instead of deleted because the user under which we run the container with the assemble script might not have permissions to delete files in the destination directory (eg. /etc/ssl).

You can use this feature to provide SSL certificates, private configuration files which contains credentials, etc.
```

**Comment by bparees** [comment]
> Same error... however it's only having a problem if the destination doesn't exist, which then leads me to believe this is "as designed"? 

failing if the destination dir does not exist is definitely "as designed".  So it works if you specify a destination that exists?

> I'd recommend revising the documentation for the cli here around that explicitly states the destination folder must exist:

PRs welcome! :)


> I think the confusion arises from that there's only one example which co-mingles the content for the builder image and assembly source and then sclorg has their repo structured like this which does the same thing however their README.md omits the docker build of the builder image before running s2i.

These are all examples of how to create a new s2i builder image, so that is why they include dockerfiles and perform docker build operations.  The fact that some also include a sample app you can build, once you have built the s2i builder image, and that they include usage information on how to use the s2i builder image, once you've built it, is secondary.

We've tried pretty hard to make these docs clear, but if there are additional notes/instructions/etc that you think would have avoided your confusion, again, PRs are very welcome.

**Comment by jimklo** [comment]
> > Same error... however it's only having a problem if the destination doesn't exist, which then leads me to believe this is "as designed"?
> 
> failing if the destination dir does not exist is definitely "as designed". So it works if you specify a destination that exists?

Yes, at least for the limited number of cases I tried.  It's still a non-obvious error when you do specify a non-existent destination. It's not clear to me how one would arrive at that conclusion from:

```
E1015 17:52:50.643873 13528 injection.go:98] Error occured during injecting "../../familyapp/build" to "/tmp/build": write unix /var/run/docker.sock: broken pipe
```

which happens more frequently than what I think is the intended error:

```
E1015 17:10:30.313904 08083 injection.go:95] The destination directory for "../foo" injection must exist in container ("/opt/app-root/src/bar")
```

So the _bug_ that's that exists is an inconsistent error message, with the more frequent variant being one that doesn't inform much on the problem. If you agree, I could open a new issue for this as this one is probably too muddied - subsequently closing this one.


> > I'd recommend revising the documentation for the cli here around that explicitly states the destination folder must exist:
> 
> PRs welcome! :)
> 

I'll see what I can do.

> > I think the confusion arises from that there's only one example which co-mingles the content for the builder image and assembly source and then sclorg has their repo structured like this which does the same thing however their README.md omits the docker build of the builder image before running s2i.
> 
> These are all examples of how to create a new s2i builder image, so that is why they include dockerfiles and perform docker build operations. The fact that some also include a sample app you can build, once you have built the s2i builder image, and that they include usage information on how to use the s2i builder image, once you've built it, is secondary.
> 
> We've tried pretty hard to make these docs clear, but if there are additional notes/instructions/etc that you think would have avoided your confusion, again, PRs are very welcome.

Sure.

**Comment by bparees** [comment]
> So the bug that's that exists is an inconsistent error message, with the more frequent variant being one that doesn't inform much on the problem. If you agree, I could open a new issue for this as this one is probably too muddied - subsequently closing this one.

Ok, I definitely did not understand that in both cases you were trying to copy to a non-existent directory, I assumed in the second case you were copying to a valid directory(after having fixed your invocation in response to the original error message) and the broken pipe error was caused by something else.

So yeah, opening a new issue might be best at this point.
