### ISSUE TITLE
Support for binary builds using --from-file

### ISSUE THREAD

**Issue by tqvarnst** [openshift/source-to-image#942]
Sometimes we have a complex maven build structures with multi-module builds. Being able to build locally and then upload the artifact to the S2I build image is something that is supported in OpenShift as binary builds and would be fantastic to have that for the source-to-image tool as well.

**Comment by bparees** [comment]
the s2i tool offers the "--copy" flag if you want to use local content as your input instead of a git repo.

It would be up to each individual s2i builder image's assemble script as to whether it can handle pre-compiled content as an input, or expects source.
