### ISSUE TITLE
How to use openshift source-to-image library instead of s2i binary or executable file????

### ISSUE THREAD

**Issue by Anonymous14322** [openshift/source-to-image#944]
How to use openshift source-to-image library https://github.com/openshift/source-to-image using go language,instead of s2i executable to build a new image from existing builder images available from docker hub.

I need to create a new image by using above library and not using s2i.exe.

I have tried using https://github.com/openshift/source-to-image/blob/master/pkg/build/strategies/dockerfile/dockerfile.go Build function but it gives me an error.

Can anyone tell me or atleast guide me how to use this library to create a new image from existing builder images from docker hub by not using s2i executable.

Thanks in advance

**Comment by adambkaplan** [comment]
You can start with https://github.com/openshift/source-to-image/blob/master/pkg/build/strategies/strategies.go#L24. Note that to get this to fully work, you'll need:

1. A host environment that has Docker running
2. A properly configured docker client interface (our implementation, which wraps the Docker Engine API) - see https://github.com/openshift/source-to-image/blob/master/pkg/cmd/cli/cmd/build.go#L165
