### ISSUE TITLE
Nvidia gpu issue

### ISSUE THREAD

**Issue by sathiez** [openshift/source-to-image#946]
When I run tensorflow inside s2i image I get **no NVIDIA GPU device is present: /dev/nvidia0 does not exist**. while I can successfully able to build and run tensorflow in normal docker image using nvidia as runtime
 How can I solve it?

**Comment by bparees** [comment]
Possibly a permission or mounting issue, I don't know what creates/grants access to the /dev/nvidia device.

Are you having issues during s2i build, or running the image after you've built it?
