### ISSUE TITLE
Permission problems when copying artifacts during non-builder Runtime build process

### ISSUE THREAD

**Issue by rezie** [openshift/source-to-image#948]
When using the `--runtime-artifacts` flag during the runtime-only build process, [the documentation notes](https://github.com/openshift/source-to-image/blob/master/docs/runtime_image.md#details) that directories and files will have their permissions modified. Because of this behavior, if I were to specify (for example) the `/wildfly/standalone/deployments` directory for a Wildfly image, the `standalone/deployments` path will no longer be owned by the original group specified in the image, which initially was the root group. As a result, Wildfly will crash on startup as it expects to be able to write in that path.

A workaround could be to send the artifacts into the WORKDIR (e.g. `/wildfly`) and then include an `assemble-runtime` script to copy* it to the correct place. What are the generally suggested options to deal with artifacts in scenarios like this?

*Specifically `cp`, because the permissions would be insufficient for `mv`.

**Comment by bparees** [comment]
The intermittent copy suggestion is a pretty good one, I don't have any other ideas offhand... the reason for the permissions changes is due to the nature of docker cp and copying content into a container.

**Comment by rezie** [comment]
Good to know that it's not unexpected/unusual. Thanks!
