### ISSUE TITLE
v1.1.13 risk problem detected

### ISSUE THREAD

**Issue by kapcus** [openshift/source-to-image#949]
After downloading windows binaries my Symantec found following on both files:

Scan type: Auto-Protect Scan
Event: Risk Found!
Security risk detected: WS.Reputation.1
File: C:\Archiv\s2i\s2i.exe

Scan type: Auto-Protect Scan
Event: Security Risk Found!
Security risk detected: WS.Reputation.1
File: C:\Archiv\s2i\sti.exe

Risk Type: Insight Network Threat

Version 1.1.12 is fine.

**Comment by bparees** [comment]
Not the first time we've seen false positives in this area:
https://github.com/openshift/source-to-image/issues/843

we're not aware of any reason to think the binaries are compromised.

Based on https://www.symantec.com/security-center/writeup/2010-051308-1854-99 

WS.Reputation 1 is a "community driven" score, so short of us petitioning symantec, there's not much we can do.
