### ISSUE TITLE
S2I fails to use proxy settings in .s2i/environment

### ISSUE THREAD

**Issue by pdebuitlear** [openshift/source-to-image#952]
When running the following command to create a test app after setup I get the following:

```
oc new-app mysql
W0305 16:36:01.481901   71176 dockerimagelookup.go:233] Docker registry lookup failed: Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
error: only a partial match was found for "mysql": "openshift/mysql-persistent"

Argument 'mysql' was classified as an image, image~source, or loaded template reference.

The argument "mysql" only partially matched the following Docker image, OpenShift image stream, or template:

Template "mysql-persistent" in project "openshift"
  Use --template="openshift/mysql-persistent" to specify this image or template
```

**Version**
minishift v1.32.0+009893b

**Steps To Reproduce**
- Windows 7 Machine behind corporate proxy (without proxy auth)
- Deploy minishift to Oracle Virtual box with the following:
`
minishift start -v2 --show-libmachine-logs --vm-driver virtualbox --http-proxy http://proxy-server:3128 --https-proxy http://proxy-server:3128 
`
- Define a .s2i/environment file and populate it with proxy settings as per the documentation.
- The try and deploy an app with:
oc new-app mysql

**Expected Result**
Successful pull of app image from the repository(docker.io)

**Actual Result**
W0305 16:36:01.481901   71176 dockerimagelookup.go:233] Docker registry lookup failed: Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
error: only a partial match was found for "mysql": "openshift/mysql-persistent"

**Additional info**
I can pull directly from docker, i.e. `docker pull mysql`

**Comment by bparees** [comment]
you didn't really provide enough details to be sure what you're doing or expecting, but the environment file provides env vars that are made available to your assemble script, it's not environment information for the s2i cli process.  You can provide proxy config to s2i itself via the standard http* proxy env vars.

**Comment by pdebuitlear** [comment]
[https://github.com/minishift/minishift/issues/3125](See related minishift issue)

**Comment by bparees** [comment]
> oc new-app mysql

this has nothing to do w/ s2i or s2i's environment file.

> W0305 16:36:01.481901 71176 dockerimagelookup.go:233] Docker registry lookup failed: Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

if you need to go through a proxy to access docker.io from your client machine, then you need to set the appropriate http* proxy env vars prior to invoking the oc command.
