### ISSUE TITLE
Add an option to ignore `.git` in `s2i build` to build from local files

### ISSUE THREAD

**Issue by yu-iskw** [openshift/source-to-image#954]
# Overview
We are using s2i with seldon. Moreover, it is natural to put machine learning models to the docker image created by s2i. But we don't want to commit machine learning models to the git repo, since sometimes the data size of a machine learning model is greater than 1GB.

`.git` directory prevent us from smoothly developing the APIs and docker images. We need an option to ignore `.git` in `s2i build`. Besides, that automaticaly switing context between the local files and `.git` is confusing, I think.

```
Build a new Docker image named <tag> (if provided) from a source repository and base image.

Usage:
  s2i build <source> <image> [<tag>] [flags]

Examples:

# Build a Docker image from a remote Git repository
$ s2i build https://github.com/openshift/ruby-hello-world centos/ruby-22-centos7 hello-world-app

# Build from a local directory.  If this directory is a git repo then the current commit will be built.
$ s2i build . centos/ruby-22-centos7 hello-world-app
```

**Comment by bparees** [comment]
can you use .s2iignore for this?

https://github.com/openshift/source-to-image#build-workflow

**Comment by yu-iskw** [comment]
@bparees Thanks for the comment. I tried to add `.s2ignore` as below. But, it didn't work. The uncommitted files were not involved in the docker image.

```
.git/
```

**Comment by bparees** [comment]
including uncommitted files is a different problem.  if you want to use uncommitted files, pass --copy

also the file is named ".s2iignore" (two `i`s)

**Comment by yu-iskw** [comment]
Thanks for the advice. I will give it a try.

**Comment by yu-iskw** [comment]
`--copy` option worked as I expected. Thanks!
