### ISSUE TITLE
The container name is not rand.

### ISSUE THREAD

**Issue by magicsong** [openshift/source-to-image#955]
Each time i run the cmd, i got the same container with suffix "9acb0442". It will make concurrent building failed, the erros is like "**s2i_centos_python_35_centos7_9acb0442 is already in use by container xxxxx**". We should set seed before generating container name. check <https://github.com/openshift/source-to-image/blob/1b34d86b72df25a14ed7adc658a6682ea25da180/pkg/docker/docker.go#L77>

**Comment by bparees** [comment]
thanks, looks like a valid bug(not seeding the generator), but s2i should also be removing the container after execution so it seems like you ran into something else as well.

do you want to submit a PR to seed the generator?

**Comment by magicsong** [comment]
@bparees Happy to do that.
