### ISSUE TITLE
No assemble-runtime script found

### ISSUE THREAD

**Issue by maslick** [openshift/source-to-image#957]
Using a non-builder image for the final application image results in:
```
/bin/sh: /usr/local/s2i/assemble-runtime: No such file or directory
```

Perhaps, there shouldn't be this check (exit if ``assemble-runtime`` cannot be found). I can of course check in a blank ``.s2i/bin/assemble-runtime`` to the source repo, but IMHO it's an overkill.

Steps to reproduce:
```
s2i build https://github.com/maslick/see-i-see-d.git#jdk11 \
   fabric8/s2i-java:latest-java11 \
   vesna:run \
   --runtime-image registry.access.redhat.com/openjdk/openjdk-11-rhel7 \
   --runtime-artifact /deployments
```

**Comment by mkwapisz** [comment]
If you don't want to provide assemble-runtime script in .s2i/bin directory, then you have to modify your runtime image and COPY that empty script to io.openshift.s2i.scripts-url location
