### ISSUE TITLE
is it possible to add "app Item" to Catalog???

### ISSUE THREAD

**Issue by angry-tony** [openshift/source-to-image#961]
Hello! all..

is there way to add "customized Item"  and see it on "Developer Catalog" in Openshift 4??
( openshift 3 can do it using "ASB + APB + local registry" )

**like below...**
![image](https://user-images.githubusercontent.com/18000837/56705270-3f141680-674b-11e9-9ebf-9dc2e503461d.png)

**Comment by bparees** [comment]
items that show up in the developer catalog are:
1) imagestreams in the openshift namespace that have the builder tag
2) templates in the openshift namespace *if* you have the service catalog enabled(it's not on by default) and the template service broker installed(it's not installed by default).
3) installed OLM operators

i'm not sure what sort of customized item you're trying to add so it's hard to give you more specific advice.

I am closing this and the duplicate issues you opened elsewhere as this isn't the right repo to track it under.  openshift/origin would be the most appropriate place.
