### ISSUE TITLE
allow users of wrapper to specify standard labels

### ISSUE THREAD

**Issue by ryandawsonuk** [openshift/source-to-image#962]
I am maintaining a wrapper and I can see how to add standard build-time labels to the wrapper base image - an example of doing so is https://github.com/weaveworks/weave/commit/9f207f161a160e1f09f472015c346976547a0dc7

However, I want users of the wrapper to be able to set the appropriate labels on the images that they build with the wrapper. The values have to specified as build-time parameters as they can't be known in advance (git commit ref, build time etc.). From a docker-perspective they[ are build-args](https://github.com/weaveworks/weave/commit/9f207f161a160e1f09f472015c346976547a0dc7#diff-b67911656ef5d18c4ae36cb6741b7965R278)

I am struggling to see any way to set a build-arg from wrapper. Is there a way to do it? Or is there any plan to support adding labels as parameters to the `s2i build` command (analogous to the `docker build --label` parameter)?

I see that there is support for [build labels](https://github.com/openshift/source-to-image/blob/b54d75d3de92d123e68a79c6ee09c2c5fe44e720/pkg/api/constants/labels.go) but it's not clear to me whether it's possible to [set those ](https://docs.openshift.com/container-platform/3.4/dev_guide/builds/build_output.html)when running s2i directly (without openshift/k8s)

**Comment by adambkaplan** [comment]
There's no way to currently add your own labels to images produced by s2i. The build labels you reference are used by s2i and openshift builds for various purposes.

Would a CLI option like `--label=<key>=<value>` make sense to you?

**Comment by ryandawsonuk** [comment]
Yeah that would be great

**Comment by adambkaplan** [comment]
Good news! Looks like we have the internal API types to handle this [1], we just have not exposed it via the CLI. In fact, the API is how OpenShift applies user-provided labels to builds.

I'd be happy to accept a contribution that adds this!

[1] https://github.com/openshift/source-to-image/blob/master/pkg/api/types.go#L227
