### ISSUE TITLE
Providing environment variables

### ISSUE THREAD

**Issue by TallFurryMan** [openshift/source-to-image#971]
I am customizing a Builder Image for OpenShift. Documentation states environment can be provided in `.s2i/environment` but it seems no code is handling the inclusion of that file automatically when testing. Executing `make test` dumps the configuration field "Environment" as empty.

In order for the environment to be provided to the container during the test phase, I need to update `test/run` with:
```
# Since we built the candidate image locally, we don't want S2I to attempt to pull
# it from Docker hub
s2i_args="--pull-policy=never --loglevel=2 --environment-file=.s2i/environment"
```

Is this the proper way to do? Will OpenShift handle this by itself?

**Comment by bparees** [comment]
i believe s2i should auto-detect if you have a .s2i/environment file in your source repo, or you can provide it via the arg as you did.

as for openshift, openshift will do it automatically (again, if your source repo has a .s2i/environment file i believe it should be picked up and used automatically during the build process)

**Comment by pisymbol** [comment]
Yes, I made this mistake myself. The .s2i/environment file has to be within the source directory you pass on the command line to s2i or it won't pick it up.

Just to add, you can use the '-E' command line option to s2i to specify the environment file directly. That also works for me.

**Comment by TallFurryMan** [comment]
Putting it in the source repo may make sense, agreed. I don't think test/test-app/.s2i worked when I tested, but I will double check.

**Comment by TallFurryMan** [comment]
Works as intended with `.s2i/environment` in source repository.
