### ISSUE TITLE
Incremental build: save artifact tar timeout

### ISSUE THREAD

**Issue by jedthe3rd** [openshift/source-to-image#974]
I am hitting a problem with my dotnet s2i incremental build where the tar stream to transfer the .nuget folder times out before it gets fully transferred. Is there a way to increase the timeout time? Environment variable of some kind?

The LOG 5 showing the problem:
https://gist.github.com/jedthe3rd/e8b4db9bf775cecda9c7956b9c53460d

save-artifacts:
https://gist.github.com/jedthe3rd/feaa2759b72494d169fa846c7044cee2

The base docker image is: mcr.microsoft.com/dotnet/core/sdk:2.2-alpine3.9
It's edited to handle the proxy and add a working directory and user for openshift. I also add bash, wget, curl.

At this point I am thinking there is little benefit time wise using network vs incremental but I want to verify that.

**Comment by bparees** [comment]
The timeout is hardcoded but it's also something like 5 minutes, so if you're hitting it it seems likely something else is going wrong (or you have a massive number of size of saved artifacts).

the timeout was raised relatively recently, it looks like you hit a 30s timeout so i wonder if you're on an older version.

https://github.com/openshift/source-to-image/pull/930

**Comment by jedthe3rd** [comment]
Ya, I am using OCP v3.9.51 so it looks like I will just have to not use incremental because of the timeout. It probably wouldn't have saved any time doing the incremental anyway.

Thanks
