### ISSUE TITLE
unable to use s2i build

### ISSUE THREAD

**Issue by har2103** [openshift/source-to-image#981]
hi,

i am running s2i on fedora and when i am using s2i build am getting below error.

[root@localhost s2i]# s2i build SRC {base image} ace-mq-app
warning: Image sha256:753aa239e25a7345eb48b7a1592f52f1185c5f97f9e66495a6d19f3305fbde28 does not contain a value for the io.openshift.s2i.scripts-url label
Build failed
ERROR: An error occurred: failed to install [assemble run]
ERROR: Suggested solution: set the scripts URL parameter with the location of the S2I scripts, or check if the image has the "io.openshift.s2i.scripts-url" label set
ERROR: If the problem persists consult the docs at https://github.com/openshift/source-to-image/tree/master/docs. Eventually reach us on freenode #openshift or file an issue at https://github.com/openshift/source-to-image/issues providing us with a log from your build using log output level 3.
[root@localhost s2i]#

**Comment by adambkaplan** [comment]
@har2103 which base image are you using? Base images must have an assemble and run script to work - see https://github.com/openshift/source-to-image/blob/master/docs/builder_image.md

**Comment by har2103** [comment]
i am building an ace-mq conatiner using (https://github.com/ot4i/ace-docker) and base its using as 
ARG BASE_IMAGE=registry.access.redhat.com/ubi7/ubi-minimal
ARG BASE_TAG=7.6-237

[root@localhost s2i]# s2i build config ibm-ace-mq-baseimage:latest isacemqbpod_aitbuild
warning: Image sha256:d5069e51a2866362097a085f2b1f00028a5b7dbf6aeae793a9d0c1af4fc5d7ca does not contain a value for the io.openshift.s2i.scripts-url label
Build failed
ERROR: An error occurred: failed to install [assemble run]
ERROR: Suggested solution: set the scripts URL parameter with the location of the S2I scripts, or check if the image has the "io.openshift.s2i.scripts-url" label set
ERROR: If the problem persists consult the docs at https://github.com/openshift/source-to-image/tree/master/docs. Eventually reach us on freenode #openshift or file an issue at https://github.com/openshift/source-to-image/issues providing us with a log from your build using log output level 3.
[


can you help how should  i and where should i inject s2i  assemble and run script?

Appreciate your prompt response.

**Comment by har2103** [comment]
@adambkaplan  : i am using base image registry.access.redhat.com/ubi7/s2i-core and building my IBM MQ on top of that also on above MQ am adding iBM ACE. but when i use s2i build with this base image it doesnt add source instead it runs IBM ACE integration Server.

**Comment by har2103** [comment]
I am getting below error while adding s2i to ibm ace+mq .and using base image "ubi7/s2i-core".

[root@localhost ace-11-05]# cd IBM-ACE/ace-docker/s2i/
[root@localhost s2i]# s2i build config ace-mq-bi-with-s2i-1105:latest app-ace-1105
ERROR: Error writing header for "scripts": io: read/write on closed pipe
ERROR: Error writing tar: io: read/write on closed pipe
Build failed 
ERROR: An error occurred: Error response from daemon: OCI runtime create failed: container_linux.go:345: starting container process caused "chdir to cwd (\"/home/aceuser\") set in config.json failed: permission denied": unknown
[root@localhost s2i]

**Comment by adambkaplan** [comment]
@har2103 appears error came from Docker - which version of Docker are you using, and which host OS?

**Comment by har2103** [comment]
i am using 19.03.1 docker version and host is fedora 29.

**Comment by adambkaplan** [comment]
@har2103 can you try `sudo s2i build ...` - looks like a file permission issue from Docker.
