### ISSUE TITLE
Unable to set Docker build-time variables

### ISSUE THREAD

**Issue by maxstepanov** [openshift/source-to-image#983]
Docker provides an ability to specify build-time variables.
https://docs.docker.com/engine/reference/commandline/build/#set-build-time-variables---build-arg

> You can use ENV instructions in a Dockerfile to define variable values. These values persist in the built image. However, often persistence is not what you want. Users want to specify variables differently depending on which host they build an image on.
A good example is http_proxy or source versions for pulling intermediate files. The ARG instruction lets Dockerfile authors define values that users can set at build-time using the --build-arg flag

Is there any support for this variables in s2i or any sane workaround to set proxy settings only during the build-time? I don't need this settings when i develop but i must have them set for CI system because it is behind proxy.

**Comment by maxstepanov** [comment]
An alternative provided by Docker would be to configure docker client(~/.docker/config.json) like so:

`        "proxies": {
                "default": {
                        "httpProxy": "http://<proxy_host>:8080",
                        "httpsProxy": "http://<proxy_host>:8080",
                        "noProxy": "localhost"
                }
        }
`

But the problem is that s2i doesn't read any of these when "build" is called.
https://github.com/openshift/source-to-image/blob/2a579ecd66dfaf9ee21bbc860fcde8e4d1d12301/pkg/cmd/cli/cmd/build.go#L112

**Comment by mikehenry-se** [comment]
We have the same issue as well and don't want to pollute the Dockerfile with usernames and passwords particular to specific environments.
Like the "-e" command line option, an "-a" (for ARG) command line option could set the "--build-arg" equivalent to docker build.

**Comment by xrow** [comment]
Hi,

I favor this feature. To me it looks like a potential security issue also.
